### ISSUE TITLE
[gauging interest] Re-enable the 15 min scan cycle (helps with apple devices)

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/Pi.Alert#102]
See details in this video:

https://youtu.be/v6an9QG2xF0?t=880

**Comment by leiweibau** [comment]
Nice to see a review of a product you were involved in yourself. :D

Regarding the scancycles: I have read the original motivations, but I can't see any problems with the current scan. Everything is detected so far for me. Longer scans cause slow devices to crash/freeze and the WLAN to slow down significantly. You have to weigh the pros and cons.

**Comment by jokob-sk** [comment]
Yeah, if the feedback is good :D

I only created this issue as I think this came up now the second time (I think someone commented on it somewhere in an issue or somewhere) so I'd like to gauge interest. 

Also a good point on the longer scans causing WIFI issues - I haven't considered that one. 👍
