### ISSUE TITLE
Apprise Setup

### ISSUE THREAD

**Issue by King-Cole** [jokob-sk/Pi.Alert#106]
I've setup PiAlert, it works great! I'd really like to utilize the Apprise piece though, and I'm guessing I don't have it set right. When I send a test notification from the Apprise config webpage, it comes through fine though. Happy to hear advice :) 

PiAlert config:
```
REPORT_APPRISE = True
APPRISE_HOST = 'http://10.x.x.x:8010/apprise'
APPRISE_URL = 'hassio://10.x.x.x/<HA-Token>'
```

**Comment by jokob-sk** [comment]
Hey!

Thanks for using PiAlert!

Here is my config with fake data:

```python
# Apprise settings
#-----------------------
REPORT_APPRISE          = True
APPRISE_HOST            = 'http://192.168.1.99:7058/notify'
APPRISE_URL             = 'mailto://smtp-relay.sendinblue.com:587?from=apprise@local.com&name=apprise&user=emailforsenditblue@example.com&pass=somePassw0rdForsenditblue&to=myEmailICheck@gmail.com'

```
`APPRISE_URL`  documentation for HA:  https://github.com/caronc/apprise/wiki/Notify_homeassistant

All this you've probably already know though. Make also sure you can ping your server from the container on the given IP (e.g. I faced issues when trying to use a VPN/Tailscale IP). I'd really recommend to ssh into the container and diagnose network access at first. 

You can also run a CURL command, check this file for it's arguments in the method `send_apprise (html)`: https://github.com/jokob-sk/Pi.Alert/blob/main/back/pialert.py

(around line 1775 in this commit) 

Hope this helps!

**Comment by King-Cole** [comment]
Hi Jokob, thanks again for your development and help on this. I did find one mistake in my setup. In the config in my initial post I was missing the "/notify/" in the APPRISE_HOST URL. It is now fixed to "http://10.x.x.x/notify/apprise".
