### ISSUE TITLE
How scan multiple networks with this fork? and can i recieve alert if any device has configured static ip out of this networks. regards.

### ISSUE THREAD

**Issue by intheshell** [jokob-sk/Pi.Alert#107]

**Comment by jokob-sk** [comment]
Hey,

If by multiple networks you mean multiple interfaces, then yes. However it doesn't support a server-client setup where you have a clients in different networks reporting to one master server. You could attempt sharing the DB by mounting it somewhere in the cloud and point your instances to the shared DB, but I haven't tested this.

I'm unfortunately not sure what you mean by:

> can i recieve alert if any device has configured static ip out of this networks

Feel free to elaborate and maybe I can help further!

Hope this helps,
j

**Comment by intheshell** [comment]
Hello how are you?, of course I mean multiple networks on different interfaces, how can I configure it?

Regarding the other question, for example if a Host connects to an interface with a 192.168.1.0/24 network, if said host has a different IP configured (172.16.0.2) will it appear in the list?

Regards

**Comment by jokob-sk** [comment]
Hey,

Not too bad, hope you are fine!

You can find an example of multiple interfaces here 👉 https://github.com/jokob-sk/Pi.Alert/blob/5164d6566d040b2b8bd531eb0642680abd9daec2/config/pialert.conf#L98

> Regarding the other question, for example if a Host connects to an interface with a 192.168.1.0/24 network, if said host has a different IP configured (172.16.0.2) will it appear in the list?

Humm, I'm not a networking guru, but I think it should if you configure the above interfaces appropriately? Not sure, give it a go! Also, let me know if that worked, curious myself 😅

Hope this helps!

Cheers,
J
