### ISSUE TITLE
Add '-Pn' option for Nmap scan

### ISSUE THREAD

**Issue by acbgbca** [jokob-sk/Pi.Alert#108]
I've been trying to identify an unknown device on my network using the Nmap scan, however I get the following output:

```
Starting Nmap 7.80 ( https://nmap.org ) at 2022-12-06 03:04 UTC
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 3.03 seconds
```

It would be good to have the ability to enable the '-Pn' option when running a scan, either via a checkbox or simply enabling it for the more detailed scans.

**Comment by jokob-sk** [comment]
Added here as a 4th option https://github.com/jokob-sk/Pi.Alert/commit/516ecdf84c50684c02ed3b0b5121c9fb8acd2bc3

![image](https://user-images.githubusercontent.com/96159884/205855064-0f53f580-5565-4e43-83b8-b79c9a006b44.png)


It is available in the [dev image](https://registry.hub.docker.com/r/jokobsk/pi.alert_dev) and I'll add it to the production image with a bigger release
