### ISSUE TITLE
No such file or directory: '/home/pi/pialert/log/pialert.log

### ISSUE THREAD

**Issue by pbek** [jokob-sk/Pi.Alert#114]
Thank you for maintaining this great tool!
After an update today the container went into an infinite loop of this error block:

```
Nothing to do here.

sed: cannot rename /home/pi/pialert/config/pialert.conf: Device or resource busy

mkdir: cannot create directory '/run/php': File exists

Starting nginx: nginx.

Traceback (most recent call last):

  File "/home/pi/pialert/back/pialert.py", line 2349, in <module>

    sys.exit(main())       

  File "/home/pi/pialert/back/pialert.py", line 153, in main

    file_print('\nLoop start')

  File "/home/pi/pialert/back/pialert.py", line 2222, in file_print

    file = open(LOG_PATH + "/pialert.log", "a")    

FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/pialert/log/pialert.log'
```

There was no `/home/pi/pialert/log` in the default image. So I created a volume and mount `- pialert_log:/home/pi/pialert/log` for it and it worked again.

I just wanted to report that this volume now seems to be mandatory and maybe should be documented as such if it really was your intention to make it mandatory. 😉 

Keep up the great work!

**Comment by pbek** [comment]
Note I left the defaults of:

```
PIALERT_PATH      = '/home/pi/pialert'
LOG_PATH          = PIALERT_PATH + '/log'
```

**Comment by jokob-sk** [comment]
Hi,

Thanks for the kind words and for reporting this issue!

I think I know what's going on. I'll fix it in the next few days. In
the meantime you can probably change the path to:

LOG_PATH          = PIALERT_PATH + '/front/log'


Or completely remove this from the config. Both should theoretically work.

Thanks,
J

**Comment by pbek** [comment]
Ah, you removed LOG_PATH in https://github.com/jokob-sk/Pi.Alert/commit/6d9ffaabf865fb9ccbbc39dbd8745cb452410d58, then I'll do that. Thank you!

**Comment by jokob-sk** [comment]
I've renamed the internal variables so there hopefully won't be further conflicts: https://github.com/jokob-sk/Pi.Alert/commit/0a80300563cf494fa980817fd8a07cc29242108f

Thanks for bringing this one up!

**Comment by pbek** [comment]
Thank you!
