### ISSUE TITLE
New version of Docker fails to start

### ISSUE THREAD

**Issue by viriatusX** [jokob-sk/Pi.Alert#12]
Hi guys!
Since I have upgraded to the latest version, Pi.Alert does not work. It shows me this error. I have not touched anything and so far it was working fine. What can it be?

Thanks!

**Comment by jokob-sk** [comment]
Hi There!

Make sure you use the up-to-date Dockerfile
<https://github.com/jokob-sk/Pi.Alert/blob/main/Dockerfile> file. The
start.sh script got moved and this is reflected in the updated CMD command:

CMD ["/home/pi/pialert/dockerfiles/start.sh"]

Hope this helps!

**Comment by viriatusX** [comment]
> 

Thanks!!!! SOLVED :)
