### ISSUE TITLE
Rework to run as nonroot user for all services

### ISSUE THREAD

**Issue by devlincashman** [jokob-sk/Pi.Alert#131]
**Is your feature request related to a problem? Please describe.**
Currently this container runs as a mixture of root and www-data. Ideally only non-privileged users would be running the necessary services in this container. Also a good excuse to further simplify user permissions.

https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security

**Describe the solution you'd like**
Use something like [supervisord](https://github.com/Supervisor/supervisor) or [overmind](https://github.com/DarthSim/overmind) to manage running the required services for this container:
php-fpm
nginx (or potentially other httpd compat with php-fpm such as caddy)
python
subprocesses spawned by python such as arp-scan

And have them all run as a nonroot user (probably pi).

**Describe alternatives you've considered**
Alternative would be a docker compose config with an external container to handle the LEMP stack and just have this container focus on the pythons ide.

**Comment by jokob-sk** [comment]
Good point but not high on my todo list. Feel free to submit a PR.

 If you submit a PR implement check that the setup is backward compatible with existing installations and existing features are preserved. 

Thanks, 
J

**Comment by jokob-sk** [comment]
Will reopen if some work happens in this regard
