### ISSUE TITLE
Issue after last update

### ISSUE THREAD

**Issue by corasaniti** [jokob-sk/Pi.Alert#135]
Hi, I love this project, congrats

The latest update broke everything!!! Many pages don't work

1. sorting and display (all) of devices is not maintained
2. the settings page is not displayed correctly (missing stylesheet???) see attached screenshot

It would be nice with every release to have a release note to let you know about new features
Thank you
![Cattura1](https://user-images.githubusercontent.com/5001932/209463147-c9ee6724-616e-4855-8f79-981aa38a95fe.PNG)

**Comment by jokob-sk** [comment]
Hey, thanks for reporting!

Will look into it the next couple of days.

Let me know if there is anything else except of the two issues as you mentioned "The latest update broke everything!!!". 

In the mean  time try switching the the skin to dark mode, that should make the settings page readable at least.

Cheers,
j

**Comment by corasaniti** [comment]
@jokob-sk 
Hi, Do you think these days you will release, to fix the stylesheet issue in settings page? 
I don't like using dark mode
Thank in advance
PC

**Comment by jokob-sk** [comment]
Hi @corasaniti !

I will, but I'm finishing a bigger piece of work so it will be released together into the production image once everything is semi-ready.

You can either use an older image in the mean time, or try your luck with a dev built (very unstable):

https://hub.docker.com/r/jokobsk/pi.alert_dev

Thanks for your patience!
j

**Comment by jokob-sk** [comment]
Hi, 

This should be fixed in the latest release. Closing for now, will re-open if the same issue persists. 

Thanks for the patience!
j

**Comment by corasaniti** [comment]
@jokob-sk 
Hi what does the "Process: wait" header mean?
Thank you

**Comment by jokob-sk** [comment]
Hey, it's the wait time between the scan or other  execution cycles when
the process waits for the next thing to do.
