### ISSUE TITLE
"i"-Link on Random MAC-Adresses is dead

### ISSUE THREAD

**Issue by anoderay** [jokob-sk/Pi.Alert#141]
Clicking the "i" Link next to the sign informing about a Device using a random MAC-Adress leads to a dead URL (https://github.com/jokob-sk/Pi.Alert/blob/main/docs/RAMDOM_MAC.md). The original Github Repo from pucherot contains the .md-file (https://github.com/pucherot/Pi.Alert/blob/main/docs/RAMDOM_MAC.md).

**Comment by jokob-sk** [comment]
Thanks for reporting! 

This will be fixed in the next release, the new link is: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/RANDOM_MAC.md

**Comment by jokob-sk** [comment]
Should be in the latest production image. Closing for now, will re-open if issues persist.
