### ISSUE TITLE
get_internet_IP does not work

### ISSUE THREAD

**Issue by DKeppi** [jokob-sk/Pi.Alert#142]
The Command
`dig +short -4 myip.opendns.com @resolver1.opendns.com`
in the file
https://github.com/jokob-sk/Pi.Alert/blob/main/back/pialert.py at line 632
does not work in my docker container

`dig TXT +short o-o.myaddr.l.google.com @ns1.google.com` will work

Is there a possibility to implement a configuration for that, so that i can decide which dig command pi.alert will use?

**Comment by iAmSaugata** [comment]
''10/01/2023 10:15:58 pm
[2023-01-10 16:37:26] Check Internet IP:
10/01/2023 10:15:58 pm
    Retrieving Internet IP:``

Yes, it is not working, hence Internet showing down. As suggested above, it will be better to have an option for this in settings.

**Comment by jokob-sk** [comment]
Thanks for the submission! Should be fixed as part of this commit: https://github.com/jokob-sk/Pi.Alert/commit/3c13f82d61cd7599f84e750f364c9872ac579316

**Comment by jokob-sk** [comment]
Should be in the latest production image. Closing for now, will re-open if issues persist.
