### ISSUE TITLE
Devices table broke

### ISSUE THREAD

**Issue by WAdama** [jokob-sk/Pi.Alert#148]
The devices table view is broke after update to 23.01.22:
![pialert1](https://user-images.githubusercontent.com/21292479/213914534-0591fba4-a295-4681-8c15-0959296ead98.PNG)
![pialert2](https://user-images.githubusercontent.com/21292479/213914542-2ac4b53d-0a37-4649-9ee0-c9ea7cc4be18.PNG)

```

[2023-01-22 12:00:18] Process: Start
[2023-01-22 12:00:18] Process: Wait

 Permissions check (All should be True)
------------------------------------------------
  /config/pialert.conf |  READ  | True
  /config/pialert.conf |  WRITE | True
  /db/pialert.db       |  READ  | True
  /db/pialert.db       |  WRITE | True
------------------------------------------------
[Setup] Attempting to fix permissions.
[Setup] Attempting to fix permissions.
[upgradeDB] Adding dev_Icon to the Devices table
[upgradeDB] Re-creating Settings table
[2023-01-22 12:00:41] Config: Imported new config
[2023-01-22 12:00:41] Process: Start
[2023-01-22 12:00:40] Check Internet IP:
    Retrieving Internet IP:
      31.18.167.174
    Retrieving previous IP:
      31.18.167.174
    No changes to perform
    Skipping Dynamic DNS update
[2023-01-22 12:00:41] Scan: Pholus for 600s (10.0min)
        Pholus scan on [interface] bond0 [mask] 192.168.181.0/24
[2023-01-22 12:10:43] Scan: Pholus SUCCESS
[2023-01-22 12:00:40] Scan Devices:
    arp-scan start
  Processing scan results
    Devices Detected.......: 16
        arp-scan detected..: 14
        Pi-hole detected...: +0
        New Devices........: 0
    Devices in this cycle..: 16
        Down Alerts........: 0
        New Down Alerts....: 0
        New Connections....: 1
        Disconnections.....: 1
        IP Changes.........: 0
  Updating DB Info
    Sessions Events (connect / discconnect)
    Creating new devices
    Updating Devices Info
    Voiding false (ghost) disconnections
    Pairing session events (connection / disconnection) 
    Creating sessions snapshot
    Inserting scan results into Online_History
    Skipping repeated notifications
  Check if something to report
    No changes to report
    Notifications: 2
[2023-01-22 12:00:40] Upkeep Database:
    Online_History: Delete all older than 1 day
    Optimize Database
    Events: Delete all older than 90 days
    Pholus_Scan: Delete all older than 7 days
    Pholus_Scan: Delete all duplicates
    Nmap_Scan: Delete all duplicates
    Shrink Database
[2023-01-22 12:10:55] Last action: cleanup
[2023-01-22 12:10:55] Process: Wait


```

```

#-----------------AUTOGENERATED FILE-----------------#
#                                                    #
#         Generated:  2023-01-15_12-32-18            #
#                                                    #
#   Config file for the LAN intruder detection app:  #
#      https://github.com/jokob-sk/Pi.Alert          #
#                                                    #
#-----------------AUTOGENERATED FILE-----------------#


# General
#---------------------------
ENABLE_ARPSCAN=True
SCAN_SUBNETS=['192.168.xxx.0/24 --interface=bond0']
PRINT_LOG=False
TIMEZONE='Europe/Berlin'
PIALERT_WEB_PROTECTION=True
PIALERT_WEB_PASSWORD='pw'
INCLUDED_SECTIONS=['internet','new_devices','down_devices']
SCAN_CYCLE_MINUTES=5
DAYS_TO_KEEP_EVENTS=90
REPORT_DASHBOARD_URL='http://pi.alert/'
DIG_GET_IP_ARG='-4 myip.opendns.com @resolver1.opendns.com'


# Email
#---------------------------
REPORT_MAIL=True
SMTP_SERVER='smtp.strato.de'
SMTP_PORT=587
REPORT_TO='mymail'
REPORT_FROM='Pi.Alert <mymail>'
SMTP_SKIP_LOGIN=False
SMTP_USER='myuser'
SMTP_PASS='pw'
SMTP_SKIP_TLS=False


# Webhooks
#---------------------------
REPORT_WEBHOOK=False
WEBHOOK_URL='http://n8n.local:5555/webhook-test/aaaaaaaa-aaaa-aaaa-aaaaa-aaaaaaaaaaaa'
WEBHOOK_PAYLOAD='json'
WEBHOOK_REQUEST_METHOD='GET'


# Apprise
#---------------------------
REPORT_APPRISE=False
APPRISE_HOST='http://localhost:8000/notify'
APPRISE_URL='mailto://smtp-relay.sendinblue.com:587?from=user@gmail.com&name=apprise&user=user@gmail.com&pass=password&to=user@gmail.com'


# NTFY
#---------------------------
REPORT_NTFY=False
NTFY_HOST='https://ntfy.sh'
NTFY_TOPIC='replace_my_secure_topicname_91h889f28'
NTFY_USER='user'
NTFY_PASSWORD='passw0rd'


# PUSHSAFER
#---------------------------
REPORT_PUSHSAFER=False
PUSHSAFER_TOKEN='ApiKey'


# MQTT
#---------------------------
REPORT_MQTT=False
MQTT_BROKER='192.168.1.2'
MQTT_PORT=1883
MQTT_USER='mqtt'
MQTT_PASSWORD='passw0rd'
MQTT_QOS=0
MQTT_DELAY_SEC=2


# DynDNS
#---------------------------
DDNS_ACTIVE=False
DDNS_DOMAIN='your_domain.freeddns.org'
DDNS_USER='dynu_user'
DDNS_PASSWORD='A0000000B0000000C0000000D0000000'
DDNS_UPDATE_URL='https://api.dynu.com/nic/update?'


# PiHole
#---------------------------
PIHOLE_ACTIVE=False
DHCP_ACTIVE=False


# Pholus
#---------------------------
PHOLUS_ACTIVE=False
PHOLUS_TIMEOUT=20
PHOLUS_FORCE=False
PHOLUS_RUN='once'
PHOLUS_RUN_TIMEOUT=600
PHOLUS_RUN_SCHD='0 4 * * *'
PHOLUS_DAYS_DATA=7


# Nmap
#---------------------------
NMAP_ACTIVE=True
NMAP_TIMEOUT=150
NMAP_RUN='none'
NMAP_RUN_SCHD='0 2 * * *'
NMAP_ARGS='-p -10000'


#-------------------IMPORTANT INFO-------------------#
#   This file is ingested by a python script, so if  #
#        modified it needs to use python syntax      #
#-------------------IMPORTANT INFO-------------------#

```

`docker-compose.yml` 
```

version: '3'

services:
  pihole:
    container_name: PiAlert
    image: jokobsk/pi.alert:latest
    network_mode: "host"
    restart: unless-stopped
    environment:
      - "TZ=Europe/Berlin"
      - "USER_GID=xxx"
      - "USER_ID=xxxx"
      - "PORT=20211"
    volumes:
      - /volume1/docker/pialert/db:/home/pi/pialert/db
      - /volume1/docker/pialert/config:/home/pi/pialert/config
      - /volume1/docker/pialert/log:/home/pi/pialert/front/log
```

**Comment by corasaniti** [comment]
@WAdama 
Hi, I have similar issue
https://github.com/jokob-sk/Pi.Alert/issues/147

**Comment by WAdama** [comment]
Also it seems I can't no longer save the settings...

**Comment by WAdama** [comment]
I just for test a new container, the error is the same...

**Comment by jokob-sk** [comment]
Hey, thanks for the report, can you try saving this setting?

![image](https://user-images.githubusercontent.com/96159884/213916370-6483882d-9093-4c5b-8367-e62216c1fd6a.png)

**Comment by jokob-sk** [comment]
Building a new image where this should be fixed. Image will be live after this workflow finishes:  https://github.com/jokob-sk/Pi.Alert/actions/runs/3979834409

**Comment by corasaniti** [comment]
@jokob-sk Thanks

**Comment by WAdama** [comment]
Thanks, too...

I ment the save button in settings, by the way...

**Comment by WAdama** [comment]
I just loaded the new image, the table problem seems to be solved.

But I have the feeling, there are much more problems.

Opening device from device list brings this:
![pialert3](https://user-images.githubusercontent.com/21292479/213920131-dfbfef3b-4877-4bfe-959f-fd03d6c741d9.PNG)

Network looks like this:
![pialert4](https://user-images.githubusercontent.com/21292479/213920149-3d93a669-2a26-4d31-bc95-50caff599ad0.PNG)

And if I opened a device over the presence list there seems information missing:
![pialert5](https://user-images.githubusercontent.com/21292479/213920183-35b308b9-51ca-4170-befd-514027c5a791.PNG)

**Comment by ToqQrrl** [comment]
I'm on the latest version and i unfortunately have the same behavior.

**Comment by jokob-sk** [comment]
Thanks for reporting and patience! These issues should be fixed in the latest build - get the latest image after this build finishes: https://github.com/jokob-sk/Pi.Alert/actions/runs/3986226783

**Comment by corasaniti** [comment]
Thanks, I will try the new release

**Comment by corasaniti** [comment]
@jokob-sk 

Thanks everything works fine 
What are columns

```
Last IP Order
Row ID
MAC parent nodes
```

The real MAC of the device is Full MAC what's the difference with the MAC parent nodes?
Thanks in advance
PC

**Comment by WAdama** [comment]
@jokob-sk Just tested it, too... 

I can second it, it works again. The network map is real nice feature.

Thanks again for the support...

**Comment by corasaniti** [comment]
> 



> @jokob-sk Just tested it, too...
> 
> I can second it, it works again. The network map is real nice feature.
> 
> Thanks again for the support...
I can't see my network map. Here's what I see...
![Cattura](https://user-images.githubusercontent.com/5001932/214064698-43a10488-ccf0-4c6c-82dc-7afd698ab5bf.PNG)

**Comment by jokob-sk** [comment]
@WAdama Glad you like it, it took a lot of work and effort > that's why there were so many bugs ;) 

@corasaniti You need to assign devices to the node. Two ways how to do this:

1)  in the Device Details >  you can assign an End device (e.g. PC) to a Network -> node (e.g. WiFi).

![image](https://user-images.githubusercontent.com/96159884/214155088-a6d95a9c-8118-4fca-ac01-ea1737afd379.png)

2) Directly in the Network tab with the Assign/Unassign buttons.

![image](https://user-images.githubusercontent.com/96159884/214155473-fbafd5b5-ea1a-49bc-ba3d-dcbbb0994577.png)

More info the FAQ section under `What means " Node (MAC)" / " Port"?`

### Info to the columns: 

* Last IP Order - Internal - To correctly order the Last IP column
* Row ID - Internal - Index in the tbale, used to correctly order the device details carousel when using arrows <- ->
* MAC parent nodes - To build the Network diagram, the parent this device is assigned to in the network itself

**Comment by corasaniti** [comment]
@jokob-sk 
Thank you so much for your suggestions, but still I can't see my network map. Maybe I'm doing something wrong.

Here is my network below. My router Fritz7590 which has DHCP server enabled has an IP 192.168.2.1. I assigned the various devices as you can see from the screen but the map does not appear. I can only view the node of my Internet Provider

Thanks again

![Cattura1](https://user-images.githubusercontent.com/5001932/214232571-ff6c3967-90cd-4447-b6b1-e06133af61ae.PNG)

![Cattura2](https://user-images.githubusercontent.com/5001932/214232632-9ef3a44f-ff5d-4931-bacf-4fc6057fa45a.PNG)

**Comment by jokob-sk** [comment]
@corasaniti The root mac needs to be "Internet"(Other mac addresses are NOT supported as a root node). You then need to connect other devices to that root node, for example:

![image](https://user-images.githubusercontent.com/96159884/214248996-52ec1cf2-b3f7-479b-b8b3-eec5eac7875d.png)

Detailed config for `Android-2` :

![image](https://user-images.githubusercontent.com/96159884/214248597-f24ec4ac-d8ee-4302-b604-d7cd5cd691f1.png)

**Comment by corasaniti** [comment]
@jokob-sk 
Hi Unfortunately in the device details I don't see the Internet node but only the node of my Fritz router and I can't assign the Internet node to the devices. What am I doing wrong?
Thanks again
![Cattura](https://user-images.githubusercontent.com/5001932/214253206-6906fe43-a760-499d-83aa-d2ee2bda996c.PNG)

**Comment by jokob-sk** [comment]
Go to your device `Fritz7590` and make sure the MAC is `Internet` on that device

**Comment by corasaniti** [comment]
@jokob-sk 
I think I don't understand. I simply have an ONT--->RouterFritz7590 with DHCP server enabled and all devices are connected to the Fritz7590 via cable or Wifi...
Thanks

**Comment by corasaniti** [comment]
@jokob-sk 
This is my situation for my network (The MAC AABBCCDD1122 is a fake MAX for example...)

![Cattura1](https://user-images.githubusercontent.com/5001932/214273725-0d04fa31-cb2b-49da-a963-2fcd2901f37c.PNG)

![Cattura2](https://user-images.githubusercontent.com/5001932/214273753-863fd09e-9267-4888-a4ee-f5c003b37e67.PNG)

**Comment by corasaniti** [comment]
@jokob-sk 
This is ma network map setting... (the MAC AABBCCDD1122 is a fake for example)
![Cattura1](https://user-images.githubusercontent.com/5001932/214274211-8b33db80-b330-451f-b22d-011d52920a02.PNG)
![Cattura2](https://user-images.githubusercontent.com/5001932/214274224-c652ad70-0625-4d95-bd8e-71c4e3f29af6.PNG)

**Comment by jokob-sk** [comment]
This needs to be Internet: 
![image](https://user-images.githubusercontent.com/96159884/214275119-5dd08be4-5a68-432a-b5c1-800890f8d19f.png)

Please thoroughly read the guide here:  https://github.com/jokob-sk/Pi.Alert/blob/main/docs/NETWORK_TREE.md

**Comment by corasaniti** [comment]
how do i open other tabs when assigning devices. I only see fritz tab
![Cattura](https://user-images.githubusercontent.com/5001932/214277113-f3422997-4d88-4fed-ac1e-f525f93565c5.PNG)

**Comment by jokob-sk** [comment]
Please thoroughly read the guide here: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/NETWORK_TREE.md

**Comment by corasaniti** [comment]
As I already said in the detail of the device in the Node Mac combo I can only see my Fritz and not the Internet node. Thanks
![214253206-6906fe43-a760-499d-83aa-d2ee2bda996c](https://user-images.githubusercontent.com/5001932/214277969-570b5abc-7ddd-48db-9a8e-45ed7fc134e8.png)

**Comment by jokob-sk** [comment]
As already said, it's described in the guide https://github.com/jokob-sk/Pi.Alert/blob/main/docs/NETWORK_TREE.md

```

    In the (2) Details tab navigate to the the Type (3) dropdown and select the type Switch (4).

    Note: Only the following device types will show up as selectable Network nodes ( = devices you can connect other devices to): AP, Firewall, Gateway, PLC, Powerline, Router, Switch, USB LAN Adapter, USB WIFI Adapter and WLAN.

```

Closing and locking as off-topic. Feel free to open a new issue if still facing problems.
