### ISSUE TITLE
Make image smaller

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/Pi.Alert#15]
Try this https://github.com/docker-slim/docker-slim to make the image smaller

**Comment by jokob-sk** [comment]
+ possibly re-base to Alpine

**Comment by Macleykun** [comment]
`ENTRYPOINT [ "/bin/sh", "-c", "command args & crond -f" ]`
Here, might come in handy ;)

**Comment by Macleykun** [comment]
I suggest to close this, as i've compared the size difference but it's not worth the time and effort to rewrite the dockerfile for a few MB :). Debian slim is already pretty small!

**Comment by jokob-sk** [comment]
Hey @Macleykun !

Long time no see. Hope you are well! You are probably right, not worth the effort :) 

Will close this for now.

**Comment by Macleykun** [comment]
heya :D is pi.alert working well in docker?

**Comment by jokob-sk** [comment]
yep, all good. Still have to figure out the permissions issue and working on making the setup easier :) maybe this pull request will help, I'll have to check
