### ISSUE TITLE
Add release tags on Docker Hub

### ISSUE THREAD

**Issue by joshuar** [jokob-sk/Pi.Alert#150]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Add release tags (as they are shown on GitHub) to the images on Docker Hub so that a user can pull a specific image version. 

**Describe alternatives you've considered**
While you can pull a specific version by correlating the git commit hash for a version with the hash tags on Docker Hub, this is not very user friendly. Would be great to use _23.01.22-HF01_ as the Docker image tag as opposed to _sha-7baae28_.

**Additional context**
In my case, I'm deploying pi.alert through Ansible, and to avoid additional logic that would tear-down and redeploy pi.alert everytime I run my playbook, being able to specify a version tag ensures the task only runs when that version changes and makes my playbook more readable. 

I'm sure however that other users would benefit in other use-cases from being able to pull a specific version from Docker Hub.

Thanks very much for maintaining this fork!

**Comment by jokob-sk** [comment]
Hey @joshuar !

Thanks for the suggestion and using this image!

I tried to, but couldn't figure it our how to pass the release tag to DockerHub - I even asked a question here, without a clear answer: 

https://stackoverflow.com/questions/75123596/creating-a-github-action-to-publish-to-dockerhub-with-the-current-release-tag

I've spend a couple of hours on it and figured my time is better used elsewhere for now. 

If you know how to integrate this into the [CI/CD pipeline via GitHub actions](https://github.com/jokob-sk/Pi.Alert/blob/main/.github/workflows/docker_prod.yml), I'm all ear :)

Cheers!
j

**Comment by masterwishx** [comment]
@jokob-sk  
Hi ,Maybe you can find answer here :  
https://github.com/dgtlmoon/changedetection.io/blob/master/.github/workflows/containers.yml

**Comment by jokob-sk** [comment]
Thanks for the suggestion - tried it but it still doesn't work. I suspect it has something to do with me triggering a release via the website and not via a commit. not sure...

**Comment by thomas-mc-work** [comment]
Maybe this configuration by https://github.com/goauthentik/authentik can help you?: https://github.com/goauthentik/authentik/blob/main/.github/workflows/release-tag.yml

**Comment by Rfkgaming89** [comment]
go to your DockerHub account and navigate to your repository.

click the "Create" button in the top navigation bar, then select "Create Automated Build".

 "Configure Automated Builds" page, select the repository and branch you want to build.

Scroll down to the "Build Settings" section and click on "Add Build Rule".

In the "Name" field, enter a name for your build rule (e.g. "Release Tag").

In the "Dockerfile Location" field, enter the path to your Dockerfile.

In the "Docker Tag Name" field, enter the tag name you want to use for your release (e.g. "release-1.0.0").

Click on "Create & Build" to save your build rule and start the build process.

Once your build rule is created and the build process is complete, your Docker image will be tagged with the specified release tag and pushed to your DockerHub repository. You can then use the release tag to deploy the specific version of your Docker image as needed.

See if that helps.

**Comment by jokob-sk** [comment]
Hi there @Rfkgaming89 and thanks for the suggestion!

Fee DockerHub accounts don't support automated builds. The PiAlert container is built via GitHub actions.

**Comment by jokob-sk** [comment]
Alright, as I suspected, the tags were not picked up by DockerHub, because the versioning didn't follow the [semantic guidelines](https://semver.org/). 

- Previous versioning numbers system: `vYY.MM.DD`
- New versioning numbers system:  `vYY.M.D`  < without a starting `0`. 

This change now allows for automatically generated DockerHub tags, such as this one: https://hub.docker.com/layers/jokobsk/pi.alert/23.5.7/images/sha256-9d8df2af5058cc8742dd663261556ae8cd58e2f0e7c5d0139dd895ee27acce90?context=repo
