### ISSUE TITLE
Devices table broke for "New Devices" ---> Sub issue from issue #148

### ISSUE THREAD

**Issue by ToqQrrl** [jokob-sk/Pi.Alert#152]
Hello @jokob-sk  ... when choosing "New Devices" ... and then editing the details of those new devices ... the information is empty.

It seems to work for the other "Filters".

(*) New devices from the "All Devices" filter are ok but not when choosing the "New Devices" filter.

Reference ---> Devices table broke https://github.com/jokob-sk/Pi.Alert/issues/148

**Comment by jokob-sk** [comment]
Thanks for the report! Can you please provide a couple of screenshots and numbered steps so I can reproduce them on my side?

**Comment by ToqQrrl** [comment]
I’ll do that later tonight … thank you for investigating the problem.

**Comment by jokob-sk** [comment]
I think I've found the bug. I'll release a fix as part of the next release. This is the relevant commit: https://github.com/jokob-sk/Pi.Alert/commit/78f90180835cc4bf4a130e76390ae5b749895c14

**Comment by ToqQrrl** [comment]
Thx … when the fix is published… I’ll check the result and confirm here if everything works.

**Comment by jokob-sk** [comment]
Should be fixed in the latest release - > closing for now
