### ISSUE TITLE
Add simple api to check if a device is currently online

### ISSUE THREAD

**Issue by RichyHBM** [jokob-sk/Pi.Alert#155]
**Is your feature request related to a problem? Please describe.**
I have some scripts to issue notifications for different things and would be great if I could use pi-alert to check if a device is online on the network or not to automate different things

**Describe the solution you'd like**
Simple API that takes in a MAC address or IP and tells you if there is a device on the lan connected to that address

**Comment by jokob-sk** [comment]
Hey @RichyHBM ,

Thanks for the suggestion!

1) Could you please elaborate on the use case?

2) Would this trigger an ad-hoc scan?

3) Why do you need such functionality (ad-hoc queries)?

4) Have you considered other integration options already available, such as the Webhooks + n8n integration and / or the MQTT integration?

5) Would simply exposing a JSON of the current state of the database be sufficient?

Answering these questions will give me a better idea of your requirements and evaluate different implementation approaches.

Thanks in advance!
j

**Comment by leiweibau** [comment]
For example, you could implement a web dashboard, based on the already existing data, which shows you which devices are online.

**Comment by RichyHBM** [comment]
> 1. Could you please elaborate on the use case?
I have a simple python service running that pings me notifications when it detects someone on CCTV, but I dont want it to do so when I am home as they are all inside and it is just detecting me. So I wanted to use pi-alert to check if my phone is on the local network and if so not to send the notification.

> 2. Would this trigger an ad-hoc scan?
This could be useful down the line, but for my use case it wouldnt need to

> 3. Why do you need such functionality (ad-hoc queries)?
N/A

> 4. Have you considered other integration options already available, such as the Webhooks + n8n integration and / or the MQTT integration?

I have used HA, but due to caching when the notification is sent it doesnt record the image properly, so I cant use it. I could possibly use MQTT and check the status there

> 5. Would simply exposing a JSON of the current state of the database be sufficient?

That would work, I can parse it and extract/find the data I need

**Comment by jokob-sk** [comment]
Thanks for the details, makes sense. 

I'd be interested what you mean by:

>...  but due to caching when the notification is sent it doesnt record the image properly, so I cant use it...

Either way, part of the next release will be a simple API endpoint: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/API.md

Relevant commit:

https://github.com/jokob-sk/Pi.Alert/commit/51e865c98d03d4817cea39b3639a63c8afe5d7b0

It took actually longer than I thought it would, but I have now an easy way to JSON serialize any DB table at least :)

**Comment by RichyHBM** [comment]
To go further into what I meant, HA only provides the latest frame from my cameras, so I am talking to frigate directly to get the events frame to then message to other services. HA would be fine if the services I notified then cached the image themselves, but one of them just links back to HA which by time time I check is displaying something new

**Comment by jokob-sk** [comment]
I see, I thought it's related to PiAlert :) Anyway, hold out for the new version, will probably release it this weekend.
