### ISSUE TITLE
Add ability for icons from font-awesome brands.css to render

### ISSUE THREAD

**Issue by mwmundy** [jokob-sk/Pi.Alert#156]
The icon pop-out link takes you to the following URL to search for icons you can use:
https://fontawesome.com/search?q=laptop&o=r&m=free

It looks like within the front/php/server/devices.php file, there is a function called getIcons() that takes your string and creates the following html:
<i class="fa fa-'.$icon.'"></i>

Within the container, the following css files exist for font-awesome:
/home/pi/pialert/front/lib/AdminLTE/bower_components/font-awesome/css/

I found that none of the icons from brands.css or anything other than fontawesome.min.css
I tried some basic debugging, including making a test page with all available icons and confirmed at the very least that brands did not render (I tried using "amazon" for firesticks and "google" for google home devices).  This is not an urgent issue, but more of a feature request.

**Comment by jokob-sk** [comment]
Hey there!

Thanks for using this fork!

You should be able to use even brand-specific icons by entering the whole set of classes, e.g. for apple enter: `fa fa-brands fa-apple`

Hope this works!
j

**Comment by mwmundy** [comment]
That definitely worked, thank you!
