### ISSUE TITLE
Send telgram alert

### ISSUE THREAD

**Issue by gregtux77** [jokob-sk/Pi.Alert#157]
Hello,
I can't get "telegram" notifications to work through "apprise".
what is the syntax for "url"?
I do not master Aprrise but I manage to send messages from the interface;

here is what I put:
APPRISE_HOST='http://192.168.10.9:8000/notify'
APPRISE_URL='tgram://5###131878:AAFDaB######bF8TnUacg-j3N8/57####15/'

is it correct ?

thanks in advance

**Comment by jokob-sk** [comment]
Hey! Thanks for reporting!

This seems to be a bug. Telegram seems to be incapable processing HTML. I'll add an option to pick between text and html payload types. This should be fixed in the next release probably released next weekend.

Thanks,
j

**Comment by gregtux77** [comment]
Hello,
thank you for this feedback. I hate to test this.

**Comment by gregtux77** [comment]
hello i m an error witl latest version, this's same problem ? 
   sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 599, in main
    send_notifications()
  File "/home/pi/pialert/back/pialert.py", line 2281, in send_notifications
    update_api(True)
  File "/home/pi/pialert/back/pialert.py", line 3100, in update_api
    write_file(folder + 'notification_text.txt'  , mail_text)
  File "/home/pi/pialert/back/pialert.py", line 3167, in write_file
    file = open (pPath, 'w', encoding='utf-8') 
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/pialert/front/api/notification_text.txt'

tky for your time
