### ISSUE TITLE
pialert can

### ISSUE THREAD

**Issue by geeflaxx** [jokob-sk/Pi.Alert#169]
**Describe the issue**

I want to try pialert, but after I start the docker it crashed. 
I had not the folder "api", so I disable ENABLE_API, create a the folder and enable this function. with ENABLE_API=True

at first was the error "table_devices.json" was not found, but there is one.
I think the log is a bit older, now I only get the error "Nothing to do here, starting Nginx:nginx"

Website doesn't load and the log doesn't give me more information :/

```

Nothing to do here.
Starting nginx: nginx.

```

**Paste your `pialert.conf` (remove personal info)**

```

-----------------AUTOGENERATED FILE-----------------#
#                                                    #
#         Generated:  2022-12-30_22-19-40            #
#                                                    #
#   Config file for the LAN intruder detection app:  #
#      https://github.com/jokob-sk/Pi.Alert          #
#                                                    #
#-----------------AUTOGENERATED FILE-----------------#
ENABLE_API=True

# General
#---------------------------
# Scan using interface eth0
# SCAN_SUBNETS    = ['192.168.1.0/24 --interface=eth0']
#
# Scan multiple interfaces (eth1 and eth0):
# SCAN_SUBNETS    = [ '192.168.1.0/24 --interface=eth1', '192.168.1.0/24 --interface=eth0' ]
SCAN_SUBNETS=['192.168.1.0/24 --interface=eth0']
PRINT_LOG=False
TIMEZONE='Europe/Berlin'
PIALERT_WEB_PROTECTION=False
PIALERT_WEB_PASSWORD='8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92'
INCLUDED_SECTIONS=['internet','new_devices','down_devices','events']
SCAN_CYCLE_MINUTES=5
DAYS_TO_KEEP_EVENTS=90
REPORT_DASHBOARD_URL='http://pi.alert/'


# Email
#---------------------------
REPORT_MAIL=False
SMTP_SERVER='smtp.gmail.com'
SMTP_PORT=587
REPORT_TO='user@gmail.com'
REPORT_FROM='Pi.Alert <user@gmail.com>'

(...) still default settings 

```

**Screenshots**
![image](https://user-images.githubusercontent.com/21129138/216796243-914cd221-f808-44d6-afee-399943b1db8d.png)
![image](https://user-images.githubusercontent.com/21129138/216796252-4c7a6003-5d38-48c9-9e45-b2d8b233bec2.png)

**Comment by jokob-sk** [comment]
Hey, this is solved by following instructions in this thread: https://github.com/jokob-sk/Pi.Alert/issues/163
