### ISSUE TITLE
UI configration persist file

### ISSUE THREAD

**Issue by tamimology** [jokob-sk/Pi.Alert#172]
**Is your feature request related to a problem? Please describe.**
When I started using this container (around a year back), I manually named every single device I had, defined its group, and set it to be monitored or not as a new device.

Now, since I had an issue with the latest version, I had to remove the container and image and create a new one. However, all the devices were reset to their default names (IP+ISP provider name).

I have defined them in the hosts file as below, but still, nothing changed.

`      - $PERSIST/pialert/hosts:/etc/hosts` 

**Describe the solution you'd like**
Is there a file to backup and restore in such scenarios, preferably to mount that file on the local host to make sure it is not deleted if the container/image is deleted and also makes it easier in case of host migration.

**Describe alternatives you've considered**
My mounted hosts file looks like below

```
 # Any manual change will be lost if the host name is changed or system upgrades.
127.0.0.1       localhost
::1             localhost
192.168.1.1 Home_Router
192.168.1.2 LAN_Extender
192.168.1.3 Zigbee_Bridge
192.168.1.4 NetworkSwitch
192.168.1.10 Synology
192.168.1.11 Broadlink_RMC4_Mini
192.168.1.12 SwitchBot_HubMini
192.168.1.20 TV
192.168.1.21 TV_BackLEDs
192.168.1.30 AndroidTV
192.168.1.40 Canon_Printer
192.168.1.50 Family_Room_Speaker
192.168.1.51 Kitchen_Speaker
192.168.1.52 Master_Bedroom_Speaker
192.168.1.53 Kids_Bedroom_Speaker
192.168.1.54 Office_Speaker
192.168.1.100 TamMobile
192.168.1.101 TamLaptop
192.168.1.103 Kids_Tab
192.168.1.104 Sony_PS3
192.168.1.106 LenovoTab8
192.168.1.107 SamsungTab8
192.168.1.110 SE_Laptop
192.168.1.111 SE_iPhone
```

**Additional context**

![image](https://user-images.githubusercontent.com/90429593/216912537-7216074b-92c7-484f-866d-2541b2d43530.png)

**Comment by jokob-sk** [comment]
Hi, there is a CSV export/import option in the maintenance section, which I think would solve the problem.

**Comment by tamimology** [comment]
I exported, modified the device names, and then imported. I am getting this error when importing

![image](https://user-images.githubusercontent.com/90429593/216928941-e5e5cab3-1dc1-47a2-b6bb-4f3b9b168b1d.png)

**Comment by jokob-sk** [comment]
Can you check what's in your response in the network tab? 

![image](https://user-images.githubusercontent.com/96159884/216942688-63154576-c2f6-4471-b016-f0ac07b1bbb8.png)

**Comment by tamimology** [comment]
Mate, it is working now. I figured out that there was MAC address duplicates in my CVS file when I added some extra devices manually.

Thanks for the hint as this saves me heaps of time renaming mass devices :)

**Comment by jokob-sk** [comment]
👍😉
