### ISSUE TITLE
Drag an drop of columbs not possible anymore

### ISSUE THREAD

**Issue by killtux** [jokob-sk/Pi.Alert#175]
**Describe the issue**
Cannot drag and drop order of columns

it was a bit clunky before, liked described on the maintanance page, but since the last update its not possible to move anything.

![image](https://user-images.githubusercontent.com/36768145/217320280-cb01d1ab-811a-46d2-9c76-18f6e04653ba.png)

**Comment by jokob-sk** [comment]
Hi there, 

It works on my end. 

Looks like the page is not loaded properly. Please reload page and check the browser error log / console by pressing F12 for details.

**Comment by killtux** [comment]
yeah it looks like. i noticed the other menu pages are not accessable anymore. you can click on it but nothing happens.

![image](https://user-images.githubusercontent.com/36768145/217474075-c3feb997-b05b-4ef3-ad20-29ff70416d7e.png)

![image](https://user-images.githubusercontent.com/36768145/217473371-faa0d254-fb53-4a37-821f-dcd8ca4f6f8d.png)

**Comment by jokob-sk** [comment]
Thanks for the details!

The 500 server error is a very generic error so not sure without more details what's causing this. 

I'd recommend also exporting the Devices in a CSV file via the Backup / Restore section in maintenance and then starting with a fresh install because your database is pretty huge (500MB). You can then import the CSV file as per instructions on a new DB.My database size is around 10MB max and it's possible SQLite  is having issues with that size or DB queries are timing out. 

j

**Comment by killtux** [comment]
the problem is, as mentioned above, i cannot get to the backup / restore section. 😮‍💨  i installed the the app 5 days ago, is there any reason the db can get that big?

is there any other way to export devices? it was really much work to completely configure nearly 80 devices hand by hand. 🤯

**Comment by jokob-sk** [comment]
Hey,

A workaround is to access this url:

`<pialert host ip>/php/server/devices.php?action=ExportCSV`

This will generate and download a CSV file of all the devices.

I highly recommend to backup everything (including DB).

The CSV only contains the Devices and Network info, not NMAP port custom comments.

Hope this helps,
j

**Comment by jokob-sk** [comment]
How often do you scan for new devices? That might influence the size of the DB - my settings are usually every 3 or 5 minutes.  Same with additional scans such as Pholus or NMAP. They might influence the DB size as well, although, depending on your version, only unique values should be stored which should prevent the DB to swell up this much.

**Comment by killtux** [comment]
the interval is set to the default 5 minutes and i changed it yesterday to 15min and days to keep events to only 1 day in hope the db will get smaller. but per today its grown even much more:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/36768145/217756068-07df3ef8-0e3d-4d48-bcec-ece0edc48957.png">

i noticed that Pholus scan is running regularly, even if its not activated in the settings. is this normal?

thanks for the hint with the direct export url. i will do a fresh install today.

**Comment by jokob-sk** [comment]
To completely disable Pholus you need to specify these 3 settings: 
![image](https://user-images.githubusercontent.com/96159884/217758806-994460b8-ac35-424b-9cf6-436e3c3da32e.png)

**Comment by killtux** [comment]
if i try to import via csv file i get that message:
![image](https://user-images.githubusercontent.com/36768145/217787816-3a6aa318-6a9e-4093-b8ea-f3b363c25ccd.png)

devices.csv is in the /config/ folder and looks fine to me. any suggestions?

**Comment by jokob-sk** [comment]
The CSV export seems to generate a file with 2 blank lines in the beginning. Please delete them and the CSV import should work again.

**Comment by killtux** [comment]
removing the 2 blank lines worked, thanks! 
db stays < 0,50mb now. would be cool if you can add the icon name to the csv export too.

and if you got drag'n' drop sometime working, it would be nice if you can drag an drop the columns directly on the main page.

and maybe you can extend the width of the page itself or make it dynamic resized with the browser screen. 
since width is fixed you have to scroll left and right all the time to see the other columns even if there is enough space on the monitor. just the background extends.

**Comment by jokob-sk** [comment]
Hi there,

Glad to hear that it's working!

I'll look into the icon not exporting as that should be an easy fix.

The UI specific requests are low priority as the framework picked by the
original developer is not very extensible (and afaik doesn't support
components) and has limited mobile support. Also is argue the value
proposition is smaller than working on something else.

Feel free to submit PRs if interested.

That being said, I'd reconsider if more people and or recurring sponsors
would request these.

Hope this position makes sense.

J

**Comment by killtux** [comment]
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/36768145/224350306-6d9a0417-1002-4872-89c9-2a4a46567b8a.png">

it happened again :(
this time the db is still pretty small.

any idea/timeline when the csv export with icons will find its way in a future release?

**Comment by jokob-sk** [comment]
Can you clear/purge the logs?

The new release is taking a while as it comes with a bigger piece of functionality. You can try the dev builds if interested: https://registry.hub.docker.com/r/jokobsk/pi.alert_dev - which obviously are less table

**Comment by killtux** [comment]
clearing the whole log dir worked.
  
  
  
  
  
  
  

  
  
>
