### ISSUE TITLE
Schedule nmap scan to run on next contact

### ISSUE THREAD

**Issue by mh166** [jokob-sk/Pi.Alert#176]
**Is your feature request related to a problem? Please describe.**
I found a new device in my network that, so far, has been seen only once. As I don't know which device it might be, I would like to have more information about it.

**Describe the solution you'd like**
In the Web UI, Pi.Alert offers nmap scans of detected devices. But at the moment the device has been offline for some hours again. So no chance of getting anymore infos in hindsight. I would like to be able to "schedule" a nmap scan: the next time Pi.Alert sees this device, it should immediately start a default system scan.

**Describe alternatives you've considered**
Another option would be to always scan any new devices the moment they are detected. But for most of them, I know very well where they're coming from. So usually it is not needed and creates unneeded traffic.

**Additional context**
N/A

**Comment by jokob-sk** [comment]
Hi there,

This can be achieved by enabling:

Cycle run
NMAP_ACTIVE

This should run an Nmap scan when a new device vice is detected.

Backup your devices (by backing up your DB and / or via the CSV export (the CSV export doesn't include Pholus and Nmap results). Then delete the device you need to scan again when it shows up next time.

Please test this ona known device before implementing the solution.

Thanks,
J

**Comment by mh166** [comment]
Oh, good point. Maybe I hadn't enabled this option when I set it up, initially. Was late that night... 😅

If it doesn't work, I'll come back to you. But from what it says on the tin, it should work as I want it. Thank you for the tip. :)

**Comment by jokob-sk** [comment]
😉👍
