### ISSUE TITLE
Updating the icon for all devices of the same type displays "KO" instead of "OK"

### ISSUE THREAD

**Issue by pmcelreavy** [jokob-sk/Pi.Alert#177]
**Describe the issue**
In the device settings, change the device icon and press the button to apply to all devices of the same type.
The message displays "KO" instead of OK

**Screenshots**
![image](https://user-images.githubusercontent.com/12051767/217395774-7d6ab7c9-a5f4-4711-8470-e78dee278581.png)

**Comment by pmcelreavy** [comment]
I believe this only happens when scanning the network. When scanning nmap or waiting, "OK" appears.

**Comment by jokob-sk** [comment]
Thanks for reporting!

KO indicates an error > KO will be renamed to "Error updating devices, try later. Probably the database is locked due to an ongoing task." in the next release.
