### ISSUE TITLE
When updating the icon for all devices of the same type and leaving the page we get an alert

### ISSUE THREAD

**Issue by pmcelreavy** [jokob-sk/Pi.Alert#178]
**Describe the issue**
ONLY change the icon for the device and apply to all the devices of the same type.
Click on "devices" to return to the device list.
An alert pops up and asks if we are sure we want to leave.

**Screenshots**
![image](https://user-images.githubusercontent.com/12051767/217396064-f07eb43e-1630-4987-8231-d49ebda47bef.png)

**Comment by jokob-sk** [comment]
Thanks for reporting!

Small issue, won't fix for now. I would have to refactor a lot of code I think to solve this, not a big issue.
