### ISSUE TITLE
Pi.Alert Wake up HIbernate or Sleep PC on LAN 

### ISSUE THREAD

**Issue by lexmark3200** [jokob-sk/Pi.Alert#184]
**Describe the issue**
Hi, after many issues I finally get worked pi.alert on docker.
The problem was with permission, The UID and GUID must be 33 otherwise you cann't do a backup database.
I cheked it after ssh to docker and check the permission rights :/home/pi/pialert/db/pialert.db .

The problem is that, when it is working, my hibernate PC is wake up.
How can I fix that without turn off on bios wake on lan function?.

Many thx for aby suggestion.

**Comment by jokob-sk** [comment]
Hi there,

I'm not sure what you want me to do. Regrettably I'm unfamiliar how wake on lan works. You can try disabling Nmap / Pholus to see if that fixes the problem but I have limited experience with this.

Thanks,
J

**Comment by lexmark3200** [comment]
Hi. Thx for your reply.

Strange situation, yesterday I turn off (stop) docker, then start it again, turn off Nmap /Pholus, then turn on, and all of the night it was working perfectly, without any wakes up my PCs.

One question and problem.
My  second PiHole is working on docker. It is running 24h, but Pi.Alert is showing status down. In LOG file I see:
[code] Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 3.18 seconds[/code]
When I click on Skip host discovery ( -Pn), it is ok, but a few minutes later the same problem.
How can I fix that??
Any port in Pihole Docker must to be "open" to detect it??

**Comment by leiweibau** [comment]
"Skip host discovery" means that in the case of nmap, the program assumes that the host is online. This means that nmap also returns that the device is online, although this is not true.

**Comment by lexmark3200** [comment]
Ok. I undertsood that, but how can I do that in auto, every scan of my network I get that docker is down.

**Comment by jokob-sk** [comment]
I'm unfortunately not sure what you mean. Can you please provide more details?

**Comment by lexmark3200** [comment]
Ok. 
PI.Alert is scanning all of them time not once per day. Or I'm wrong ;) 
So when I start it in docker it discover my devices on my network. It is ok. It working great. But only with pi-hole which is working on docker all of the time (always), pi.alert is showing pi-hole is down.
So what I need from you is the info what I must to do, that pi.alert show my pihol is working.
When I click Skip host discovery, pi.alert not change the status of mi pi-hole on docker it is still down but really is working fine. 
Do you understand me now?
So maybe my docker with pi.alert is working not like should working.

**Comment by jokob-sk** [comment]
Thanks for the details! 

What do you mean by:

> pi.alert is showing pi-hole is down.

You mean the server where PiHole is running is down?

There are only 2 ways how devices are discovered, PiHole or arp-scan.:

1) To enable arpscan you need to correctly specify:  SCAN_SUBNETS and ENABLE_ARPSCAN + follow instruction on those settings.
2) To enable PiHole you need to enable PIHOLE_ACTIVE and DHCP_ACTIVE  + follow instruction on those settings.

If devices appear in your devices list, then the chosen mechanism works. 

PiAlert is not discovering docker images, only physical devices on the network. Nmap is used to discover open ports on those discovered devices.
Hope this helps,
j

**Comment by lexmark3200** [comment]
`You mean the server where PiHole is running is down?`

No PiHole is working on the same mashine as pialert, but in macvlan, so it has own IP adress like standalone mashine. 

`Nmap is used to discover open ports on those discovered devices.`

So my thinking was right. 
I have open port to login PiHole and some porta TCP and UDP.  But pialert show the PiHole is down.

**Comment by jokob-sk** [comment]
Regrettably, my network knowledge is limited so unsure what "macvlan" is. I don't think this setup is supported (as in arpscan and pihole won't recognise that as stand-alone network devices).

Not sure if this conversation helps: https://github.com/jokob-sk/Pi.Alert/issues/183

**Comment by lexmark3200** [comment]
https://docs.docker.com/network/macvlan/

**Comment by jokob-sk** [comment]
Thanks, as mentioned I don't think this is supported by tools such as PiHole or arpscan. 

I'm closing this as the original issue seems to be solved.

**Comment by leiweibau** [comment]
Sorry for writing in a closed issue. 
I have experimented with "macvlan" via portainer and can confirm at this point that these "hosts/containers" are also detected via arp-scan. Why this does not work correctly with @lexmark3200, can have a lot of reasons.

**Comment by lexmark3200** [comment]
Ypur macvlan docker was Pihole like my?? Can you put your stack script??

**Comment by leiweibau** [comment]
I had a macvlan container that was detected by Pi.Alert. However, after further research I found out that there is a problem with the accessibility of the macvlans when they are configured on the same computer.

- Pi.Alert does not detect the macvlan container when it is running on the same computer.
- Pi.Alert recognizes the macvlan container when it is running on a different computer.

Since this is not my fork here, I would hate to post external links. In my estimation, @jokob-sk can not do much here.

**Comment by lexmark3200** [comment]
`Pi.Alert does not detect the macvlan container when it is running on the same computer.`

That is my configurstion. So you discovered what the problem is.

**Comment by jokob-sk** [comment]
thanks @leiweibau for the info! Much appreciated
