### ISSUE TITLE
Force a Rescan

### ISSUE THREAD

**Issue by zilvernet** [jokob-sk/Pi.Alert#186]
Hi, I would love a feature that allows you to force a rescan of you network.
The idea is to not wait for the configured cycle to start if for example, you need to get the ip of a new added device on your network.

Im not a huge fan of using too aggressive cycles just because you would like to wait less anytime you add a new device on your network.

**Comment by jokob-sk** [comment]
Hi,

This should be possible via this button: 

![image](https://user-images.githubusercontent.com/96159884/221288318-76250097-de62-4a68-ae13-5f70300297db.png)

**Comment by zilvernet** [comment]
Thanks, i missed that option.

Maybe moving it to the main page outside the settings makes it more obvious.

![image](https://user-images.githubusercontent.com/75147745/221370781-00703f21-f89e-48b7-a1ca-b61d6e7196bf.png)

And also, adding the state to the element so that you can only force scan one time until the force scan ends. right after it is pressed you can disable the element and enable back once it has finished its forced scan.

These are just suggestions to improve it, however the current feature works, thanks for pointing out where it is located.

**Comment by jokob-sk** [comment]
Thanks for the suggestions!

The button is in Settings to keep the app code manageable/maintainable. I can think of an extension framework in the future that would allow adding custom actions to the navbar, but it's low on my priority list. My priorities and how I decide then are mentioned here if interested: https://github.com/jokob-sk/Pi.Alert/issues/118
