### ISSUE TITLE
Better handling of Log Files

### ISSUE THREAD

**Issue by XxAcielxX** [jokob-sk/Pi.Alert#187]
Hello,

I'm using PiAlert since 2 to 3 months, and recently I have noticed that the Log Files tend to get way out of size.

I have my `SCAN_CYCLE_MINUTES` set to 10 minutes, and the size of the `pialert.log` goes approximately:
* 1d = 500KB
* 7d = 3.5MB
* 28d = 14MB

The is no auto pruning at all, and then the log files' size grows out of control.

This also affects the loading time of the Logs Page on the WebUI, and this will also affect SDCard/SSD/NVMe writes.

There should be 2 available options for all logs type (`pialert.log`, `pialert_pholus.log`, `pialert_nmap.log`, etc,):
1. Auto Pruning of Logs (like create daily logs and then delete log files order than x days)
2. Disable Logging

Kindly look into this.

Regards,
XxAcielxX

**Comment by jokob-sk** [comment]
Hi There,

Thanks for using the app and for the suggestion.

The next release will contain a minimal no logging setting:

https://github.com/jokob-sk/Pi.Alert/issues/138

![image](https://user-images.githubusercontent.com/96159884/221351464-53d855c7-ffb0-4aab-bb16-4b0f2f086769.png)


Thanks,
j

**Comment by harr2969** [comment]
Mine is worse for pialert_pholus.log (134 MB.. not sure how  many days.)

root@nas:/home/pi/pialert/front/log# ls -lh
total 146M
**-rw-rw-rw- 1 root     root      12M Feb 28 22:03 pialert.log**
-rw-rw-rw- 1 www-data www-data  706 Feb 28 05:56 pialert_front.log
-rw-rw-rw- 1 root     root      81K Feb 26 23:16 pialert_nmap.log
**-rw-rw-rw- 1 root     root     134M Feb 28 22:03 pialert_pholus.log**
-rw-rw-rw- 1 root     root      14K Feb 28 22:03 pialert_pholus_lastrun.log
-rw-rw-rw- 1 root     root        0 Feb 28 22:03 pialert_pholus_subp_pr.log
-rw-rw-rw- 1 root     root     3.5K Feb 28 21:58 report_output.html
-rw-rw-rw- 1 root     root      517 Feb 28 21:58 report_output.txt

**Comment by jokob-sk** [comment]
@harr2969 Removed the mentioned log in this commit as it's (hopefully) not needed anymore: https://github.com/jokob-sk/Pi.Alert/commit/176a436ad4dd2084ad708c037abf22c9bc608ddf

This also will be part of the next release.

**Comment by jokob-sk** [comment]
🆕 New release is live:

- Release announcement: https://github.com/jokob-sk/Pi.Alert/releases/tag/v23.03.11
- Docker image: https://registry.hub.docker.com/r/jokobsk/pi.alert
