### ISSUE TITLE
Services Screen

### ISSUE THREAD

**Issue by zilvernet** [jokob-sk/Pi.Alert#188]
**Is your feature request related to a problem? Please describe.**
The majority of network scanning tools provide services (open ports) on the main list where they scan the networks.
This view helps to quickly identify and known or unknown devices from the network you are scanning.

**Describe the solution you'd like**
I would consider adding a different type of scan that can be run at another scheduler cycle. (To not affect the speed to view results on the devices screen) 

and even use a different screen so that there is less change on the current devices screen.

![image](https://user-images.githubusercontent.com/75147745/221372061-64518066-b66c-4ee9-8bb2-33ba700fa16f.png)

This screen should be able to filter by services, and the edit screen can be unified with the screen of the device.

This is an example of a scanned network that on the list it includes known services that were reported on the scan:
![image](https://user-images.githubusercontent.com/75147745/221372122-7099f6fd-33a4-484e-936d-30e4479dae33.png)

**Comment by jokob-sk** [comment]
Thanks for the suggestion!

This was implemented via a new plugin system in the latest release: 

- Release announcement: https://github.com/jokob-sk/Pi.Alert/releases/tag/v23.03.11
- Docker image: https://registry.hub.docker.com/r/jokobsk/pi.alert
