### ISSUE TITLE
Update default password notice

### ISSUE THREAD

**Issue by p3l1** [jokob-sk/Pi.Alert#196]
When using the default password, a warning message on the login screen appears which tells you to run the reset_password.py script. After having trouble finding the given script, I found out it was replaced by the pialert-cli.

https://github.com/jokob-sk/Pi.Alert/blob/176a436ad4dd2084ad708c037abf22c9bc608ddf/front/index.php#L148

The warning should give the same information as the settings page:

```
The default password is 123456. To change the password run /home/pi/pialert/back/pialert-cli in the container
```

**Comment by jokob-sk** [comment]
Thanks for reporting. Will be fixed in the next release

**Comment by jokob-sk** [comment]
Fix in latest release > closing
