### ISSUE TITLE
Docker Compose Example 3 - wrong volume path

### ISSUE THREAD

**Issue by SeimusS** [jokob-sk/Pi.Alert#200]
**Describe the issue**
Following the Example 3 in https://github.com/jokob-sk/Pi.Alert/blob/main/dockerfiles/README.md will not create the proper container. Maybe I missed something but looks like the Example tries to MAP File into a Folder 

This is due to the Volume mapping is as following: 
- ./pialert/pialert.conf:/home/pi/pialert/config/pialert.conf 

This will give an error:
ERROR: for PiAlert  Cannot start service pialert: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/pi/internet-monitoring/pialert/pialert.conf" to rootfs at "/home/pi/pialert/config/pialert.conf": mount /home/pi/internet-monitoring/pialert/pialert.conf:/home/pi/pialert/config/pialert.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for pialert  Cannot start service pialert: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/pi/internet-monitoring/pialert/pialert.conf" to rootfs at "/home/pi/pialert/config/pialert.conf": mount /home/pi/internet-monitoring/pialert/pialert.conf:/home/pi/pialert/config/pialert.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

Basicaly the example forces to Map a file into a directory thus will not work.

**FIX**
Should be: - ./pialert/pialert.conf:/home/pi/pialert/config

**Request**
Can this be please in the Example 3 adjusted?

**Comment by jokob-sk** [comment]
Hi,

Thanks for the report.

Example Number 3 is community sourced and before changing it I need to check your setup:

Could you please confirm `./pialert/pialert.conf` is a file not a folder? 

> FIX
> Should be: - ./pialert/pialert.conf:/home/pi/pialert/config

The fix you are proposing is confusing me, because `./pialert/pialert.conf` looks like a file and `/home/pi/pialert/config` is a folder. 

Thanks in advance for clarifying!
j

**Comment by SeimusS** [comment]
Hello,

Thank you for your response.

Yes it is true that the entry should mount file into a file. But the problem is it will only happen in case the file is already existing in the Docker Host. Which looks like is not, thus the error.

https://docs.docker.com/storage/bind-mounts/#differences-between--v-and---mount-behavior

**`If you use -v or --volume to bind-mount a file or directory that does not yet exist on the Docker host, -v creates the endpoint for you. It is always created as a directory.`**

**There are several ways how we can go around this.**

1. Creating volumes inside Docker itself
2. Mapping volume with type bind + source and target assets specification to the host Directories and PiAlert Container
3. Mapping volumes to Directories between Docker host and PiAlert container
4. Having the Docker host already an existing pialert.conf

I think Option 1 and 2 are bit annoying as I find it simplier to use a host directories instead at least for my user case. Options 3. and 4. are more easier. Thus this from my user prespective leaves us with Option 3. which is actually easy to do.

I also redone my composer for PiAlert looks like this:

```
  pialert:
    container_name: PiAlert
    hostname: PiAlert
    privileged: true
    image: jokobsk/pi.alert:latest
    environment:
      - TZ=Europe/Bratislava
    restart: always
    volumes:
      - ./pialert/pialert_db:/home/pi/pialert/db
      - ./pialert/pialert_config:/home/pi/pialert/config
    network_mode: host
```

If you agree I think for ease of use for users that dont have much experience with composer and docker, the Example 3 volumes could be changed to my volume example or even whole config as I have set other goodies that will have cleaner look in the GUI:

```
    volumes:
      - ./pialert/pialert_db:/home/pi/pialert/db
      - ./pialert/pialert_config:/home/pi/pialert/config
```

This should guarantee its close working always :)

**Comment by jokob-sk** [comment]
Hi @SeimusS !

Thanks for the clarification. 

I've added your example based on your feedback as Number 2 in the examples list: https://github.com/jokob-sk/Pi.Alert/tree/main/dockerfiles#example-2

Let me know if this is an acceptable solution :)

Thanks for using this app,
j

**Comment by SeimusS** [comment]
Hi @jokob-sk !

I feel honored! I definitely accept this solution.

Thank you, and good job on the app! I very much like it. Looking foward to new releases/features!

Regards,
SeimusS

**Comment by jokob-sk** [comment]
👍😉
