### ISSUE TITLE
Accessing device out of device list shows empty page

### ISSUE THREAD

**Issue by WAdama** [jokob-sk/Pi.Alert#205]
**Describe the issue**
When I'm opening a device in the device list I get an empty list with message "device not found":

Out of "Presence" for example it works.

**Paste last few lines from `pialert.log`**

> You can use `tail -20 /home/pi/pialert/front/log/pialert.log`

```
[2023-04-04 13:31:08] Notifications: 0
[2023-04-04 13:31:08] Last action: network_scan
[2023-04-04 13:31:08] Process: Wait
[2023-04-04 13:31:58] Process: Start
[2023-04-04 13:31:58] Process: Wait
[2023-04-04 13:32:58] Process: Start
[2023-04-04 13:32:58] Check Internet IP:
    Retrieving Internet IP:
      31.17.79.27
    Retrieving previous IP:
      31.17.79.27
    No changes to perform
    Skipping Dynamic DNS update
  Check if something to report
    No changes to report
[2023-04-04 13:32:59] Notifications: 0
[2023-04-04 13:32:59] Last action: internet_IP
[2023-04-04 13:32:59] Process: Wait
[2023-04-04 13:33:59] Process: Start
[2023-04-04 13:33:59] Process: Wait

```

**Paste your `pialert.conf` (remove personal info)**

```
#-----------------AUTOGENERATED FILE-----------------#
#                                                    #
#         Generated:  2023-02-05_10-04-22            #
#                                                    #
#   Config file for the LAN intruder detection app:  #
#      https://github.com/jokob-sk/Pi.Alert          #
#                                                    #
#-----------------AUTOGENERATED FILE-----------------#


# General
#---------------------------
ENABLE_ARPSCAN=True
SCAN_SUBNETS=['192.168.xxx.0/24 --interface=bond0']
PRINT_LOG=False
TIMEZONE='Europe/Berlin'
PIALERT_WEB_PROTECTION=True
PIALERT_WEB_PASSWORD='xxx'
INCLUDED_SECTIONS=['internet','new_devices','down_devices']
SCAN_CYCLE_MINUTES=5
DAYS_TO_KEEP_EVENTS=90
REPORT_DASHBOARD_URL='https://pialert.service.xxx.de:50015/'
DIG_GET_IP_ARG='-4 myip.opendns.com @resolver1.opendns.com'
UI_LANG='English'


# Email
#---------------------------
REPORT_MAIL=True
SMTP_SERVER='smtp.xxx.de'
SMTP_PORT=465
REPORT_TO='push@xxx.de'
REPORT_FROM='Pi.Alert <pi.alert@xxx.de>'
SMTP_SKIP_LOGIN=False
SMTP_USER='relay@xxx.de'
SMTP_PASS='xxx'
SMTP_SKIP_TLS=True
SMTP_FORCE_SSL=True


# Webhooks
#---------------------------
REPORT_WEBHOOK=False
WEBHOOK_URL='http://n8n.local:5555/webhook-test/aaaaaaaa-aaaa-aaaa-aaaaa-aaaaaaaaaaaa'
WEBHOOK_PAYLOAD='json'
WEBHOOK_REQUEST_METHOD='GET'


# Apprise
#---------------------------
REPORT_APPRISE=False
APPRISE_HOST='http://localhost:8000/notify'
APPRISE_URL='mailto://smtp-relay.sendinblue.com:587?from=user@gmail.com&name=apprise&user=user@gmail.com&pass=password&to=user@gmail.com'
APPRISE_PAYLOAD='html'


# NTFY
#---------------------------
REPORT_NTFY=False
NTFY_HOST='https://ntfy.sh'
NTFY_TOPIC='replace_my_secure_topicname_91h889f28'
NTFY_USER='user'
NTFY_PASSWORD='passw0rd'


# PUSHSAFER
#---------------------------
REPORT_PUSHSAFER=False
PUSHSAFER_TOKEN='ApiKey'


# MQTT
#---------------------------
REPORT_MQTT=False
MQTT_BROKER='192.168.1.2'
MQTT_PORT=1883
MQTT_USER='mqtt'
MQTT_PASSWORD='passw0rd'
MQTT_QOS=0
MQTT_DELAY_SEC=2


# DynDNS
#---------------------------
DDNS_ACTIVE=False
DDNS_DOMAIN='your_domain.freeddns.org'
DDNS_USER='dynu_user'
DDNS_PASSWORD='A0000000B0000000C0000000D0000000'
DDNS_UPDATE_URL='https://api.dynu.com/nic/update?'


# PiHole
#---------------------------
PIHOLE_ACTIVE=False
DHCP_ACTIVE=False


# Pholus
#---------------------------
PHOLUS_ACTIVE=False
PHOLUS_TIMEOUT=20
PHOLUS_FORCE=False
PHOLUS_RUN='once'
PHOLUS_RUN_TIMEOUT=600
PHOLUS_RUN_SCHD='0 4 * * *'
PHOLUS_DAYS_DATA=7


# Nmap
#---------------------------
NMAP_ACTIVE=True
NMAP_TIMEOUT=150
NMAP_RUN='none'
NMAP_RUN_SCHD='0 2 * * *'
NMAP_ARGS='-p -10000'


# API
#---------------------------
ENABLE_API=False
API_RUN='schedule'
API_RUN_SCHD='*/3 * * * *'
API_RUN_INTERVAL=10
API_CUSTOM_SQL='SELECT * FROM Devices WHERE dev_PresentLastScan = 0'


#-------------------IMPORTANT INFO-------------------#
#   This file is ingested by a python script, so if  #
#        modified it needs to use python syntax      #
#-------------------IMPORTANT INFO-------------------#

```

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 

```
version: '3'

services:
  pialert:
    container_name: PiAlert
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: unless-stopped
    environment:
      - "TZ=Europe/Berlin"
      - "USER_GID=xxx"
      - "USER_ID=xxx"
      - "PORT=20211"
    volumes:
      - /xxx/pialert/db:/home/pi/pialert/db
      - /xxx/pialert/config:/home/pi/pialert/config
      - /xxx/pialert/log:/home/pi/pialert/front/log
```

**Screenshots**
![error](https://user-images.githubusercontent.com/21292479/229775469-3028bfeb-12da-4afa-ae35-359c269a42b7.PNG)

**Comment by jokob-sk** [comment]
Hi there!

Thanks for taking the time to describe your issue in such detail!

I think the link you've clicked doesn't contain a valid MAC address. 

The link to a Device detail view should look look like this:

`http://<pialert IP>:20211/deviceDetails.php?mac=d0:21:f9:f4:f4:f4`

1) Can you check if your URL is in the above format?

If not, can you check if this is an issue for all or only certain devices?

2) Could you please confirm which page you are on clicking these links (e.g. Presence/ Devices etc?)
3) Could you please check if there are any javascript errors in the page you click the link on (hit F12  in your browser and go into Console and reload your page > ar there any red errors?)?

Thanks in advance for the additional details!
j

**Comment by WAdama** [comment]
As I already wrote it's only happening in the devices list, in all other sites it works as expected.

And yes, the MAC is missing in the URI. As I just saw it's also missing in the table of the devices:
![mac](https://user-images.githubusercontent.com/21292479/230683604-1b8ec015-4088-467f-835d-917dbfee35d4.png)

And the check for javascript errors is negative

**Comment by jokob-sk** [comment]
Hi,

Thanks for the follow-up answers.

1) Can you check if this is an issue for all or only certain devices?
2) The MAC column in the table is not the actual MAC address. Can you go into Maintenance and add the column `Full MAC` under UI Settings? ()
![image](https://user-images.githubusercontent.com/96159884/230689602-72e51b41-fb63-42bb-a2e2-239e3b87b260.png)
3) To double check, you are saying that the links from other pages (which ones?), such as Presence, work correctly, yes? 

Thanks in advance,
j

**Comment by WAdama** [comment]
Sorry, I thought I mentioned it. It's happening with all devices.

That's funny. If I activate "Full MAC" in the table it's working again.

And to second that, all other sites are working as expected.

**Comment by jokob-sk** [comment]
Cool, thanks, should be fixed in the next release.

**Comment by dtech77pl** [comment]
> 2\. Full MAC

Confirmed that after adding Full MAC into the UI setting all work as expected.  Problem with the device not found is gone.
