### ISSUE TITLE
Show Version Number in UI

### ISSUE THREAD

**Issue by jordantrizz** [jokob-sk/Pi.Alert#209]
**Is your feature request related to a problem? Please describe.**
I couldn't find the current version number within the WebUI

**Describe the solution you'd like**
The version number is easily shown in the WebUI, maybe the footer of each page?

**Describe alternatives you've considered**
Loggingin into docker container.

**Additional context**

**Comment by jokob-sk** [comment]
If someone has an idea how to automate this, e.g. as part of GitHub actions, please let me know.

**Comment by jokob-sk** [comment]
For clarification, the app already notifies you if you are running an outdated version. Is the version you are running currently still important in that case?

I've written up an overview how the app currently notifies of a new version here: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/VERSIONS.md

**Comment by jordantrizz** [comment]
It's been programmed into my brain that there will always be a version number somewhere within an application that can be used to reference changelogs and Github issues. I understand it's important to be on the latest version, but it's also good to know if and when a change or bug was introduced. Also good to know if watchtower is busted :) I'll leave this decision in your hands.

**Comment by Data-Monkey** [comment]
Hi, I had the message come up that a newer version is available and the first thing I did was look for my current version number somewhere. Is it really required? Maybe not, but it is a nice to have.

**Comment by jordantrizz** [comment]
You could do something like this

https://stackoverflow.com/questions/51071891/auto-increment-version-number-in-a-python-webserver-with-git
https://stackoverflow.com/questions/17101473/change-version-file-automatically-on-commit-with-git

But what are you using to generate releases? Some ideas.

https://github.com/release-it/release-it
https://github.com/googleapis/release-please
https://github.com/franiglesias/versiontag

Here are some other good reads.

https://towardsdatascience.com/setup-version-increment-and-automated-release-process-591d87ea1221
https://www.sipios.com/blog-tech/tips-for-creating-stunning-software-releases-automatically

**Comment by jokob-sk** [comment]
Hi,

Thanks!

I'm using the current date as the release number. I would need github actions to pick up the current release tag.

Not sure if the above approaches applie in that case.

J

**Comment by jordantrizz** [comment]
> I'm using the current date as the release number. I would need github actions to pick up the current release tag.

What about moving to semantic versioning?

> Edit: I went thru the linked articles and regrettably, none seem to provide a solution to embed the current release tag into the app.

I see right now you're using isNewVersion():  which ./front/buildtimestamp.txt and compares it the published_at field on https://api.github.com/repos/jokob-sk/Pi.Alert/releases

I put in a pull request to print out the buildtimestamp.txt into the footer and .VERSION file.

You can use this to add the git tag into the .VERSION file https://github.com/marketplace/actions/write-version-to-file

**Comment by jordantrizz** [comment]
Thanks for merging it. You can now just create a .VERSION file within the root of the repository with the release number.

**Comment by jordantrizz** [comment]
@jokob-sk looks like I didn't put a version file in the release, sorry about that I didn't know if you were going to add it or not :(

I've started using Glint for my own projects, and figured it might be helpful for you https://github.com/brigand/glint super easy way to do conventional commits.

I'm also going to implement change https://github.com/adamtabrams/change as a method to generate changelogs but also bump the version number. It's not well documented, but I'm going to try and get it working.

As my workflow is mostly bash/zsh and in a shell, these work for me.

**Comment by jokob-sk** [comment]
>  looks like I didn't put a version file in the release, sorry about that I didn't know if you were going to add it or not :(

All good, it has to be generated as part of the build process. I hope this will do the trick:

https://github.com/jokob-sk/Pi.Alert/blob/8a1e472fede96e96dbf60b155bbf0a14fa4da9a1/.github/workflows/docker_prod.yml#L50

Thanks for the help and good luck with versioning your projects! 😉

**Comment by jordantrizz** [comment]
> All good, it has to be generated as part of the build process. I hope this will do the trick:

I took a look at the code you introduced and saw the .github bits. I might adopt the same. Have you thought about pre-releases for testing?

**Comment by jokob-sk** [comment]
I played with the idea but not sure if worth the effort. Unsure how many people would actually participate in testing and how much overhead it would introduce into the release process.

**Comment by jokob-sk** [comment]
@jordantrizz FYI hit a snag with this approach, will have to investigate further 😅

**Comment by jordantrizz** [comment]
Looks like the .VERSION file is missing?

**Comment by jokob-sk** [comment]
Yes, not sure why the git action didn't create one. Had to roll back for now and I'll give it another go later.

**Comment by jokob-sk** [comment]
Should be included in the latest release > Closing

**Comment by jordantrizz** [comment]
Just noticed it might also be a good idea to include the version number in the log when pialert starts.

**Comment by jokob-sk** [comment]
In release (not yet in logs though - future possible improvement) > Closing for now
