### ISSUE TITLE
Can't figure out how to give devices new icons

### ISSUE THREAD

**Issue by crispybegs** [jokob-sk/Pi.Alert#211]
**Describe the issue**
Just installed pi/alert (very nice btw!). Can't figure out how to change device icons though. I click the link out to fontawesome to find, for example, a raspberry pi logo [like this one](https://fontawesome.com/icons/raspberry-pi?f=brands&s=solid) but whatever I insert into the device icon field (for example, `raspberry-pi`)returns either a blank icon or a crossed rectangle.

**Screenshots**
<img width="392" alt="Screenshot 2023-04-28 at 22 48 28" src="https://user-images.githubusercontent.com/129169122/235259888-e810c55f-4f3f-484a-b158-401ec10396d5.png">

<img width="297" alt="Screenshot 2023-04-28 at 22 48 16" src="https://user-images.githubusercontent.com/129169122/235259931-16ce66b5-0c8d-480c-a232-14852216ffa8.png">

what's the magic secret?

**Comment by jokob-sk** [comment]
Hey there,

Thanks!

I have a default `fa-` prefix in the code, so if you want to use an e.g. brand - prefixed class, e.g. `fa-brands fa-raspberry-pi` enter 'brands fa-raspberry-pi'.

j

**Comment by crispybegs** [comment]
thanks very much @jokob-sk. that worked for the pi.
is there any documention about the icon syntax to use, or it it always `brands fa-[fontawesome-icon-name]`?

**Comment by jokob-sk** [comment]
No problem!

Yes, that's for the brands' specific ones. I will create some simple description and link it instead of linking to the fontawesome website.

**Comment by crispybegs** [comment]
amazing, thank you so much. really loving this so far, great work

**Comment by jokob-sk** [comment]
Glad to hear that!

I drafted a quick documentation entry on Icons, so hope this will clarify the usage: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/ICONS.md

**Comment by crispybegs** [comment]
ahh that's fantastic, thank you so much

**Comment by jokob-sk** [comment]
😉👍
