### ISSUE TITLE
Pi.Alert reports a different device IP than my router

### ISSUE THREAD

**Issue by crispybegs** [jokob-sk/Pi.Alert#212]
I have an imac connected only to wifi. 

It has a static IP allocated from my router of 192.168.1.41.

The router reports it as 192.168.1.41

<img width="494" alt="Screenshot 2023-04-29 at 09 33 40" src="https://user-images.githubusercontent.com/129169122/235293452-acd2667e-4029-49aa-9ef7-227ba36f3e63.png">

But pi.alert reports it as 192.168.1.55

<img width="672" alt="Screenshot 2023-04-29 at 09 34 14" src="https://user-images.githubusercontent.com/129169122/235293554-656d9769-843e-4633-b0f2-7b44bdaa0858.png">

What could be causing this discprepancy? There's nothing in my router listed as 192.168.1.55

<img width="140" alt="Screenshot 2023-04-29 at 09 39 23" src="https://user-images.githubusercontent.com/129169122/235293602-53fa3f07-c535-4f49-bd7b-4a34b54fd6f0.png">

**Comment by jokob-sk** [comment]
Hi,

As you didn't post your `pialert.conf` I'm not sure what discovery method you are using.

Could you please post it?

In general, PiAlert uses one of the methods mentioned in the [main readme](https://github.com/jokob-sk/Pi.Alert#-scan-methods), so the results from these methods can't be influenced.

 You could try to remove the device and see if the new scan pickups the same or a different IP.

You can also verify if the IP is really the one in PiAlert/Router by trying to ping it.

j

**Comment by crispybegs** [comment]
well now i'm completely confused. Both Pi.Alert and Fing report my imac as being at 192.168.1.55. 
When I go into the network setting of the actual imac itself it says its IP address is 192.168.1.41, which is exactly what my router has been told to allocate to it.

192.168.1.41 isn't listed at all in Pi.Alert or Fing. They don't see it at all.
I tried deleting the imac from Pi.Alert but it picked up the exact same thing on a rescan. It knows it's an apple device as well, I can see it in the device details.

BUT ALSO, i can ping both of those IP addresses and get a response!

<img width="634" alt="Screenshot 2023-05-01 at 22 19 23" src="https://user-images.githubusercontent.com/129169122/235533493-02643218-5fdd-4558-b358-2c78df77b033.png">

Does this from my .conf tell you anything?

```
# General
#---------------------------
ENABLE_ARPSCAN=True
SCAN_SUBNETS=['192.168.1.0/24 --interface=eth1','192.168.1.0/24 --interface=enp2s0']
LOG_LEVEL='verbose'
TIMEZONE='Europe/London'
ENABLE_PLUGINS=True
PIALERT_WEB_PROTECTION=False
PIALERT_WEB_PASSWORD='8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92'
INCLUDED_SECTIONS=['internet','new_devices','down_devices','events']
SCAN_CYCLE_MINUTES=5
DAYS_TO_KEEP_EVENTS=90
REPORT_DASHBOARD_URL='http://pi.alert'
DIG_GET_IP_ARG='-4 myip.opendns.com @resolver1.opendns.com'
UI_LANG='English'
```

I'm totally confused by this

**Comment by jokob-sk** [comment]
Does the device in question have ethernet + wifi connections? That is what happens with my Intel NUC sometimes. PiAlert only stores the last reported IP to a unique MAC so this really doesn't seem to be an issue with PiAlert but rather an expected behavior as the device actually uses more than one IP address.

**Comment by crispybegs** [comment]
I did think of that, but the imac is only on wifi, no ethernet attached.
weirdly, after several days of both fing and pi.alert reporting the IP at .55 they both now report it correctly at .41, without me doing anything and without the imac ever restarting since I started looking at this.

¯\_(ツ)_/¯

**Comment by jokob-sk** [comment]
lol, weird... anyway, thanks for the update > closing
