### ISSUE TITLE
Manually Add devices

### ISSUE THREAD

**Issue by dudefoxlive** [jokob-sk/Pi.Alert#213]
I recently started using this after seeing someone suggest it on Reddit. So far I really like it. One of the features that I like is the ability to create a network map. I did run into a small issue. I have a dumb switch connected in between some of my systems. Since the switch is not a managed switch it does not appear on the scans. I would like the ability to manually add a device so that my network map can be correct.

**Comment by jokob-sk** [comment]
I'll join this question with a discussion that was [started here,](https://github.com/jokob-sk/Pi.Alert/discussions/208) so > closing this issue

**Comment by Viper7000** [comment]
I take some devices that I must delete (random MAC) and rename it to switch. After I build my network map with it
