### ISSUE TITLE
Custom icon don't render

### ISSUE THREAD

**Issue by webysther** [jokob-sk/Pi.Alert#215]
**Describe the issue**
Icon vacuum-robot or vacuum dont render even trying put all css like in #156.

I have tried:

```
vacuum-robot 
fa-vacuum-robot
solid fa-vacuum-robot
fa-solid fa-vacuum-robot
```

https://fontawesome.com/icons/vacuum-robot?f=classic&s=solid
https://fontawesome.com/icons/vacuum?f=classic&s=solid

These icons was released on FW 5.12.0
Current version: Font Awesome Free 6.2.1
Solid and brands looks download in network of chrome

Pi-Alert 11b9637363a6 [v23.04.01](https://github.com/jokob-sk/Pi.Alert/tree/v23.04.01)

**Comment by leiweibau** [comment]
The icons are not rendered because they are not part of free icons from fontawesome, which are the only currently supported icons according to docs.

**Comment by jokob-sk** [comment]
closing for now, as above should have answered the original question

**Comment by webysther** [comment]
For who want to change the icon for the pro version in docker create the mount:

```yaml
    /.../custom/css:/home/pi/pialert/front/lib/AdminLTE/bower_components/font-awesome/css:ro
```
