### ISSUE TITLE
Keep same device after change MAC and Vendor changed

### ISSUE THREAD

**Issue by webysther** [jokob-sk/Pi.Alert#217]
Great project, for small lab killed the netbox solution I has before.

I understand the lock device is based on MAC but to fixed new device emerging maybe a simple solution is lock device based on IP when the IP is marked as static, this will be a great progress for docker, because when creating a macvlan with[out] communication of host <--> container in the new version of compose mac address cannot be fixed anymore. I think the final step is creating a flag to make possible to mark which device I want to become ip rather mac based.

Just curious, why vendor is always updated? Make sense is automatic but when changed don't make sense anymore for my point of view.

I look around for this kind of questions, sorry if is too basic.

**Comment by jokob-sk** [comment]
Hi,

Thanks for using this app!

- The IP address can't be used as the MAC is used as the primary IP to link different objects together (e.g. Event history). To use the IP as an alternative ID it would require to rewrite all SQL queries used to retrieve entries in any of the view and for internal matching of records, which is not something I'm planning to implement as the value of such feature isn't in my opinion worth the effort.

- The all device vendors were updated in the original code, but I changed it so now only devices with a missing Vendor will be updated. This was implemented as part of this commit and will be available in the production image after the next release: https://github.com/jokob-sk/Pi.Alert/commit/c74ef127d1d5644ee1b04da7315cb06ad5f08f69

Thanks for reporting!
j

**Comment by webysther** [comment]
> * The all device vendors were updated in the original code, but I changed it so now only devices with a missing Vendor will be updated. This was implemented as part of this commit and will be available in the production image after the next release: [c74ef12](https://github.com/jokob-sk/Pi.Alert/commit/c74ef127d1d5644ee1b04da7315cb06ad5f08f69)

Thanks! Great!

**Comment by webysther** [comment]
@jokob-sk if i start this change you will ken to accept the PR?

**Comment by jokob-sk** [comment]
> The IP address can't be used as the MAC is used as the primary IP to link different objects together (e.g. Event history). To use the IP as an alternative ID it would require to rewrite all SQL queries used to retrieve entries in any of the view and for internal matching of records, which is not something I'm planning to implement as the value of such feature isn't in my opinion worth the effort.

If you are talking about this, then only after **⚠VERY extensive** testing. To give you an idea of the extent of changes, only searching for `dev_MAC` in `pialert.py` has 64 results! Searching for `MAC` yields 204 results. Searching for `MAC` across all files, you get `486`⚠ results in 30 files. On top of that, giving the users an option to pick IP address or MAC as their primary id would result in a lot of bugs. 

Maybe (just thinking here), it would be easier to create:
-  a tool in the Maintenance section to replace an existing MAC with a custom one across the system (a mass search& replace function). This tool/function needs to be callable from the python script (another challenge, or you can keep it as a python function) 
- Then as a second stage of the implementation you could find a way to detect during a scan if a new device is actually an existing one with a changed MAC address and then apply the mass search&replace function for it to use the new MAC address. 

So there you have it, it's actually a pretty significant change to achieve this functionality, with not that much benefit in my opinion. Please read [this comment](https://github.com/jokob-sk/Pi.Alert/issues/118) of you'd like to submit a PR.

**Comment by webysther** [comment]
The second option is what I look in the code, the section with a few SQLs need only a refactor to check before insert the new device, like if have static ip checked and for another constraints, but is needed to remove INSERT-SELECT strategy, but its ok.
