### ISSUE TITLE
MQTT all below 1 line "Pi.Alert"

### ISSUE THREAD

**Issue by poudenes** [jokob-sk/Pi.Alert#219]
Hi ALl,

The MQTT is working. Only they all separate in the list. I know you can add some more info so all become under a nice name.

Here a example of "TooGoodToGo" how he did it:

{
     "name": "TooGoodToGo - Broodhuys Meijer (Verrassingspakket)", 
     "icon": "mdi:food", 
     "state_topic": "homeassistant/sensor/toogoodtogo_9159/state", 
     "json_attributes_topic": "homeassistant/sensor/toogoodtogo_9159/attr", 
     "unit_of_measurement": "portions", 
     "value_template": "{{ value_json.stock }}", 
     **"device": {
          "identifiers": [
                    "toogoodtogo_bridge"
          ], 
          "manufacturer": "Max Winterstein", 
          "model": "TooGoodToGo favorites", 
          "name": "Too Good To Go"
     },** 
     "unique_id": "toogoodtogo_9159"
}

**Comment by jokob-sk** [comment]
Hi there!

Could you please be more specific what you'd like to see added?

Most of the properties are already being passed. Please also remember, I can only send data that is available on a device. With that in mind, you can find the current structure broadcast to the [MQTT server here](https://github.com/jokob-sk/Pi.Alert/blob/3578bbfcadfebfd7f20f5d6bed22d6c4fa1f8f01/back/pialert.py#L2896), if you'd like to submit a PR.  Please read [this comment](https://github.com/jokob-sk/Pi.Alert/issues/118) of you'd like to submit a PR.

Here is the actual code at the time of writing:

```python
message = '{ \
                "name":"'+ sensorConf.deviceName +' '+sensorConf.sensorName+'", \
                "state_topic":"system-sensors/'+sensorConf.sensorType+'/'+sensorConf.deviceId+'/state", \
                "value_template":"{{value_json.'+sensorConf.sensorName+'}}", \
                "unique_id":"'+sensorConf.deviceId+'_sensor_'+sensorConf.sensorName+'", \
                "device": \
                    { \
                        "identifiers": ["'+sensorConf.deviceId+'_sensor"], \
                        "manufacturer": "PiAlert", \
                        "name":"'+sensorConf.deviceName+'" \
                    }, \
                "icon":"mdi:'+sensorConf.icon+'" \
                }'

```

j

**Comment by poudenes** [comment]
That means that every sensor will combined under "PiAlert" But all sensors are separate in the lost

**Comment by jokob-sk** [comment]
Hi,

This is on purpose so that you can easier find all Pi.Alert entities. Also the manufacturer is sometimes unknown so that value would then be blank/unknown making it harder to find these entities.

Let me know if you have an alternative suggestion.

J

**Comment by jokob-sk** [comment]
Closing this for now unless a better suggestion is given
