### ISSUE TITLE
Discord notification not working

### ISSUE THREAD

**Issue by ajmathews** [jokob-sk/Pi.Alert#222]
**Describe the issue**
I've configured a Discord Webhook but every call seems to get back a 400. I believe the JSON is being sent everytime instead of the html payload but I'm not certain if that is the case.

**Paste last few lines from `pialert.log`**

```
[2023-05-07 00:41:34] Process: Wait
[2023-05-07 00:42:29] START Test: REPORT_WEBHOOK
curl-i-XPOST-HContent-Type:application/json-d{"username": "Pi.Alert", "text": "There are new notifications", "attachments": [{"title": "Pi.Alert Notifications", "title_link": "http://pi.alert", "text": "Report Date: 2021-12-08 12:30\nServer:      *********  More Info: \t\n\n\n"}]}https://discordapp.com/api/webhooks/***/*****
[2023-05-07 00:42:29] END Test: REPORT_WEBHOOK
```

**Paste your `pialert.conf` (remove personal info)**

```
# Webhooks
#---------------------------
REPORT_WEBHOOK=True
WEBHOOK_URL='https://discordapp.com/api/webhooks/***/******'
WEBHOOK_PAYLOAD='html'
WEBHOOK_REQUEST_METHOD='POST'
```

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 

```
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/pialert/config:/home/pi/pialert/config
      - ${TEMP_DIR}/pialert/db:/home/pi/pialert/db
      - ${TEMP_DIR}/pialert/logs:/home/pi/pialert/front/log
    environment:
      - TZ=${TZ}
      - HOST_USER_ID=${PUID}
      - HOST_USER_GID=${PGID}
      - PORT=20211
```

`.env` 

```
paste_here
```

**Screenshots**

**Comment by jokob-sk** [comment]
Hi there!

I've just tried this and the notifications seem to work fine with these settings:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/8aa5c293-0b08-43fd-9ef4-4d4c411fec39)


![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/448ca627-8ff0-42fd-a3ec-226bf98ffc0b)

**Comment by ajmathews** [comment]
Thanks @jokob-sk! I changed the url domain from `discordapp` to `discord` and it worked. `discordapp` is what Discord generated for me.
