### ISSUE TITLE
Lost all data with update

### ISSUE THREAD

**Issue by catalans1980** [jokob-sk/Pi.Alert#223]
I'm running pialert in my PC, it's been runnign for a week as a docker container (in a synology NAS, managed and deployed with portainer), and today i found out i update itself (i have watchtower running) and all my config and data was lost (names, email notif, a lot of stuff). Wtf? How can i recover it? why does this happen? How do i prevent from happening?

I see "DB Backups	0 backups were found / total disk usage: 0,00 MB"

https://i.imgur.com/cDsI8Dg.png

**Comment by catalans1980** [comment]
Ok, i think that i left to appoint the db, logs and config data while deploying the container. Added the following info to the deploy stack and now i think it should work:

     volumes:
      - /volume1/docker/pialert/config:/home/pi/pialert/config:rw
      - /volume1/docker/pialert/db:/home/pi/pialert/db:rw
      - /volume1/docker/pialert/logs:/home/pi/pialert/front/log:rw

**Comment by jokob-sk** [comment]
> Ok, i think that i left to appoint the db, logs and config data while deploying the container. Added the following info to the deploy stack and now i think it should work:
> 
> ```
>  volumes:
>   - /volume1/docker/pialert/config:/home/pi/pialert/config:rw
>   - /volume1/docker/pialert/db:/home/pi/pialert/db:rw
>   - /volume1/docker/pialert/logs:/home/pi/pialert/front/log:rw
> ```

Exactly, you need to map these to a permanent location as[ per documentation](https://github.com/jokob-sk/Pi.Alert/blob/main/dockerfiles/README.md#-basic-usage) to not lose data. 

Closing as resolved
