### ISSUE TITLE
DHCP Lease Plugin no longer operates

### ISSUE THREAD

**Issue by Ange11991** [jokob-sk/Pi.Alert#224]
Hi,

Great work on PI.Alert. I have just updated to the latest commit today.

I note the plugin for parsing the dhcp.lease file is no longer working nor reporting under plugins. I have tried changing the dhcp lease file name and generally fiddling about with it, but to no avail.

I always get "No output received from the plugin DHCPLSS" and the log file is empty. Have tried on a fresh deployment too.

The mapping is correctly in place wihtin docker-compose.yml file too.

 [Plugins] display_name: DHCP Leases
     [Plugins] CMD: python3 /home/pi/pialert/front/plugins/dhcp_leases/script.py paths={paths}
     [Plugins] Timeout: 500
/mnt/dhcp1.leases/mnt/dhcp2.leases/mnt/dhcp3.leases
        [Plugins]: Pre-Resolved CMD: python3/home/pi/pialert/front/plugins/dhcp_leases/script.pypaths={paths}
     [Plugins] Executing: python3 /home/pi/pialert/front/plugins/dhcp_leases/script.py paths={paths}
     [Plugins] Resolved : ['python3', '/home/pi/pialert/front/plugins/dhcp_leases/script.py', 'paths=/mnt/dhcp1.leases,/mnt/dhcp2.leases,/mnt/dhcp3.leases']
        [Plugins] No output received from the plugin DHCPLSS - enable LOG_LEVEL=debug and check logs

**Comment by Data-Monkey** [comment]
I have the same problem but I am new to PiAlert and have never had this running before. I changed to DEBUG but got no extra details.

```
     [Plugins] Check if any plugins need to be executed on run type: always_after_scan
     [Plugins] ---------------------------------------------
     [Plugins] display_name: DHCP Leases
     [Plugins] CMD: python3 /home/pi/pialert/front/plugins/dhcp_leases/script.py paths={paths}
     [Plugins] Timeout: 5
/mnt/fake-dhcp.leases
        [Plugins]: Pre-Resolved CMD: python3/home/pi/pialert/front/plugins/dhcp_leases/script.pypaths={paths}
     [Plugins] Executing: python3 /home/pi/pialert/front/plugins/dhcp_leases/script.py paths={paths}
     [Plugins] Resolved : ['python3', '/home/pi/pialert/front/plugins/dhcp_leases/script.py', 'paths=/mnt/fake-dhcp.leases']
        [Plugins] No output received from the plugin DHCPLSS - enable LOG_LEVEL=debug and check logs
```

The content of /mnt/fake-dhcp.leases is:
```
root@c37cf4981d90:/# cat /mnt/fake-dhcp.leases
1683363111 B8:3E:59:01:CB:F0 192.168.1.2 TV_Switch_Hub
1683363111 0C:56:5C:3B:66:A1 192.168.1.3 OFFICE_Switch_Hub
```

**Comment by Data-Monkey** [comment]
OK, so my problem was that I thought the piHole file format would work here, but it does not!
It should be like the one here: https://askubuntu.com/questions/819536/change-the-dhcp-lease-table-with-script-sed

and mine now looks like this:

```
lease 192.168.1.2 {
    hardware ethernet 00:00:00:00:00:A0;
    uid 00:00:00:00:00:00;
    client-hostname "TV_Switch_Hub";
    binding state active;
}

lease 192.168.1.3 {
    hardware ethernet 00:00:00:00:00:A1;
    uid 00:00:00:00:00:A1;
    client-hostname "TV_Switch_Hub";
    binding state active;
}
```

make sure the binding state line is there, it wouldn't work without for me. 
All good from my side now!

**Comment by jokob-sk** [comment]
Thanks @Data-Monkey for the tip!
@Ange11991 can you double check it's not a data structure issue? You can try using @Data-Monkey 's sample data from the post above.

**Comment by Ange11991** [comment]
Thank you very much @Data-Monkey & @jokob-sk this has addressed the issue. Now reporting correctly across the board and adding to the database.

Now to format the file correct...eek.
