### ISSUE TITLE
unable to delete the device

### ISSUE THREAD

**Issue by voxie12** [jokob-sk/Pi.Alert#228]
![image](https://github.com/jokob-sk/Pi.Alert/assets/65469239/8763d772-27b1-4335-a204-83457ce7fc41)

seems i cant delete this device, how do i remove it?

**Comment by jokob-sk** [comment]
Hi!

Can you please follow the issue template and post your config, log and docker compose file?

Please also read this thread https://github.com/jokob-sk/Pi.Alert/issues/202

Thanks,
J

**Comment by crispybegs** [comment]
i have exactly this that appeared a few days ago. also can't delete it

<img width="1214" alt="Screenshot 2023-05-12 at 10 22 29" src="https://github.com/jokob-sk/Pi.Alert/assets/129169122/2eac8947-61ab-4fb3-b9dd-7f9be11fbf19">

**Comment by jokob-sk** [comment]
Hummm, I'll have a look at where to prevent this value to be inserted in the code. In the meantime, try this as a workaround:

(make sure you have a backup of the DB/config/original CSV etc.)

1) Export your devices via `Maintenance > Backup / Restore > CSV Export`
2) Remove the incorrect entry.
3) Import the modified CSV file via `Maintenance > Backup / Restore > CSV Import`

Hope this helps,
j

**Comment by crispybegs** [comment]
> Hummm, I'll have a look at where to prevent this value to be inserted in the code. In the meantime, try this as a workaround:
> 
> (make sure you have a backup of the DB/config/original CSV etc.)
> 
> 1. Export your devices via `Maintenance > Backup / Restore > CSV Export`
> 2. Remove the incorrect entry.
> 3. Import the modified CSV file via `Maintenance > Backup / Restore > CSV Import`
> 
> Hope this helps, j

that got rid of it, thanks @jokob-sk

**Comment by jokob-sk** [comment]
In the latest release > closed
