### ISSUE TITLE
excessive cpu load

### ISSUE THREAD

**Issue by jaymz668** [jokob-sk/Pi.Alert#230]
just updated to the latest release over the weekend from a february release and the CPU load on the host went insane

looking at it, it's a memory hog
used 17GB of ram before it took the server down

**Comment by jokob-sk** [comment]
Hi!

I'll need more info to determine the issue. 

Can you please post the last few lines of the pialert.log file?

Can you please post the pialert.conf file?

Can you please try to delete the log files?

Also try disabling the plugins by setting ENABLE_PLUGINS to false.

Thanks,
J

**Comment by jaymz668** [comment]
following up on this, MY high CPU was because my NIC changed name with a new NIC installed and it started acting correctly again when I modified the NIC to monitor to the new name

**Comment by jokob-sk** [comment]
Cool, thanks for the update > closing for now as solution provided
