### ISSUE TITLE
Getting "Error: Email service not set up correctly"

### ISSUE THREAD

**Issue by vladaurosh** [jokob-sk/Pi.Alert#234]
**Describe the issue**

Getting error message:
"Error: Email service not set up correctly"

Not using authentication (meaning user and pass are not used) but code from below checks for both and if empty throws an error.
```
def check_config(service):

    if service == 'email':
        if SMTP_PASS == '' or SMTP_SERVER == '' or SMTP_USER == '' or REPORT_FROM == '' or REPORT_TO == '':
            mylog('none', ['    Error: Email service not set up correctly. Check your pialert.conf SMTP_*, REPORT_FROM and REPORT_TO variables.'])
            return False
        else:
            return True
```

This doesn't make sense because if not using authentication these 2 can be empty. If I put anything for user and pass, email sending works fine.

**Paste last few lines from `pialert.log`**
   
> You can use `tail -20 /home/pi/pialert/front/log/pialert.log`

```
Changes detected, sending reports
Error: Email service not set up correctly. Check your pialert.conf SMTP_*, REPORT_FROM and REPORT_TO variables.
```

**Paste your `pialert.conf` (remove personal info)**

```
REPORT_MAIL=True
SMTP_SERVER='myhostname'
SMTP_PORT=587
REPORT_TO='my@email.com'
REPORT_FROM='Pi.Alert <my@email2.com>'
SMTP_SKIP_LOGIN=True
SMTP_USER=''
SMTP_PASS=''
SMTP_SKIP_TLS=False
SMTP_FORCE_SSL=False
```

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 

```
paste_here
```

`.env` 

```
paste_here
```

**Screenshots**

**Comment by jokob-sk** [comment]
Thanks, didn't know you can have unauthenticated SMTP servers, will be fixed in the next release or you can download the [dev image](https://registry.hub.docker.com/r/jokobsk/pi.alert_dev) after this build finishes: https://github.com/jokob-sk/Pi.Alert/actions/runs/5035030350

**Comment by vladaurosh** [comment]
Thanks for quick reply. :)

Yes, I am using local postfix server with no authentication (which relays to sendgrid).

**Comment by jokob-sk** [comment]
In the latest release > closed
