### ISSUE TITLE
Support for Blocky

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/Pi.Alert#241]
### Discussed in https://github.com/jokob-sk/Pi.Alert/discussions/240

<div type='discussions-op-text'>

<sup>Originally posted by **atcasanova** May 30, 2023</sup>
As you already support PiHole, I guess blocky would be a nice addition down the road.

https://github.com/0xERR0R/blocky

</div>

**Comment by jokob-sk** [comment]
Could be implemented as a plugin. Open for the taking if someone wants to submit a PR.

FYI there is current a PR freeze on the pialert.py file due to some ongoing work. Follow the PR guidelines of this project.

Thanks!

**Comment by Data-Monkey** [comment]
From PiHole the DHCP features are used to determine the devices on the network, not actually the DNS part of PiHole. 
Looking at the decumentation of Blocky I don't see any DHCP option there. Is there a way Blocky can provie a list of devices on the network?

**Comment by jokob-sk** [comment]
I do not see any API that can be leveraged to interface with Blocky so closing this for now.
