### ISSUE TITLE
Before send a notification for down devices, add an option to wait X rounds.

### ISSUE THREAD

**Issue by pabloalcantara** [jokob-sk/Pi.Alert#242]
**Is your feature request related to a problem? Please describe.**
Before send a notification for down devices, add an option to wait X (configurable) rounds.

**Describe the solution you'd like**
An option for each device to set an amount X for passes before notifications.

**Describe alternatives you've considered**
For example: I set 3 times before notification, It failed the first and the second time, but on the third pass the devices responds. And the notifications is not sent.
Only sent the notifications if 3 failures in a row.

**Comment by jokob-sk** [comment]
I'm leaning towards won't fix because it probably requires a DB modification (or temporary variable). 

Can you elaborate how important this feature is for you and WHY it is that important?

AN alternative is not to monitor a device or to increase the delays between scans.

**Comment by pabloalcantara** [comment]
I have many devices for home automation, and it's important to know when they're down. The problem is that as they are stremmely low power, some times it ignores the scan and don't response the query. The way it works now, I contatly receives false positive notifications.
Infornutaly I don't program in PHP, but I think you coukd add an item on the device to count every time it can't be contacted, and zero when the devices respond.

**Comment by jokob-sk** [comment]
Note to myself: 

If implemented consider also:

https://github.com/jokob-sk/Pi.Alert/discussions/262

**Comment by jokob-sk** [comment]
+1 by @D3SOX  in #451

**Comment by D3SOX** [comment]
@jokob-sk Can you implement such a feature in the near future? I'm willing to make a one-time donation for it. Otherwise, I can try creating a PR myself, but it would require me to get familiar with the codebase.

**Comment by jokob-sk** [comment]
@D3SOX Hold off with the donation once I release it ;)

**Comment by D3SOX** [comment]
Yup, I'm looking forward to it. Thanks for your quick responses.

**Comment by jokob-sk** [comment]
This will require a bit more work and some changes to the core app, so it might take a bit, because I might implement is as part of a bigger feature release. I don't like doing one-off features, but rather something that enables a broader set of use-cases. Keep checking the release notes :)

**Comment by jokob-sk** [comment]
WIll be available in the next release (you can test it in the `_dev` image):

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/1b862e87-7463-4fcc-8ed6-4a0f3ac287f8)

**Comment by pabloalcantara** [comment]
Thanks, but I´m using the docker container. As soon as it´s release on you docker hub repo, i´ll test it.

**Comment by D3SOX** [comment]
Even with a new config/DB the settings do not show for me

![image](https://github.com/jokob-sk/Pi.Alert/assets/24937357/b74154a1-8fe9-4f1a-a3d9-f0c5ad14fb85)

**Comment by jokob-sk** [comment]
Can you please try to use a different browser? I think it's a caching issue

**Comment by D3SOX** [comment]
Oh you're correct, should've tried a CTRL+F5 before. It shows fine now

**Comment by jokob-sk** [comment]
Released -> Closing
