### ISSUE TITLE
Improve NMAP Plugin Report

### ISSUE THREAD

**Issue by jordantrizz** [jokob-sk/Pi.Alert#247]
**Is your feature request related to a problem? Please describe.**
The current email report for the nmap plugin lists each port change as a single row in the table. This makes it harder to quickly identify changes.

**Describe the solution you'd like**
For duplicate data in rows, there should be a rowspan to make it more human readable.

**Describe alternatives you've considered**
None are possible.

**Additional context**

![image](https://github.com/jokob-sk/Pi.Alert/assets/345869/e1c7ab49-a8c1-4586-893c-3a61d4bcfa60)

**Comment by jordantrizz** [comment]
I think the DateTimeChange should be rowspan'd and the Watched_Value# columns need to be adjusted to only display a singe column as some of them are null? As well as color code the "Status" column cells.

**Comment by jordantrizz** [comment]
I'd be good with null's being hidden, sounds like the whole reporting system needs to be rebuilt ;)

**Comment by jokob-sk** [comment]
Cool, `null` values should be fixed in the next release.

Re: Report system rebuilt - if someone isn't valuing their free time, be my guest :)

**Comment by jordantrizz** [comment]
> Re: Report system rebuilt - if someone isn't valuing their free time, be my guest :)

Exactly, would there not be something that could be bolted on, that could deal with displaying data using templates? Have you thought about moving to Laravel for the PHP side of things?

**Comment by jokob-sk** [comment]
Probably possible, but not sure if worth the effort. Not something that I'm planning to do. PRs are welcome though, although there is a lot of legacy functionality that needs to be preserved.

**Comment by jokob-sk** [comment]
In the latest release > closed
