### ISSUE TITLE
feature: allow autodeletion of new devices after X time

### ISSUE THREAD

**Issue by sbe-arg** [jokob-sk/Pi.Alert#250]
**Is your feature request related to a problem? Please describe.**

Would be awesome to have a way to auto remove unapproved devices ( by unapproved I mean those devices that remain marked as `new device` ) after X time so you can leverage the notifications every time those devices come back without having to cleanup the lists all the time.

I do a lot of testing of devices and also use a guest network extensively, would be really nice feature to avoid manual cleaning.

**Describe the solution you'd like**
settings option to autoremove `new devices` after X hours.

**Describe alternatives you've considered**
haven't tried anything out of the box

**Comment by jokob-sk** [comment]
Thanks for the suggestion!

So to understand the request, you'd like an option for the devices that are marked `New Device` after X hours (configurable) after the first time a device was detected to be deleted.

How about if a deleted device gets detected again after it is deleted? I'd assume the normal detection loop is run, Keeping a database of deleted devices would grow the Devices table pretty quickly I assume in your use case.

**Comment by sbe-arg** [comment]
Thnks for the quick reaponse.

By the way love this tool.

There is a setting for deleting older entries on events I assume I have set everything to 3 weeks retentions I have a 12mb db or I'm missing something that some data gets stored in db even post retention?

But yes your understanding is correct ideally if devices are found again they might be deleted again if are temporary devices. The main even is to keep receiving notifications for this casual devices or guests without having to handle the cleaning manually.

**Comment by jokob-sk** [comment]
Will be in the next release - feel free to test it in the _dev image 😉

**Comment by jokob-sk** [comment]
Should be included in the latest release > Closing
