### ISSUE TITLE
Logs not visible in UI

### ISSUE THREAD

**Issue by vladaurosh** [jokob-sk/Pi.Alert#255]
**Describe the issue**
Logs not visible in UI. Found in maintenance.php this line:
`<?php echo file_get_contents( "./log/pialert.log", false, null, -200000); ?>`
which should start from 200 000th char from the end of file and show everything till the end of file. If I see this to -20000 I get some lines from the file.
By default it seems there's one blank line, visible on screenshot. File normally opens when I click on the icon.

Latest 23.6.16 version. 

**Paste last few lines from `pialert.log`**
```
19:13:03 [Notification] Notifications changes: 0
19:13:56 [Process Scan] Print Stats
19:13:56 [Process Scan] Stats end
19:14:59 [Process Scan] Print Stats
19:14:59 [Process Scan] Stats end
19:16:03 [Process Scan] Print Stats
19:16:03 [Process Scan] Stats end
19:16:03 [Notification] Notifications changes: 0
```
> You can use `tail -20 /home/pi/pialert/front/log/pialert.log`

```
paste_here
```

**Paste your `pialert.conf` (remove personal info)**

```
paste_here
```

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 

```
paste_here
```

`.env` 

```
paste_here
```

**Screenshots**
![image](https://github.com/jokob-sk/Pi.Alert/assets/47857324/17c67207-5857-4bae-8298-eccb2ecc4da2)

**Comment by jokob-sk** [comment]
Thanks for the report! 

Should be fixed in the next release.

**Comment by jokob-sk** [comment]
Should be included in the latest release > Closing
