### ISSUE TITLE
Some custom names do not stick

### ISSUE THREAD

**Issue by s33d1ing** [jokob-sk/Pi.Alert#259]
**Describe the issue**

I have many devices that show up with the name "(name not found)". After editing the name, some devices save the custom name, but some revert to "(name not found)". Are edited named supposed to persist?

**Paste last few lines from `pialert.log`**

> You can use `tail -20 /home/pi/pialert/front/log/pialert.log`

```
paste_here
```

**Paste your `pialert.conf` (remove personal info)**

```
paste_here
```

**Paste your `docker-compose.yml` and `.env` (remove personal info)**

`docker-compose.yml` 

```
paste_here
```

`.env` 

```
paste_here
```

**Screenshots**

![image](https://github.com/jokob-sk/Pi.Alert/assets/3750598/825f19c9-d511-4db6-b296-dca0a3856528)

**Comment by jokob-sk** [comment]
Hi there!

Could you please verify the names are saved once you click the save button navigate back to the device later?

I haven't happened to me before so hard to debug without additional information. 

Are there any patterns between the devices that revert back? 

Thanks, 
J

**Comment by s33d1ing** [comment]
Hi J,

Sorry for the lack of information, but I didn't feel that the logs or docker compose file had any useful information for this issue. I did some more testing and have some additional information for you.

I made sure that the names were saved after clicking the save button then and navigating back to devices. However, after the active scans finished running, almost all of them reverted back to "(name not found)".

I disabled all currently enabled scans (ARP, Pholus, and Nmap), waited for them to finish, then renamed all unnamed devices. I let it sit for a while and the names were still there. As a side note, this caused all of the devices to show as offline, but I assume that is by design since no scans were running.

After re-enabling the scans, and letting them run a few times, the custom names seemed to persist. I guess we could close the issue now unless you would like any additional information.

**Comment by jokob-sk** [comment]
Hi @s33d1ing ,

Thanks for the additional info and testing. I'm glad the issue got resolved. I'll keep this in mind if a similar issue occurs, and then your test results may be really useful to figure out if there is a bug hidden in the code.

I'll close this for now,
Thanks,
j
