### ISSUE TITLE
Add Virtual Host type

### ISSUE THREAD

**Issue by s33d1ing** [jokob-sk/Pi.Alert#260]
**Is your feature request related to a problem? Please describe.**
In order to add devices as a network node, the parent device has to be of type "AP, Firewall, Gateway, PLC, Powerline, Router, Switch, USB LAN Adapter, USB WIFI Adapter and WLAN". I have an Unraid server and Raspberry Pi running Docker containers and virtual machines. I would like to assign the parent network to the server without changing the parent server's type to something like "Switch". 

**Describe the solution you'd like**
Create a "Hypervisor" (or similar) type that allows selectable Network nodes.

**Describe alternatives you've considered**
Change the type of  my Unraid server or Raspberry Pi type to switch.

**Comment by jokob-sk** [comment]
Hi!

Thanks for the suggestion.

`Hypervisor` has been added and will be in the next release. Handling (maintaining) the list of network device types is a bit of pain right now so if anyone reading wants to create e.g. a Setting that is used as a source of truth for network-type devices, please submit a PR. It's mostly python and jquery(javascript) code and this commit is a good reference point where things have to change:

https://github.com/jokob-sk/Pi.Alert/commit/c61a5bedcf18bc71cda448787ddb601275c76396

Thanks,
j

**Comment by qJake** [comment]
Just ran into the same issue setting up Pi.Alert, I have an ESXi host as part of my home lab. Would be nice to have a Hypervisor category.

**Comment by jokob-sk** [comment]
Should be included in the latest release > Closing
