### ISSUE TITLE
fork of your repo started a workflow

### ISSUE THREAD

**Issue by Data-Monkey** [jokob-sk/Pi.Alert#266]
**Describe the issue**
Hi,
I updated my fork of your repo and after I committed to my branch it tried to run a workflow.
see error here: https://github.com/Data-Monkey/Pi.Alert/actions/runs/5363505013

is there a way you can set it up so it won't run from someone else's repo?

**Comment by jokob-sk** [comment]
GHood point!

This should have fixed this: 

https://github.com/jokob-sk/Pi.Alert/blob/abe9ff5b2cccd2be58442fc1b783268dd7461012/.github/workflows/docker_dev.yml#L23
