### ISSUE TITLE
Devices details page has "--" for every field except for Comments.  Can not edit device.

### ISSUE THREAD

**Issue by helix26j** [jokob-sk/Pi.Alert#269]
I have only one device I cannot edit thus cannot mark not New, nor turn off notifications.  There seems to be an issue with how the device is stored, perhaps by device name as it does not match what is received in the Pholus scan?

Devices details page has "--" for every field except for Comments.  The device details cannot be edited in any way.

Pholus scan of IP shows Answer entry:
`Answer	222.5.168.192.in-addr.arpa. PTR Class:32769 "001788121314.local."`

This name does not match what is seen in the device list, it seems the preceeding zeros are stripped:
`17881213	(unknown)					2023-06-11   14:05	2023-06-24   16:22	192.168.5.222		New	00:17:88:12:13:14	3232236260	94				Philips Lighting BV`

Events tab only has Connected/Disconnected events with correct IP.
Sessions page is updated normally and shows IP address
Presence tab is populated normally as device is found during scan.

I'm not sure how useful the pialert.log will be, the Philips Hue hub is the only device with the issue.
16:56:26 [PholusScan] Scan: Pholus SUCCESS
16:56:26 [MAIN] cycle:1
16:56:26 [Network Scan] Scan Devices:
16:56:26 [Network Scan] arp-scan start
16:56:37 [Network Scan] arp-scan ends
16:56:37 [Network Scan] Pi-hole start
16:56:37 [Process Scan]  Processing scan results
16:56:38 [Process Scan] Print Stats
16:56:38 [Scan Stats]    Devices Detected.......: 26
16:56:38 [Scan Stats]        arp-scan detected..: 23
16:56:38 [Scan Stats]        Pi-hole detected...: +0
16:56:38 [Scan Stats]        New Devices........: 0
16:56:38 [Scan Stats]    Devices in this cycle..: 25
16:56:38 [Scan Stats]        Down Alerts........: 0
16:56:38 [Scan Stats]        New Down Alerts....: 0
16:56:38 [Scan Stats]        New Connections....: 2
16:56:38 [Scan Stats]        Disconnections.....: 1
16:56:38 [Scan Stats]        IP Changes.........: 0
16:56:38 [Process Scan] Stats end
16:56:38 [Process Scan] Updating DB Info
16:56:38 [Process Scan] Sessions Events (connect / discconnect)
16:56:38 [Process Scan] Creating new devices
16:56:38 [Process Scan] Updating Devices Info
16:56:38 [Mac Vendor Check] Error: b''
16:56:38 [Mac Vendor Check] Error: b''
16:56:38 [Process Scan] Resolve devices names
16:56:38 [Update Device Name] Trying to resolve devices without name
16:56:38 [Update Device Name] Pholus entries from prev scans: 72
16:56:38 [Update Device Name] Names Found (DiG/Pholus): 0 (0/0)
16:56:38 [Update Device Name] Names Not Found         : 4
16:56:38 [Process Scan] Voiding false (ghost) disconnections

Pholus log entry:
`00:17:88:12:13:14 | 192.168.5.222               | Answer              | 222.5.168.192.in-addr.arpa. PTR Class:32769 "001788121314.local."`

**Comment by jokob-sk** [comment]
Hi there!

1) Could you please check if there is any error in the browser console? Please follow the steps here:

https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_INVALID_JSON.md

2) Could you please provide a few explanatory screenshots?

Thanks!
j

**Comment by helix26j** [comment]
The browser developer tools did indicate an error referencing dev_Name.

Could this be because the entire dev_Name provided by the Philips Hue device is numerical?  The MAC address contains no hex digits above 9.  This is the only device and if delete all and start over this device persists to have this issue.

The link when selecting the name 17881213 from the devices list:
https://pialert.dc.domain.home.arpa/deviceDetails.php?mac=00:17:88:12:13:14

from getDeviceData, the contents appear what should appear in the Details tab but do not (error follows):

`{"rowid":94,"dev_MAC":"00:17:88:12:13:14","dev_Name":17881213,"dev_Owner":"(unknown)","dev_DeviceType":null,"dev_Vendor":"Philips Lighting BV","dev_Favorite":0,"dev_Group":null,"dev_Comments":null,"dev_FirstConnection":"2023-06-11   14:05","dev_LastConnection":"2023-06-24   17:52","dev_LastIP":"192.168.5.222","dev_StaticIP":0,"dev_ScanCycle":1,"dev_LogEvents":1,"dev_AlertEvents":1,"dev_AlertDeviceDown":0,"dev_SkipRepeated":0,"dev_LastNotification":"2023-06-24 17:52:25.103264","dev_PresentLastScan":1,"dev_NewDevice":1,"dev_Location":null,"dev_Archived":0,"dev_Network_Node_MAC_ADDR":null,"dev_Network_Node_port":null,"dev_Icon":null,"dev_Status":"On-line","dev_RandomMAC":0,"dev_Sessions":16,"dev_Events":2,"dev_DownAlerts":0,"dev_PresenceHours":17}`

```
deviceDetails.php?mac=00:17:88:12:13:14:1752 Uncaught TypeError: deviceData.dev_Name.indexOf is not a function
    at Object.success (deviceDetails.php?mac=00:17:88:12:13:14:1752:32)
    at c (jquery.min.js:2:27742)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:28487)
    at l (jquery.min.js:2:78789)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:81117)
```

There is not much in the screenshot of the device page itself.
![Pi Alert at 2023-06-24 19-23-18](https://github.com/jokob-sk/Pi.Alert/assets/43703247/963f947b-3815-4e48-bc0b-74dd13b883e1)

**Comment by jokob-sk** [comment]
Thanks for the details! This helped.

It will be fixed in the next release or you can test it in the dev image:

https://registry.hub.docker.com/r/jokobsk/pi.alert_dev

J

**Comment by helix26j** [comment]
Tried the dev image and it works, the device now displays correctly and updates successfully when edited.

Thanks

**Comment by jokob-sk** [comment]
Should be included in the latest release > Closing
