### ISSUE TITLE
Rename the Activity over the last 12H chart

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/Pi.Alert#27]
Rename to something like "Activity over the last x scans" as per https://github.com/jokob-sk/Pi.Alert/commit/567472a51be04a202637d75b9be1a4845f73279c#commitcomment-78721186

**Comment by jokob-sk** [comment]
Renamed to "Device presence over time "

**Comment by corasaniti** [comment]
With the new version, Does the section "Device presence over time" show  more than the last 24H? Right?
Thank you

**Comment by jokob-sk** [comment]
Hi @corasaniti !

It shows last 144 entries. So the time frame depends on the frequency of the scans you've configured in settings.

**Comment by leiweibau** [comment]
Of course, you could also increase the value, but depending on the display size on which you view the page, more values no longer make sense.
