### ISSUE TITLE
Wrong format in Discord notification message

### ISSUE THREAD

**Issue by adebrouvier** [jokob-sk/Pi.Alert#271]
**Describe the issue**
After updating to 23.6.16 the Discord webhook message is no longer displayed correctly.

**Screenshots**
![image](https://github.com/jokob-sk/Pi.Alert/assets/12373856/68c014f1-5409-440f-9b3e-6902dc34c304)

![image](https://github.com/jokob-sk/Pi.Alert/assets/12373856/19366694-3e54-432d-8d24-d80d8c5765a9)

**Comment by vipinpg** [comment]
Yes, Discord is showing raw html data for all the Alerts now.

**Comment by smrodman83** [comment]
> **Describe the issue** After updating to 23.6.16 the Discord webhook message is no longer displayed correctly.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/12373856/249206029-68c014f1-5409-440f-9b3e-6902dc34c304.png)
> 
> ![image](https://user-images.githubusercontent.com/12373856/249205070-19366694-3e54-432d-8d24-d80d8c5765a9.png)

Same here. Fell back to email alerts for now

**Comment by Data-Monkey** [comment]
the method used to be this:

```
    # use data type based on specified payload type
    if WEBHOOK_PAYLOAD == 'json':
        payloadData = _json        
    if WEBHOOK_PAYLOAD == 'html':
        payloadData = _html
    if WEBHOOK_PAYLOAD == 'text':
        payloadData = to_text(_json)
```

but what I see now is that the method was always called with mail_text in the HTML parameter.
`send_webhook (json_final, mail_text)`

the pialert/publishers/webhook.py needs to be updated

```
    if conf.WEBHOOK_PAYLOAD == 'html':
        payloadData = msg.text
```

this is my hunch and not tested because I can't test it at the moment.

**Comment by jokob-sk** [comment]
Hey,

I've changed the way webhooks work and now the recommended payload format for discord is `text`. You can test this by using the dev image:

https://registry.hub.docker.com/r/jokobsk/pi.alert_dev

Thanks,
j

**Comment by masterwishx** [comment]
Waiting for latest docker version :) with fix ...

**Comment by jokob-sk** [comment]
Should be included in the latest release > Closing
