### ISSUE TITLE
Backup folder

### ISSUE THREAD

**Issue by tamimology** [jokob-sk/Pi.Alert#272]
**Is your feature request related to a problem? Please describe.**
DB backups to have a folder mounted other than the `/home/pi/pialert/db/`

**Describe the solution you'd like**
The reason is to be able to have that folder only somewhere else not on the same machine running pialert, in case of something went wrong, db is still their when restoring

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jokob-sk** [comment]
Hi there,

Thanks for the suggestion.

I was thinking about this for a while and I think it should be handled by an underlying backup solution, such as duplication, kopia or at least syncthing.

So I'm leaving towards leaving it as is for now unless there is another reason to have a different folder?

I'll keep this open for a while if you have any feedback.

Thanks,
J

**Comment by jokob-sk** [comment]
Closing for now
