### ISSUE TITLE
New device configuration defaults 

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/Pi.Alert#274]
Hi

Many thanks for the response.  Honestly, the way the notifications themselves work is absolutely spot on from my perspective.  The feature I would love to see would be the ability to set a default "New Device" notification profile to change the defaults.

Currently, any new device is set to:

Scan Device: Yes
Alert All Events: Checked
Alert Down: Checked
Skip Repeated Notifications for: 0h (All Events)
New Device: Checked
Archived: Unchecked

I would love to have some control over these options when a New device is detected.   

Personally, I would love to just have  a single notification to tell me that a New Device has hit the network (that wouldn't repeat more than 1 time per hour) and then have the ability to have everything else turned off (except for the New Device flag)

Other than that, I genuinely like the notification options as it allows me to monitor all of my devices.

Many thanks

_Originally posted by @PureLoneWolf in https://github.com/jokob-sk/Pi.Alert/discussions/262#discussioncomment-6300719_

**Comment by jokob-sk** [comment]
Alright,

@PureLoneWolf you can test this by using the dev image:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/760c28de-4660-462c-b83d-dc26959d155d)

https://registry.hub.docker.com/r/jokobsk/pi.alert_dev

I only tested this with `arp-scan` not pihole or pihole-dhcpleases methods so anyone reading, please test this if possible.

Thanks,
j

**Comment by PureLoneWolf** [comment]
Thanks - I just need to get the dev image installed into Unraid :)

**Comment by jokob-sk** [comment]
Should be included in the latest release > Closing
