### ISSUE TITLE
Allow Copying Device Details

### ISSUE THREAD

**Issue by qJake** [jokob-sk/Pi.Alert#276]
**Is your feature request related to a problem? Please describe.**

I am working on setting up Pi.Alert on my home network, where I have 80+ devices. Setup is slow and tedious, when I have many similar IP cameras, or Amazon Echo devices, or WiFi Smart Plugs.

Setting the Owner, Type, Icon, Group, and Location over and over again is very tiresome!

**Describe the solution you'd like**

On the "Details" page, have an area with a dropdown that says *Copy settings from:* [ -choose device- ▼ ] [Copy] that would allow me to select another device from the dropdown, and when I click "Copy", it will auto-fill all of the information in the "Details" tab with the info from that other device. (It should do this client-side, so that I still can make adjustments and finally press "Save".)

Because all of my cameras are identical except for their names. All of my smart plugs are identical except for their names. You get the idea. 🙂 

**Describe alternatives you've considered**

I am not sure how else to do this except manually typing each entry out, which is not ideal for this many devices.

**Additional context**

Here's a mockup of what I'm sort of envisioning:

![image](https://github.com/jokob-sk/Pi.Alert/assets/652006/9a1dba58-3552-4ecc-b16f-a2604d0ac183)

**Comment by jokob-sk** [comment]
Thanks for the suggestion!

Server-side device details copy will be available in the next release. A client-side implementation would be too complex. 

Feel free to test it in the _dev image.

j

**Comment by jokob-sk** [comment]
Should be included in the latest release > Closing
