### ISSUE TITLE
Add "Clear New Flag from All Devices" Tool Button

### ISSUE THREAD

**Issue by qJake** [jokob-sk/Pi.Alert#277]
**Is your feature request related to a problem? Please describe.**

When setting up the app for the first time, on larger networks, it is tedious to go through one-by-one and disable the "New Device" flag.

**Describe the solution you'd like**

A button on the tool page to clear the "New Device" flag from all devices, as a one-time operation.

**Describe alternatives you've considered**

Editing 80+ devices by hand takes quite a long time. 🙂 

**Additional context**

Here's a mockup of what I was thinking:

![image](https://github.com/jokob-sk/Pi.Alert/assets/652006/c2093b67-8075-4835-b754-6950695f081f)

**Comment by jokob-sk** [comment]
Hey!

You can use the CSV export > Mass replace > CSV import approach to perform bulk actions. Use e.g Notepad ++ to preserve line endings.

Thanks,
j

**Comment by qJake** [comment]
Oh, I didn't think of that... That's a good workaround. I'm a developer, so that makes sense to me, but I know it may confuse some other folks.

If I have some spare time, I will try to implement this and submit a PR!

**Comment by jokob-sk** [comment]
Cheers in advance for the PR!

I'll close this for now.

**Comment by jokob-sk** [comment]
FYI Multi-edit support is coming in the next release, for more info on how to test if interested, please check: #571
