### ISSUE TITLE
Network Graph: Add Port Number / Group and Sort By Port Number

### ISSUE THREAD

**Issue by qJake** [jokob-sk/Pi.Alert#278]
**Is your feature request related to a problem? Please describe.**

If I'm configuring the devices on a switch, and entering in all of the port numbers on the switch, I would expect to be able to visualize that information.

**Describe the solution you'd like**

If a device has at least one child device with a port number assigned, then the network graph should be grouped and sorted by port number. I want to see the port numbers listed in sequential order, and the devices on that port should be grouped together (with some space in between each port).

**Describe alternatives you've considered**

I don't know of any.

**Additional context**

Here's a screenshot of the issue - as of right now, the devices are grouped/spaced together in a seemingly random order, even with ports assigned:

![image](https://github.com/jokob-sk/Pi.Alert/assets/652006/f12df83e-6b88-4f5f-9367-2d02e84e5970)

Here are the port numbers for each device:

![image](https://github.com/jokob-sk/Pi.Alert/assets/652006/7079bf55-88d8-49fc-81ad-39e31d398825)

So, I think these should be in order, grouped by port, and with the port number visible on the graph somewhere.

**Comment by jokob-sk** [comment]
Hey!

Added the network port into the diagram, I don't plan t implement sorting/grouping for now. Feel free to submit a PR if you'd like to help out :)

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/d960f49c-6940-4da4-ba95-a154c6e9bfe4)


You can test this by using the dev image:

https://registry.hub.docker.com/r/jokobsk/pi.alert_dev

Thanks,
j

**Comment by qJake** [comment]
Awesome, thank you! 😁

**Comment by jokob-sk** [comment]
Should be included in the latest release > Closing
