### ISSUE TITLE
Devices always reporting "new" status

### ISSUE THREAD

**Issue by roger-** [jokob-sk/Pi.Alert#282]
Sorry if this is mentioned somewhere but I've been running Pi Alert for a few weeks and all my devices have their status set to "new". I assumed there would be a timeout after a few days where they'd be marked as something else.

How do I change them from new?

Running latest stable version.

**Comment by sbe-arg** [comment]
Enter to the device details select New Device

![image](https://github.com/jokob-sk/Pi.Alert/assets/23391642/8dc69e4a-4aea-474e-9607-5ed04d5b8da3)

**Comment by jokob-sk** [comment]
Hi!

As @sbe-arg mentioned, this has to be done manually.

The new build (or you can check the `_dev` image), will have a template for new devices where you can uncheck this checkbox.

j

**Comment by jokob-sk** [comment]
This is now available in the production image.

**Comment by jordantrizz** [comment]
I'm confused, so pardon my stupidity here.

I updated to the dev image to fix another issue, and now all new devices are stuck as new devices unless I manually uncheck them. However, I thought this would be done automatically on the next scan? Or must I update the new device template to have this unchecked? If so, will I still get alerts about new devices?

**Comment by jokob-sk** [comment]
@jordantrizz 
That was how it always worked. All new devices are kept new until you manually uncheck it being new. There is a setting to un-mark a device as new after X hours: `HRS_TO_KEEP_NEWDEV`. Also, as yo mentioned, you can adjust the new device template. You still should get alerts about a new device (you can try to test it by deleting one).

**Comment by jordantrizz** [comment]
> That was how it always worked.

I didn't know this, I just setup pialert this year. At which point I would get alert about new devices when new devices were seen and then I wouldn't get another alert about new devices. That's how the notifications work for me. So I'm really confused and wondering what I did or how pialert would even function like this....

> There is a setting to un-mark a device as new after X hours: `HRS_TO_KEEP_NEWDEV`. Also, as yo mentioned, you can adjust the new device template. You still should get alerts about a new device (you can try to test it by deleting one).

Going to do this!

Would there be a faster way to mark all devices as not new? Didn't see a method to mass action devices on the devices page.

**Comment by jokob-sk** [comment]
You can use the CSV Export functionality in the maintenance section.

CSV Export > Modify > CSV Import

Please use an app that keeps Linux line endings, such as Notepad++

**Comment by jordantrizz** [comment]
> There is a setting to un-mark a device as new after X hours: `HRS_TO_KEEP_NEWDEV`. Also, as yo mentioned, you can adjust the new device template. You still should get alerts about a new device (you can try to test it by deleting one).

This worked, set the template to uncheck new device, deleted the device, and then got a new device alert.



> You can use the CSV Export functionality in the maintenance section.
> 
> CSV Export > Modify > CSV Import
> 
> Please use an app that keeps Linux line endings, such as Notepad++
> 
> ps. also backup everything just in case

Awesome. Thanks.

**Comment by jokob-sk** [comment]
Glad I could help - consider sponsoring my work ;) Have a good one!

**Comment by jordantrizz** [comment]
Bought some coffees ;)

**Comment by jokob-sk** [comment]
Thank you ♥ Really appreciate it!

**Comment by roger-** [comment]
I set `HRS_TO_KEEP_NEWDEV` to 48 and it seemed to create some issues (orange part):

<img width="726" alt="image" src="https://github.com/jokob-sk/Pi.Alert/assets/1389709/9f93e720-35ba-4c4a-9bce-778a6ca04b0d">

Basically every hour all my devices were reported as dropped. When I disabled the setting things went back to normal (green).

**Comment by jokob-sk** [comment]
@roger-

Hummm this seems to be a separate problem , can you please open a new issue and I'll investigate as this thread is getting off topic

**Comment by jokob-sk** [comment]
FYI Multi-edit support is coming in the next release, for more info on how to test if interested, please check: #571
