### ISSUE TITLE
404 on this site

### ISSUE THREAD

**Issue by halfagascan** [jokob-sk/Pi.Alert#287]
## Describe the issue
Using GUI, link to: `[Pi.Alert](https://github.com/jokob-sk/Pi.Alert/tree/main)/[front](https://github.com/jokob-sk/Pi.Alert/tree/main/front)/[plugins](https://github.com/jokob-sk/Pi.Alert/tree/main/front/plugins)/snmp_discovery/` goes 404
> When submitting an issue ❗[enable debug](https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_TIPS.md)❗ and [have a look at the docs](https://github.com/jokob-sk/Pi.Alert/tree/main/docs)

[describe your issue]

## Paste your `pialert.conf` (remove personal info)

```
paste_here
```

## Paste your `docker-compose.yml` and `.env` (remove personal info)

`docker-compose.yml` 

```
paste_here
```

`.env` 

```
paste_here
```

## Screenshots

[If applicable, add screenshots to help explain your problem.]

## Paste last few lines from `pialert.log`

> You can use `tail -100 /home/pi/pialert/front/log/pialert.log`

```bash

# paste code below

**Comment by jokob-sk** [comment]
Thanks for the report. Should be fixed now with a workaround.
