### ISSUE TITLE
Possible to add unmanaged switches to network diagram?

### ISSUE THREAD

**Issue by ajtatum** [jokob-sk/Pi.Alert#288]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently, the network diagram shows only devices that have an IP Address (for obvious reasons), but it would be nice if I could add devices, such as unmanaged switches, to my network diagram. This would help as I could make better use of the "Port Number" feature and would be REALLY nice when I'm trying to figure out what cable goes where because I forgot to label it. 

My network diagram currently looks like Router -> Managed Switch -> Client Device, whereas it would be nice if I could do Router -> Managed Switch -> Unmanaged Switch -> Client Device.

**Describe alternatives you've considered**
Labeling cables? Even then it would be nice to have a visual of the network topology through Pi.Alert.

**Additional context**
Not Applicable

**Comment by jokob-sk** [comment]
Hi there,

There is a Plugin called Undiscoverables. It should help you achieve just that.

Thanks,
J
