### ISSUE TITLE
About to consult a "week" "présence" of a "device". Pop up menu not visible on the rigth of the screen 

### ISSUE THREAD

**Issue by Walgo** [jokob-sk/Pi.Alert#294]
## Describe the issue

> When submitting an issue ❗[enable debug](https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_TIPS.md)❗ and [have a look at the docs](https://github.com/jokob-sk/Pi.Alert/tree/main/docs)

[Hi Jokob, I try to consult the week présence of a device. On the right of the screen, the pop up is not visible.]

## Paste your `pialert.conf` (remove personal info)

```
paste_here
```

## Paste your `docker-compose.yml` and `.env` (remove personal info)

`docker-compose.yml` 

```
paste_here
```

`.env` 

```
paste_here

```

## Screenshots
![2023-07-23_085033](https://github.com/jokob-sk/Pi.Alert/assets/137160247/a2b7bd97-b6dd-46b1-a9f9-c45f0941bc79)
[If applicable, add screenshots to help explain your problem.]

## Paste last few lines from `pialert.log`

> You can use `tail -100 /home/pi/pialert/front/log/pialert.log`

```bash

# paste code below

**Comment by leiweibau** [comment]
since it affects my fork as well ...
https://github.com/jokob-sk/Pi.Alert/blob/56f35f5068613e7674d54d0e96b3fb8bde330c71/front/deviceDetails.php#L1281

**Comment by jokob-sk** [comment]
Thanks @leiweibau , really appreciated 🙏
@Walgo will be fixed in the next release

**Comment by Walgo** [comment]
Hi Jokob & Leiweibau !

Thank you both !!!

Regards

**Comment by jokob-sk** [comment]
In release > Closing
