### ISSUE TITLE
New feature "port number in network diagram" is broken

### ISSUE THREAD

**Issue by vladaurosh** [jokob-sk/Pi.Alert#295]
## Describe the issue

> When submitting an issue ❗[enable debug](https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_TIPS.md)❗ and [have a look at the docs](https://github.com/jokob-sk/Pi.Alert/tree/main/docs)

In latest v23.7.22, new feature "port number in network diagram" is broken. Looks like devices with port number are shown in 2 rows for some reason. 

## Paste your `pialert.conf` (remove personal info)

```
paste_here
```

## Paste your `docker-compose.yml` and `.env` (remove personal info)

`docker-compose.yml` 

```
paste_here
```

`.env` 

```
paste_here
```

## Screenshots

[If applicable, add screenshots to help explain your problem.]

![image](https://github.com/jokob-sk/Pi.Alert/assets/47857324/3240765e-583d-4cda-82dd-d08804658355)

## Paste last few lines from `pialert.log`

> You can use `tail -100 /home/pi/pialert/front/log/pialert.log`

```bash

# paste code below

**Comment by jokob-sk** [comment]
Hi there!

I can't seem to reproduce the issue. It works fine on my end. Tested in Firefox, Chrome, Edge.

Can you try a different browser, reset your zoom settings (usually `Ctrl` + `0`), clear cache etc?

Thanks!
j

**Comment by vladaurosh** [comment]
Hey there!

Looks like it's ok now. I guess after upgrade something was still there in browser cache or whatever. :) 

This can be closed.

**Comment by jokob-sk** [comment]
Cool 😉
