### ISSUE TITLE
Network view : distinguish a wired connection and a wifi connection

### ISSUE THREAD

**Issue by Walgo** [jokob-sk/Pi.Alert#296]
Hi, Jokob-sk

In the network display, would it be possible to distinguish a wired connection and a wifi connection. For example with another link color. To activate it, if in the "port" area you don't put a port number but write "wifi", the color or the quality of the link changes.
I hope to be clear enough.

Thanks
Walgo

**Comment by jokob-sk** [comment]
Hey, 

I researched this a bit and the [used plugin](https://github.com/PierreCapo/treeviz) doesn't support changing the link color between specific nodes as far as I can tell.
This means too much work and time that could be used elsewhere. 

Happy for someone to submit a PR if they know how to achieve this.

I will keep this open for a couple of days.

j

**Comment by Walgo** [comment]
Hi, Jokob !

I understand! ... 

for the moment I use the wifi icon for the devices which are wifi connected ,  but I lose their own device symbol. 

Is it the same problem for cell's color (background)? 

Perhaps a wifi symbol instead of the port number
Thanks for the research.

Walgo

**Comment by jokob-sk** [comment]
Hey, 

Next release will generate background icons for ports and wifi (wifi icon if port is empty or 0):

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/7ac6d8fb-a083-4360-a1f0-403941142052)

For any other adjustments please submit a PR as UI work is currently deprioritized.

> Consider sponsoring my work to keep me motivated :) 

Thanks,
j

**Comment by jokob-sk** [comment]
In release > Closing
