### ISSUE TITLE
When the port number is two characters, it is pasted to the icon.

### ISSUE THREAD

**Issue by Walgo** [jokob-sk/Pi.Alert#298]
## Describe the issue

Hi   Jokob-sk,
A detail...

When the port number is two characters, it is pasted to the icon.

## Screenshots

![image](https://github.com/jokob-sk/Pi.Alert/assets/137160247/860474b7-c5fc-49c6-a294-350183b734ca)

**Comment by jokob-sk** [comment]
Hi there! 

Will be fixed in the next release. 

Thanks,
j

**Comment by jokob-sk** [comment]
In release > Closing
