### ISSUE TITLE
Presence Graphs do not update correctly.

### ISSUE THREAD

**Issue by Final-Hawk** [jokob-sk/Pi.Alert#30]
When a device stays connected and has no disconnection events, the presence graph does not work and is simply empty.  If the device disconnects and reconnects the presence graph will start showing the graph properly. Because of this reporting issue, the presence hours also does not report correctly for devices that have no disconnect events.

I had a quick look to see if i could find the issue but i couldn't.

Edit: Seems like this is caused by the device not being added to Convert_Events_to_Sessions in the database, and hence the Sessions table that the presence data is gathered from.

Thanks

**Comment by jokob-sk** [comment]
I've implemented at least highlighting for still connected devices in this one and I think somewhere around that place in the code we can find a way to fix the incorrect end time of the bars:

https://github.com/jokob-sk/Pi.Alert/commit/3df87f6f36645cfef4f427c782b5df573db45194

**Comment by Final-Hawk** [comment]
Closed with #47
