### ISSUE TITLE
Update reverse proxy configuration documentation

### ISSUE THREAD

**Issue by cvc90** [jokob-sk/Pi.Alert#300]
Hi, reviewing the documentation I see that there is a section for reverse proxy in https://github.com/jokob-sk/Pi.Alert/blob/main/docs/REVERSE_PROXY.md but does not contain configuration available for the two servers par excellence such as "NGINX" or "APACHE", could you update it to include these two options?

**Comment by jokob-sk** [comment]
Hey!

Regrettably this guide is sourced from a user and I don't have a reverse proxy setup (or experience) with any of the mentioned systems. 

If anyone reading this has experience, feel free to comment or submit a PR.

Thanks,
j

**Comment by cvc90** [comment]
Hello! 

I am very sorry for what you say and I will try to help you, here I leave this configuration so that you can add it to the Pi.Alert guide, but for Pi.Alert to work correctly in Sub Path mode it would be advisable to add it in Pi.Alert a "PROXY PATH URL"
<br>

**NGINX HTTP Configuration (Direct Path)**

1. On your NGINX server, create a new file called /etc/nginx/sites-available/pialert

2. In this file, paste the following code:

```
   server { 
     listen 80; 
     server_name pi.alert; 
     proxy_preserve_host on; 
     proxy_pass http://localhost:20211/; 
     proxy_pass_reverse http://localhost:20211/; 
    }
``` 

3. Activate the new website by running the following command:

   `nginx -s reload` or `systemctl restart nginx`

4. Once NGINX restarts, you should be able to access the proxy website at http://pi.alert/

<br>

**NGINX HTTP Configuration (Sub Path)**

1. On your NGINX server, create a new file called /etc/nginx/sites-available/pialert

2. In this file, paste the following code:

```
   server { 
     listen 80; 
     server_name pi.alert; 
     proxy_preserve_host on; 
     location ^~ /pi.alert/ {
          proxy_pass http://localhost:20211/;
          proxy_pass_reverse http://localhost:20211/; 
          rewrite //pi.alert(.*) $1 break;			
     }
    }
``` 

3. Activate the new website by running the following command:

   `nginx -s reload` or `systemctl restart nginx`

4. Once NGINX restarts, you should be able to access the proxy website at http://pi.alert/pi.alert/

<br>

**NGINX HTTPS Configuration (Direct Path)**

1. On your NGINX server, create a new file called /etc/nginx/sites-available/pialert

2. In this file, paste the following code:

```
   server { 
     listen 443; 
     server_name pi.alert; 
     SSLEngine On;
     SSLCertificateFile /etc/ssl/certs/pi.alert.pem;
     SSLCertificateKeyFile /etc/ssl/private/pi.alert.key;
     proxy_preserve_host on; 
     proxy_pass http://localhost:20211/; 
     proxy_pass_reverse http://localhost:20211/; 
    }
``` 

3. Activate the new website by running the following command:

   `nginx -s reload` or `systemctl restart nginx`

4. Once NGINX restarts, you should be able to access the proxy website at https://pi.alert/

<br>

**NGINX HTTPS Configuration (Sub Path)**

1. On your NGINX server, create a new file called /etc/nginx/sites-available/pialert

2. In this file, paste the following code:

```
   server { 
     listen 443; 
     server_name pi.alert; 
     SSLEngine On;
     SSLCertificateFile /etc/ssl/certs/pi.alert.pem;
     SSLCertificateKeyFile /etc/ssl/private/pi.alert.key;
     location ^~ /pi.alert/ {
          proxy_pass http://localhost:20211/;
          proxy_pass_reverse http://localhost:20211/; 
          rewrite //pi.alert(.*) $1 break;			
     }
    }
``` 

3. Activate the new website by running the following command:

   `nginx -s reload` or `systemctl restart nginx`

4. Once NGINX restarts, you should be able to access the proxy website at https://pi.alert/pi.alert/

<br>

**Apache HTTP Configuration (Direct Path)**

1. On your Apache server, create a new file called /etc/apache2/sites-available/pialert.conf.

2. In this file, paste the following code:

```
    <VirtualHost *:80>
         ServerName pi.alert
         ProxyPreserveHost On
         ProxyPass / http://localhost:20211/
         ProxyPassReverse / http://localhost:20211/
    </VirtualHost>
``` 

3. Activate the new website by running the following command:

   `a2ensite pialert` or `service apache2 reload`

4. Once Apache restarts, you should be able to access the proxy website at http://pi.alert/

<br>

**Apache HTTP Configuration (Sub Path)**

1. On your Apache server, create a new file called /etc/apache2/sites-available/pialert.conf.

2. In this file, paste the following code:

```
    <VirtualHost *:80>
         ServerName pi.alert
         location ^~ /pi.alert/ {
               ProxyPreserveHost On
               ProxyPass / http://localhost:20211/
               ProxyPassReverse / http://localhost:20211/
         }
    </VirtualHost>
```   

3. Activate the new website by running the following command:

   `a2ensite pialert` or `service apache2 reload`

4. Once Apache restarts, you should be able to access the proxy website at http://pi.alert/

<br>

**Apache HTTPS Configuration (Direct Path)**

1. On your Apache server, create a new file called /etc/apache2/sites-available/pialert.conf.

2. In this file, paste the following code:

```
    <VirtualHost *:443>
         ServerName pi.alert
         SSLEngine On
         SSLCertificateFile /etc/ssl/certs/pi.alert.pem
         SSLCertificateKeyFile /etc/ssl/private/pi.alert.key
         ProxyPreserveHost On
         ProxyPass / http://localhost:20211/
         ProxyPassReverse / http://localhost:20211/
    </VirtualHost>
```   

3. Activate the new website by running the following command:

    `a2ensite pialert` or `service apache2 reload`

4. Once Apache restarts, you should be able to access the proxy website at https://pi.alert/

<br>

**Apache HTTPS Configuration (Sub Path)**

1. On your Apache server, create a new file called /etc/apache2/sites-available/pialert.conf.

2. In this file, paste the following code:
                            
```
	<VirtualHost *:443> 
        ServerName pi.alert
        SSLEngine On 
        SSLCertificateFile /etc/ssl/certs/pi.alert.pem
        SSLCertificateKeyFile /etc/ssl/private/pi.alert.key
        location ^~ /pi.alert/ {
              ProxyPreserveHost On
              ProxyPass / http://localhost:20211/
              ProxyPassReverse / http://localhost:20211/
        }
    </VirtualHost>
```       

3. Activate the new website by running the following command:

   `a2ensite pialert` or `service apache2 reload`

4. Once Apache restarts, you should be able to access the proxy website at https://pi.alert/pi.alert/

**Comment by jokob-sk** [comment]
@cvc90, you are my favorite person on the internet today. Thanks so much. I added your guide here: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/REVERSE_PROXY.md

Let me know if I need to change anything else.

I'm not sure what this means, so any advise on this would be appreciated as well:

>for Pi.Alert to work correctly in Sub Path mode it would be advisable to add it in Pi.Alert a "PROXY PATH URL"

thanks again @cvc90 this is amazing content 🙏

**Comment by cvc90** [comment]
@jokob-sk   If I detect an error or detect that some information is missing, I'll tell you, but at the moment everything seems to be correct in the guide.

I meant with this "PROXY PATH URL" that in Pi.Alert you could indicate a proxy url path in that way all the urls were converted from host/devices.php to host/"PROXY PATH"/devices.php natively.

Another serious way with the BASE_URL function

The BASE URL feature is a great way to centralize all your app URLs in one place. This can make it easier to find and change your app's URLs, and it can also make your code easier to read and maintain.

To add the BASE URL function to your application, you can use the following function:

const BASE_URL = 'https://www.example.com/';

Once you've added the BASE URL function, you can use it to build other URLs in your app. For example, if you want to build the URL of your app's home page, you can use the following function:

const homepageUrl = `${BASE_URL}/home`;

The BASE URL function is a great way to improve the quality of your code. If you're developing an app, I recommend adding the BASE URL function to your app.

Here are some additional benefits of using the BASE URL function:

Makes it easier to find and change your app URLs.
It makes your code easier to read and maintain.
You can improve the performance of your application by reducing the number of HTTP requests that are made.

There are many applications with these functions such as [Filebrowser](https://filebrowser.org/cli/filebrowser), [Sonarr](https://sonarr.tv/), [Radarr](https://radarr.video/), etc...

Thanks for the mention :)

**Comment by jokob-sk** [comment]
Amazing, thanks for the information. I'll try to get something into the next release and Ping you if I implemented the setting accurately according to the description above.

**Comment by cvc90** [comment]
That seems perfect to me! I'll keep an eye out for the next versions :v:

**Comment by cvc90** [comment]
Could you update [README.md](https://github.com/jokob-sk/Pi.Alert/blob/main/docs/README.md)?

In the submenu "♻ Misc" 

[Reverse proxy with SWAG](https://github.com/jokob-sk/Pi.Alert/blob/main/docs/REVERSE_PROXY.md) --> [Reverse proxy](https://github.com/jokob-sk/Pi.Alert/blob/main/docs/REVERSE_PROXY.md)

**Comment by jokob-sk** [comment]
Feel free to submit a PR 😉

**Comment by cvc90** [comment]
Ok, the request is here ([PR](https://github.com/jokob-sk/Pi.Alert/pull/306))

**Comment by jokob-sk** [comment]
Most of the docs were updated (missing is the option to configure the root URL - but I don't have the energy/bandwidth for this now), detailed description:


> To add the BASE URL function to your application, you can use the following function:
> 
> const BASE_URL = 'https://www.example.com/';
> 
> Once you've added the BASE URL function, you can use it to build other URLs in your app. For example, if you want to build the URL of your app's home page, you can use the following function:
> 
> const homepageUrl = ${BASE_URL}/home;
> 
> The BASE URL function is a great way to improve the quality of your code. If you're developing an app, I recommend adding the BASE URL function to your app.
> 
> Here are some additional benefits of using the BASE URL function:
> 
> Makes it easier to find and change your app URLs.
> It makes your code easier to read and maintain.
> You can improve the performance of your application by reducing the number of HTTP requests that are made.


I'm happy to approve a PR if someone is thinking of implementing this. Closing this issue for now
