### ISSUE TITLE
Update style of "reports"

### ISSUE THREAD

**Issue by cvc90** [jokob-sk/Pi.Alert#304]
Hi, @jokob-sk 

reviewing certain parts of Pi.Alert and come to the reports, I think the visual image of the "reports" does not fit the current image of Pi.Alert seems outdated, could you update the style?

Even if it's not too much to ask maybe you should stick to the default theme in Pi.Alert, but if not at least change the current layout of the reports.

**1. The title backgrounds look better by changing the colors from yellow to the current blue used in Pi.Alert and the lettering to white.**

   ````
   bgcolor=#EFB956 --> bgcolor=#3c8dbc
   bgcolor=#FFD966 --> bgcolor=#00c0ef
   color:#000000 --> color:#ffffff
   ````

_Current image_
![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/23a380b3-7b5d-4f0a-bcca-ee83d8c2a4ce)

_New image_
![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/ba407449-2983-469a-8e4a-f858de93863a)

<br>

**2. Also perhaps it would be advisable to discard the "Footer" for the current footer in the Pi.Alert application** 

_Current image_
![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/f7db8a2a-4714-4f04-9c65-5ba13c655dd5)

_New image_
![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/9e0b06d8-ad58-4d10-92a4-07a2000d40e2)

<br>

**3. Change the style of the report tables to the style of the current Pi.Alert tables (changing backgrounds, fonts and table style)**

_Current image_
![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/66a8cc65-b04f-4799-9e03-aedb35a0b21c)

_New image_
![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/76fc2cb0-2bbf-4336-8419-4f40adacc3ef)

<br>

**4. Inside tables when displaying event information(Change text for button with text)**

_Current image_
![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/fbe07628-1eab-4c20-bdbf-708541eabc41)

_New image_
![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/07335782-3f34-449f-b5a2-0c172689826f)

**Comment by jokob-sk** [comment]
Hi @cvc90 !

Thanks for the suggestions!

I implemented number 1.

Everything else is a bit complicated and would require hours of work that I feel are better spent elsewhere. Especially since the reports are auto-generated and are used for a range of objects (Plugins, devices etc... ) it's not easy to e.g. change a text to a button without complex decision logic. Also, UI improvements are lower priority than core work as per:

https://github.com/jokob-sk/Pi.Alert/issues/118 section 👩‍💻 Development priorities

Happy to approve a PR.

If you contribute, I would focus on individual bullet points, e.g a PR for number 2 first, then a PR for number 3. Number 4 is way too complex right now. You can check the `def construct_notifications` method for details.

Thanks,
j

**Comment by leiweibau** [comment]
I apologize for interfering here without being asked, but please keep in mind that there are also users who use system-wide dark mode on their computer. So you can not rely on this color code. In the end, it is not so trivial to get a halfway coherent result that looks good in both modes.

#3c8dbc should turn to #c37243
#00c0ef should turn to #FF4010

especially #FF4010 is a pretty bright/intense color

**Comment by cvc90** [comment]
If I have already seen that you have implemented suggestion 1, I have 2 almost finished.

I leave you an image so you can see how it is turning out and tell me your opinion

![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/95734ba4-77f7-4fae-a875-b46af7c959ca)

**Comment by jokob-sk** [comment]
Looks good! I'd probably make the text white so it's easier to read. 👍

**Comment by cvc90** [comment]
@jokob-sk when you can look [PR modified the style of the reports](https://github.com/jokob-sk/Pi.Alert/pull/315)

**Comment by cvc90** [comment]
@jokob-sk when you can look [PR #322](https://github.com/jokob-sk/Pi.Alert/pull/322) & [PR #323](https://github.com/jokob-sk/Pi.Alert/pull/323)

**Comment by jokob-sk** [comment]
In release > Closing
