### ISSUE TITLE
Update date format and existence of the "Version" file

### ISSUE THREAD

**Issue by cvc90** [jokob-sk/Pi.Alert#305]
Hi! @jokob-sk,

I've been checking timezone.php

1. When you show the date in a "Y-m-d" format and most of the European countries use the "d-m-Y" format, could you change it? Or for the Spanish language?

```php
$timestamp = $date->format('Y-m-d_H-i-s'); --> $timestamp = $date->format('d-m-Y_H-i-s');
``` 

I've been going through footer.php and I've come across a couple of things.

1. When it shows the date, it shows the format "Y-m-d" and that in most European countries the format "d-m-Y" is used, could you change it? Or for the Spanish language?

```php
<?php echo date("Y-m-d", ((int)file_get_contents( "buildtimestamp.txt")));?>  --> <?php echo date("d-m-Y", ((int)file_get_contents( "buildtimestamp.txt")));?>
``` 

2. It looks for a file called "VERSION" but I can't find anywhere that this file exists and therefore it will always show "File not found", simply creating the file with the current version of Pi.Alert would be solved.

```php
<?php $filename = "/.VERSION";

if(file_exists($filename))
{
  echo file_get_contents($filename);
}
else{
  echo "File not found";
}               

?>
```

**Comment by jokob-sk** [comment]
Hi @cvc90 !

As mentioned in an earlier thread, UI improvements are a lower priority now (I only have around 1h of time per day to dedicate to this project). Feel free to submit a PR with your changes.

If you do submit a PR, make sure:

- Users can pick time format via settings or the time format is applied automatically according to current locale ideally in all places.

The version file is part of a bigger body of work, so it's not as easy, feel free to study this thread: https://github.com/jokob-sk/Pi.Alert/issues/209

Thanks,
j

**Comment by cvc90** [comment]
ok i'll take a look 👍

**Comment by jokob-sk** [comment]
🙏

**Comment by cvc90** [comment]
@jokob-sk I'm looking around and I see certain things that don't seem to fit.

In the footers of the page, when it comes to knowing the version, you call the file like this /.VERSION, which means that it is located in the root. After checking that the file does not currently exist in that location and therefore the error displayed in the footer.

In docker_prod.yml instead I see that when you generate the file "echo "${{ steps.get_version.outputs.version }}" >> .VERSION" you are generating the VERSION file in the current directory of that workflows.

Here we have several errors because the directory should be the same in the sites.

I have indeed verified that changing /.VERSION to its current path works correctly. (Attached screenshot)

![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/3add6265-fb71-4261-bddb-8977a32dc3d7)

There is a second error that does not affect because the file is only created when the workflow is executed but if the file already existed in our git we would add the new version to that file infinitely instead of replacing the existing version, to solve this error simply in the workflow file it would be to change >> to > so that it always modifies the content of the existing file, the command should be "echo "${{ steps.get_version.outputs.version }}" > /.VERSION".

**UPDATE: Several PRs are on the way with these changes**

**Comment by jokob-sk** [comment]
Amazing @cvc90, looking forward 👍

**Comment by cvc90** [comment]
@jokob-sk  [PR #326](https://github.com/jokob-sk/Pi.Alert/pull/326) with the changes to make "version" and "build" work on the rest of the website

**Comment by jokob-sk** [comment]
In release > Closing
