### ISSUE TITLE
Header overflowing on mobile

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/Pi.Alert#327]
## Describe the issue

2 lines necessary in Mobile view cause overflow of the menu due to the new header icons. Can you please have a look @cvc90? 

## Screenshots
![Screenshot_20230808-203752-643](https://github.com/jokob-sk/Pi.Alert/assets/96159884/65408fa0-81dc-44b5-9d8b-dd998d79b104)

**Comment by cvc90** [comment]
Hello @jokob-sk!,

I am reviewing what you comment, the jump to that second line occurs with devices less than 464px wide, several ideas occur to me.

1. Move the icons to another place such as in the menu list area

2. Reduce available options

3. Move div class="header-server-time small to the "Logo" area

Which option do you think is the right one?

**Comment by jokob-sk** [comment]
Hummm,

Maybe hiding the icons on small screens is a good idea? They are most useful on big screens I think.

**Comment by cvc90** [comment]
It is another option, I think that hiding the forward and backward buttons would be enough.

**Comment by jokob-sk** [comment]
Cool, sounds good! Just be aware that the status messages can be longer, e.g.:

```py
    # Header
    updateState(db,"Scan: Internet IP")
```

**Comment by cvc90** [comment]
Fixed buttons to fade out as you trigger overflow


The [PR #348](https://github.com/jokob-sk/Pi.Alert/pull/348) of "Corrected overflow header on mobile" is now available

**Comment by jokob-sk** [comment]
Nice fix @cvc90 🙏
