### ISSUE TITLE
Some options are not shown in the configure section

### ISSUE THREAD

**Issue by cvc90** [jokob-sk/Pi.Alert#332]
In the "configuration" section, it does not show most of the menus, everything seems to indicate that many text translations are missing to be added to other languages, because in English it works correctly.

_Screenshot version "Spanish"_
![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/9760e6f4-de5b-48b3-86de-fdd38dd19f7a)

_Screenshot version "English"_
![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/fbb5b6fc-794e-4507-9d08-40f8b47f5f9b)

**Comment by jokob-sk** [comment]
Hummm there might be a bug somewhere here in getString
https://github.com/jokob-sk/Pi.Alert/blob/main/front/js/pialert_common.js

**Comment by jokob-sk** [comment]
Also try clearing the cache, but a bug is more likely

**Comment by cvc90** [comment]
I'm trying a solution, now I'll tell you

**Comment by cvc90** [comment]
At first everything seemed to indicate that it was an error, but it is simply that the language variables only exist in English and not for the rest of the languages.

I have updated the .json file of the "Website_monitor" plugin, adding a Spanish translation and I can say that now it loads the text correctly again.

**Comment by jokob-sk** [comment]
Fixed missing English fallbacks

**Comment by cvc90** [comment]
Ok, now when it does not find the variable in the selected language it correctly shows the fallbacks in English

**Comment by jokob-sk** [comment]
🚀 @cvc90 you 🧑‍🎤
