### ISSUE TITLE
Errors on the "Internet" device page

### ISSUE THREAD

**Issue by cvc90** [jokob-sk/Pi.Alert#360]
Hi @jokob-sk !

Could you check this error? It happens to me with the Docker dev version, recently installed and with the default configuration.

Everything seems to indicate that the error occurs when the .json is not loaded correctly, as you can see in the last photo attached, the file is empty.

![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/8e9099b8-f692-47e8-903a-5c41e10c211e)
![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/e0c2cdf6-1b9d-4b35-9280-86b301b689e9)
![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/cce0f8b2-f90e-4414-b87c-8a0b9bb35b33)
![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/c0586b1f-66ff-46a1-9a92-b846e5b82fce)

**Comment by jokob-sk** [comment]
Thanks, should be fixed now!

**Comment by cvc90** [comment]
Hi @jokob-sk !

There is still some error when loading the .json and it doesn't show most of the information and it doesn't only happen on the "Internet" device, it happens on all network devices.

![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/f0cf30e2-4d06-496e-b4b0-a175e64ecf56)

The first column "Main Info" seems to load correctly, but the rest of the info columns don't seem to load.

![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/5a165baa-e462-4580-a47d-5ac56a4d8643)

**Comment by jokob-sk** [comment]
Hey!

I think this happens mostly when the DB is locked. I'm not sure how to further prevent DB locks - probably by rewriting the data retrieval to the json field instead of relying on the DB connection - but this will be a lengthy process.

You can also try to debug these errors yourself by following this guide and inspecting network calls:

https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_INVALID_JSON.md

Thanks,
j

**Comment by cvc90** [comment]
I already imagined that the thing had to do with the blocks and the lower the scanning time, the more times you update and the more times you block... and the option is to avoid the database as much as possible and do it directly...

If I have time I'll take a look to see if we can improve it.

**Comment by jokob-sk** [comment]
In release > Closing
