### ISSUE TITLE
Translated plugin texts are not displayed

### ISSUE THREAD

**Issue by cvc90** [jokob-sk/Pi.Alert#361]
Hi @jokob-sk !

As shown in the attached photo it doesn't show the translated plugin texts, it doesn't seem to load the translations available in config.json.

Could you check this error?

It happens to me with the Docker dev version, recently installed and with the default configuration.

![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/72f7ca53-8232-4d8c-a7d4-d5fca53b3339)

**Comment by jokob-sk** [comment]
Thanks! Should be fixed now

**Comment by jokob-sk** [comment]
In release > Closing
