### ISSUE TITLE
MQTT : Select what to send to Home Assistant

### ISSUE THREAD

**Issue by AdmiralRaccoon** [jokob-sk/Pi.Alert#364]
Hello,

**Is your feature request related to a problem? Please describe.**
When enabling MQTT, everything along all devices is send to Home Assistant. In fact, I´m only interested in this stats entity:
![image](https://github.com/jokob-sk/Pi.Alert/assets/41727850/403ed8b7-4d52-4a92-b798-2fc9c8827fd4)

**Describe the solution you'd like**
On The MQTT Page in PiAlert, it would be nice to exclude some/all devices and then just send the collection of stats to Home Assistant.

**Describe alternatives you've considered**
Disabling the Devices i don´t want to see in HA - but that would be a lot of work and maintenance.

Thank you and keep up the good work,
Philipp

**Comment by lorki97** [comment]
Hi @AdmiralRaccoon,

would something like in the attached screenshot fulfil your request? @jokob-sk IMO this would be only a small change with backwards-compatibility. Both settings default to `True` and thus would not change anything for people that have MQTT enabled. If you agree to this change I'd continue working on a PR.

![image](https://github.com/jokob-sk/Pi.Alert/assets/6028798/ff74f3f5-8771-4e29-9ade-265c1ce2050d)

**Comment by jokob-sk** [comment]
@lorki97 I'm currently working on breaking out the notification gateways into new publisher plugins, so I parked this request for a bit. Ideally I want to unify notification settings that make sense to unify, and having a summary in all reports makes sense. I'd like to avoid a scenario where there is duplication in notification settings. Implementing this now separately for webhooks, and then separately for e.g. email etc. makes maintaining it more difficult. You can check some very early work here: https://github.com/jokob-sk/Pi.Alert/tree/main/front/plugins/_publisher_apprise

**Comment by jokob-sk** [comment]
It might in the end be a publisher-specific set of settings, but getting the publishers system in place and making it more modular is for me now a higher priority, so adding new publishers as plugins is easier done by the developer community as well.

**Comment by jokob-sk** [comment]
This will be available in the next release: 
![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/739883e1-03e3-4b2f-b309-a7010664b31c)

**Comment by jokob-sk** [comment]
Released -> Closing
