### ISSUE TITLE
Change location of "tab_settings"

### ISSUE THREAD

**Issue by cvc90** [jokob-sk/Pi.Alert#367]
Hi @jokob-sk!

Don't you think that the "tab_settings" section fits the settings in settings.php more than where it currently is in maintenance.php?

![image](https://github.com/jokob-sk/Pi.Alert/assets/76731844/88194bcb-4d42-4006-b090-a6cbb4153e63)

**Comment by jokob-sk** [comment]
Hi @cvc90 ,

Thematically yes, but these are mostly front-end settings and the Settings system is built completely different from this Maintenance section.

It may look easy to move these to Settings, but the Settings page has pre-defined setting types handled by the backend and front end  so things might need to be adjusted in multiple places. 

Here is a high-level description of how Settings work:

https://github.com/jokob-sk/Pi.Alert/blob/main/docs/SETTINGS_SYSTEM.md

I'm not against moving it to the Settings section, but it has to be done carefully. 

All this work means this is very low priority and if a PR is submitted is has to follow best practices. 

Thanks for your hard work,
j

**Comment by cvc90** [comment]
Ok, I'll take a look at it, but maybe I'll leave it for later, I think that right now other things have more priority.
