### ISSUE TITLE
Sessions, Events, and Presence tabs do not update

### ISSUE THREAD

**Issue by Final-Hawk** [jokob-sk/Pi.Alert#40]
When switching between devices using the arrows on the device details page, only the details tab updates with the information for the newly selected device. The sessions, events, and presence tabs do not update their shown information accordingly. 

Reproduction Steps:
1. Select a device from the main page
2. Select either the sessions, events, or presence tab.
3. Use the arrows to change to the next device
4. Watch the information not update

**Comment by jokob-sk** [comment]
Humm a quick mitigation can be just disabling the pagination. As with the dropdown, I've actually never used it before. There is already a global Presence overview so I'm not sure what's the benefit of being able to navigate the devices this way. What would you think about removing this functionality? I tried to use it and it's buggy as it is (sometimes being disabled for no reason and sometimes not enumerating all devices (I get 1/1)...

My thinking goes it's better if we remove unused functionality (and not spend time on pointless maintenance) and focus on adding value elsewhere. But if you think this is critical I can try to debug it, but it could lead nowhere :/ Happy to discuss...

**Comment by Final-Hawk** [comment]
> As with the dropdown, I've actually never used it before.

Dropdown i haven't really used too much at all as well, except for trying to debug the issue with it. Only time i use it is to change the presence hours to report just today instead of all time. Even if we modified it to only change presence hours between "today" and "all time" I wouldn't be upset at all. 

> What would you think about removing this functionality? 

I use this functionality quite a bit, mainly for just flicking between the details of offline or new devices. 

This issue fixed in #46 though!

**Comment by jokob-sk** [comment]
Thanks for the fix, great work!
