### ISSUE TITLE
Plugins -> PiHole Device Sync there is no IP shown

### ISSUE THREAD

**Issue by ace16vitamine** [jokob-sk/Pi.Alert#418]
Built on: 2023-09-10 | Version: v23.9.10

In Plugins -> PiHole Device Sync there is no IP shown (it is the vendor Name displayd)

See screenshot
![Bildschirmfoto 2023-09-10 um 13 14 36](https://github.com/jokob-sk/Pi.Alert/assets/22064392/e2d895e8-152e-4f1c-9c77-5db419700c13)

**Comment by jokob-sk** [comment]
Could you please share the settings for the PiHole plugin and how you have mapped the files in your docker compose file?

**Comment by ace16vitamine** [comment]
It was a fresh installation, I reinstalled it already but the files are right mapped in docker. For me it seems that this comes from the SQL Select.

I try it again and post the infos

**Comment by ace16vitamine** [comment]
I found a similar problem.


It is not the Mac shown -> Its the Hostname

![Bildschirmfoto 2023-09-10 um 15 26 58](https://github.com/jokob-sk/Pi.Alert/assets/22064392/904abc11-ecb6-4ec4-bab7-0b9e903cf2a0)

**Comment by jokob-sk** [comment]
Hey,
Can you re-download the latest _dev image and give it a try? the IP should be now populated. 

If you are using an existing config:

 remove the `PIHOLE_CMD` setting from your pialert.conf file or replace the value in the Settings page with `SELECT n.hwaddr AS Object_PrimaryID, 'null' AS Object_SecondaryID, datetime() AS DateTime, na.ip  AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, {s-quote}null{s-quote} AS Extra, n.hwaddr AS ForeignKey FROM EXTERNAL_PIHOLE.Network AS n LEFT JOIN EXTERNAL_PIHOLE.Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE {s-quote}ip-%{s-quote} AND n.hwaddr <> {s-quote}00:00:00:00:00:00{s-quote};`

**Comment by jokob-sk** [comment]
Please let me know if the name gets populated as well. Thanks in advance

**Comment by jokob-sk** [comment]
Released in today's hotfix (23.9.11). You need to complete the below step if you have saved the settings on the 23.9.10 version:

remove the `PIHOLE_CMD` setting from your `pialert.conf` file or replace the value in the Settings page with the below value:

`SELECT n.hwaddr AS Object_PrimaryID, 'null' AS Object_SecondaryID, datetime() AS DateTime, na.ip  AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, {s-quote}null{s-quote} AS Extra, n.hwaddr AS ForeignKey FROM EXTERNAL_PIHOLE.Network AS n LEFT JOIN EXTERNAL_PIHOLE.Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE {s-quote}ip-%{s-quote} AND n.hwaddr <> {s-quote}00:00:00:00:00:00{s-quote}; `
