### ISSUE TITLE
No DHCP Import possible

### ISSUE THREAD

**Issue by ace16vitamine** [jokob-sk/Pi.Alert#420]
Built on: 2023-09-10 | Version: v23.9.10

If I activate DHCP Import over GUI no import is done:

# DHCPLSS
#---------------------------
DHCPLSS_RUN='schedule'

The DHCP File from pihole exist, rights are OK and it is configured in the correct path.

![Bildschirmfoto 2023-09-10 um 13 30 36](https://github.com/jokob-sk/Pi.Alert/assets/22064392/280a2040-7781-4f80-beae-c0c1339df159)

**Comment by ace16vitamine** [comment]
root@jokobsk-pi:/etc/pihole# python3 /home/pi/pialert/front/plugins/dhcp_leases/script.py paths=dhcp.leases                                         
[plugin_helper] reading config file                                                                                                                 
13:40:12 [DHCPLSS] In script                                                                                                                        
13:40:12 [DHCPLSS] 0 Entries found in "dhcp.leases"

**Comment by jokob-sk** [comment]
Hi,

Can you please confirm that you are following settings instructions as per:

Add all dhcp.leases mapped paths to watch. Enter full path within the container, e.g. /mnt/dhcp2.leases. You must map these files accordingly in your docker-compose.yml file. (If you are mapping a PiHole dhcp.leases file the path in the container must contain pihole, e.g.: :/etc/pihole/dhcp.leases)

Thanks in advance,
J

**Comment by ace16vitamine** [comment]
I confirm.

![Bildschirmfoto 2023-09-10 um 14 58 15](https://github.com/jokob-sk/Pi.Alert/assets/22064392/caa475aa-a69d-45f1-b897-ab01e964ac0a)
![Bildschirmfoto 2023-09-10 um 14 57 50](https://github.com/jokob-sk/Pi.Alert/assets/22064392/69558e26-2598-4ad2-acbf-4926fe015a00)

**Comment by jokob-sk** [comment]
Thanks! Can you please share an anonymized version of the dhcp.leases file so that I can test it on my end? A couple of devices is sufficient, I probably do not need the whole file.

**Comment by ace16vitamine** [comment]
root@jokobsk-pi:/# cat /etc/pihole/dhcp.leases                                                                                                      
1694464868 c0:49:ef:ba:a8:64 192.168.1.152 espressif *                                                                                              
1694869819 b8:d6:1a:86:87:48 192.168.1.191 shellyplus1-b8d61a868748 01:b8:d6:1a:86:87:48                                                            
1694610460 64:1c:ae:f8:04:9a 192.168.1.184 Samsung 01:64:1c:ae:f8:04:9a

**Comment by jokob-sk** [comment]
Thanks @ace16vitamine , that helped a lot. Found a bug and it should be fixed in the _dev image. Can you test it?

**Comment by ace16vitamine** [comment]
Confirmed:
22:24:22 [DHCPLSS] 43 Entries found in "/etc/pihole/dhcp.leases"
00:24:22 [Plugins] SUCCESS, received 43 entries

**Comment by jokob-sk** [comment]
Thanks 🙏Keeping it open to write release notes later :)

**Comment by jokob-sk** [comment]
Released in today's hotfix (23.9.11)
