### ISSUE TITLE
Network map Issue with v23.9.10 

### ISSUE THREAD

**Issue by corasaniti** [jokob-sk/Pi.Alert#424]
## Describe the issue

With version v23.9.10 I found a bug in the network map. After adding the icon in the network map I am no longer able to view the name of the device.

Here is the difference between version v23.9.10 and the previous version v23.7.22

In addition many times I am unable to view the network map. I cleared the browser cache and tried with Chrome, Opera, Firefox. Upon loading the page flashes but then shows nothing. See screen3

## Screenshots
![Cattura2](https://github.com/jokob-sk/Pi.Alert/assets/5001932/43a101d7-40b5-4465-ab8a-38695933be8f)
![Cattura1](https://github.com/jokob-sk/Pi.Alert/assets/5001932/5abaaeef-9e5f-4a12-81e4-390f13a9ebbd)
![Cattura3](https://github.com/jokob-sk/Pi.Alert/assets/5001932/b0fc9e0b-1097-4c1b-a294-cd8f5080ffca)

Thanks in advance
corpie

**Comment by sky4055** [comment]
same issue here.

**Comment by jokob-sk** [comment]
Hi there!

Thanks for the report and patience to get this resolved.

1. Could you please send me a screenshot of the browser developer console if there are any errors?
2. Can you try clearing your cache?
3. Can you try a different browser?

Thanks in advance!
j

**Comment by corasaniti** [comment]
@jokob-sk 
Hi, as I wrote above, I cleared the browser cache and tried with Chrome, Opera, Firefox.
Today I try  pullthe dev tag
Thanks

**Comment by masterwishx** [comment]
have same issue , blank map on chrome and firefox

**Comment by masterwishx** [comment]
> Sorry I still can't find the dev tag
> https://hub.docker.com/r/jokobsk/pi.alert/tags?page=1

https://registry.hub.docker.com/r/jokobsk/pi.alert_dev

**Comment by corasaniti** [comment]
@jokob-sk 
Even with the dev branch the network map page is blank. Here is the error from the Chrome dev panel

Thank you
![Immagine 2023-09-11 114708](https://github.com/jokob-sk/Pi.Alert/assets/5001932/b058f7ba-fcd8-447c-8f50-2e66aa30c228)

**Comment by jokob-sk** [comment]
Hey,

1. Can you please try the _dev image? 
2. Are you using a reverse proxy?
3. Can you pause the execution on an exception and send me a screenshot of where in code the exception occurs in the browser dev tools? 

Thanks in advance,
j

**Comment by jokob-sk** [comment]
This should be fixed in the dev image - please have a look - tested in chrome and FF

**Comment by corasaniti** [comment]
@jokob-sk 
The dev branch seems to be working now. I'll try it on a test Raspberry for a few days. 
As soon as I see the stable release I will delete the dev branch...
Thanks

**Comment by jokob-sk** [comment]
Released
