### ISSUE TITLE
Problems with the pialert.conf file

### ISSUE THREAD

**Issue by cvc90** [jokob-sk/Pi.Alert#425]
Hi @jokob-sk,

When you can, check the pialert.conf file, it seems not to be updated when it is created from 0, continue with the old variables.

I also see that the file [pialert.conf](https://github.com/jokob-sk/Pi.Alert/blob/main/config/pialert.conf) is also not updated to the new version.

UPDATE:  It seems that something has been broken, when saving the file "_metadata" variables are saved
UPDATE 2: This error may be due to the fact that the function "initDeviceListAll_JSON()" is not loaded.

**Comment by jokob-sk** [comment]
Hi, thanks!

Did your PR fix this issue?

**Comment by cvc90** [comment]
If you can, create it, I'm not available today.
