### ISSUE TITLE
[feature request] Undiscoverables to specify more values e.g. MAC|IP|dummy_name

### ISSUE THREAD

**Issue by SeimusS** [jokob-sk/Pi.Alert#426]
Hello,

I updated to the latest version fo PiAlert v23.9.10. And I can see that within the events TAB my GW shows a lot of IP Changes which vere not previously reported.

This IP changes are IPs of GWs I have. Basicaly, instead of showing each individual GW as discovered it creates an event of "IP changed" from point of simple networking GWs/VLANs L3 will inherit same MAC address but PiAlert doest not know to diverse it and instead reports it as "IP changed".

Sadly this si flooding the event log as I have lot of GWs.

My question is:
1. Is there any way to have PiAlert discover them and have them as nodes even thought they have all the same MAC?
2. Is there any way to disable the event logging for "IP changed" for a specific node?

![obrázok](https://github.com/jokob-sk/Pi.Alert/assets/126393602/fa218375-268b-48e2-823b-4b7f7bb76e1a)

Regards,
S.

**Comment by jokob-sk** [comment]
Hi there!

Can you please let me know which Plugin is detecting these? (What plugins do you have enabled?)

You could create a list of dummy devices with the Undiscoverables plugin. Have a look and let me know if you have suggestions how t improve it.

**Comment by SeimusS** [comment]
Hello jokob-sk,

I tried the Undiscoverables  plugin, this will indeed create them and show them in the Device list but it doesnt solve the problem of "IP Changed" state for GWs.

Here I have a question you have pre-set the IP 0.0.0.0 and MAC mirroring the NAME of the dummy device, do you plan or would it be possible we can adjust the IP or as well the MAC?


**Back to main Question/Issue/proposition to improve**


In regards of your question **"Can you please let me know which Plugin is detecting these? (What plugins do you have enabled?)"**

The only pluggin I am using is art-scope. These devices/GWs are discovered by art-scope. Here I would suggest a proposition for improvement. Which is:

What about to build the DB the device list as well based on VLANs? We can already scan networks in VLANs defining teh TAG. And when you check the log you can see art-scope regonizes that a specific Host is in specific VLAN:

```
12:33:50 [ARP Scan] arpscan_output: Interface: eth0, type: EN10MB, MAC: -MAC omitted-, IPv4: (none)
Starting arp-scan 1.9.7 with 256 hosts (https://github.com/royhills/arp-scan)
10.0.0.138 -MAC omitted-	S-Bluetech co., limited (802.1Q VLAN=999)


12:34:14 [ARP Scan] arpscan_output: Interface: eth0, type: EN10MB, MAC: -MAC omitted-, IPv4: (none)
Starting arp-scan 1.9.7 with 256 hosts (https://github.com/royhills/arp-scan)
10.0.10.138 -MAC omitted-	S-Bluetech co., limited (802.1Q VLAN=10)


12:34:25 [ARP Scan] arpscan_output: Interface: eth0, type: EN10MB, MAC: -MAC omitted-, IPv4: (none)
Starting arp-scan 1.9.7 with 256 hosts (https://github.com/royhills/arp-scan)
10.0.50.138 -MAC omitted-	S-Bluetech co., limited (802.1Q VLAN=50)



12:34:37 [ARP Scan] arpscan_output: Interface: eth0, type: EN10MB, MAC: -MAC omitted-, IPv4: (none)
Starting arp-scan 1.9.7 with 256 hosts (https://github.com/royhills/arp-scan)
10.0.99.138 -MAC omitted-	S-Bluetech co., limited (802.1Q VLAN=99)



12:34:49 [ARP Scan] arpscan_output: Interface: eth0, type: EN10MB, MAC: -MAC omitted-, IPv4: (none)
Starting arp-scan 1.9.7 with 256 hosts (https://github.com/royhills/arp-scan)
10.0.101.138 -MAC omitted-	S-Bluetech co., limited (802.1Q VLAN=101)


12:35:01 [ARP Scan] arpscan_output: Interface: eth0, type: EN10MB, MAC: -MAC omitted-, IPv4: (none)
Starting arp-scan 1.9.7 with 256 hosts (https://github.com/royhills/arp-scan)
10.0.201.138 -MAC omitted-	S-Bluetech co., limited (802.1Q VLAN=201)

```
As you can see above several IPs from same MAC (MAC is omitted but its the same). And arp-scope knows that these IPs are in different VLANs.
(802.1Q VLAN=999)
(802.1Q VLAN=10)
(802.1Q VLAN=50)
(802.1Q VLAN=99)
(802.1Q VLAN=101)
(802.1Q VLAN=201)


As I mentioned from Network prespective If we have Several IPs for the same MAC as long as they come from different VLANs we take them as valid and not as Duplicate IP. So If it would be possible to have the script recognized that 1 MAC has several IPs but those IPs are comming from different VLANs you would achieve more granular discovery.

Regards,
S.

**Comment by jokob-sk** [comment]
Hi @SeimusS ,

How the original author designed the app it is now difficult to add another key to identify separate devices. MAC addresses are used as a primary key throughout the app and that is difficult to change. 

An alternative could be to disable notifications on IP changes - which would be pretty straightforward to implement - or you could disable reporting for that particular device. - This is already supported in the app now. 

Let me know if you have another workaround in mind. 

### Undiscoverables plugin

Q: Here I have a question you have pre-set the IP 0.0.0.0 and MAC mirroring the NAME of the dummy device, do you plan or would it be possible we can adjust the IP or as well the MAC?
A: The undiscoverables plugin could be extended to support such functionality - you can have a look yourself:

1. A new setting component needs to be build to allow eneting of 3 values at once, or you can define a pipe or coomam separated notation as input, e.g. MAC|IP|dummy_name
2. In the plugin parse the value and populate accordingly

**Comment by SeimusS** [comment]
Hello @jokob-sk,

As always thank you for the reply.

This **"An alternative could be to disable notifications on IP changes - which would be pretty straightforward to implement"** would be perfect. If we get the possibility to disable specific notification per discovered device. Overall for example non Network devices such as IoT and others where we may have policies bind to IP its good to know if IP changed. However if we are able to disable it on Network devices such as GWs where are several VLANs to overcome the IP change notification this would be awesome.

**If you are able to implement it I would be gratefull!**

In regards of the Undiscoverables plugin thank you for the hint I will try to play with it (not good at coding and programing).

Regards,
S.

**Comment by jokob-sk** [comment]
Hey @SeimusS ,

### Disabling notifications

Can you try the following configuration for the device you don't want IP changes to be reported on, but you want offline notifications for:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/5418543c-bdc3-494b-ab06-4b0b6bebf035)

### Undiscoverables plugin:

The undiscoverables plugin was originally developed by @data-monkey so he might be able to help out a bit ;) (hope you don't mind the ping - I'm not able to accommodate all feature requests for all plugins by myself at this point - as for a lot of FOSS initiatives, this is currently only a hobby and I don't want to get burned out 🔥)

Thanks,
j

**Comment by SeimusS** [comment]
Hello @jokob-sk 

So I did as you suggested for the GW device. 

![obrázok](https://github.com/jokob-sk/Pi.Alert/assets/126393602/164de3c2-684f-42c4-a001-be0db1a1e5ce)

I can see two things:
1. I can still see in the  Events tab the event "IP Changed"
2. I dont anymore see in the Report tab "IP Changed"

Is this the expected behaviour? Shouldnt the "Alert all Events" option as well disable any events within the Event tab?

Regards,
S.

**Comment by jokob-sk** [comment]
Hey,

That's the expected behaviour. The events will always be logged, but the notifications not sent out. 

J

**Comment by SeimusS** [comment]
Hello,

Thanks for the confirmation!

Regards,
S.

**Comment by jokob-sk** [comment]
hey @SeimusS ,

Just to confirm - is your issue solved and is this acceptable or do you have another suggestion how to improve the app?

Thanks,
j

**Comment by Data-Monkey** [comment]
Hi, no problem with the ping, but at the moment I don't have the time to look into this. Maybe add it as a feature request and I look at it later. Thanks

**Comment by SeimusS** [comment]
> Hi, no problem with the ping, but at the moment I don't have the time to look into this. Maybe add it as a feature request and I look at it later. Thanks

Thank you! I appreciate even the consideration of future feature request.

> hey @SeimusS ,
> 
> Just to confirm - is your issue solved and is this acceptable or do you have another suggestion how to improve the app?
> 
> Thanks, j

hmm Maybe last one if its possible to do.

**Would it be possible to do a selection field or a filter within Events > all events that we can specify what event we want to see from the all list?**

Currently the All events really have all events like disconnected, connected, IP change, down etc. If there would be a field that cabn display only specific events this would massively help in overall T-shoot and review of what is going on the network :)

Regards,
S.

**Comment by jokob-sk** [comment]
Hey @SeimusS ,

There is a filter already available, is this one not sufficient?

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/e1fa4004-ad41-44b5-a9bf-d5ef99d57e90)

**Comment by SeimusS** [comment]
Hello @jokob-sk 

Sorry for the delay I was on vacation.

Well the Search functionality is more or less a search functionality but not a full fledged filter that would allow to perform pre-setuped views. I am currently using the Search option as there is nothing else currently to filter thru the Event logs. It can do the job. If you have a small network its totaly doing the job, but if you have a medium size network (like I have ;D) or larger, or setup with VLANs and L3 GWs, going thru the logs 1st in order to find what was going on and then use the Search to filter it out take some time (not much but still)

But I was thinking a filter in a more granular way a filter option "like a popup menu to filter only specific message/messages" would be better.


P.S. Good work on the latest PiAlert release, those tunning parementers added for pluggins are realy awesome.

Regards,
S.

**Comment by jokob-sk** [comment]
@SeimusS Feel free to submit a PR with filter functionality. I might get to it at a later stage, but it will take quite a while (if ever). 

Closing this for now as low priority
