### ISSUE TITLE
Device names being overwritten

### ISSUE THREAD

**Issue by ameer1234567890** [jokob-sk/Pi.Alert#431]
When I change names of devices for which `(name not found)` is shown, they are overwritten upon the next scan. Any way to avoid this and persist my custom naming?

**Comment by jokob-sk** [comment]
Hi there,

I tried to reproduce this on my end, but it seems to behave correctly. Maybe some additional info would help:

1. Are there any steps I need to follow to reproduce the issue?
2. What scans do you have running?
3. After what scan is the name overwritten?
4. How long do you have to wait for the name to disappear?
5. What version are you using?

Thanks in advance!
j

**Comment by ameer1234567890** [comment]
Wow! Suddenly it seems to work as required now. I will check back and report in a day or two and close this issue.

**Comment by jokob-sk** [comment]
👍😁

**Comment by ameer1234567890** [comment]
OK. It works now. Confirmed on Pi.Alert installs (docker) at home and at work
