### ISSUE TITLE
Missing Border around the Date (in section Report)

### ISSUE THREAD

**Issue by ace16vitamine** [jokob-sk/Pi.Alert#433]
## Describe the issue
The blue border around the Date (in section Report) is missing in WEB UI.

It should be

![Bildschirmfoto 2023-09-11 um 17 21 43](https://github.com/jokob-sk/Pi.Alert/assets/22064392/fcca331b-6b77-448e-b65e-8a7ec5719589)

It is

![Bildschirmfoto 2023-09-11 um 17 21 32](https://github.com/jokob-sk/Pi.Alert/assets/22064392/e331adbf-ffee-4f87-801b-a9e5f7851b83)

**Comment by cvc90** [comment]
Yes, there seems to be something wrong with the style on the report page when the selected theme is in light mode, if you select Dark mode, it works correctly.

It is probably due to some coincidence in the style sheet (CSS).

Could you review it and see if you can find a solution?

**Comment by jokob-sk** [comment]
fixed in dev image

**Comment by jokob-sk** [comment]
Released
