### ISSUE TITLE
Fix "CMD" function in pihole_scan plugin

### ISSUE THREAD

**Issue by cvc90** [jokob-sk/Pi.Alert#438]
Hi @jokob-sk,

Problem detected in the "default_value" string of the "CMD" function in "config.json" of the "pihole_scan" plugin, which causes it to cause an error in the Pi.Alert configuration file, it is corrected by adding {s-quote}. 

 [PULL REQUEST 437](https://github.com/jokob-sk/Pi.Alert/pull/437) has been sent with the solution

You have also included this error in the [latest version readme](https://github.com/jokob-sk/Pi.Alert/releases/tag/v23.9.11), you could modify it by adding {s-quote} as in the [PR](https://github.com/jokob-sk/Pi.Alert/pull/437).

**Comment by jokob-sk** [comment]
Thanks so much 🙏

**Comment by jokob-sk** [comment]
Released
