### ISSUE TITLE
[idea] Allow clearing (full/or keep last 12h) of the Online_History table via the Maintenance tools

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/Pi.Alert#44]
Pretty easy to implement, just follow patterns in these files (approximate locations):

https://github.com/jokob-sk/Pi.Alert/blob/7057e059259a82f45036e8b5f46cbd4154fec49f/front/maintenance.php#L308

https://github.com/jokob-sk/Pi.Alert/blob/7057e059259a82f45036e8b5f46cbd4154fec49f/front/php/server/devices.php#L48

https://github.com/jokob-sk/Pi.Alert/blob/7057e059259a82f45036e8b5f46cbd4154fec49f/front/php/server/devices.php#L258

**Comment by leiweibau** [comment]
I take this as a challenge.

**Comment by jokob-sk** [comment]
@leiweibau thanks for implementing this 👍
