### ISSUE TITLE
Many Issue in latest and dev tag

### ISSUE THREAD

**Issue by corasaniti** [jokob-sk/Pi.Alert#441]
## Describe the issue
I'm very sorry but I have to stick to version 23.7.22
There are many problems

**ARMv7**
The **latest tag** fails to start the ngnix server on the Raspberry with arch armv7. 
I attach a screenshot, I have no other logs
![Cattura](https://github.com/jokob-sk/Pi.Alert/assets/5001932/5f884392-1514-46a8-ba52-d7d2de1c2f4b)

**ARMv8 (ARM64)**
I continue to have problems with the network map and it is not displayed (I attach screen)
![Cattura2](https://github.com/jokob-sk/Pi.Alert/assets/5001932/57361644-a6da-4aed-be44-0463b50f512d)

I'm hoping for a very stable latest tag soon...
Thank you

**Comment by jokob-sk** [comment]
Hi there @corasaniti !

Thanks for your patience,

I tested the _dev image on a Raspberry PI 4 and it's running fine. The Network tree is displayed correctly as well:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/c7b4d836-d38e-463e-b140-1721a1c8ed6c)

Can you delete your dev image and re-download it and try again?

**Comment by jokob-sk** [comment]
Also, if on an RPI4, try following the "sudo execution failing (e.g.: on arpscan) on a Raspberry Pi 4" in this doc: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_TIPS.md#sudo-execution-failing-eg-on-arpscan-on-a-raspberry-pi-4

**Comment by corasaniti** [comment]
@jokob-sk 
I solved the problem of starting the nginx server by recreating the DB.
Unfortunately I cannot view the network map
I attach a Chrome debug screen. I cleared my browser cache
![Cattura1](https://github.com/jokob-sk/Pi.Alert/assets/5001932/2d9f8f9a-a7fe-4d72-b317-1624076aec8a)

Thank you

**Comment by corasaniti** [comment]
@jokob-sk 
With the latest stable version v23.9.12, everything seems to work!!!
Thanks for the great work.
