### ISSUE TITLE
DeviceSync shows not IP

### ISSUE THREAD

**Issue by ace16vitamine** [jokob-sk/Pi.Alert#443]
Built on: 2023-09-13 | Version: Dev

The PiHole Device Sync shows not the IP, you can see the vendor

![Bildschirmfoto 2023-09-13 um 02 53 21](https://github.com/jokob-sk/Pi.Alert/assets/22064392/6306cd4e-7c98-41c1-9cad-a158bb585e34)
![Bildschirmfoto 2023-09-13 um 02 54 21](https://github.com/jokob-sk/Pi.Alert/assets/22064392/f78780bc-889f-41cd-b14b-9e4915be6bcc)

**Comment by jokob-sk** [comment]
Hey there,

Can you please remove the PIHOLE_CMD from your config file or reinitialize it according to the latest release notes?

Please post the value of taht setting after you have done so. Thanks

**Comment by ace16vitamine** [comment]
I removed it from config and started the dev env again. Seems to be fixed. 

New generated:
PIHOLE_CMD='SELECT n.hwaddr AS Object_PrimaryID, {s-quote}null{s-quote} AS Object_SecondaryID, datetime() AS DateTime, na.ip  AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, {s-quote}null{s-quote} AS Extra, n.hwaddr AS ForeignKey FROM EXTERNAL_PIHOLE.Network AS n LEFT JOIN EXTERNAL_PIHOLE.Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE {s-quote}ip-%{s-quote} AND n.hwaddr <> {s-quote}00:00:00:00:00:00{s-quote};':


But now I have another issue:

In Log Files I See:
00:11:10 [Mac Vendor Check] Error: b''
00:11:10 [Mac Vendor Check] Error: b''
00:11:10 [Mac Vendor Check] Error: b''
00:11:10 [Mac Vendor Check] Error: b''


![Bildschirmfoto 2023-09-14 um 00 16 05](https://github.com/jokob-sk/Pi.Alert/assets/22064392/adb4f365-c722-4a08-bd3e-f8c418434fd6)

**Comment by jokob-sk** [comment]
Hi there,

Thanks for confirming that PiHole is working. Closing this as done. Please open a new issue as that seems unrelated to the original issue to keep the issue log clean.

Please also provide additional pialert.log entries around the error message.

Thanks,
J

**Comment by ace16vitamine** [comment]
It not complete ;-) It brings another issue...
