### ISSUE TITLE
Almost all devices showing offline but are actually online

### ISSUE THREAD

**Issue by ameer1234567890** [jokob-sk/Pi.Alert#447]
Almost all of my devices (except for my file server and the internet modem) are showing as offline, whereas they are actually online (checked physically and being used as well).

Sctreenshot:
![Screenshot 2023-09-16 194739](https://github.com/jokob-sk/Pi.Alert/assets/160157/f1796b42-fbb0-4054-8dbb-89cc3503c620)

Part of log:
```
1 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.9.7: 256 hosts scanned in 11.077 seconds (23.11 hosts/sec). 0 responded
```

**Comment by jokob-sk** [comment]
Hi there!

It looks like you have multiple device discovery plugins running. 
If so, please use the same scheduling interval (`RUN_SCHD`) so they discover the availability of the devices at the same time. 

Thanks,
j

**Comment by ameer1234567890** [comment]
How do I set it?

**Comment by jokob-sk** [comment]
Please go thru the settings of the plugins you have enabled and set the `<plugin>_RUN_SCHD` setting to the same schedule.

**Comment by ameer1234567890** [comment]
I have now found the issue. The `Un-Discoverable Devices` plugin was scheduled, which was causing the issue. I disabled it and the issue is resolved.
