### ISSUE TITLE
[idea] Allow export/import of device configuration

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/Pi.Alert#45]
Might be a simple generated SQL query. In the end presence is not that important, but configuring devices, mapping their IP etc. can be a lengthy process if you don't use Pi.hole

**Comment by bonelifer** [comment]
Just pulled the current image and this addition is fantastic, Eventually when I get around to adding OPSense, it will be helpful in allowing me to set static ip's to the current ones based on the mac address.

**Comment by jokob-sk** [comment]
Closed with https://github.com/jokob-sk/Pi.Alert/commit/5a1c1036dd66a260186410e884b40fe1fb1170f7
