### ISSUE TITLE
Device setting to alert down only after a specified time period

### ISSUE THREAD

**Issue by D3SOX** [jokob-sk/Pi.Alert#451]
**Is your feature request related to a problem? Please describe.**
I have some devices in my network that always disconnect for some minutes and then reconnect. I'm not sure if it is device specific or if it's a misconfiguration of my Pi.Alert setup. The interval is always a little different. It varies between 2 and 15 minutes. I think it also depends on the scan interval of Pi.Alert which I have currently set to the default of 3 minutes.

**Describe the solution you'd like**
Adding a setting in the device details page where you can select a time period like 20 min for a device to be considered down.

**Describe alternatives you've considered**
I could change the schedule of the Arp-Scan module to 20 minutes but then the notification might be delayed when it disconnects just after a scan so I will receive the notification 20 minutes later.

**Additional context**
Events page
![image](https://github.com/jokob-sk/Pi.Alert/assets/24937357/8ad9f065-814d-4695-862d-99934454e68e)

**Comment by D3SOX** [comment]
I just saw #51 as a possible duplicate. I just pressed the “Delete Events” button on the affected devices and will report back if that fixed the problem. Still, I think this could be a useful addition.

**Comment by jokob-sk** [comment]
Note: same as #242

**Comment by jokob-sk** [comment]
Thanks for the feature suggestion. As this is a duplicate, I'll link it in the original request and close this one.

**Comment by D3SOX** [comment]
Deleting the events doesn't seem to have fixed the issue. It's happens again now.

**Comment by D3SOX** [comment]
Sorry for creating a duplicate. I didn't found the issue doing a quick search

**Comment by jokob-sk** [comment]
No problem at all! :) Thanks for the suggestion - stay tuned and I will look into it probably in the future. Probably not in the next release, maybe the one after
