### ISSUE TITLE
HRS_TO_KEEP_NEWDEV causing session matching issues

### ISSUE THREAD

**Issue by roger-** [jokob-sk/Pi.Alert#454]
I set HRS_TO_KEEP_NEWDEV to 48 and it seemed to create some issues (orange part):

![](https://user-images.githubusercontent.com/1389709/269688866-9f93e720-35ba-4c4a-9bce-778a6ca04b0d.png)
Basically every hour all my devices were reported as dropped. When I disabled the setting things went back to normal (green).

**Comment by roger-** [comment]
Still seeing this in the latest version with HRS_TO_KEEP_NEWDEV=24

**Comment by jokob-sk** [comment]
Hey @roger- ,

I currently don't have the energy to look into this. Happy to approve a PR if submitted or maybe I'll get to it sometimes much later.

Thanks,
j
