### ISSUE TITLE
Network node not showing the map

### ISSUE THREAD

**Issue by astronyu** [jokob-sk/Pi.Alert#457]
When I first installed the script, I can clearly see and assign devices to show on the network map.
Now, when I go to the network tab, I can see all the information except the network map. I think it might be because I set "Internet" to use its own "Internet" as node.

Is there a way to reset this so that the map comes back?

![image](https://github.com/jokob-sk/Pi.Alert/assets/3217740/348d4c67-9c7f-475f-a160-af51d0ab3ab0)

**Comment by jokob-sk** [comment]
Hi there!

Could you please check if there is an error in the dev console in the browser?
Also, what browser are you using?

thanks,
j

**Comment by astronyu** [comment]
I tried on 3 browsers; brave, chrome and edge and all of them showed no network map.

**Comment by jokob-sk** [comment]
Could you please check if there is an error in the dev console in the browser?
Also, what version are you using?

**Comment by astronyu** [comment]
Ah, missed that one. I check dev console and all three showed me this.
![image](https://github.com/jokob-sk/Pi.Alert/assets/3217740/69c56212-3373-4a81-b041-c6794da2c079)

Version: 
Brave [Version 1.58.135 Chromium: 117.0.5938.140 (Official Build) (64-bit)](https://brave.com/latest/)
Chrome Version 117.0.5938.132 (Official Build) (64-bit)
Microsoft Edge Version 117.0.2045.43 (Official build) (64-bit)

**Comment by jokob-sk** [comment]
Thanks for the details! Can you please try to deploy the dev build to see if it is fixed in it?

`pi.alert_dev`

**Comment by astronyu** [comment]
> Thanks for the details! Can you please try to deploy the dev build to see if it is fixed in it?
> 
> `pi.alert_dev`

Err...what do you mean by that? Do you mean to reinstall?

**Comment by tismofied** [comment]
I am having the exact same issue. I was working on it all day today and I goofed and gave the internet parent node a  Node (MAC).
It was empty and selected modem thinking since it was my modem it's fitting but that acted (I think) assigned itself to itself? lol
and it got confused and the map topology stopped working for me as well.
I can't even deselect it or unassigne it back. It's greyed out
![Screenshot 2023-09-30 at 13-00-52 Pi Alert - Turnkey-Docker](https://github.com/jokob-sk/Pi.Alert/assets/90809124/96a19013-fed8-48f3-bdb8-0baf1638da77)

**Comment by tismofied** [comment]
> Thanks for the details! Can you please try to deploy the dev build to see if it is fixed in it?
> 
> `pi.alert_dev`

Didn't help.

**Comment by jokob-sk** [comment]
Hi @tismofied, thanks for the additional info. 
 
> I am having the exact same issue. I was working on it all day today and I goofed and gave the internet parent node a Node (MAC).
> It was empty and selected modem thinking since it was my modem it's fitting but that acted (I think) assigned itself to itself? lol

Yeah - this will be the issue. How did you manage to do this? I disabled it on the Devices screen. Did you add it via the Network section?

@astronyu, @tismofied - To fix this, if you have a MAC other than `Internet` specified on the Internet node, you can do a Device.csv export/import. 

The system creates timestamped `devices.csv` export files with every start and stores it in the /config folder. (can be adjusted in the CSV Backup settings of the plugin) You can do a manual export as well via the Maintenance > Backup section. 

You can edit the Internet node in the CSV file and re-import it back. Just make sure you use an editor that doesn't change the line endings to Windows ones (e.g. Notepad ++, Nano, etc).

**Comment by tismofied** [comment]
In my usual haste of tinkering with things lol I made a backup and deleted the internet device and saved the config. That initiated a scan whic
![Screenshot 2023-09-30 at 16-59-51 Pi Alert - Turnkey-Docker](https://github.com/jokob-sk/Pi.Alert/assets/90809124/f6f571f6-881a-4727-aecc-2fa51dc4781b)
h resulted in finding my internet node again. All is good now. Thank you for the amazing fork.

**Comment by astronyu** [comment]
> In my usual haste of tinkering with things lol I made a backup and deleted the internet device and saved the config. That initiated a scan which resulted in finding my internet node again. All is good now. Thank you for the amazing fork.
> 
> ![Screenshot 2023-09-30 at 16-59-51 Pi Alert - Turnkey-Docker](https://user-images.githubusercontent.com/90809124/271795090-f6f571f6-881a-4727-aecc-2fa51dc4781b.png)

Any chance you could tell me what to do when trying to create a backup returns "The original database could not be saved."?
Or did you just delete the internet device from csv?

**Comment by astronyu** [comment]
> Hi @tismofied, thanks for the additional info.
> 
> > I am having the exact same issue. I was working on it all day today and I goofed and gave the internet parent node a Node (MAC).
> > It was empty and selected modem thinking since it was my modem it's fitting but that acted (I think) assigned itself to itself? lol
> 
> Yeah - this will be the issue. How did you manage to do this? I disabled it on the Devices screen. Did you add it via the Network section?
> 
> @astronyu, @tismofied - To fix this, if you have a MAC other than `Internet` specified on the Internet node, you can do a Device.csv export/import.
> 
> The system creates timestamped `devices.csv` export files with every start and stores it in the /config folder. (can be adjusted in the CSV Backup settings of the plugin) You can do a manual export as well via the Maintenance > Backup section.
> 
> You can edit the Internet node in the CSV file and re-import it back. Just make sure you use an editor that doesn't change the line endings to Windows ones (e.g. Notepad ++, Nano, etc).

Thank a lot. Did like what you explained, deleted the "Internet" from MAC and the network map returned.

**Comment by tismofied** [comment]
> Hi @tismofied, thanks for the additional info.
> 
> > I am having the exact same issue. I was working on it all day today and I goofed and gave the internet parent node a Node (MAC).
> > It was empty and selected modem thinking since it was my modem it's fitting but that acted (I think) assigned itself to itself? lol
> 
> Yeah - this will be the issue. How did you manage to do this? I disabled it on the Devices screen. Did you add it via the Network section?
I think what happened was , I was on the internet tab under network section and I saw a device that was unassigned at the bottom and I clicked assign and that added a device to the internet node. If there could be a way prehaps to make it not possible to assign devices under the internet node that might save a lot of people some headache.

**Comment by jokob-sk** [comment]
I can't promise this won't happen again, but I added another check before someone tries adding the node with the MAC `Internet` as a child leaf node. That would be now blocked by the app. Hope this will help. 

closing as resolved for now
