### ISSUE TITLE
[workaround] Down alerts for internet after update to 23.10.2 if schedules <plugin>_RUN_SCHD don't match

### ISSUE THREAD

**Issue by ameer1234567890** [jokob-sk/Pi.Alert#462]
After the recent update to 23.10.2, internet is showing as Down. All other devices are working fine. Please note that I have a NAT connection from ISP where I do not have a publicly accessible IP address.

**Comment by jokob-sk** [comment]
Hi,
Can you please try to make sure that you have the internet scan on the same schedule as the other scans that you have enabled?

Thanks,
J

**Comment by djraw** [comment]
I have the same issue with my docker container. Watchtower automatically updated today and after the container restarted, I received tons of down messages in my ntfy. But not only for the Internet device but for several other devices which are in fact runnung. I restarted the container hoping it would stop, but it continued.
I had to stop the container until this is fixed now. I didn't set anything special up for scheduling so I don't know what you asked for in the previous post @jokob-sk 

Here is one screenshots from my iPhone showing one of the ntfy messages:
![IMG_2428](https://github.com/jokob-sk/Pi.Alert/assets/10433914/29c5e9a9-14c8-427d-90c2-a2f50ee05a4d)

**Comment by jokob-sk** [comment]
@djraw can you confirm that you have the same schedule for all scans?

**Comment by djraw** [comment]
@jokob-sk what do you mean with that? I didn't set up any schedules..

**Comment by jokob-sk** [comment]
There is a schedule for each scan, including the internet scan. These schedules should be set to the same value if you want them to be reported in the same result. Check your settings on your scans. The internet scan is performed every 5 minutes by default (`*/5 * * * *`). Set the same schedule value on all scans of you want them reported in the same run.

**Comment by djraw** [comment]
OK, now I restartet the container and checked th config. Internet scan is still default */5 * * * *, Network scan ARP is set to */3 * * * *

**Comment by tismofied** [comment]
try to set ARP to match the internet and see if that fixes it. Watchtower just updated my container and both of my scans are on the same schedule and no issues with 23.10.2

**Comment by ameer1234567890** [comment]
I have now manually set same schedule for ARP and Internet plugins. No issues so far.

**Comment by djraw** [comment]
Setting the ARP schedule to */5 * * * * seems to have fixed it for me. I tested a bit and as soon as the schedules are different, I get false down messages again. I don't get how this is related. The schedules should work either way, synced or not synced.

And they did before the update today.
Also I noticed that the config format has changed. I made the last change to the config in February and now today. I checked the conf backups and saw the huge difference (some kind of json now?). Don't know if that leads to any of this, just wanted to let you know.

**Comment by corasaniti** [comment]
@jokob-sk 
Hi, I don't understand if there is a solution or we have to wait for a new release.
Thanks in advance

**Comment by corasaniti** [comment]
> I have now manually set same schedule for ARP and Internet plugins. No issues so far.
@ameer1234567890 
I don't quite understand what I should do and where to go to change? You could help me
Thank you

**Comment by corasaniti** [comment]
UPDATE
In the Scheduling settings I set the following parameter
`ARPSCAN_RUN_SCHD=*/5 * * * *`
it was before
`ARPSCAN_RUN_SCHD=*/3 * * * *`
I think it's now set up as the Internet SCAN
For now everything seems to be working.

**Comment by rama31244** [comment]
I also started receiving heaps of 'new device' notifications after the update and tried the suggested solution of updating ARPSCAN_RUN_SCHD to match the internet scan schedule but I'm still receiving emails constantly through the day. Any other ideas of solutions to try?

**Comment by jokob-sk** [comment]
@rama31244 this sounds like a separate issue as you are receiving new device notifications, not down notifications. Please open a new issue as this seems unrelated.

**Comment by masterwishx** [comment]
i have also disconnected messages for all network devices include intternet every scan :
1st scan connect
2nd scan disconnect 
...
...

**Comment by jokob-sk** [comment]
@masterwishx Can you please post your schedules for all enabled scans?

**Comment by masterwishx** [comment]
*/3 * * * * Arp
*/5 * * * * interent
now checking with both */5 * * * *

**Comment by masterwishx** [comment]
becose of this persistence look like this :  only server is green

![image](https://github.com/jokob-sk/Pi.Alert/assets/28630321/a4a35105-a6fb-4fb5-aade-a2dba0701eb0)

**Comment by jokob-sk** [comment]
@masterwishx Not sure what you are saying - if unrelated to the main topic, please open a new issue or contribute to an existing one (e.g. #454 might be of similar nature)

**Comment by masterwishx** [comment]
> Can you please post your schedules for all enabled scans?

i think problem solved when same schedule for ARP and Internet scan

**Comment by jokob-sk** [comment]
Locking as resolved

**Comment by jokob-sk** [comment]
The next release will display a warning in the new Settings dashboard if schedules on Device discovery scanners are out-of-sync.
![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/eb31b167-ce12-4777-9396-895fc879836e) 
![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/b4d7acd9-153f-40b0-92e7-c01ce24791d8)

**Comment by jokob-sk** [comment]
Released in 23.11.11
