### ISSUE TITLE
Internet Down With the latest version 23.10.2

### ISSUE THREAD

**Issue by corasaniti** [jokob-sk/Pi.Alert#463]
With the latest version 23.10.2 I noticed that the root node  of my network of the Internet Provider disconnects and reconnects approximately every 15 minutes.

It's a fake disconnect, obviously it's not true.
 For the moment I have downgraded to version 23.9.12.

Has anyone encountered the same problem?
Thanks in advance

**Comment by AleksCee** [comment]
Same issue on my instance.

**Comment by mixio60** [comment]
Internet down for me too.

**Comment by jokob-sk** [comment]
Answered in #462

**Comment by corasaniti** [comment]
@jokob-sk  only a question
what are events in events list?
VOIDED - Connected
VOIDED - Disconnected
VOIDED - Connected
VOIDED - Disconnected
...
...
VOIDED - Connected
VOIDED - Disconnected
Thanks

**Comment by jokob-sk** [comment]
I assume (since this is part of an older piece of code I didn't write) that this shows session events. When a session starts and ends. I will probably be looking at improving the notification system next, so I get also a better understanding of this part of the code.
