### ISSUE TITLE
Webhooks not Working

### ISSUE THREAD

**Issue by blackadar** [jokob-sk/Pi.Alert#469]
Webhooks do not appear to be working. I am using [https://webhook.site](https://webhook.site) to view all POSTs from Pi.Alert, and see none when using the "Test" button.

I would like to eventually use Webhooks with Discord.

This is what happens when I click Test:

![image](https://github.com/jokob-sk/Pi.Alert/assets/20449792/ac1050d4-1785-4e58-a8c8-6d51d2c55883)

Eventually it displays "0", then "finished". The webhook does not ever appear to be used.

The Webhook config is as follows:
![image](https://github.com/jokob-sk/Pi.Alert/assets/20449792/361011ca-7ad4-4f57-85e7-54630b271b7f)

The container is using "host" networking and detects devices and the internet.

**Comment by jokob-sk** [comment]
Hi there,

I'm testing webhooks regularly and they seemed to work on my end the last time I tested the feature.

> This is what happens when I click Test:

This is an unrelated issue.

Here is my testing setup with n8n: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/WEBHOOK_N8N.md

Please also follow the issue template, especially submitting the `pialert.log` to help you further.

See https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_TIPS.md for details. 

There is also a `webhook_payload.json` in the logs folder to help you debug the issue further. 

Thanks in advance for more details,
j

**Comment by Minituff** [comment]
I'm getting a Similar issue with NFTY. Notifications aren't working and I see this before switching to `finished`.

<img width="482" alt="image" src="https://github.com/jokob-sk/Pi.Alert/assets/8152401/d918953b-beb5-4130-bafb-93b445d5f1f0">

**Comment by jokob-sk** [comment]
@Minituff please read my above message for assistance.

**Comment by Minituff** [comment]
@jokob-sk Sorry for leaving out information. I created a new issue here: https://github.com/jokob-sk/Pi.Alert/issues/472

**Comment by jokob-sk** [comment]
MIght be related to #472

**Comment by blackadar** [comment]
Sorry for the lack of detail! And thanks for the quick follow up!

It turns out that, as you expected, the webhooks from normal processes are being delivered, just the test message is not:

![image](https://github.com/jokob-sk/Pi.Alert/assets/20449792/b92fa37b-b0b9-40d3-b589-f3e02f66e8e7)

Here is the log output from clicking the Webhook test button:

```
21:42:18 [Notification] Check if something to report
21:42:18 [Notification] Open text Template
21:42:18 [Notification] Open html Template
21:42:18 [Notification] Using template/back/report_template.html
21:42:19 [Notification] included sections: ['new_devices']
21:42:19 [Notification] New Devices sections done.
21:42:19 [Notification] No changes to report
21:42:19 [Notification] Notifications changes: 0
21:42:19 [MAIN] Process: Wait
21:42:24 [MAIN] waiting to start next loop
21:42:29 [MAIN] waiting to start next loop
21:42:34 [MAIN] waiting to start next loop
21:42:39 [MAIN] waiting to start next loop
21:42:44 [MAIN] waiting to start next loop
21:42:49 [MAIN] waiting to start next loop
21:42:54 [MAIN] waiting to start next loop
21:43:00 [MAIN] waiting to start next loop
21:43:05 [MAIN] waiting to start next loop
21:43:10 [MAIN] waiting to start next loop
21:43:15 [MAIN] waiting to start next loop
21:43:20 [Notification] Check if something to report
21:43:20 [Notification] Open text Template
21:43:20 [Notification] Open html Template
21:43:20 [Notification] Using template/back/report_template.html
21:43:20 [Notification] included sections: ['new_devices']
21:43:20 [Notification] New Devices sections done.
21:43:20 [Notification] No changes to report
21:43:20 [Notification] Notifications changes: 0
21:43:20 [MAIN] Process: Wait
21:43:25 [2023-10-07 21:43:25-04:00] START Test: Webhooks
mkdir: cannot create directory '/run/php': File exists
Starting nginx: nginx.
```

So it seems the ad-hoc test for the webhooks might be broken, as in #472?

**Comment by jokob-sk** [comment]
Great, thanks for the follow-up. Closing as duplicate :)
