### ISSUE TITLE
Crash error on python in docker

### ISSUE THREAD

**Issue by pabloalcantara** [jokob-sk/Pi.Alert#477]
After upgrade to version 23.10.2, onde docker container, the app stop working with an python error, returning to version 23.9 works again:

`  File "/home/pi/pialert/pialert/reporting.py", line 282, in send_notifications
    send_email (msg )
  File "/home/pi/pialert/pialert/publishers/email.py", line 85, in send
    smtp_connection.sendmail (conf.REPORT_FROM, conf.REPORT_TO, msg.as_string())
  File "/usr/lib/python3.9/smtplib.py", line 892, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (550, b'maximum allowed line length is 998 octets, got 1322')
11:05:07 [MAIN] Setting up ...
11:05:07 [conf.tz] Setting up ...
11:05:07 
11:05:07 The container restarted (started). If this is unexpected check https://bit.ly/PiAlertDebug for troubleshooting tips.
11:05:07 `

**Comment by lorki97** [comment]
Hi, please post your `pialert.conf` (remove personal info) and more of your `pialert.log` or docker logs (also remove personal info).

Line length limits is defined in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt). This would mean some line in the email exceeds this limit, this can be sender, receiver or body. How many devices do you have in your system? Maybe the report body becomes too long and requires splitting according to [RFC 5322](https://www.rfc-editor.org/rfc/rfc5322).

> 2.1.1. Line Length 
>
> Limits
> 
> There are two limits that this specification places on the number of characters in a line. Each line of characters MUST be no more than 998 characters, and SHOULD be no more than 78 characters, excluding the CRLF.
> 
> The 998 character limit is due to limitations in many implementations that send, receive, or store IMF messages which simply cannot handle more than 998 characters on a line.

> 2.2.3. Long Header Fields
>
> Each header field is logically a single line of characters comprising the field name, the colon, and the field body. For convenience however, and to deal with the 998/78 character limitations per line, the field body portion of a header field can be split into a multiple-line representation; this is called "folding". The general rule is that wherever this specification allows for folding white space (not simply WSP characters), a CRLF may be inserted before any WSP.

**Comment by jokob-sk** [comment]
closing as resolved / no repsonse
