### ISSUE TITLE
No device listed but two

### ISSUE THREAD

**Issue by adm2k** [jokob-sk/Pi.Alert#478]
Hello,

I am running pi.alert in a docker container on a Proxmox VM. When launched it only shows two devices.

Any suggestions are appreciated!

![image](https://github.com/jokob-sk/Pi.Alert/assets/120423301/456567f3-9a03-4f68-8430-e94293186744)

**Comment by jokob-sk** [comment]
Hi,

Please provide your pialert.conf. 

Thanks,
j

**Comment by adm2k** [comment]
see attached and thank you!

[config.txt](https://github.com/jokob-sk/Pi.Alert/files/12881703/config.txt)

**Comment by adm2k** [comment]
attaching logs as well...
[pialert.log](https://github.com/jokob-sk/Pi.Alert/files/12883869/pialert.log)

**Comment by jokob-sk** [comment]
Thanks you for the details!

Could you please confirm that your subnet is set correctly (with the correct interface (`192.168.1.0/24 --interface=eth0`)?

The log file shows that arpscan isn't returning any results, so I assume the interface isn't set correctly: 

```
07:06:44 [ARP Scan] userSubnetsParam: 192.168.1.0/24 --interface=eth0
07:06:55 [ARP Scan] arpscan_output: Interface: eth0, type: EN10MB, MAC: 3e:5a:4f:79:1e:f5, IPv4: 192.168.86.250
Starting arp-scan 1.9.7 with 256 hosts (https://github.com/royhills/arp-scan)

0 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.9.7: 256 hosts scanned in 11.179 seconds (22.90 hosts/sec). 0 responded

07:06:55 [ARP Scan] Found: Devices without duplicates 0
07:06:55 Devices List len:0
```

You can check available network interfaces under  `System info` > `Network Hardware`. It usually is eth0, eth1 etc. Please also read the docs for details: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/SUBNETS.md

Hope this helps,
j

**Comment by adm2k** [comment]
The config file shows http://192.168.1.0/24) --interface=eth0

and, ip a shows eth0

**Comment by jokob-sk** [comment]
Can you provide me with a screenshot of  System info > Network Hardware?

**Comment by adm2k** [comment]
By the way I am running this in a Docker container in Proxmox. Ubuntu 22.04

**Comment by adm2k** [comment]
![image](https://github.com/jokob-sk/Pi.Alert/assets/120423301/377dd3b7-8abf-4c5a-8d67-d7fea547dd7a)

**Comment by jokob-sk** [comment]
Please submit a screenshot of the `Network hardware` section

**Comment by ftrueck** [comment]
Change this:
SCAN_SUBNETS=['192.168.1.0/24 --interface=eth0']

to this:
SCAN_SUBNETS=['192.168.86.0/24 --interface=eth0']

**Comment by adm2k** [comment]
Made the change, is there a way to force a scan?

**Comment by adm2k** [comment]
It is working now!  two more quick questions in the devices tab it does not show any hostnames? and how do i load icons here
![image](https://github.com/jokob-sk/Pi.Alert/assets/120423301/3b0606b1-effa-42cd-ad19-233fce2013d0)

**Comment by ftrueck** [comment]
Device names: 
Your DNS server in your network has to provide the name for an given IP Address. If this does not work you have to configure your reverse DNS settings.

Icons:
the icons come from fontawesome free version.
Check here: https://fontawesome.com/search?m=free&o=r
These should work when you enter the names of them in the device settings.

**Comment by adm2k** [comment]
Thank you very much for all your help, I do appreciate it!

al...

**Comment by jokob-sk** [comment]
Click on the little (?) to read more about how to use icons. Thanks @ftrueck for the help 🙏
> closing as resolved

**Comment by adm2k** [comment]
I am assuming I need to install these icons somewhere first

**Comment by jokob-sk** [comment]
Click on the little (?) next to the icon input box to read more about how to use icons.
