### ISSUE TITLE
Time zone is not correct on current time and the presence graph

### ISSUE THREAD

**Issue by gkovacsp** [jokob-sk/Pi.Alert#48]
The top-right corner always shows GMT instead of the specified time-zone.

The currently active sessions on the presence graph seem to end at the current universal time and not the current local time. Already completed sessions are correct.

I've just recreated the container fresh from https://registry.hub.docker.com/r/jokobsk/pi.alert:latest (9:24 GMT) hoping one of the fixes will address it but it seems they do not
<img width="1103" alt="2022-07-26_11-26-36" src="https://user-images.githubusercontent.com/1654787/180973436-6fd5bcbb-7ba7-4b66-b268-3ac96f5cdce3.png">
.

**Comment by Final-Hawk** [comment]
Try adding this to your pialert.conf
`
TIMEZONE = 'your timezone'
`

**Comment by gkovacsp** [comment]
It is already set in the docker_compose file, is that not enough?
`    environment:
      - TZ=Europe/Budapest
`
If I add your line to pialert.conf it fixes the top-right clock, but not the end pf the active sessions on the presence graph.

**Comment by Final-Hawk** [comment]
> It is already set in the docker_compose file, is that not enough?

Not at the moment, working to fix that though. 

> not the end pf the active sessions on the presence graph.

I thought i fixed it before, but i seem to have only partially fixed it. I don't think its a timezone error, it seems to just not be passing the correct end time. I will look into it as i can reproduce on my end.

**Comment by Final-Hawk** [comment]
Update: I have identified and produced a fix locally. Will fix it up and make it suitable for a merge when i get a moment.
