### ISSUE TITLE
Default column sort order 

### ISSUE THREAD

**Issue by adm2k** [jokob-sk/Pi.Alert#480]
Is there a way to set the default column sort order on the devices screen? Or can one be added?

For example, sort order on last IP as default.

Many thanks, great tool!

al...

**Comment by jokob-sk** [comment]
Hi there,

This is currently not supported and my development priorities lie elsewhere. Feel free to submit a PR if you'd like to contribute :) See priorities below:

👨‍💻 Development priorities

Highest to lowest:

-     Fixing core functionality bugs not solvable with workarounds
-     New core functionality unlocking other opportunities (e.g.: plugins)
-     Refactoring enabling faster implementation of future functionality
-     UI improvements

More info in this issue: https://github.com/jokob-sk/Pi.Alert/issues/118

Thanks,
j
