### ISSUE TITLE
[idea] Generic webhook/MQTT notifications

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/Pi.Alert#49]
Similar to https://github.com/fosspill/Pi.Alert/blob/3654a07e3cceafdf5e9ebc72c8c6535ec7c6aaab/back/pialert.py#L1503

Webhooks allow for more integration options e.g.: 

https://docs.n8n.io/integrations/core-nodes/n8n-nodes-base.webhook/

And MQTT allows direct integration with home assistant

https://www.emqx.com/en/blog/how-to-use-mqtt-in-python

Not sure if users are after such a feature

**Comment by pabohoney1** [comment]
Would also love this, mostly for Discord alerting than anything else.

**Comment by jokob-sk** [comment]
Webhook support added (not tested on Discord/Slack, only on [n8n](https://n8n.io/):

https://github.com/jokob-sk/Pi.Alert/commit/4bdbba2eb1d9266e9088b0a1ce9a94f3bfc3a938
