### ISSUE TITLE
The new docker images are now 900mb comapred to 400mb previous version

### ISSUE THREAD

**Issue by sbe-arg** [jokob-sk/Pi.Alert#501]
![image](https://github.com/jokob-sk/Pi.Alert/assets/23391642/c73d0475-39e7-4c4a-8151-b6c1413c2979)

**Comment by jokob-sk** [comment]
I'm aware of that - I rewrote the whole installation script to make it easier maintainable across the on-HW and Docker install so this is expected. Happy to work on bringing the size down again, but I needed to get this release out for my own sanity :)

**Comment by sbe-arg** [comment]
Makes sense.

Ill try to help trimming down the image in a few weeks.

**Comment by jokob-sk** [comment]
closing for now
