### ISSUE TITLE
Can't set a password via the set_password plugin

### ISSUE THREAD

**Issue by ssellmann** [jokob-sk/Pi.Alert#503]
I use a fresh install of pialert. So no old config files or an old db. Debug mode is set. before_config_save is also set.

When I try to set a password for pialert via the plugin the password no password is set. 

[pialert.conf.txt](https://github.com/jokob-sk/Pi.Alert/files/13333703/pialert.conf.txt)

# last logs 
10:50:08 [Config] No old setting names found in the file. No changes made.
10:50:08 [Import Config] checking config file 
10:50:08 [Import Config] lastImportedConfFile     :1699868968.1392877
10:50:08 [Import Config] fileModifiedTime         :1699868968.1392877
10:50:08 [Import Config] skipping config file import
10:50:08 [2023-11-13 10:50:08+01:00] START Run: SETPWD
10:50:08 [Plugins] setTyp: password
10:50:08 [Plugins] Resolved value: secret_password
10:50:08 [Plugins] Convert to Base64: False
10:50:08 [Plugins] Timeout: 10
10:50:08 [Plugin utils] Pre-Resolved CMD: /home/pi/pialert/back/pialert-cliset_password{password}
10:50:08 [Plugins] Executing: /home/pi/pialert/back/pialert-cli set_password {password}
10:50:08 [Plugins] Resolved : ['/home/pi/pialert/back/pialert-cli', 'set_password', 'secret_password']
10:50:08 [Plugins] No output received from the plugin SETPWD - enable LOG_LEVEL=debug and check logs
10:50:08 [2023-11-13 10:50:08+01:00] END Run: SETPWD
tail: execution_queue.log: file truncated

**Comment by jokob-sk** [comment]
Hi there!

I just tried it now and it seems to work fine. 

You also have to set `PIALERT_WEB_PROTECTION=True`

Could you please try again?

Thanks,
j

**Comment by ssellmann** [comment]
Yeah I activated the option but nothing happened. Now I deactivated and activated the option again and now it works for some reason. Sorry for the inconvenience.

**Comment by jokob-sk** [comment]
All good - glad it's working 👍
