### ISSUE TITLE
Notifications exceptions 

### ISSUE THREAD

**Issue by pitoganzado** [jokob-sk/Pi.Alert#504]
Possibility to add exceptions to notifications. For example, continuing to detect devices and display them in the GUI, but there may be the possibility of not sending notifications for new devices on a network segment.

**Comment by jokob-sk** [comment]
Additional filtering options will be available in the next release. Check the announcement here for details: https://github.com/jokob-sk/Pi.Alert/issues/138

**Comment by jokob-sk** [comment]
Released -> Closing
