### ISSUE TITLE
Always receiving 403 Forbidden error

### ISSUE THREAD

**Issue by Schmidsfeld** [jokob-sk/Pi.Alert#506]
## Describe the issue

PiAlert is up and runing (according to docker)
if I connect to the correct IP/port I receive an nginx error 403 Forbidden.

For example: 
http://10.0.1.202:20211/

I tried it on another host using the default docker file, no configs (compeltely empty folders to start with) - same problem.

I also tried accessing 
http://10.0.1.202:20211/pialert
http://10.0.1.202:20211/admin

both resulted in a 404 not found error.

## Paste last few lines from `pialert.log`

12:31:51 [MAIN] waiting to start next loop
12:31:56 [MAIN] waiting to start next loop
12:32:01 [MAIN] waiting to start next loop
12:32:06 [MAIN] waiting to start next loop
12:32:11 [MAIN] waiting to start next loop
12:32:16 [MAIN] waiting to start next loop
12:32:22 [MAIN] waiting to start next loop
12:32:27 [MAIN] waiting to start next loop
12:32:32 [MAIN] waiting to start next loop
12:32:37 [MAIN] waiting to start next loop
12:32:42 [Notification] Check if something to report
12:32:42 [Notification] Open text Template
12:32:42 [Notification] Open html Template
12:32:42 [Notification] Using template/back/report_template.html
12:32:42 [Notification] included sections: ['internet', 'new_devices', 'down_devices', 'events']
12:32:42 [Notification] New Devices sections done.
12:32:42 [Notification] Down Devices sections done.
12:32:42 [Notification] Events sections done.
12:32:42 [Notification] Udating API files
12:32:42 [Send API] Updating notification_* files in /home/pi/pialert/front/api/
12:32:42 [Notification] No changes to report
12:32:42 [MAIN] Process: Wait
12:32:47 [MAIN] waiting to start next loop
12:32:52 [MAIN] waiting to start next loop
12:32:57 [MAIN] waiting to start next loop
12:33:02 [MAIN] waiting to start next loop
12:33:07 [MAIN] waiting to start next loop
12:33:13 [MAIN] waiting to start next loop
12:33:18 [MAIN] waiting to start next loop
12:33:23 [MAIN] waiting to start next loop
12:33:28 [MAIN] waiting to start next loop
12:33:34 [MAIN] waiting to start next loop
12:33:39 [MAIN] waiting to start next loop
12:33:44 [Notification] Check if something to report
12:33:44 [Notification] Open text Template
12:33:44 [Notification] Open html Template
12:33:44 [Notification] Using template/back/report_template.html
12:33:44 [Notification] included sections: ['internet', 'new_devices', 'down_devices', 'events']
12:33:44 [Notification] New Devices sections done.
12:33:44 [Notification] Down Devices sections done.
12:33:44 [Notification] Events sections done.
12:33:44 [Notification] Udating API files
12:33:44 [Send API] Updating notification_* files in /home/pi/pialert/front/api/
12:33:44 [Notification] No changes to report
12:33:44 [MAIN] Process: Wait
12:33:49 [MAIN] waiting to start next loop
12:33:54 [MAIN] waiting to start next loop
12:33:59 [MAIN] waiting to start next loop
12:34:04 [MAIN] waiting to start next loop
12:34:09 [MAIN] waiting to start next loop
12:34:14 [MAIN] waiting to start next loop
12:34:19 [MAIN] waiting to start next loop
12:34:24 [MAIN] waiting to start next loop
12:34:29 [MAIN] waiting to start next loop
12:34:34 [MAIN] waiting to start next loop
12:34:39 [MAIN] waiting to start next loop
12:34:44 [MAIN] waiting to start next loop
12:34:49 [Notification] Check if something to report
12:34:49 [Notification] Open text Template
12:34:49 [Notification] Open html Template
12:34:49 [Notification] Using template/back/report_template.html
12:34:49 [Notification] included sections: ['internet', 'new_devices', 'down_devices', 'events']
12:34:49 [Notification] New Devices sections done.
12:34:49 [Notification] Down Devices sections done.
12:34:49 [Notification] Events sections done.
12:34:49 [Notification] Udating API files
12:34:49 [Send API] Updating notification_* files in /home/pi/pialert/front/api/
12:34:49 [Notification] No changes to report
12:34:49 [MAIN] Process: Wait
12:34:54 [MAIN] waiting to start next loop
12:34:59 [MAIN] waiting to start next loop
12:35:05 [MAIN] waiting to start next loop
12:35:10 [MAIN] waiting to start next loop
12:35:15 [MAIN] waiting to start next loop
12:35:21 [MAIN] waiting to start next loop
12:35:26 [MAIN] waiting to start next loop
12:35:31 [MAIN] waiting to start next loop
12:35:37 [MAIN] waiting to start next loop
12:35:42 [MAIN] waiting to start next loop
12:35:47 [MAIN] waiting to start next loop

**Comment by Schmidsfeld** [comment]
looked a bit deeper (nginx log inside the docker container):
(Dont mind the different IP from before - different test system (server instead of raspberry pi)

2023/11/17 10:32:22 [error] 147#147: *1 directory index of "/var/www/html/" is forbidden, client: 10.0.4.1, server: _, request: "GET / HTTP/1.1", host: "10.0.1.111:20211"
2023/11/17 12:10:13 [error] 146#146: *2 directory index of "/var/www/html/" is forbidden, client: 10.0.4.1, server: _, request: "GET / HTTP/1.1", host: "10.0.1.111:20211"

seems to be a permission error on an internal folder 
although when looking on said permissions they seem ok:
root@pialert:/var/www/html# ls -alh
total 182K
drwxrwxrwx 10 pi www-data   27 Nov 17 10:29 .
drwxrwxrwx 10 pi www-data   10 Nov 17 10:29 ..
drwxrwxrwx  2 pi www-data   17 Nov 17 10:29 api
-rwxrwxrwx  1 pi www-data   11 Nov 11 01:51 buildtimestamp.txt
drwxrwxrwx  3 pi www-data    7 Nov 17 10:28 css
-rwxrwxrwx  1 pi www-data  72K Nov 11 01:49 deviceDetails.php
-rwxrwxrwx  1 pi www-data 8.8K Nov 11 01:49 deviceDetailsTools.php
-rwxrwxrwx  1 pi www-data  25K Nov 11 01:49 devices.php
-rwxrwxrwx  1 pi www-data 2.8K Nov 11 01:49 donations.php
-rwxrwxrwx  1 pi www-data  14K Nov 11 01:49 events.php
-rwxrwxrwx  1 pi www-data  793 Nov 11 01:49 flows.php
-rwxrwxrwx  1 pi www-data 9.1K Nov 11 01:49 help_faq.php
drwxrwxrwx  2 pi www-data   11 Nov 17 10:28 img
-rwxrwxrwx  1 pi www-data 6.4K Nov 11 01:49 index.php
drwxrwxrwx  2 pi www-data    6 Nov 17 10:29 js
drwxrwxrwx  5 pi www-data    5 Nov 17 10:29 lib
drwxrwxrwx  2 pi www-data   10 Nov 17 10:30 log
-rwxrwxrwx  1 pi www-data  43K Nov 11 01:49 maintenance.php
-rwxrwxrwx  1 pi www-data  30K Nov 11 01:49 network.php
drwxrwxrwx  4 pi www-data    4 Nov 17 10:28 php
drwxrwxrwx 30 pi www-data   34 Nov 17 10:30 plugins
-rwxrwxrwx  1 pi www-data  794 Nov 11 01:49 plugins.php
-rwxrwxrwx  1 pi www-data  22K Nov 11 01:49 pluginsCore.php
-rwxrwxrwx  1 pi www-data  16K Nov 11 01:49 presence.php
-rwxrwxrwx  1 pi www-data 7.0K Nov 11 01:49 report.php
-rwxrwxrwx  1 pi www-data  32K Nov 11 01:49 settings.php
-rwxrwxrwx  1 pi www-data  29K Nov 11 01:49 systeminfo.php


Is there somewhere the 192.*.*.* Networks hardcoded?

**Comment by jokob-sk** [comment]
Can you please post your docker-compose.yml file?

**Comment by Schmidsfeld** [comment]
Sure thing (had to change surprisingly little from the reference):

user 1000 exists and is called "home" on the host system.  This user is the owner of the /mnt/config directory. 
Time zone of the whole system is Europe/Berlin .

I forgot to mention - this container was operational (at least showing the webinterface) roughly 4-6 months ago - but I did not have the time to configure it completely.  

From what I garthered so far the root problems seems to be with the php interpretation of the webui. 
nginx is running, the gathering works (less successfull without configurations) just the rendring of index.php seems to fail. The permission error hints nginx wants to show the folder structure instead of rendering the correct php file / executing the php interpreter.... 

services:
  pialert:
    container_name: pialert
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/pi.alert_dev:latest" 
    image: "jokobsk/pi.alert:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - /mnt/config/pialert/config:/home/pi/pialert/config
      - /mnt/config/pialert/db:/home/pi/pialert/db      
      # (optional) useful for debugging if you have issues setting up the container
      - /mnt/config/pialert/logs:/home/pi/pialert/front/log
    environment:
      - TZ=Europe/Berlin      
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
      - PORT=20211

**Comment by Schmidsfeld** [comment]
I just tried the dev branch - and it works!

usually I don't want to run dev, because stuff needs to just work (when the family is home).
seems there might be a regression in the stable branch.

I tried again  using the identical command just deleteing the _dev and the problem returns.
trying to access for example http://10.0.1.202:20211/devices.php results in a download of the php file instad of the shown device overviw webinterface as before (I just reloaded the page still open).

hope this helps narrowing things down.

**Comment by jokob-sk** [comment]
Glad to hear this is fixed in the `_dev` image. That means this will be fixed in the next release. The odd thing is the current image seems to be working fine for me. You can try deleting the container, all cached images and rebuilding it again with the latest tag. 

But again, since this is working in the `_dev` image the fix will be rolled out into the next release.

**Comment by shaunsull** [comment]
Just confirming the issue on a new deployment of the main branch, but worked in the jokobsk/pi.alert_dev:latest

**Comment by Schmidsfeld** [comment]
confirmed - i swittched to the dev branch and it now works.

**Comment by JayKayUk** [comment]
I just spent 3h trying to fix this, turned out it was UFW blocking requests... `sudo ufw allow from 192.168.1.0/24 to any port 20211` fixed it.

**Comment by jokob-sk** [comment]
closing as released 🚀

**Comment by NikMAX2077** [comment]
I faced the same problem in the both release and dev latest version

**Comment by jokob-sk** [comment]
@NikMAX2077 please open a separate issue with additional details so that I can help you.

**Comment by NikMAX2077** [comment]
> @NikMAX2077 please open a separate issue with additional details so that I can help you.

In my case problem was in docker user namespaces remap. After I disabled and recreates container in "normal" docker - web ui started successfully.
