### ISSUE TITLE
[bug] Saving the root Internet node saves incorrect data - "Unconfigurable root"

### ISSUE THREAD

**Issue by costispavlou** [jokob-sk/Pi.Alert#507]
I'm loosing my mind trying to figure out what's wrong with this.
![image](https://github.com/jokob-sk/Pi.Alert/assets/57916603/9ad0e3ab-3c35-4928-9b61-76a17bd6a1d9)
![image](https://github.com/jokob-sk/Pi.Alert/assets/57916603/cf46678d-c627-4be7-add8-6c56582fa21b)
can someone please explain how to fix this?

**Comment by jokob-sk** [comment]
This is probably a bug - try deleting the device, let the app rediscover it again. You won't be able to save the changes until this is fixed or you could export the CSV > Edit the device > Import the CSV via the maintenance section as a temporary workaround.

**Comment by jokob-sk** [comment]
same as #467

**Comment by costispavlou** [comment]
> This is probably a bug - try deleting the device, let the app rediscover it again. You won't be able to save the changes until this is fixed or you could export the CSV > Edit the device > Import the CSV via the maintenance section as a temporary workaround.

How can I import the csv back to pi.alert? I edited successfully the devices.csv but can't upload it back.

**Comment by jokob-sk** [comment]
This guide should help: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEVICES_BULK_EDITING.md

**Comment by jokob-sk** [comment]
This should be fixed in the dev image and next release - you can test the _dev image in about 20 min

**Comment by jokob-sk** [comment]
closing as released 🚀
