### ISSUE TITLE
Multiples IP on a single MAC

### ISSUE THREAD

**Issue by Korvenwin** [jokob-sk/Pi.Alert#515]
I'm using an UnRaid server on my network. This server is running lots of dockers and some of them are connected to the a custom network so each one have a diferent IP. I use the network driver ipvlan becaus if I use macvlan, the server is not stable.

So my problem is that Pi.alert find only one MAC for the server with variable IPs over time.

Is there any solution to find this IPs or manually add them to the same MAC?

**Comment by jokob-sk** [comment]
Hi there,

IP addresses could be tracked via the Plugin section depending on the scanner plugins you've enabled:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/edcb87b5-2f04-4d3a-b50a-196dc8652b37)

Some users add fake devices via the Undiscoverables plugin - there has been a request to make the IP address configurable: https://github.com/jokob-sk/Pi.Alert/issues/426

This way you could have a fake MAC and the correct IP in your Devices view. If that would solve your use case you can either submit a PR (faster) or I might get to it in the next few months (slower). It's not high on my priority list.  

J

**Comment by jokob-sk** [comment]
workaround provided & no reply for a while > closing for now
