### ISSUE TITLE
Device with "vendor-class-identifier" MAC Address and an "=" for IP Address

### ISSUE THREAD

**Issue by ajtatum** [jokob-sk/Pi.Alert#516]
## Describe the issue

There's a device on my network, I support, that's returning a MAC Address of "vendor-class-identifier" and an equal sign for the IP address. This breaks the front end in such a way that I can't view any devices. I'm not sure where this device is coming from or anything, but I was hoping to find a way so that it would simply skip the one record so that it can display the rest.

```
{
			"rowid": 101,
			"dev_MAC": "vendor-class-identifier",
			"dev_Name": "\"udhcp",
			"dev_Owner": "House",
			"dev_DeviceType": "",
			"dev_Vendor": null,
			"dev_Favorite": 0,
			"dev_Group": "",
			"dev_Comments": "",
			"dev_FirstConnection": "2023-12-07 12:40:07-05:00",
			"dev_LastConnection": "2023-12-07 12:40:07-05:00",
			"dev_LastIP": "=",
			"dev_StaticIP": 0,
			"dev_ScanCycle": 1,
			"dev_LogEvents": 1,
			"dev_AlertEvents": 1,
			"dev_AlertDeviceDown": 0,
			"dev_SkipRepeated": 0,
			"dev_LastNotification": "2023-12-07 12:40:12-05:00",
			"dev_PresentLastScan": 1,
			"dev_NewDevice": 1,
			"dev_Location": "",
			"dev_Archived": 0,
			"dev_Network_Node_MAC_ADDR": "",
			"dev_Network_Node_port": null,
			"dev_Icon": ""
		}
```

**Comment by ajtatum** [comment]
I should have checked this before, but I recently turned on DHCP Leases and have OPNsense send over it's dhcpd.leases file over to my NAS where Pi.Alert runs. When I looked at the logs more closely in Pi.Alert, it seemed to be stemming from that Plugin so I took a look at the dhcpd.leases file (I kind of assumed that the format of this file was standard, but perhaps not).

Here are a few entries:

```
lease 192.168.185.45 {
  starts 3 2023/12/06 18:52:49;
  ends 3 2023/12/06 20:52:49;
  cltt 3 2023/12/06 18:52:49;
  binding state active;
  next binding state free;
  rewind binding state free;
  hardware ethernet e0:46:ee:ff:fd:f7;
}
lease 192.168.145.27 {
  starts 3 2023/12/06 18:56:39;
  ends 3 2023/12/06 20:56:39;
  cltt 3 2023/12/06 18:56:39;
  binding state active;
  next binding state free;
  rewind binding state free;
  hardware ethernet 44:07:0b:ee:32:bb;
  set vendor-class-identifier = "dhcpcd-6.8.2:Linux-3.8.13+:armv7l:Marvell";
  client-hostname "Google-Home-Mini";
}
lease 192.168.185.35 {
  starts 3 2023/11/22 02:41:42;
  ends 3 2023/11/22 04:41:42;
  tstp 3 2023/11/22 04:41:42;
  cltt 3 2023/11/22 02:41:42;
  binding state free;
  hardware ethernet 18:c2:3c:15:07:8f;
  uid "\001\030\302<\025\007\217";
  set vendor-class-identifier = "udhcp 1.22.1";
}
```

Most entries look like the first on; however, there are a handful that appear as the last two. If the first object is what's to be expected; I could probably run some script to remove all lines that start with "uid" and "set vendor-class-identifier". If the output is totally off, then I guess I won't bother with the plugin. Any thoughts?

(By the way, for now, I logged into the container and modified some of the Javascript that interacts with the data result set so that it filters out objects that have an improper IP or MAC, so at least now I can view the dashboard. This obviously isn't an ideal long term solution.)

**Comment by ajtatum** [comment]
Any ideas in regards to the formatting of the dhcp.leases file?

**Comment by jokob-sk** [comment]
Hi @ajtatum, 
Thanks for the patience - recovering from the flu. 

I implemented a MAC validity check which should fix this issue. The change is being deployed in the `_dev` image so would be great if you could give it a try. 

Cheers,
j

**Comment by jokob-sk** [comment]
closing as released 🚀
