### ISSUE TITLE
UnboundLocalError: cannot access local variable 'json_plugins_meta' where it is not associated with a value

### ISSUE THREAD

**Issue by iball** [jokob-sk/Pi.Alert#519]
## PiAlert constantly restarting
PiAlert keeps crashing out and restarting since last dev update.  Starts importing 26 plugins then always hangs on "Import plugin 25 of 26" and eventually crashes PiAlert entirely.

```bash
PiAlert  | ---------------------------------------------------------
PiAlert  | [INSTALL]                                    Run start.sh
PiAlert  | ---------------------------------------------------------
PiAlert  | [INSTALL] Run setup scripts
PiAlert  | ---------------------------------------------------------
PiAlert  | [INSTALL]                             Run user-mapping.sh
PiAlert  | ---------------------------------------------------------
PiAlert  | Nothing to do here.
PiAlert  | ---------------------------------------------------------
PiAlert  | [INSTALL]                     Run install_dependencies.sh
PiAlert  | ---------------------------------------------------------
PiAlert  | Reading package lists...
PiAlert  | Building dependency tree...
PiAlert  | Reading state information...
PiAlert  | tini is already the newest version (0.19.0-1).
PiAlert  | snmp is already the newest version (5.9.3+dfsg-2).
PiAlert  | ca-certificates is already the newest version (20230311).
PiAlert  | curl is already the newest version (7.88.1-10+deb12u4).
PiAlert  | libwww-perl is already the newest version (6.68-1).
PiAlert  | arp-scan is already the newest version (1.10.0-2).
PiAlert  | perl is already the newest version (5.36.0-7+deb12u1).
PiAlert  | apt-utils is already the newest version (2.6.1).
PiAlert  | cron is already the newest version (3.0pl1-162).
PiAlert  | sudo is already the newest version (1.9.13p3-1+deb12u1).
PiAlert  | nginx-light is already the newest version (1.22.1-9).
PiAlert  | php is already the newest version (2:8.2+93).
PiAlert  | php-cgi is already the newest version (2:8.2+93).
PiAlert  | php-fpm is already the newest version (2:8.2+93).
PiAlert  | php-sqlite3 is already the newest version (2:8.2+93).
PiAlert  | php-curl is already the newest version (2:8.2+93).
PiAlert  | sqlite3 is already the newest version (3.40.1-2).
PiAlert  | dnsutils is already the newest version (1:9.18.19-1~deb12u1).
PiAlert  | net-tools is already the newest version (2.10-0.1).
PiAlert  | python3 is already the newest version (3.11.2-1+b1).
PiAlert  | iproute2 is already the newest version (6.1.0-3).
PiAlert  | nmap is already the newest version (7.93+dfsg1-1).
PiAlert  | python3-pip is already the newest version (23.0.1+dfsg-1).
PiAlert  | zip is already the newest version (3.0-13).
PiAlert  | systemctl is already the newest version (1.4.4181-1.1).
PiAlert  | usbutils is already the newest version (1:014-1).
PiAlert  | traceroute is already the newest version (1:2.1.2-1).
PiAlert  | 0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
PiAlert  | Reading package lists...
PiAlert  | Building dependency tree...
PiAlert  | Reading state information...
PiAlert  | nginx is already the newest version (1.22.1-9).
PiAlert  | nginx-core is already the newest version (1.22.1-9).
PiAlert  | mtr is already the newest version (0.95-1).
PiAlert  | php-fpm is already the newest version (2:8.2+93).
PiAlert  | php8.2-fpm is already the newest version (8.2.7-1~deb12u1).
PiAlert  | php-cli is already the newest version (2:8.2+93).
PiAlert  | php8.2 is already the newest version (8.2.7-1~deb12u1).
PiAlert  | php8.2-sqlite3 is already the newest version (8.2.7-1~deb12u1).
PiAlert  | 0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
PiAlert  | Reading package lists...
PiAlert  | Building dependency tree...
PiAlert  | Reading state information...
PiAlert  | python3.11-venv is already the newest version (3.11.2-6).
PiAlert  | python3.11-venv set to manually installed.
PiAlert  | 0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
PiAlert  | Requirement already satisfied: requests in /myenv/lib/python3.11/site-packages (2.31.0)
PiAlert  | Requirement already satisfied: paho-mqtt in /myenv/lib/python3.11/site-packages (1.6.1)
PiAlert  | Requirement already satisfied: scapy in /myenv/lib/python3.11/site-packages (2.5.0)
PiAlert  | Requirement already satisfied: cron-converter in /myenv/lib/python3.11/site-packages (1.0.2)
PiAlert  | Requirement already satisfied: pytz in /myenv/lib/python3.11/site-packages (2023.3.post1)
PiAlert  | Requirement already satisfied: json2table in /myenv/lib/python3.11/site-packages (1.1.5)
PiAlert  | Requirement already satisfied: dhcp-leases in /myenv/lib/python3.11/site-packages (0.1.6)
PiAlert  | Requirement already satisfied: pyunifi in /myenv/lib/python3.11/site-packages (2.21)
PiAlert  | Requirement already satisfied: speedtest-cli in /myenv/lib/python3.11/site-packages (2.1.3)
PiAlert  | Requirement already satisfied: chardet in /myenv/lib/python3.11/site-packages (5.2.0)
PiAlert  | Requirement already satisfied: charset-normalizer<4,>=2 in /myenv/lib/python3.11/site-packages (from requests) (3.3.2)
PiAlert  | Requirement already satisfied: idna<4,>=2.5 in /myenv/lib/python3.11/site-packages (from requests) (3.6)
PiAlert  | Requirement already satisfied: urllib3<3,>=1.21.1 in /myenv/lib/python3.11/site-packages (from requests) (2.1.0)
PiAlert  | Requirement already satisfied: certifi>=2017.4.17 in /myenv/lib/python3.11/site-packages (from requests) (2023.11.17)
PiAlert  | Requirement already satisfied: python-dateutil in /myenv/lib/python3.11/site-packages (from cron-converter) (2.8.2)
PiAlert  | Requirement already satisfied: six>=1.5 in /myenv/lib/python3.11/site-packages (from python-dateutil->cron-converter) (1.16.0)
PiAlert  | [INSTALL] Setup NGINX
PiAlert  | Disabling default NGINX site, removing sym-link in /etc/nginx/sites-enabled
PiAlert  | Setting webserver to user-supplied port (20211)
PiAlert  | [INSTALL] Run the hardware vendors update
PiAlert  | The file ieee-oui.txt exists. Skipping update_vendors.sh...
PiAlert  | [INSTALL] Fixing file permissions
PiAlert  | [INSTALL] Copy starter pialert.db and pialert.conf if they don't exist
PiAlert  | Starting nginx: nginx.
PiAlert  | Traceback (most recent call last):
PiAlert  |   File "<frozen runpy>", line 198, in _run_module_as_main
PiAlert  |   File "<frozen runpy>", line 88, in _run_code
PiAlert  |   File "/home/pi/pialert/pialert/__main__.py", line 195, in <module>
PiAlert  |     sys.exit(main())       
PiAlert  |              ^^^^^^
PiAlert  |   File "/home/pi/pialert/pialert/__main__.py", line 154, in main
PiAlert  |     final_json = get_notifications(db)
PiAlert  |                  ^^^^^^^^^^^^^^^^^^^^^
PiAlert  |   File "/home/pi/pialert/pialert/reporting.py", line 141, in get_notifications
PiAlert  |     "plugins_meta": json_plugins_meta,
PiAlert  |                     ^^^^^^^^^^^^^^^^^
PiAlert  | UnboundLocalError: cannot access local variable 'json_plugins_meta' where it is not associated with a value
PiAlert  | 17:22:09 [MAIN] Setting up ...
PiAlert  | 17:22:09 [conf.tz] Setting up ...
PiAlert  | 17:22:09 
PiAlert  | 
PiAlert  | 17:22:09 The container restarted (started). If this is unexpected check https://bit.ly/PiAlertDebug for troubleshooting tips.
PiAlert  | 17:22:09 
PiAlert  | 
PiAlert  | 17:22:09 Permissions check (All should be True)
PiAlert  | 17:22:09 ------------------------------------------------
PiAlert  | 17:22:09   /config/pialert.conf |  READ  | True
PiAlert  | 17:22:09   /config/pialert.conf |  WRITE | True
PiAlert  | 17:22:09   /db/pialert.db       |  READ  | True
PiAlert  | 17:22:09   /db/pialert.db       |  WRITE | True
PiAlert  | 17:22:09 ------------------------------------------------
PiAlert  | 17:22:09 [Setup] Attempting to fix permissions.
PiAlert  | 17:22:10 [Setup] Attempting to fix permissions.
PiAlert  | 17:22:10 [Database] Opening DB
PiAlert  | 17:22:10 [upgradeDB] Re-creating Settings table
PiAlert  | 17:22:10 [upgradeDB] Re-creating Pholus_Scan table
PiAlert  | 17:22:10 [upgradeDB] Re-creating Parameters table
PiAlert  | 17:22:10 [Version check] Running the latest version.
PiAlert  | 17:22:10 [Config] reading config file
PiAlert  | 11:22:10 [Config] Plugins: Number of dynamically loaded plugins: 26
PiAlert  | 11:22:17 [Config] Imported new config
PiAlert exited with code 0
'''
From the logs inside PiAlert itself:

'''
17:46:29 The container restarted (started). If this is unexpected check https://bit.ly/PiAlertDebug for troubleshooting tips.
17:46:29 

17:46:29 Permissions check (All should be True)
17:46:29 ------------------------------------------------
17:46:29   /config/pialert.conf |  READ  | True
17:46:29   /config/pialert.conf |  WRITE | True
17:46:29   /db/pialert.db       |  READ  | True
17:46:29   /db/pialert.db       |  WRITE | True
17:46:29 ------------------------------------------------
17:46:29 [Setup] Attempting to fix permissions.
17:46:29 [Setup] Attempting to fix permissions.
17:46:29 [Database] Opening DB
17:46:29 [upgradeDB] Re-creating Settings table
17:46:29 [upgradeDB] Re-creating Pholus_Scan table
17:46:29 [upgradeDB] Re-creating Parameters table
17:46:29 [Config] reading config file
11:46:29 [Config] Plugins: Number of dynamically loaded plugins: 26
'''

**Comment by jokob-sk** [comment]
Thanks for testing the `_dev` image. Let me know if issues persist after the next build.

**Comment by iball** [comment]
Will do, Jokob.

**Comment by iball** [comment]
OK, just updated the DEV container and it seems to have fixed it.

``
PiAlert  | ---------------------------------------------------------
PiAlert  | [INSTALL]                                    Run start.sh
PiAlert  | ---------------------------------------------------------
PiAlert  | [INSTALL] Run setup scripts
PiAlert  | ---------------------------------------------------------
PiAlert  | [INSTALL]                             Run user-mapping.sh
PiAlert  | ---------------------------------------------------------
PiAlert  | Nothing to do here.
PiAlert  | ---------------------------------------------------------
PiAlert  | [INSTALL]                     Run install_dependencies.sh
PiAlert  | ---------------------------------------------------------
PiAlert  | Reading package lists...
PiAlert  | Building dependency tree...
PiAlert  | Reading state information...
PiAlert  | tini is already the newest version (0.19.0-1).
PiAlert  | snmp is already the newest version (5.9.3+dfsg-2).
PiAlert  | ca-certificates is already the newest version (20230311).
PiAlert  | curl is already the newest version (7.88.1-10+deb12u4).
PiAlert  | libwww-perl is already the newest version (6.68-1).
PiAlert  | arp-scan is already the newest version (1.10.0-2).
PiAlert  | perl is already the newest version (5.36.0-7+deb12u1).
PiAlert  | apt-utils is already the newest version (2.6.1).
PiAlert  | cron is already the newest version (3.0pl1-162).
PiAlert  | sudo is already the newest version (1.9.13p3-1+deb12u1).
PiAlert  | nginx-light is already the newest version (1.22.1-9).
PiAlert  | php is already the newest version (2:8.2+93).
PiAlert  | php-cgi is already the newest version (2:8.2+93).
PiAlert  | php-fpm is already the newest version (2:8.2+93).
PiAlert  | php-sqlite3 is already the newest version (2:8.2+93).
PiAlert  | php-curl is already the newest version (2:8.2+93).
PiAlert  | sqlite3 is already the newest version (3.40.1-2).
PiAlert  | dnsutils is already the newest version (1:9.18.19-1~deb12u1).
PiAlert  | net-tools is already the newest version (2.10-0.1).
PiAlert  | python3 is already the newest version (3.11.2-1+b1).
PiAlert  | iproute2 is already the newest version (6.1.0-3).
PiAlert  | nmap is already the newest version (7.93+dfsg1-1).
PiAlert  | python3-pip is already the newest version (23.0.1+dfsg-1).
PiAlert  | zip is already the newest version (3.0-13).
PiAlert  | systemctl is already the newest version (1.4.4181-1.1).
PiAlert  | usbutils is already the newest version (1:014-1).
PiAlert  | traceroute is already the newest version (1:2.1.2-1).
PiAlert  | 0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
PiAlert  | Reading package lists...
PiAlert  | Building dependency tree...
PiAlert  | Reading state information...
PiAlert  | nginx is already the newest version (1.22.1-9).
PiAlert  | nginx-core is already the newest version (1.22.1-9).
PiAlert  | mtr is already the newest version (0.95-1).
PiAlert  | php-fpm is already the newest version (2:8.2+93).
PiAlert  | php8.2-fpm is already the newest version (8.2.7-1~deb12u1).
PiAlert  | php-cli is already the newest version (2:8.2+93).
PiAlert  | php8.2 is already the newest version (8.2.7-1~deb12u1).
PiAlert  | php8.2-sqlite3 is already the newest version (8.2.7-1~deb12u1).
PiAlert  | 0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
PiAlert  | Reading package lists...
PiAlert  | Building dependency tree...
PiAlert  | Reading state information...
PiAlert  | python3.11-venv is already the newest version (3.11.2-6).
PiAlert  | python3.11-venv set to manually installed.
PiAlert  | 0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
PiAlert  | Requirement already satisfied: requests in /myenv/lib/python3.11/site-packages (2.31.0)
PiAlert  | Requirement already satisfied: paho-mqtt in /myenv/lib/python3.11/site-packages (1.6.1)
PiAlert  | Requirement already satisfied: scapy in /myenv/lib/python3.11/site-packages (2.5.0)
PiAlert  | Requirement already satisfied: cron-converter in /myenv/lib/python3.11/site-packages (1.0.2)
PiAlert  | Requirement already satisfied: pytz in /myenv/lib/python3.11/site-packages (2023.3.post1)
PiAlert  | Requirement already satisfied: json2table in /myenv/lib/python3.11/site-packages (1.1.5)
PiAlert  | Requirement already satisfied: dhcp-leases in /myenv/lib/python3.11/site-packages (0.1.6)
PiAlert  | Requirement already satisfied: pyunifi in /myenv/lib/python3.11/site-packages (2.21)
PiAlert  | Requirement already satisfied: speedtest-cli in /myenv/lib/python3.11/site-packages (2.1.3)
PiAlert  | Requirement already satisfied: chardet in /myenv/lib/python3.11/site-packages (5.2.0)
PiAlert  | Requirement already satisfied: charset-normalizer<4,>=2 in /myenv/lib/python3.11/site-packages (from requests) (3.3.2)
PiAlert  | Requirement already satisfied: idna<4,>=2.5 in /myenv/lib/python3.11/site-packages (from requests) (3.6)
PiAlert  | Requirement already satisfied: urllib3<3,>=1.21.1 in /myenv/lib/python3.11/site-packages (from requests) (2.1.0)
PiAlert  | Requirement already satisfied: certifi>=2017.4.17 in /myenv/lib/python3.11/site-packages (from requests) (2023.11.17)
PiAlert  | Requirement already satisfied: python-dateutil in /myenv/lib/python3.11/site-packages (from cron-converter) (2.8.2)
PiAlert  | Requirement already satisfied: six>=1.5 in /myenv/lib/python3.11/site-packages (from python-dateutil->cron-converter) (1.16.0)
PiAlert  | [INSTALL] Setup NGINX
PiAlert  | Disabling default NGINX site, removing sym-link in /etc/nginx/sites-enabled
PiAlert  | Setting webserver to user-supplied port (20211)
PiAlert  | [INSTALL] Run the hardware vendors update
PiAlert  | The file ieee-oui.txt exists. Skipping update_vendors.sh...
PiAlert  | [INSTALL] Fixing file permissions
PiAlert  | [INSTALL] Copy starter pialert.db and pialert.conf if they don't exist
PiAlert  | Starting nginx: nginx.

**Comment by jokob-sk** [comment]
Cool, thanks > closing
