### ISSUE TITLE
[bug] PiHole (Device sync) not working due to incorrect PIHOLE_CMD SQL query

### ISSUE THREAD

**Issue by jsmith432** [jokob-sk/Pi.Alert#521]
First time install, I have four scanners: Internet-Check, PiHole (Device sync), DHCP Leases (Device import), and Arp-Scan (Network scan). They are all on the same schedule [*/10 * * * *]. DHCP leases and ARP took a while to produce anything, but they are working. I don't see anything coming from PiHole (Device sync). I enabled debug but cannot see anything abnormal in the log. I also had debug on because I couldn't make SMTP publisher work but I quit that and configured apprise to talk to my SMTP. During that time, no errors from SMTP were in the log, so I wonder where all plugin errors go. 

The files are properly mounted, I logged inside the container just to make sure it was there (/etc/pihole/pihole-FTL.db)

Happy to provide more information.

**Comment by jokob-sk** [comment]
Hi there!

Can you please provide the log for the PiHole plugin load from the pialert.log file? The relevant section should contain a log similar to the one below (notice the first line):

```
17:31:05 [Scheduler] - Scheduler run for PIHOLE: YES
17:31:05 [Plugin utils] ---------------------------------------------
17:31:05 [Plugin utils] display_name: PiHole (Device sync)
17:31:05 [Plugins] CMD: SELECT n.hwaddr AS Object_PrimaryID, {s-quote}null{s-quote} AS Object_SecondaryID, datetime() AS DateTime, na.ip  AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, {s-quote}null{s-quote} AS Extra, n.hwaddr AS ForeignKey FROM EXTERNAL_PIHOLE.Network AS n LEFT JOIN EXTERNAL_PIHOLE.Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE {s-quote}ip-%{s-quote} AND n.hwaddr is not {s-quote}00:00:00:00:00:00{s-quote}  AND na.ip is not null
17:31:05 [Plugins] setTyp: subnets
17:31:05 [Plugin utils] Flattening the below array
17:31:05 ['192.168.1.0/24 --interface=eth1']
17:31:05 [Plugin utils] isinstance(arr, list) : False | isinstance(arr, str) : True
17:31:05 [Plugins] Resolved value: 192.168.1.0/24 --interface=eth1
17:31:05 [Plugins] Convert to Base64: True
17:31:05 [Plugins] base64 value: b'MTkyLjE2OC4xLjAvMjQgLS1pbnRlcmZhY2U9ZXRoMQ=='
17:31:05 [Plugins] Timeout: 10
17:31:05 [Plugins] Executing: SELECT n.hwaddr AS Object_PrimaryID, 'null' AS Object_SecondaryID, datetime() AS DateTime, na.ip  AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, 'null' AS Extra, n.hwaddr AS ForeignKey FROM EXTERNAL_PIHOLE.Network AS n LEFT JOIN EXTERNAL_PIHOLE.Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE 'ip-%' AND n.hwaddr is not '00:00:00:00:00:00'  AND na.ip is not null
17:31:05 [Plugins] SUCCESS, received 2 entries
17:31:05 [Plugins] sqlParam entries: [(0, 'PIHOLE', '01:01:01:01:01:01', 'null', 'null', '2023-12-25 06:31:05', '172.30.0.1', 0, 'aaaa', 'vvvvvvvvv', 'not-processed', 'null', 'null', '01:01:01:01:01:01'), (0, 'PIHOLE', '02:42:ac:1e:00:02', 'null', 'null', '2023-12-25 06:31:05', '172.30.0.2', 0, 'dddd', 'vvvvv2222', 'not-processed', 'null', 'null', '02:42:ac:1e:00:02')]
17:31:05 [Plugins] Processing        : PIHOLE
17:31:05 [Plugins] Existing objects from Plugins_Objects: 4
17:31:05 [Plugins] Logged events from the plugin run    : 2
17:31:05 [Plugins] pluginEvents      count: 2
17:31:05 [Plugins] pluginObjects     count: 4
17:31:05 [Plugins] events_to_insert  count: 0
17:31:05 [Plugins] history_to_insert count: 4
17:31:05 [Plugins] objects_to_insert count: 0
17:31:05 [Plugins] objects_to_update count: 4
17:31:05 [Plugin utils] In pluginEvents there are 2 events with the status "watched-not-changed" 
17:31:05 [Plugin utils] In pluginObjects there are 2 events with the status "missing-in-last-scan" 
17:31:05 [Plugin utils] In pluginObjects there are 2 events with the status "watched-not-changed" 
17:31:05 [Plugins] Mapping objects to database table: CurrentScan
17:31:05 [Plugins] SQL query for mapping: INSERT into CurrentScan ( "cur_MAC", "cur_IP", "cur_LastQuery", "cur_Name", "cur_Vendor", "cur_ScanMethod") VALUES ( ?, ?, ?, ?, ?, ?)
17:31:05 [Plugins] SQL sqlParams for mapping: [('01:01:01:01:01:01', '172.30.0.1', 0, 'aaaa', 'vvvvvvvvv', 'PIHOLE'), ('02:42:ac:1e:00:02', '172.30.0.2', 0, 'dddd', 'vvvvv2222', 'PIHOLE')]
17:31:05 [API] Update API starting
17:31:06 [API] Updating table_plugins_history.json file in /front/api
```

If nothing too different shows up, check also the Plugins objects imported by the plugin:

![plugin_objects_pihole](https://github.com/jokob-sk/Pi.Alert/assets/96159884/8a8707f9-84cf-46a6-8c04-4921b6548f09)

**Comment by jokob-sk** [comment]
One more thing - can you try to use the dev branch to see if issues persist?

```yaml
version: "3.9"
services:
  pialert_dev:
    ...
    image: "jokobsk/pi.alert_dev:latest"
    ...

```

**Comment by jsmith432** [comment]
I see more information on the logs now with the _dev:

`19:50:59 [Scheduler] - Scheduler run for PIHOLE: YES
19:50:59 [Plugin utils] ---------------------------------------------
19:50:59 [Plugin utils] display_name: PiHole (Device sync)
19:50:59 [Plugins] CMD: SELECT n.hwaddr AS Object_PrimaryID, {s-quote}null{s-quote} AS Object_SecondaryID, datetime() AS DateTime, na.ip  AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, {s-quote}null{s-quote} AS Extra, n.hwaddr AS ForeignKey FROM EXTERNAL_PIHOLE.Network AS n LEFT JOIN EXTERNAL_PIHOLE.Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE {s-quote}ip-%{s-quote} AND n.hwaddr <> {s-quote}00:00:00:00:00:00{s-quote} AND na.ip <> null;
19:50:59 [Plugins] setTyp: subnets
19:50:59 [Plugin utils] Flattening the below array
19:50:59 ['10.1.1.0/24 --interface=eth0']
19:50:59 [Plugin utils] isinstance(arr, list) : False | isinstance(arr, str) : True
19:50:59 [Plugins] Resolved value: 10.1.1.0/24 --interface=eth0
19:50:59 [Plugins] Convert to Base64: True
19:50:59 [Plugins] base64 value: b'MTAuMS4xLjAvMjQgLS1pbnRlcmZhY2U9ZXRoMA=='
19:50:59 [Plugins] Timeout: 10
19:50:59 [Plugins] Executing: SELECT n.hwaddr AS Object_PrimaryID, 'null' AS Object_SecondaryID, datetime() AS DateTime, na.ip  AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, 'null' AS Extra, n.hwaddr AS ForeignKey FROM EXTERNAL_PIHOLE.Network AS n LEFT JOIN EXTERNAL_PIHOLE.Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE 'ip-%' AND n.hwaddr <> '00:00:00:00:00:00' AND na.ip <> null;
19:50:59 [Plugins] No output received from the plugin PIHOLE - enable LOG_LEVEL=debug and check logs
19:50:59 [Scheduler] - Scheduler run for MAINT: NO
19:50:59 [Scheduler] - Scheduler run for CSVBCKP: NO
19:50:59 [Scheduler] - Scheduler run for DHCPLSS: YES
19:50:59 [Plugin utils] ---------------------------------------------
19:50:59 [Plugin utils] display_name: DHCP Leases (Device import)`


![Screenshot 2023-12-31 202738](https://github.com/jokob-sk/Pi.Alert/assets/4900328/e809831a-51cb-400e-8387-b6b9515eb047)

**Comment by jokob-sk** [comment]
Can you try to replace the PIHOLE_CMD setting with the following value?

```
SELECT n.hwaddr AS Object_PrimaryID, {s-quote}null{s-quote} AS Object_SecondaryID, datetime() AS DateTime, na.ip  AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, {s-quote}null{s-quote} AS Extra, n.hwaddr AS ForeignKey FROM EXTERNAL_PIHOLE.Network AS n LEFT JOIN EXTERNAL_PIHOLE.Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE {s-quote}ip-%{s-quote} AND n.hwaddr is not {s-quote}00:00:00:00:00:00{s-quote}  AND na.ip is not null
```

**Comment by jsmith432** [comment]
New log file: 
[pialert_pihole2.txt](https://github.com/jokob-sk/Pi.Alert/files/13802662/pialert_pihole2.txt)

**Comment by jokob-sk** [comment]
Thanks!

I can still see the old setting value in the log:

```
21:10:21 [Plugins] CMD: SELECT n.hwaddr AS Object_PrimaryID, {s-quote}null{s-quote} AS Object_SecondaryID, datetime() AS DateTime, na.ip  AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, {s-quote}null{s-quote} AS Extra, n.hwaddr AS ForeignKey FROM EXTERNAL_PIHOLE.Network AS n LEFT JOIN EXTERNAL_PIHOLE.Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE {s-quote}ip-%{s-quote} AND n.hwaddr <> {s-quote}00:00:00:00:00:00{s-quote} AND na.ip <> null;
```

Can you make sure the setting is set to (notice the `NOT null` vs `<> null` usage:

```
SELECT n.hwaddr AS Object_PrimaryID, {s-quote}null{s-quote} AS Object_SecondaryID, datetime() AS DateTime, na.ip  AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, {s-quote}null{s-quote} AS Extra, n.hwaddr AS ForeignKey FROM EXTERNAL_PIHOLE.Network AS n LEFT JOIN EXTERNAL_PIHOLE.Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE {s-quote}ip-%{s-quote} AND n.hwaddr is not {s-quote}00:00:00:00:00:00{s-quote}  AND na.ip is not null
```

**Comment by jsmith432** [comment]
Oh... I thought I double-checked that. Anyway, now it is working! Thank you, and happy new year!

**Comment by jokob-sk** [comment]
Thanks for the update, the default value will be fixed in the next release 👍 
Happy New Year :)

**Comment by jokob-sk** [comment]
Released -> Closing
