### ISSUE TITLE
[bug] Devices stopped showing in "all devices" or "connected" due to IPv6 validation failing

### ISSUE THREAD

**Issue by jsmith432** [jokob-sk/Pi.Alert#523]
Devices stopped showing in "all devices" or "connected"

I am past the 100 devices, not sure if that triggered something but I cannot see the devices anymore on the devices tab.

![Screenshot 2024-01-01 122628](https://github.com/jokob-sk/Pi.Alert/assets/4900328/46a7a49b-9550-4edd-bb08-a17da99b34cd)

**Comment by jokob-sk** [comment]
Hi @jsmith432!

Can you try to check if there are any javascript errors in the browser dev tools? General steps are described here: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_INVALID_JSON.md

Could you please also check that accessing the API endpoint `<pialert URL>/api/table_devices.json?nocache=123` shows a JSON of your devices?

Thanks,
j

**Comment by jsmith432** [comment]
hello there again :)

Looks like IPv6 address is causing an error. 
![Screenshot 2024-01-01 145151](https://github.com/jokob-sk/Pi.Alert/assets/4900328/17f48928-2c31-4775-85f3-a1fb003ee97e)

The API is returning IPV4 addresses. I tried to look for this address in the API, and it is not listed. I don't have IPv6 enabled on my router, DHCP is through pihole and IPv6 is disabled there. 

Thanks

**Comment by jokob-sk** [comment]
Thanks for that!

I think one of the plugins is passing incorrect data to the main app (where the app expects an IP). Can you please check the plugin data returned by the plugins you enabled in the UI under Plugins?

For example for PIHOLE:

https://github.com/jokob-sk/Pi.Alert/blob/main/docs/img/DEBUG_PLUGINS/plugin_objects_pihole.png

**Comment by jsmith432** [comment]
It's coming from PIHOLE. Some are IPv4, and some are IPv6 in the link to the device. 

![Screenshot 2024-01-01 154625](https://github.com/jokob-sk/Pi.Alert/assets/4900328/4b5bf6f0-156b-42e0-a313-a17fddf14da0)

I also saw on Pihole->Tools->Network some devices have ipv4 and ipv6.

**Comment by jokob-sk** [comment]
Thanks for that! There might be more work required to get full v6 support, but I fixed that one function. The fix can be tested in the `pi.alert_dev` container once this build finishes: https://github.com/jokob-sk/Pi.Alert/actions/runs/7390255497

**Comment by jsmith432** [comment]
Seems that it is still erroring out. 

![Screenshot 2024-01-02 203839](https://github.com/jokob-sk/Pi.Alert/assets/4900328/aace736e-35bd-4d87-aab1-b483ab1e8019)

**Comment by jokob-sk** [comment]
Thanks for checking @jsmith432 !

I made the ip/ipv6 check more forgiving and only logged an error in the console instead of throwing an exception. I also account for different length ipv6 addresses (the previous code didn't handle ipv4 mapped to ipv6 formats (I don't use IPv6 and this is all new to me 😅). 

If you could test the `pi.alert_dev` image after the build finishes that would be very helpful: https://github.com/jokob-sk/Pi.Alert/actions/runs/7402871088

Thanks in advance,
j

**Comment by jsmith432** [comment]
Thank you. I can see the list of devices now. Here is the thing, though. I don't "use" ipv6. I have it disabled on my router and pi-hole. But somehow, Pi-hole is reading from the devices when they connect. I didn't research how that all works.

**Comment by jokob-sk** [comment]
Ah glad to hear things work again. I could probably filter out ipv6 import from PiHole but not sure if that's a desired behavior for other users. Anyway, let's see what people say after the next release and I'll adjust accordingly. Thanks for the help, I think this issue should then be solved, yes?

**Comment by jokob-sk** [comment]
@eitch Could you please try a different browser? The file might be cached.

**Comment by eitch** [comment]
You are right! Thanks!

**Comment by Absoblogginlutely** [comment]
I can confirm I have several  ipv6 devices on my network and the console was showing invalid ip address format -
Uncaught Error: Invalid IP address format
    at formatIPlong (pialert_common.js:524:13)
    at devices.php:755:17
    at Array.map (<anonymous>)
    at Object.success (devices.php:740:28)
    at c (jquery.min.js:2:27742)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:28487)
    at l (jquery.min.js:2:78789)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:81117)

I was running 2023-12-21 
Upgraded to 2024-01-05 and after launching in an incognito window the devices are showing up (standard browser window was caching the file (so maybe thats an additional setting to expire the page?

It is working for me now though, so thanks!

**Comment by jokob-sk** [comment]
Released -> Closing
