### ISSUE TITLE
[setup] Second SUBNET (VPN) is not discovering devices.

### ISSUE THREAD

**Issue by TheZeekA** [jokob-sk/Pi.Alert#526]
My primary subnet is in the range 10.10.10.0/24 range and Pi.alert discovers these devices and works as normal.

I have a secondary subnet (Assigned by Wireguard VPN) that assigns 10.162.0.0 addresses. Four mobile phones connect to this VPN at all times with said IP Addresses. Pi.Alert doesn't pick these up. When the VPN is turned off, these devices are allocated IP addresses from primary subnet and are discovered just fine.

My issue is, how do I get Pi.Alert to scan this VPN subnet?

Pi.Alert is running inside a Debian VM on a Proxmox server. It uses the ens18 interface. 

My pialert.conf has the below.

```
SCAN_SUBNETS = '--localnet'
SCAN_SUBNETS = '10.10.10.0/24 10.162.0.0/24'
SCAN_SUBNETS = '--localnet --interface=ens18'
```
Any ideas or suggestions on how I could solve this?

**Comment by jokob-sk** [comment]
Hi @TheZeekA ,

The above configuration is incorrect and you need to specify an array if you have multiple subnets. I'm however not sure if the subnet on a VPN will work, still, check these docs at first or use the UI to configure the settings to make sure your config file is in the correct format: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/SUBNETS.md

Thanks,
j

**Comment by TheZeekA** [comment]
Hi @jokob-sk,

Appreciate the speedy response. I have edited my config in line with the documentation and as you mentioned it doesn't pick up the VPN subnet. Not to worry, I will spend some time and see if I can solve it.

Thanks

**Comment by jokob-sk** [comment]
You are welcome. You can try SSH-ing into the container and run an ARP-SCAN manually to see if the container can access the VPN (or at least trying to ping those devices). I, for example, have to often specify non-VPN IPs to access networks and devices, but I'm not too knowledgeable when it comes to networking intricacies.

**Comment by jokob-sk** [comment]
If you can solve this, please get back so I can document your findings or submit a PR directly.

Thanks,
j

**Comment by jokob-sk** [comment]
No reply for 2 weeks > closing
