### ISSUE TITLE
ARMv6 compatibility (Pi Zero)

### ISSUE THREAD

**Issue by hardwareadictos** [jokob-sk/Pi.Alert#527]
Hey! Good morning!

Is it posible to add ARMv6 compatibility to the images for using pialert on docker?

I installed it baremetal with https://github.com/leiweibau/Pi.Alert and it works just fine on Pi Zero W but containericing would be nice to isolate the service from the O.S.

Those devices have a great performance/cost ratio and are ideal to execute network analyzers like this 24/7.

Please, if you work on it let me know, i can test on my Zeros :)

Thanks in advance.

**Comment by jokob-sk** [comment]
Hey @hardwareadictos !

If this [build finishes without issues](https://github.com/jokob-sk/Pi.Alert/actions/runs/7414631563/job/20176100511) there should be an ARMv6 `pi.alert_dev` container available in a few minutes. Please have a look and test it if you can. I don't own any armv6 devices so any testing/troubleshooting or improvements will have to be done by the community. 

Thanks,
j

**Comment by hardwareadictos** [comment]
That was fast. THANKS A LOT!!

Will test tomorrow on the morning and i will edit this post with the results.

**Comment by jokob-sk** [comment]
@hardwareadictos - thanks a lot for the testing 🙏🙂

**Comment by hardwareadictos** [comment]
> @hardwareadictos - thanks a lot for the testing 🙏🙂

You are welcome :+1: 

On this week i didn't notice anything different on behaviour compared to mi Pi4 where i have another pialert from this Git hosted, for me it's fine for running into production environment :D

**Comment by jokob-sk** [comment]
Glad to hear it's stable 👍🙂

**Comment by jokob-sk** [comment]
Released -> Closing
