### ISSUE TITLE
IndexError: list index out of range - in query_MAC_vendor

### ISSUE THREAD

**Issue by pgfeller** [jokob-sk/Pi.Alert#533]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues amd I cheked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

**System Environment**:

- Docker image `jokobsk/pi.alert:23.12.16`(Built on: 2023-12-16 | Version: v23.12.16)
- Host:
  - Ubuntu 22.04.3 LTS x86_64 (6.5.0-14-generic)
  - CPU: Intel i3-8109U (4) @ 3.600GHz
  - GPU: Intel CoffeeLake-U GT3e [Iris Plus Graphics 655]
  - Memory: 15852MiB
---

The `pi.alert` container was no able to start anymore; the log showed the folloing error:
```
2024-01-11T17:28:18.272746102Z   File "/home/pi/pialert/pialert/networkscan.py", line 41, in process_scan
2024-01-11T17:28:18.297274033Z     update_devices_data_from_scan (db)
2024-01-11T17:28:18.297310909Z   File "/home/pi/pialert/pialert/device.py", line 246, in update_devices_data_from_scan
2024-01-11T17:28:18.297540604Z     vendor = query_MAC_vendor (device['dev_MAC'])
2024-01-11T17:28:18.297649130Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11T17:28:18.297660159Z   File "/home/pi/pialert/pialert/device.py", line 369, in query_MAC_vendor
2024-01-11T17:28:18.297803848Z     vendor = line.split(' ', 1)[1].strip()
2024-01-11T17:28:18.297887833Z              ~~~~~~~~~~~~~~~~~~^^^
2024-01-11T17:28:18.297897450Z IndexError: list index out of range
``` 
[pialert/device.py#L369](https://github.com/jokob-sk/Pi.Alert/blob/b5afdb2bce8bb580541851dd625dd4461e3e8995/pialert/device.py#L369)

As this might be related to the vendor information file stored at `vendorsPath = '/usr/share/arp-scan/ieee-oui.txt'` I restored I fetched a fresh copy of the file from the repository [ieee-oui.txt](https://github.com/jokob-sk/Pi.Alert/blob/b5afdb2bce8bb580541851dd625dd4461e3e8995/install/ieee-oui.txt) and mounted it from the host filesystem to keep an eye on it - as I assume it got corrupted somehow.

```yaml
version: '3.9'
services:
  pi.alert:
    depends_on:
      - pi.hole
    container_name: ${COMPOSE_PROJECT_NAME}-pi.alert
    restart: unless-stopped
    image: jokobsk/pi.alert:23.12.16
    network_mode: host      
    volumes:
      - ${MOUNT}/pi.alert/config:/home/pi/pialert/config
      - ${MOUNT}/pi.alert/db:/home/pi/pialert/db
      - ${MOUNT}/pi.alert/log:/home/pi/pialert/front/log
      - ${MOUNT}/pi.alert/usr/share/arp-scan/ieee-oui.txt:/usr/share/arp-scan/ieee-oui.txt:rw
    environment:
      - PORT=20211
      - USER_ID=${USER}
      - USER_GID=${GROUP}
      - TZ=${TZ}
```
After this the software did start again; however - there seems to be a scenario that can corrupt `ieee-oui.txt`.

### Expected Behavior

I was not able to determine to root cause for the corrupt file - but I propose to handle `IndexError` exceptions in [query_MAC_vendor](https://github.com/jokob-sk/Pi.Alert/blob/9f5884c4e769b026135be484dce38a36d6deadf8/pialert/device.py#L332) and to return `-1`. It might also make sense to add additional logging in this case to get more information in what scenario this occurs to understand if theres in a problem with the vendor file itself.

```python
def query_MAC_vendor (pMAC):    
    # Check MAC parameter
    # ...

    # Search vendor in HW Vendors DB
    #...  

    try:
        with open(vendorsPath, 'r') as f:
            for line in f:
                if line.startswith(mac_start_string6):
                    vendor = line.split(' ', 1)[1].strip()
                    mylog('debug', [f"[Vendor Check] Found '{vendor}' for '{pMAC}' in {vendorsPath}"])
                    return vendor
        return -1  # MAC address not found in the database

    except FileNotFoundError:
        mylog('none', [f"[Vendor Check] Error: Vendors file {vendorsPath} not found."])
        return -1
     except IndexError:
        # log relevant information; with loglevel debug maybe even dump the lookup table used.
        return -1
    except Exception:
       # Maybe even catch generic errors and log relevant information;
       # I'm aware that there are arguments against this kind of exception catching - that's always a debate; as it can
       # hide problems in the software and do more harm in the long run.
       return -1
```

### Steps To Reproduce

I was not yet able to reproduce the problem - unfortunately the potentially corrupt file was no longer present when I did the analysis in the source. However - if it happens again I should be able to provide more information.

In any case I propose to harden the code as proposed. It might even make sense in such a situation to restore the default vendor lookup ...

➡️ I've no experience in python nor this project - but with if I get some feedback how the SW should behavie in this case I would create a PR to implement the proposed improvements. Let me know ... 

### pialert.conf

I'll provide details on request - as I think that the problem is not directly related to the configuration, - and the effort to sanitize it from personal info and to bring it into a human readable format seems not justified in this case.

### docker-compose.yml

```python
version: '3.9'
services:
  pi.alert:
    depends_on:
      - pi.hole
    container_name: ${COMPOSE_PROJECT_NAME}-pi.alert
    restart: unless-stopped
    image: jokobsk/pi.alert:23.12.16
    network_mode: host      
    volumes:
      - ${MOUNT}/pi.alert/config:/home/pi/pialert/config
      - ${MOUNT}/pi.alert/db:/home/pi/pialert/db
      - ${MOUNT}/pi.alert/log:/home/pi/pialert/front/log
      - ${MOUNT}/pi.alert/usr/share/arp-scan/ieee-oui.txt:/usr/share/arp-scan/ieee-oui.txt:rw
    environment:
      - PORT=20211
      - USER_ID=${USER}
      - USER_GID=${GROUP}
      - TZ=${TZ}
```

### What branch are you running?

Production

### pialert.log

```
2024-01-11T17:28:18.272746102Z   File "/home/pi/pialert/pialert/networkscan.py", line 41, in process_scan
2024-01-11T17:28:18.297274033Z     update_devices_data_from_scan (db)
2024-01-11T17:28:18.297310909Z   File "/home/pi/pialert/pialert/device.py", line 246, in update_devices_data_from_scan
2024-01-11T17:28:18.297540604Z     vendor = query_MAC_vendor (device['dev_MAC'])
2024-01-11T17:28:18.297649130Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11T17:28:18.297660159Z   File "/home/pi/pialert/pialert/device.py", line 369, in query_MAC_vendor
2024-01-11T17:28:18.297803848Z     vendor = line.split(' ', 1)[1].strip()
2024-01-11T17:28:18.297887833Z              ~~~~~~~~~~~~~~~~~~^^^
2024-01-11T17:28:18.297897450Z IndexError: list index out of range
``` 

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Thank you @pgfeller for the detailed issue description, this helps a lot. 

I just pushed a check after the split command and added a debug entry to print out the line to process: 

https://github.com/jokob-sk/Pi.Alert/blob/90bfa70d1bb668406f0fcdc77b410fe94b561819/pialert/device.py#L375

Once the above build finishes, feel free to try to deploy the `pi.alert_dev` image to re-check the log file.

**Comment by pgfeller** [comment]
:+1: great - as I can not reproduce the problem atm I can not test the build - but as far as I understand the changes this should take care of the issue. Many thanks!

**Comment by jokob-sk** [comment]
Thanks for the detailed report again 🙏

**Comment by jokob-sk** [comment]
Released -> Closing
