### ISSUE TITLE
Custom reports

### ISSUE THREAD

**Issue by ghc88uk** [jokob-sk/Pi.Alert#535]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Is there a way of customising/modifying the reports? I'm using SMTP to push a report to Pushover but it arrives badly formatted and is hard to read.

### Describe the solution you'd like

Is there a way of modifying the report template email?

### Describe alternatives you've considered

I can't seem to find a way of editing this from the config file or existing files within the docker container.

### Anything else?

N/A

**Comment by jokob-sk** [comment]
Hi @ghc88uk ,

Can you please illustrate your point with screenshots? 

I didn't plan to allow template modifications, but it will depend on the nature and details of the request. "badly formated" is a pretty broad description and feedback that is hard to action so any additional details would help.

Thanks in advance,
j

**Comment by ghc88uk** [comment]
Hi @jokob-sk 

Sure, here is an example:

![unnamed](https://github.com/jokob-sk/Pi.Alert/assets/113256120/4ff5319f-1389-4989-894d-8b7911481a28)

Sending the report via email via an SMTP server was the only reliable way I could get it to Pushover. Is there any plans for native support of Pushover going forward? For now I was hoping to be able to modify the template to make the reports easier to read. Thanks.

**Comment by jokob-sk** [comment]
Thanks!

This looks like it can be solved with a different approach. 

Have you tried using an apprise bridge as it supports pushover?

https://github.com/caronc/apprise/wiki/Notify_pushover

I wasn't planning to support pushover as Apprise (already supported) has support for this gateway embedded. 

Let me know what you think about this approach.
j

**Comment by ghc88uk** [comment]
I've just got apprise running in another docker container, that was really straight forward to setup and has worked perfectly. Thanks so much, that's much better than having to run it through SMTP server as well. The only thing I haven't figured out is how to disable notifications totally for nuisance devices like apple devices and some of my IoT devices that do not like responding to ARP scans. I set them to "Scan Device: No" in pi.alert but for some reason the notifications keep coming through. The only temporary fix I've found so far is to select the longest possible setting for "Skip repeated notifications for" (1 week). I assume it's something I'm missing in the setting and not an issue, but I haven't figured it out yet...

**Comment by jokob-sk** [comment]
Glad to hear that!

There will be a feature in the next release to filter out notification for specific devices. You can have a look at the `pi.alert_dev` image or at the upcoming release announcement: https://github.com/jokob-sk/Pi.Alert/issues/138

I'll mark this as resolved as the main issue was solved.
