### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by u175** [jokob-sk/Pi.Alert#538]
Hi, 

Is it possible to create an API key by calling pialert-cli in the "/back" directory?

Thanks

**Comment by leiweibau** [comment]
This is possible with a newer version of "pialert-cli". However, I cannot answer whether this version is still compatible with jokob-sk's fork.

**Comment by jokob-sk** [comment]
@u175 let me know what detailed use case you have and I might be able to provide a workaround. 

Thanks,
j

**Comment by jokob-sk** [comment]
Ah, I see, have you tried this doc specific to my fork?

https://github.com/jokob-sk/Pi.Alert/blob/main/docs/HOME_ASSISTANT.md

**Comment by u175** [comment]
No I missed that sorry!

Thank you so much for the info.

Very easy to set up :)

**Comment by jokob-sk** [comment]
great 👍🙂
