### ISSUE TITLE
[help] nslookup plugin 

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/Pi.Alert#543]
Simply input: nslookup 192.168.8.12

output:
![image](https://github.com/jokob-sk/Pi.Alert/assets/3944295/e53f1e36-decb-431a-9097-a2c3f4e6ffbb)

This is one of the devices it didn't find.

_Originally posted by @uldtot in https://github.com/jokob-sk/Pi.Alert/issues/534#issuecomment-1904853124_

**Comment by jokob-sk** [comment]
Hi @uldtot ,

I implemented a NSLOOKUP plugin but I can't get any valid results on my network. It would be great if you could help testing it:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/e7f7ebf0-9bd7-46d0-a9a6-832227830c61)


It's available in the `pi.alert_dev` image in ~20 min form now. Here is the output in the log file that I'm getting on my end:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/e13ba291-ebd3-4371-be9f-4b8be434fe6e)

The nslookup command I execute for every device is:

`nslookup <device IP>`

**Comment by uldtot** [comment]
I tried the dev and now no devices are shown and the nslookup settings are empty. 
![image](https://github.com/jokob-sk/Pi.Alert/assets/3944295/34ba3334-c397-415f-bbb3-7f2db8b8a1a5)

Console error: 
![image](https://github.com/jokob-sk/Pi.Alert/assets/3944295/eda505c2-5344-4ed3-b6d9-1d74235106ae)

**Comment by jokob-sk** [comment]
Thanks @uldtot for checking! Can you please try a different browser or refresh your browser cache? The function seems to be deployed, but it sounds like the old files are cached by the browser: https://github.com/jokob-sk/Pi.Alert/blob/d18a59944bba1e64b810b89e19734fc702cab105/front/js/pialert_common.js#L352

**Comment by uldtot** [comment]
That worked. didnt think if cache. 

Here is what it said in logs ():

`19:47:20 [Plugin utils] display_name: NSLOOKUP (Name discovery)
19:47:20 [Plugins] CMD: python3 /home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
19:47:20 [Plugin utils] Flattening the below array
19:47:20 ['0.0.0.0']['192.168.8.16']['192.168.8.8']['192.168.8.104']['192.168.8.13']['192.168.8.12']['192.168.8.1']['192.168.8.14']['192.168.8.15']['192.168.8.9']
19:47:20 [Plugin utils] isinstance(arr, list) : True | isinstance(arr, str) : False
19:47:20 [Plugin utils] Flattened array: 0.0.0.0,192.168.8.16,192.168.8.8,192.168.8.104,192.168.8.13,192.168.8.12,192.168.8.1,192.168.8.14,192.168.8.15,192.168.8.9
19:47:20 [Plugins] Resolved value: 0.0.0.0,192.168.8.16,192.168.8.8,192.168.8.104,192.168.8.13,192.168.8.12,192.168.8.1,192.168.8.14,192.168.8.15,192.168.8.9
19:47:20 [Plugins] Convert to Base64: False
19:47:20 [Plugins] The parameter "name":"ips" will multiply the timeout 10 times. Total timeout: 100s
19:47:20 [Plugins] Timeout: 100
19:47:20 [Plugin utils] Pre-Resolved CMD: python3/home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
19:47:20 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
19:47:20 [Plugins] Resolved : ['python3', '/home/pi/pialert/front/plugins/nslookup_scan/nslookup.py']
19:47:20 [NSLOOKUP] In script
19:47:20 [Database] Opening DB
19:47:20 [plugin_helper] reading config file
19:47:20 [NSLOOKUP] In script
19:47:20 [Database] Opening DB
Traceback (most recent call last):
  File "/home/pi/pialert/front/plugins/nslookup_scan/nslookup.py", line 134, in <module>
    main()
  File "/home/pi/pialert/front/plugins/nslookup_scan/nslookup.py", line 55, in main
    domain_name, dns_server = execute_nslookup(device['dev_LastIP'], timeout)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pialert/front/plugins/nslookup_scan/nslookup.py", line 100, in execute_nslookup
    domain_match = domain_pattern.search(output.stdout)        
                                         ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'stdout'

19:47:20 [Plugins] ⚠ ERROR - enable LOG_LEVEL=debug and check logs
19:47:20 [Plugins] The file /home/pi/pialert/front/plugins/nslookup_scan/last_result.log does not exist
19:47:20 [Plugins] No output received from the plugin NSLOOKUP - enable LOG_LEVEL=debug and check logs
19:47:20 [Plugin utils] ---------------------------------------------`

**Comment by jokob-sk** [comment]
Thanks a lot! Can you try again to download the image once this run finishes (in ~17 min form now)? I hope I fixed the error above:

https://github.com/jokob-sk/Pi.Alert/actions/runs/7674821635

**Comment by uldtot** [comment]
`14:06:20 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
14:06:20 [Plugins] Resolved : ['python3', '/home/pi/pialert/front/plugins/nslookup_scan/nslookup.py']
14:06:21 [NSLOOKUP] In script
14:06:21 [Database] Opening DB
14:06:21 [NSLOOKUP]** server can't find 0.0.0.0.in-addr.arpa: NXDOMAIN


14:06:21 [NSLOOKUP] ⚠ ERROR - check logs
14:06:21 [NSLOOKUP] Scan: FAIL - check logs
14:06:21 [NSLOOKUP] Script finished
14:06:21 [Plugins] No output received from the plugin NSLOOKUP - enable LOG_LEVEL=debug and check logs
14:06:21 [2024-01-27 14:06:21+01:00] END Run: NSLOOKUP
14:06:21 [API] Update API starting
14:06:21 [MAIN] waiting to start next loop
14:06:26 [Config] No old setting names found in the file. No changes made.
14:06:26 [Import Config] checking config file 
14:06:26 [Import Config] lastImportedConfFile     :1706360641.9622402
14:06:26 [Import Config] fileModifiedTime         :1706360641.9622402
14:06:26 [Import Config] skipping config file import
14:06:26 [API] Update API starting
14:06:26 [MAIN] waiting to start next loop
14:06:31 [Config] No old setting names found in the file. No changes made.
14:06:31 [Import Config] checking config file 
14:06:31 [Import Config] lastImportedConfFile     :1706360641.9622402
14:06:31 [Import Config] fileModifiedTime         :1706360641.9622402
14:06:31 [Import Config] skipping config file import
14:06:31 [API] Update API starting
14:06:31 [MAIN] waiting to start next loop
14:06:36 [Config] No old setting names found in the file. No changes made.
14:06:36 [Import Config] checking config file 
14:06:36 [Import Config] lastImportedConfFile     :1706360641.9622402
14:06:36 [Import Config] fileModifiedTime         :1706360641.9622402
14:06:36 [Import Config] skipping config file import
14:06:36 [API] Update API starting
14:06:36 [MAIN] waiting to start next loop
14:06:41 [Config] No old setting names found in the file. No changes made.
14:06:41 [Import Config] checking config file 
14:06:41 [Import Config] lastImportedConfFile     :1706360641.9622402
14:06:41 [Import Config] fileModifiedTime         :1706360641.9622402
14:06:41 [Import Config] skipping config file import
14:06:41 [API] Update API starting
14:06:42 [Plugins] Check if any plugins need to be executed on run type: schedule
14:06:42 [Scheduler] - Scheduler run for VNDRPDT: NO
14:06:42 [Scheduler] - Scheduler run for INTRSPD: NO
14:06:42 [Scheduler] - Scheduler run for ARPSCAN: NO
14:06:42 [Scheduler] - Scheduler run for NSLOOKUP: NO
14:06:42 [Scheduler] - Scheduler run for CSVBCKP: NO
14:06:42 [Scheduler] - Scheduler run for MAINT: NO
14:06:42 [Scheduler] - Scheduler run for DBCLNP: NO
14:06:42 [Plugins] Check if any plugins need to be executed on run type: always_after_scan
14:06:42 [MAIN] processScan: False
14:06:42 [Notification] Check if something to report
14:06:42 [Notification] Included sections: ['new_devices']
14:06:42 [Notification] new_devices SQL query: SELECT eve_MAC as MAC, eve_DateTime as Datetime, dev_LastIP as IP, eve_EventType as "Event Type", dev_Name as "Device name", dev_Comments as Comments  FROM Events_Devices
                        WHERE eve_PendingAlertEmail = 1
                        AND eve_EventType = 'New Device' 
                         
                        ORDER BY eve_DateTime
14:06:42 [Notification] No changes to report
14:06:42 [MAIN] Process: Wait
14:06:47 [Config] No old setting names found in the file. No changes made.
14:06:47 [Import Config] checking config file 
14:06:47 [Import Config] lastImportedConfFile     :1706360641.9622402
14:06:47 [Import Config] fileModifiedTime         :1706360641.9622402
14:06:47 [Import Config] skipping config file import
14:06:47 [API] Update API starting
14:06:47 [MAIN] waiting to start next loop
14:06:52 [Config] No old setting names found in the file. No changes made.
14:06:52 [Import Config] checking config file 
14:06:52 [Import Config] lastImportedConfFile     :1706360641.9622402
14:06:52 [Import Config] fileModifiedTime         :1706360641.9622402
14:06:52 [Import Config] skipping config file import
14:06:52 [API] Update API starting
14:06:52 [MAIN] waiting to start next loop`

**Comment by jokob-sk** [comment]
Thanks! That looks better, can you send me a screenshot from Plugins -> NSLOOKUP if there are any valid names I can use?

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/59e3a869-4bb8-4a62-bcc8-64be3e1f4559)

**Comment by uldtot** [comment]
its empty:

![image](https://github.com/jokob-sk/Pi.Alert/assets/3944295/2f75d4db-cd3b-4d9e-9a9f-fbbe4887de60)

**Comment by uldtot** [comment]
`14:12:42 [Import Config] checking config file 
14:12:42 [Import Config] lastImportedConfFile     :1706446962.822595
14:12:42 [Import Config] fileModifiedTime         :1706446962.822595
14:12:42 [Import Config] skipping config file import
14:12:42 [API] Update API starting
14:12:42 [MAIN] waiting to start next loop
14:12:47 [Config] No old setting names found in the file. No changes made.
14:12:47 [Import Config] checking config file 
14:12:47 [Import Config] lastImportedConfFile     :1706446962.822595
14:12:47 [Import Config] fileModifiedTime         :1706446962.822595
14:12:47 [Import Config] skipping config file import
14:12:47 [2024-01-28 14:12:47+01:00] START Run: NSLOOKUP
14:12:47 [Plugin utils] Flattening the below array
14:12:47 ['0.0.0.0']['192.168.8.16']['192.168.8.8']['192.168.8.17']['192.168.8.104']['192.168.8.13']['192.168.8.12']['192.168.8.1']['192.168.8.14']['192.168.8.15']['192.168.8.9']
14:12:47 [Plugin utils] isinstance(arr, list) : True | isinstance(arr, str) : False
14:12:47 [Plugin utils] Flattened array: 0.0.0.0,192.168.8.16,192.168.8.8,192.168.8.17,192.168.8.104,192.168.8.13,192.168.8.12,192.168.8.1,192.168.8.14,192.168.8.15,192.168.8.9
14:12:47 [Plugins] Resolved value: 0.0.0.0,192.168.8.16,192.168.8.8,192.168.8.17,192.168.8.104,192.168.8.13,192.168.8.12,192.168.8.1,192.168.8.14,192.168.8.15,192.168.8.9
14:12:47 [Plugins] Convert to Base64: False
14:12:47 [Plugins] The parameter "name":"ips" will multiply the timeout 11 times. Total timeout: 110s
14:12:47 [Plugins] Timeout: 110
14:12:47 [Plugin utils] Pre-Resolved CMD: python3/home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
14:12:47 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
14:12:47 [Plugins] Resolved : ['python3', '/home/pi/pialert/front/plugins/nslookup_scan/nslookup.py']
14:12:48 [NSLOOKUP] In script
14:12:48 [Database] Opening DB
14:12:48 [NSLOOKUP] DEBUG OUTPUT : ;; Got recursion not available from 192.168.8.1, trying next server
13.8.168.192.in-addr.arpa	name = Kims-A54.

Authoritative answers can be found from:


14:12:48 [NSLOOKUP]** server can't find 0.0.0.0.in-addr.arpa: NXDOMAIN


14:12:48 [NSLOOKUP] ⚠ ERROR - check logs
14:12:48 [NSLOOKUP] Scan: FAIL - check logs
14:12:48 [NSLOOKUP] DEBUG OUTPUT : ;; Got recursion not available from 192.168.8.1, trying next server
17.8.168.192.in-addr.arpa	name = Kims-A54.

Authoritative answers can be found from:


14:12:48 [NSLOOKUP] Script finished`

**Comment by jokob-sk** [comment]
Hey @uldtot ,

Thanks a lot for the help! I finally got NSLOOKUP running on my local LAN and I was able to test this on my end. 

If you want to test it also on your setup, you can try after this build finishes: https://github.com/jokob-sk/Pi.Alert/actions/runs/7710412087

Thanks for all the help!
j

**Comment by jokob-sk** [comment]
Oh, my bad - fixed it now and the new image will be available after this action finishes: https://github.com/jokob-sk/Pi.Alert/actions/runs/7732279513

Thanks again for your help 🙏

**Comment by uldtot** [comment]
Look like it worked, will do more tests tomorrow. :)

**Comment by jokob-sk** [comment]
Yayyy - getting there :) thanks for the help. Let me know if you have feedback 👍

**Comment by jokob-sk** [comment]
Cool, thanks! Pushing hopefully a fix for that 👍

**Comment by jokob-sk** [comment]
released -> closing
