### ISSUE TITLE
Setting to override hostname

### ISSUE THREAD

**Issue by corasaniti** [jokob-sk/Pi.Alert#545]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I migrated a pialert installation from one raspberry to another, moving the entire configuration folder.

In the new device I find the hostname (visible at the top right) of the first Raspberry. What is the DB table and property to change the hostname?

### Describe the solution you'd like

I found nothing in docker-compose and in the configuration file.

### Describe alternatives you've considered

Thank you

### Anything else?

Help
![Screenshot 2024-01-26 141853](https://github.com/jokob-sk/Pi.Alert/assets/5001932/38301623-6049-437f-a053-15517815c49c)

**Comment by jokob-sk** [comment]
Hi @corasaniti,

The hostname is retrieved with the standard PHP call [gethostname](https://www.php.net/manual/en/function.gethostname.php). There is currently no way to change that via configuration. Let me know if you'd like to see a setting to override this and I will have a think about it and see if others would like similar functionality.

Thanks,
j

**Comment by corasaniti** [comment]
@jokob-sk 
Sure, It would be very nice to have the functionality of being able to change the hostname in the settings
Thank you

**Comment by corasaniti** [comment]
@jokob-sk 
Using this thread to ask for further help: is it possible to hide devices marked as archived from the device list? I would like to exclude them from the list of my devices and view them only when I enter the "Archived" section..
Thank you again
PC

**Comment by SeimusS** [comment]
You can change the hostname in the docker compose file. There are two variables that can achieve that _container_name_ or _hostname_

usually per container I set up both, but last time I had it for Pialert is was showing wrong, currently have it set using _container_name_  only and its reflecting properly >

```
  pialert:
    container_name: PiAlert
```
![image](https://github.com/jokob-sk/Pi.Alert/assets/126393602/89468888-8d55-452f-b902-48a0e32403d5)

Regards,
S.

**Comment by SeimusS** [comment]
https://docs.docker.com/compose/compose-file/compose-file-v3/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir

Regards,
S.

**Comment by jokob-sk** [comment]
Thanks @SeimusS for the tip!

@corasaniti - Can you please confirm if the above has worked for you?

Thanks in advance,
j

**Comment by corasaniti** [comment]
Yes I confirm, with : v24.2.17 the host name is automatically set with the host name.
Thanks

**Comment by jokob-sk** [comment]
Thanks for the confirmation @corasaniti > Closing as resolved
