### ISSUE TITLE
Localization + translation panel

### ISSUE THREAD

**Issue by realgooseman** [jokob-sk/Pi.Alert#547]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Not really a problem, just an overall UI improvement.

### Describe the solution you'd like

Currently, Pi.Alert is only available in English, German and Spanish. The process to submit new translations is unconvenient too. Setting up a translation panel like [**Crowdin**](https://crowdin.com/) would be a good idea, and speed up the process of translation contributions.

### Describe alternatives you've considered

An alternative translation platform could be [**Weblate**](https://weblate.org/).

### Anything else?

Links already provided in previous boxes.

**Comment by jokob-sk** [comment]
That's a good idea. I've contacted Weblate as they have a FOSS plan, however with a caveat:

* Using Weblate has been approved by the upstream project.

Which is difficult as the upstream project has been inactive since 2021. Checking if I need to re-create a repo to be able to use this plan. I'd rather not.

**Comment by realgooseman** [comment]
I see, what about Crowdin ?

I believe they offer their services free of charge for FOSS projects as well, you need to request a license.
https://crowdin.com/page/open-source-project-setup-request

**Comment by jokob-sk** [comment]
Ah thanks, didn't see that one. I'll see what Weblate reply and try Crowdin if not successful - Weblate looks a bit more user-friendly.

**Comment by jokob-sk** [comment]
@realgooseman Hey, tried to set up weblate. Let me know what you think (I might have misconfigured things): https://hosted.weblate.org/projects/pialert/pialert-core/

**Comment by realgooseman** [comment]
Great, the project needs to be approved as FOSS by Weblate first I think. And you need to add languages, I can personally contribute in French.

**Comment by jokob-sk** [comment]
Thanks for checking - I will setup a blank fr_fr.json file and let you know once the project is approved. Thanks for the help! :)

**Comment by comradekingu** [comment]
> That's a good idea. I've contacted Weblate as they have a FOSS plan, however with a caveat:
> 
>     * Using Weblate has been approved by the upstream project.
> 
> 
> Which is difficult as the upstream project has been inactive since 2021. Checking if I need to re-create a repo to be able to use this plan. I'd rather not.

What this means is the project upstream from the translation.
This isn't just a translation, so all is good.

The wrong license is selected btw.

[GNU **Lesser** General Public License v3.0 **only**](https://spdx.org/licenses/LGPL-3.0-only.html)

Should be

[GNU General Public License v3.0 **or later**](https://spdx.org/licenses/GPL-3.0-or-later.html)

Can be changed in 

https://hosted.weblate.org/projects/pialert/pialert-core/
and
https://hosted.weblate.org/projects/pialert/glossary/

I am https://hosted.weblate.org/user/kingu/ if you want to add me.
(Only admins and reviewers get to see the actual config.)

**Comment by jokob-sk** [comment]
Hi @comradekingu,

Thanks for the offer, and tips, really appreciate it 🙏 I'm still figuring out how to use Weblate and how to incorporate it into the workflow and deployments. I created a power-users team and hope you have sufficient permission to access what you need.

Still also waiting on the libre license approval.

If anything feel also to reach out on jokob-sk@gmail.com

Thanks,
j

**Comment by comradekingu** [comment]
Joined the power user group.

Still LGPL (Lesser GPL) as opposed to GPL for
https://hosted.weblate.org/projects/pialert/pialert-core/

Can be made GPLv3-or-later in
https://hosted.weblate.org/settings/pialert/pialert-core/

**Comment by jokob-sk** [comment]
Hey @comradekingu ,

Thanks for pointing this out. Hopefully, it's set up correctly now:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/ae90c9e5-1680-455c-9700-14ceba56d344)

**Comment by jokob-sk** [comment]
I had to re-do the whole setup (needed to switch the default language from EN to EN_US) and change how strings are handled in the application, but I hope we now have a working setup:

https://hosted.weblate.org/projects/pialert/core/

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/a42f9a68-bf6d-405f-b91d-aa8fb29c034a)

**Comment by jokob-sk** [comment]
released -> closing
