### ISSUE TITLE
Modify the button 'Delete (unknown) devices' under maintenance/tools to also delete '(name not found)' devices

### ISSUE THREAD

**Issue by mdijkens-oracle** [jokob-sk/Pi.Alert#551]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

All my new devices have a Name '(name not found)' instead op '(unknown)'
Because of this, the button 'Delete (unknown) devices' under maintenance/tools is not useable anymore

I think the Pholus-Scan on new devices sets the name to '(name not found)'.

### Describe the solution you'd like

Pholus-Scan on new devices should set/leave the name to '(unknown)' if the name cannot be resolved

### Describe alternatives you've considered

export/import csv can be used when list of new devices is very long, but it's a lot of steps for such simple problem.

Is there a way to have Pholus-Scan set/leave the name to '(unknown)' or is there a way to define the button clean action/filter?

### Anything else?

Not sure if this is a feature request or a bug?

**Comment by jokob-sk** [comment]
Hi @mdijkens-oracle 👋

Thanks you for the detailed description. I modified the SQL query to delete `(unknown)` and `(name not found)` devices. This will be released in the next couple of weeks. Hope this solves your use cases. 

Thanks,
j

**Comment by jokob-sk** [comment]
released -> closing
