### ISSUE TITLE
Add support for choosing a priority level for notifications (ntfy)

### ISSUE THREAD

**Issue by Eirikr70** [jokob-sk/Pi.Alert#553]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have found no way to configure the priorities of the notifications emitted by pi.alert to ntfy. They seem to always be set at the highest level. It would be nice to be able to define the priority level.

### Describe the solution you'd like

Permit the configuration of the alert priority by inserting a Priority field in the ntfy (and the other) chapter of the settings.

### Describe alternatives you've considered

I haven't found any way to set up the priority in the configuration on the ntfy side.

### Anything else?

-

**Comment by jokob-sk** [comment]
Hi @Eirikr70 ,

This should be available in the next release. Please test the setting in the `pi.alert_dev` image after this run finishes (https://github.com/jokob-sk/Pi.Alert/actions/runs/7761362970) if you have a minute.

Thanks,
j

**Comment by jokob-sk** [comment]
released -> closing
