### ISSUE TITLE
Bugs with Port and Connected Devices columns

### ISSUE THREAD

**Issue by vladaurosh** [jokob-sk/Pi.Alert#556]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

Latest docker image, just set it up (not an upgrade), default settings, Port column is named "undefined". 
"Connected Devices" column shows 0 for all, though in Network tab number of connected devices seems to be good.

![port](https://github.com/jokob-sk/Pi.Alert/assets/47857324/136bf33b-ea9a-49fc-8765-58b6182bcfe5)
![network](https://github.com/jokob-sk/Pi.Alert/assets/47857324/ca422f3e-ac37-4378-98bc-995554b3e2d6)
![connected_devices](https://github.com/jokob-sk/Pi.Alert/assets/47857324/701c14c4-319d-4506-bb2d-b518859637bb)

### Expected Behavior

Port column should be named Port, Connected Devices should show number of connected devices, this is regression, as in previous version, this was correct.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hey,

Thanks for the report. It was actually something started working on and forgot to finish :) Should be available in the next release or you can test  the `pi.alert_dev` image:
![302438994-15e4a15a-c97f-49d8-94ba-c56e959b623c](https://github.com/jokob-sk/Pi.Alert/assets/96159884/a818541a-d2e5-4309-b7ed-a474168acd05)


Thanks,
j

**Comment by vladaurosh** [comment]
Thanks @jokob-sk 

I'll try dev image. 

In the meantime I found another issue:
`[error] 146#146: *3 open() "/var/www/html/pialert/log/execution_queue.log" failed (2: No such file or directory), `

Indeed file doesn't exist.

**Comment by jokob-sk** [comment]
thanks @vladaurosh , should be also fixed after the next `_dev` image build finishes and available in the next release.

**Comment by vladaurosh** [comment]
Latest _dev looks good for those columns. nginx logs are showing this
`FastCGI sent in stderr: "PHP message: PHP Warning:  file_get_contents(./log/pialert_front.log): Failed to open stream: No such file or directory in /home/pi/pialert/front/maintenance.php on line 426`

**Comment by jokob-sk** [comment]
Thanks, hope the above fixes it :) you can test in the dev image once the above run finishes

**Comment by vladaurosh** [comment]
Looks to be fixed now, thanks.

**Comment by jokob-sk** [comment]
Thanks for checking!

**Comment by jokob-sk** [comment]
released -> closing
