### ISSUE TITLE
Remember password does not work

### ISSUE THREAD

**Issue by daniel-alomar** [jokob-sk/Pi.Alert#557]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

I have set a password and enable login. I check the "Remember (valid for 7 days)"  check but it ask me again the password next time

### Expected Behavior

To not ask for the password for 7 days

### Steps To Reproduce

1.- Set a password
2.- Enable login
3.- Sign out and sign again
4.- write the password and check "Remember"
5.- Logout
6.- Login without ask the password

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by leiweibau** [comment]
Hello @jokob-sk and @daniel-alomar,

As I am involved in this password protection, I also see myself in a position to help a little here. You describe the steps to reproduce the error here

```
Steps To Reproduce

1 - Set a password
2 - Enable login
3.- Sign out and sign again
4.- write the password and check "Remember"
5.- Logout
6.- Login without asking the password
```

If you do the 5th point, you will be logged out and the cookie that stores the password will be deleted and that's how it should be. You must not log out, then you will be able to access the frontend again for the next 7 days without logging in.

**Comment by daniel-alomar** [comment]
sorry, you are right...

**Comment by daniel-alomar** [comment]
It was a misunderstanding of the "remember" functionality
