### ISSUE TITLE
sqlite3.OperationalError: no such table: ScanCycles

### ISSUE THREAD

**Issue by zell-mbc** [jokob-sk/Pi.Alert#56]
Hi there, I am looking at PI.Alert (Docker) right now, seems to be exactly what I was looking for. But for some reason the scan doesn't seem to start hence I am looking for some troubleshooting help.
I can get to the (empty) just UI fine, but no data will show up even after running the service for 30 minutes. 
When checking the log I can see the that there seems to be a table missing from the DB?

```
cat log/pialert.1.log 

Pi.Alert 3.5_leiweibau (2022-07-07)
---------------------------------------------------------
Scan Devices
    ScanCycle: 1
    Timestamp: 2022-07-31 13:35:00
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 1599, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 89, in main
    res = scan_network()
  File "/home/pi/pialert/back/pialert.py", line 350, in scan_network
    scanCycle_data = query_ScanCycle_Data (True)
  File "/home/pi/pialert/back/pialert.py", line 439, in query_ScanCycle_Data
    WHERE cic_ID = ? """, (cycle,))
sqlite3.OperationalError: no such table: ScanCycles

```

When checking the database file I can see that only one table got created?
```
#sqlite3 pialert.db
SQLite version 3.39.1 2022-07-13 19:41:41
Enter ".help" for usage hints.
sqlite> .tables
Online_History
sqlite>

```
Anyone got an idea what might be going on or what to check next?

**Comment by jokob-sk** [comment]
Hey!

I just pulled the [latest image](https://registry.hub.docker.com/r/jokobsk/pi.alert) (uploaded yesterday so if you have an older image please delete tit and re-download it).

It seems to be working without issues on my end.
Can you try to download the `pialert.db` file and mount it according to [instructions](https://github.com/jokob-sk/Pi.Alert/tree/main/dockerfiles#-setup-and-backups)? You can download it form here:

https://github.com/jokob-sk/Pi.Alert/tree/main/db

**Comment by zell-mbc** [comment]
That did the trick, now the UI gets populated. Thanks for the swift response!
