### ISSUE TITLE
Network map not working

### ISSUE THREAD

**Issue by rcjcarr** [jokob-sk/Pi.Alert#560]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

I can assign devices as indicated in instructions, but the graphical network map never appears.

### Expected Behavior

Network map to draw on network tab.

### pialert.conf

```python
#-----------------AUTOGENERATED FILE-----------------#
#                                                    #
#         Generated:  2024-02-09_12-21-29            #
#                                                    #
#   Config file for the LAN intruder detection app:  #
#      https://github.com/jokob-sk/Pi.Alert          #
#                                                    #
#-----------------AUTOGENERATED FILE-----------------#


# General
#---------------------------
LOG_LEVEL='verbose'
LOG_LEVEL__metadata="{}"
TIMEZONE='America/Toronto'
TIMEZONE__metadata="{}"
PLUGINS_KEEP_HIST=250
PLUGINS_KEEP_HIST__metadata="{}"
PIALERT_WEB_PROTECTION=False
PIALERT_WEB_PROTECTION__metadata="{}"
PIALERT_WEB_PASSWORD='8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92'
PIALERT_WEB_PASSWORD__metadata="{}"
REPORT_DASHBOARD_URL='http://192.168.1.25:20211'
REPORT_DASHBOARD_URL__metadata="{}"
UI_LANG='English'
UI_LANG__metadata="{}"
UI_PRESENCE=['online','offline','archived']
UI_PRESENCE__metadata="{}"
DAYS_TO_KEEP_EVENTS=90
DAYS_TO_KEEP_EVENTS__metadata="{}"
HRS_TO_KEEP_NEWDEV=0
HRS_TO_KEEP_NEWDEV__metadata="{}"
API_CUSTOM_SQL='SELECT * FROM Devices WHERE dev_PresentLastScan = 0'
API_CUSTOM_SQL__metadata="{}"
NETWORK_DEVICE_TYPES=['AP','Gateway','Firewall','Hypervisor','Powerline','Switch','WLAN','PLC','Router','USB LAN Adapter','USB WIFI Adapter','Internet']
NETWORK_DEVICE_TYPES__metadata="{}"


# ARPSCAN
#---------------------------
SCAN_SUBNETS=['192.168.1.0/24 --interface=eth0']
SCAN_SUBNETS__metadata="{}"
ARPSCAN_RUN='schedule'
ARPSCAN_RUN__metadata="{\"function\": \"RUN\", \"type\": \"text.select\", \"default_value\": \"schedule\", \"options\": [\"disabled\", \"once\", \"schedule\", \"always_after_scan\", \"on_new_device\"], \"localized\": [\"name\", \"description\"], \"events\": [\"run\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"When to run\"}, {\"language_code\": \"es_es\", \"string\": \"Cuando ejecutar\"}, {\"language_code\": \"de_de\", \"string\": \"Wann ausf\\u00fchren\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Specify when your Network-discovery scan will run. Typical setting would be <code>schedule</code> and then you specify a cron-like schedule in the <a href=\\\"#ARPSCAN_RUN_SCHD\\\"><code>ARPSCAN_RUN_SCHD</code>setting</a>. \\u26a0 Use the same schedule if you have multiple <i class=\\\"fa-solid fa-magnifying-glass-plus\\\"></i> Device scanners enabled.\"}, {\"language_code\": \"es_es\", \"string\": \"Especifique cu\\u00e1ndo se ejecutar\\u00e1 su an\\u00e1lisis de descubrimiento de red. La configuraci\\u00f3n t\\u00edpica ser\\u00eda <code>schedule</code> y luego se especifica una programaci\\u00f3n similar a cron en la configuraci\\u00f3n <a href=\\\"#ARPSCAN_RUN_SCHD\\\"><code>ARPSCAN_RUN_SCHD</code></a> \"}, {\"language_code\": \"de_de\", \"string\": \"Ausw\\u00e4hlen wann der Netzwerkscan laufen soll. Typischerweise wird <code>schedule</code> ausgew\\u00e4hlt und ein cron-Intervall in der <a href=\\\"#ARPSCAN_RUN_SCHD\\\"><code>ARPSCAN_RUN_SCHD</code>Einstellung</a> gesetzt.\"}]}"
ARPSCAN_CMD='python3 /home/pi/pialert/front/plugins/arp_scan/script.py userSubnets={subnets}'
ARPSCAN_CMD__metadata="{\"function\": \"CMD\", \"type\": \"readonly\", \"default_value\": \"python3 /home/pi/pialert/front/plugins/arp_scan/script.py userSubnets={subnets}\", \"options\": [], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"Command\"}, {\"language_code\": \"es_es\", \"string\": \"Comando\"}, {\"language_code\": \"de_de\", \"string\": \"Befehl\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Command to run. This should not be changed\"}, {\"language_code\": \"es_es\", \"string\": \"Comando para ejecutar. Esto no debe ser cambiado\"}, {\"language_code\": \"de_de\", \"string\": \"Auszuf\\u00fchrender Befehl. Dieser sollte nicht ge\\u00e4ndert werden\"}]}"
ARPSCAN_RUN_TIMEOUT=300
```

### docker-compose.yml

```python
version: "3"
services:
  pialert:
    container_name: pialert
    # use the below line if you want to test the latest dev image
    #image: "jokobsk/pi.alert_dev:latest"
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./config:/home/pi/pialert/config
      - ./db:/home/pi/pialert/db/
      # (optional) useful for debugging if you have issues setting up the container
      - ./logs:/home/pi/pialert/front/log
    environment:
      - TZ=America/Toronto
      - PORT=20211
#      - HOST_USER_ID=0
#      - HOST_USER_GID=0
      - LOG_LEVEL='debug'
```

### What branch are you running?

Production

### pialert.log

no errors in logs

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @rcjcarr ,

Can you please send me:

1. A screenshot of the Network page?
2. Any debug output of the browser dev console?
3. If there is a JSON error, please follow this guide: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_INVALID_JSON.md
4. Please confirm your root device has the MAC `Internet`.

Thanks,
j

**Comment by rcjcarr** [comment]
Yes confirmed root device has the MAC Internet designation.
![image](https://github.com/jokob-sk/Pi.Alert/assets/50344858/5621ce7f-7283-4cc6-a572-695f99cd2ee8)
![image](https://github.com/jokob-sk/Pi.Alert/assets/50344858/6ce0cec0-197e-4c01-8f28-3e0d12e1d767)
Not sure where to get the 'browser dev' console....

**Comment by rcjcarr** [comment]
![image](https://github.com/jokob-sk/Pi.Alert/assets/50344858/b8deffd8-4e9b-4f5f-911b-b6cbf5fb6d12)

**Comment by rcjcarr** [comment]
![image](https://github.com/jokob-sk/Pi.Alert/assets/50344858/b3db546c-eed4-413c-900a-86d37d09412e)

**Comment by rcjcarr** [comment]
Browser is Firefox 122.0.1 (64-bit). Checked with Chrome, also no network map.

**Comment by jokob-sk** [comment]
Hi @rcjcarr ,

Thanks for the details!

Can you unassign this:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/ac2a4a9b-7db5-4bab-a183-26862229ba8d)

I wonder, do you remember how you assigned the Internet device to itself? I'd like to try to reproduce it on my end. It shouldn't be possible, I have an explicit check, but I probably have a bug somewhere.

**Comment by rcjcarr** [comment]
I can't un-assign it:
![image](https://github.com/jokob-sk/Pi.Alert/assets/50344858/ed5885d2-cefb-4731-8126-1fd6902c01e4)

**Comment by jokob-sk** [comment]
I see, in that case, please delete the device with the MAC `Internet`:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/1202d279-75fa-4491-a329-70940b24f225)

Now wait until PiALert re-discovers it, and set it up as the parent for the next device (probably SR516 from your screenshot).

Do you remember how you assigned the Internet device to itself?

**Comment by rcjcarr** [comment]
I deleted the MAC Internet device, and will wait a bit. I just assigned it as the Internet device after a fresh install, as per the instructions.

**Comment by rcjcarr** [comment]
Ahh working now. I suspect I may have assigned the ethernet device to itself, so probably my fault. Thanks for your help! Great work maintaining this app; much appreciated.
![image](https://github.com/jokob-sk/Pi.Alert/assets/50344858/9da6c296-7aa0-4afb-a38c-c6f3b2b0c349)

**Comment by jokob-sk** [comment]
thanks for the update -> closing
