### ISSUE TITLE
Devices discovered but then majority show as offline when they are online

### ISSUE THREAD

**Issue by n1nj4888** [jokob-sk/Pi.Alert#563]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

I'm running the jokobsk/pi.alert:latest docker image on a Synology NAS with the default config (other than SCAN_SUBNETS=['192.168.0.254/23 --interface=ovs_bond0']) and pialert seems to successfully find the devices on the network on initial scans however on subsequent scans only around 10% of the devices are showing as "Online" in the Devices screen with the other 90% showing as New/Offline in Devices screen when they are actually Online.

![image](https://github.com/jokob-sk/Pi.Alert/assets/29934446/7ab0b3b0-7985-4f9f-b554-d46481a389c3)

If I select one of the devices (with IP 192.168.0.253) it shows as Offline as follows - But I know this device is online and pingable across the network:

![image](https://github.com/jokob-sk/Pi.Alert/assets/29934446/7a535001-1d61-4b6b-a0dd-825a69f2667a)

However if I click "Tools" on that same device and do either a Traceroute or manual Nmap Scan, the same device returns results indicating the device with IP 192.168.0.253 is indeed Online...

![image](https://github.com/jokob-sk/Pi.Alert/assets/29934446/2e1c8f32-9483-483a-b103-e2a67261567c)

![image](https://github.com/jokob-sk/Pi.Alert/assets/29934446/10adeb64-16ea-4fba-8488-3ea522767c20)

NOTE: I have checked other gitlab issues such as https://github.com/jokob-sk/Pi.Alert/issues/447 and have confirmed that my scanner schedules are in sync with `<plugin>_RUN_SCHD` set to the same schedule and that I do not have `Un-Discoverable Device` plugin enabled: 

![image](https://github.com/jokob-sk/Pi.Alert/assets/29934446/1b7a3f8c-daf5-49dc-ac07-09a2e81c0597)

### Expected Behavior

Expected behaviour is that devices that are online and can return ping results across the network (and returning results in pi.alert Traceroute and NMAP tools) are shown as Online in the Devices screen and not Offline.

### Steps To Reproduce

(1) Deploy pi.alert on Synology using Container Manager (using the `docker-compose.yml` file below)
(2) As the Synology is using an LACP bond (with name ovs_bond0 and CIDR 192.168.0.0/23), set the `SCAN_SUBNETS` to `SCAN_SUBNETS=['192.168.0.254/23 --interface=ovs_bond0']`
(3) Let pi.alert run a few scheduled scans and see that devices known to be online are shows as offline.

### pialert.conf

```python
Can be shared on request however this file is 192KB and breaks the gitlab text size limits.
```

### docker-compose.yml

```python
version: "3.9"
services:
  pialert:
     container_name: pialert
     healthcheck:
      test: curl -f http://localhost:20211/ || exit 1
     mem_limit: 2g
     cpu_shares: 768
     volumes:
      - /volume1/docker/pialert/config:/home/pi/pialert/config:rw
      - /volume1/docker/pialert/db:/home/pi/pialert/db:rw
      - /volume1/docker/pialert/front/log:/home/pi/pialert/front/log:rw
      - /etc/localtime:/etc/localtime:ro
     environment:
      - TZ=Asia/Singapore
      - PORT=20211
      - HOST_USER_ID=1026
      - HOST_USER_GID=100
     network_mode: host
     restart: on-failure:5
     image: jokobsk/pi.alert:latest
```

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @n1nj4888 ,

Thanks for the detailed report.

Can you please make sure the enabled scans finish without issues?

It could be that the scan gets interrupted early and then only some devices get picked up by the enabled scans. 

Try adjusting the `ARPSCAN_RUN_SCHD` and `ARPSCAN_RUN_TIMEOUT` and increase values of those settings. 

Check the `pialert.log` after you enable debug (https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_TIPS.md) and search for logs for the following entry:

`[Scheduler] - Scheduler run for ARPSCAN: YES`

Paste the debug output after this log entry to debug your issue further.  

Also, are there any similarities between the devices reported as offline?

Thanks in advance,
j

**Comment by n1nj4888** [comment]
Hi @jokob-sk. I was able to identify the issue after noticing that the `arp-scan 192.168.0.0/23 --interface=ovs_bond0` command when ran directly in the pi.alert container was also only returning 5-10 hosts out of ~80. The same command run directly on another host in a different area of the building was able to return around 70/80 of the hosts (with the ~10 missing being the ones physically near the original pi.alert host) ...

The root cause of the issue was the switch that the pi.alert host was connected to appears to be blocking some of the arp packets - Specifically in my case a DLINK switch with the `Safeguard Engine = enabled` setting on the switch was blocking the packets (https://eu.dlink.com/uk/en/support/faq/switches/layer-2-gigabit/dgs-series/es_dgs-1210_saveguard_proteccion-del-switch-contra-virus-maliciosos-o-ataques-de-gusanos).

Setting  `Safeguard Engine = disabled` on the switch appears to resolve the issue and the hosts are then shown as Online in pi.alert as expected:

![image](https://github.com/jokob-sk/Pi.Alert/assets/29934446/c63e40fd-3873-4f87-95c8-0e7398cf2be8)

**Comment by jokob-sk** [comment]
Hi @n1nj4888 ,

Thanks a lot for the follow-up. This might help someone in the future :)

Closing as resolved.
