### ISSUE TITLE
Password reset feature not working as advertised

### ISSUE THREAD

**Issue by rcjcarr** [jokob-sk/Pi.Alert#565]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

New passwords don't seem to be active if the Settings -> Set passwords -> When to Run -> disabled, such as after setting a new password. GUI states that 'You can set to disabled once the password is changed. '

### Expected Behavior

Setting the Settings -> Set passwords -> When to run to 'disabled' causes the password to revert back to the default '123456'

### Steps To Reproduce

1. Tick the Settings -> Core -> Enable Login Box
2. Setting the Settings -> Set Passwords -> before_config_save
3. Enter new password in Settings -> Set Passwords -> Password box
4. Hit the execute button besides Setting the Settings -> Set passwords -> before_config_save
5. Save the configuration.
6. Logout/Log back in with the new password.
7. Set Settings -> Set Passwords -> disabled
8. Logout, log back in.
9. GUI shows this:
![image](https://github.com/jokob-sk/Pi.Alert/assets/50344858/ee666d9c-04c1-4a02-8739-0cee691ad9b4)
New password is no longer accepted. One must use 123456 once again to login.
10. Set Settings -> Set passwords -> before_config_save
11. New password accepted again as proper login credentials.

### pialert.conf

```python
#-----------------AUTOGENERATED FILE-----------------#
#                                                    #
#         Generated:  2024-02-13_14-23-33            #
#                                                    #
#   Config file for the LAN intruder detection app:  #
#      https://github.com/jokob-sk/Pi.Alert          #
#                                                    #
#-----------------AUTOGENERATED FILE-----------------#


# General
#---------------------------
LOG_LEVEL='verbose'
LOG_LEVEL__metadata="{}"
TIMEZONE='America/Toronto'
TIMEZONE__metadata="{}"
PLUGINS_KEEP_HIST=250
PLUGINS_KEEP_HIST__metadata="{}"
PIALERT_WEB_PROTECTION=True
PIALERT_WEB_PROTECTION__metadata="{}"
PIALERT_WEB_PASSWORD = 'xxxxxxxxxxxxxxxxxxx'
PIALERT_WEB_PASSWORD = 'xxxxxxxxxx525918'
REPORT_DASHBOARD_URL='http://192.168.1.25:20211'
REPORT_DASHBOARD_URL__metadata="{}"
UI_LANG='English'
UI_LANG__metadata="{}"
UI_PRESENCE=['online','offline','archived']
UI_PRESENCE__metadata="{}"
DAYS_TO_KEEP_EVENTS=90
DAYS_TO_KEEP_EVENTS__metadata="{}"
HRS_TO_KEEP_NEWDEV=0
HRS_TO_KEEP_NEWDEV__metadata="{}"
API_CUSTOM_SQL='SELECT * FROM Devices WHERE dev_PresentLastScan = 0'
API_CUSTOM_SQL__metadata="{}"
NETWORK_DEVICE_TYPES=['AP','Gateway','Firewall','Hypervisor','Powerline','Switch','WLAN','PLC','Router','USB LAN Adapter','USB WIFI Adapter','Internet']
NETWORK_DEVICE_TYPES__metadata="{}"


# ARPSCAN
#---------------------------
SCAN_SUBNETS=['192.168.1.0/24 --interface=eth0']
SCAN_SUBNETS__metadata="{}"
ARPSCAN_RUN='schedule'
```

### docker-compose.yml

```python
version: "3"
services:
  pialert:
    container_name: pialert
    # use the below line if you want to test the latest dev image
    #image: "jokobsk/pi.alert_dev:latest"
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./config:/home/pi/pialert/config
      - ./db:/home/pi/pialert/db/
      # (optional) useful for debugging if you have issues setting up the container
      - ./logs:/home/pi/pialert/front/log
    environment:
      - TZ=America/Toronto
      - PORT=20211
#      - HOST_USER_ID=0
#      - HOST_USER_GID=0
      - LOG_LEVEL='debug'
~
```

### What branch are you running?

Production

### pialert.log

no errors in logs

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @rcjcarr ,

Thanks for the detailed report. I changed the description and removed the "run" option as it seems to interfere with the application flow. 

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/616c9bc7-cacf-4356-a569-2c3283160f4f)

These changes will be deployed with the next release and can be tested in the `pi.alert_dev` image once the above build finishes.

Thanks,
j

**Comment by rcjcarr** [comment]
Ok thanks for the update. Sounds good.

**Comment by jokob-sk** [comment]
released -> closing
