### ISSUE TITLE
QEMU MAC Address ranges are shown as "Random MAC"

### ISSUE THREAD

**Issue by n1nj4888** [jokob-sk/Pi.Alert#566]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

On the devices page, all QEMU VMs (with MAC address 52:54:00...) are shown as having a "Random MAC". Whilst the MAC of the QEMU VM might be randomized at creation, it should not be expected to be change for the life of the VM in the same way that a "Random MAC" might regularly do for IOS/android mobile devices?

### Expected Behavior

QEMU VMs are not shown as Random MAC or there is the ability to mark specific ranges as not "Random MAC"

### Steps To Reproduce

Create a qemu VM (for example in Proxmox) with a MAC address of 52:54:00:xx:xx:xx - this will be shown as "Random MAC" in pi.alert.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hey,

**Random MACs** are recognized by the characters "2", "6", "A", or "E" as the 2nd character in the Mac address. I checked and QEMU doesn't; have any reserved prefixes, so the behavior is correct. 

However, in the next release, you will be able to disable specific prefixes to be detected as random MAC addresses by specifying the `UI_NOT_RANDOM_MAC` setting.

You can test this in the `pi.alert_dev` image in about 15 minutes from now.

Thanks,
j

**Comment by jokob-sk** [comment]
released -> closing
