### ISSUE TITLE
UniFi Import not bringing across Vendor Information

### ISSUE THREAD

**Issue by Tharic99** [jokob-sk/Pi.Alert#567]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

Currently the only device scanner I have enabled is the UniFi Import set on a schedule for every 15 minutes.

I can see in the Plugins -> UniFi Import page that the devices are found with their corresponding MAC address, IP and vendor information, as expected.

However, when I click on any of the devices and it navigates to the deviceDetails.php page, the MAC address and IP appears correct, but the Vendor data is not moving over from the the UniFi Import plugin to the actual Device Details. 

### Expected Behavior

Expected behavior would be to take the Vendor information from the UniFi Plugin and update the Device Details data.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @Tharic99 ,

Thanks for the report.

This should be available in the next release. If you can, please have a look at the `pi.alert_dev` docker image, in about 15 minutes from now, to test these changes right away.

Thanks in advance,
j

**Comment by jokob-sk** [comment]
released -> closing
