### ISSUE TITLE
Hidden Archivied Device

### ISSUE THREAD

**Issue by corasaniti** [jokob-sk/Pi.Alert#569]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

I have setup hidding of archivied device in "Show My Device" setting, and after save setting and reload configuration, I expected NOT to see the archived devices anymore. 

### Expected Behavior

Don't see archived devices anymore

### Steps To Reproduce

![Cattura](https://github.com/jokob-sk/Pi.Alert/assets/5001932/d373b6f1-eecb-4fa4-8ebc-d981e767edba)
![Cattura2](https://github.com/jokob-sk/Pi.Alert/assets/5001932/f25dcacd-27a3-4ed9-9fec-d310fd0e988b)

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by SeimusS** [comment]
Seeing the same issue, for Presents its working but for the Device TAB, it will be still shown even if in settings its se to be hidden

![image](https://github.com/jokob-sk/Pi.Alert/assets/126393602/f621a239-35f7-4dae-9b43-a9fd60ba26bb)

Regards,
S.

**Comment by jokob-sk** [comment]
Hi,

Thanks for the report. I re-ordered the priorities of the check and what I think is the issue that even if the device is Archived, if it's in another status, such as "Online", it would be displayed. I made the device filter hide Archived devices, even if they are online in the latest build. 

This should be available in the next release. If you can, please have a look at the `pi.alert_dev` docker image, in about 15 minutes from now, to test these changes right away. 

Thanks in advance,
j

**Comment by corasaniti** [comment]
@jokob-sk 
Perfect!!! I tried pi.alert_dev branch, and after setup and save "hidden" archivied devices from devices view, the archivied devices disappares and they are only visible if I go to the "Archived" section.
I'm waiting for the fix in the main/latest branch
Thanks

**Comment by corasaniti** [comment]
@jokob-sk 
everything works also inside presence graph . If I hide the archived devices they are not displayed. Just one detail, is it possible to remove the "Archived" label from the attendance graph if I have hidden the archived devices? 
Thank you
![Cattura](https://github.com/jokob-sk/Pi.Alert/assets/5001932/16d90993-10f2-471e-b982-0f620d1e5125)

**Comment by jokob-sk** [comment]
Hi @corasaniti ,

This should be available in the next release. If you can, please have a look at the `pi.alert_dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/Pi.Alert/actions)) from now. 

It would be great if you could test this on your end by switching to the above image and letting me know if the issue was resolved.

Thanks in advance,
j

**Comment by corasaniti** [comment]
@jokob-sk 
Sure. I just tested it and it works perfectly!!!
Thanks
![Cattura](https://github.com/jokob-sk/Pi.Alert/assets/5001932/1b996757-2a2c-4d55-931b-765550d45f2d)

**Comment by jokob-sk** [comment]
released -> closing
