### ISSUE TITLE
Mass edit?

### ISSUE THREAD

**Issue by hobybrenner** [jokob-sk/Pi.Alert#571]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Any chance at getting a mass edit feature?   It would be nice to be able to select large groups of devices and mark them as not new, etc.

### Describe the solution you'd like

Option to select multiple devices and edit.

### Describe alternatives you've considered

Option to select all, or have a select box allowing you to select a group or all devices on the "Devices" page.

### Anything else?

I think one of the other forks has this feature.

**Comment by jokob-sk** [comment]
Hi @hobybrenner ,

Thanks for the suggestion!

Can you elaborate on your use case?

Are you requesting mass-editing all fields or only the New device flag? 

Have you considered changing the defaults in the New Devices plugin (Set `NEWDEV_dev_NewDevice` to false)? If yes and this doesn't solve your issue, could you please elaborate on why?

I'm also considering some rudimentary workflow support, where I'm currently gathering feedback here: https://github.com/jokob-sk/Pi.Alert/issues/562

A current workaround is to use the Device CSV Export > Import approach described here: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEVICES_BULK_EDITING.md

I'm trying to understand the exact use case and how to make it useful to as many users :) 

Thanks in advance,
j

**Comment by Tharic99** [comment]
Not OP, but I was just wondering about this about an hour ago. Outside of the "new" flag, one use case I could see for a mass edit would be to set the Icon on multiple devices.

For example, I've got about two dozen Kasa Smart Plugs through the house. They show up on device list as a vendor of "Tp-Link Technologies Co.,Ltd." and a name of "HS103". 

A mass edit would be handy to be able to go to Devices, sort by Vendor, select "Mass Edit", put a checkbox in the 19 items from that same Vendor and then update the Icon to all be "plug" (just picked the closest thing that seemed an option on the FA site, but then that also goes back to #550 some too

**Comment by jokob-sk** [comment]
![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/1ddfb042-a41d-4832-8486-1e6fae33f92b)

This should be available in the next release. If you can, please have a look at the `pi.alert_dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/Pi.Alert/actions)) from now. 

It would be great if you could test this on your end by switching to the above image and letting me know if the issue was resolved.

Thanks in advance,
j

**Comment by schmidiij** [comment]
this is still in dev only or?

**Comment by jokob-sk** [comment]
Hey @schmidiij ,

Yes, I hope for a release in the next few days. Would be great if you could test it if interested. The image name is `pi.alert_dev`.

Thanks,
j

**Comment by jokob-sk** [comment]
released -> closing
