### ISSUE TITLE
Settings not displaying in Brave browser latest...

### ISSUE THREAD

**Issue by intraxit** [jokob-sk/Pi.Alert#574]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

Settings not correctly displaying in Brave browser latest

### Expected Behavior

correct display...

### Steps To Reproduce

Start pi-alert in Brave browser.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @intraxit ,

Could you please provide more details?

I just checked Brave and Settings seem to display just fine:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/9e7dd7e6-a299-4171-ab06-cc780f58aa19)

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/f4779f07-5447-448d-b5af-66e203de67c9)

Could you please paste any errors you see in the log or in the browser console if that is the case? See below for more guides on debugging issues:

- https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_TIPS.md
- https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_INVALID_JSON.md

Thanks in advance,
j

**Comment by Absoblogginlutely** [comment]
I actually just got the same issue  in Edge dev. I just updated to latest dev version (2024.2.17 by the looks of things) and after loading, my settings page does not show any of the configuration settings, I just get "Read more in the docs" when I click on any of the settings pages.
![image](https://github.com/jokob-sk/Pi.Alert/assets/21364480/30089819-6a19-4383-863b-a9ffd7875b14)
Console log as below.
```Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'run-ad-auction'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'join-ad-interest-group'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.
VM980 pialert_common.js:726 init pialert_common.js
VM982 pialert_common.js:726 init pialert_common.js
ui_components.js:16 undefined
ui_components.js:186 init ui_components.js
pialert_common.js:726 init pialert_common.js
VM980 pialert_common.js:641 {data: Array(92)}
VM982 pialert_common.js:641 {data: Array(92)}
pialert_common.js:641 {data: Array(92)}
handle_version.js:38 1710155822
handle_version.js:39 false
handle_version.js:7 false
handle_version.js:19 All up-to-date!
settings.php:1289 1710155821443.3242
settings.php:1294 11/03/2024, 07:17:01
pialert_common.js:133 Setting with key "General_RUN" not found
pialert_common.js:133 Setting with key "NEWDEV_RUN" not found
pialert_common.js:133 Setting with key "NTFPRCS_RUN" not found
pialert_common.js:133 Setting with key "WORKFLOWS_RUN" not found
settings.php:1062  Uncaught ReferenceError: isSQLQuery is not defined
    at generateInputOptions (settings.php:1062:5)
    at settings.php:917:27
    at Array.forEach (<anonymous>)
    at initSettingsPage (settings.php:831:20)
    at Object.success (settings.php:692:11)
    at c (jquery.min.js:2:27742)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:28487)
    at l (jquery.min.js:2:78789)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:81117)
generateInputOptions @ settings.php:1062
(anonymous) @ settings.php:917
initSettingsPage @ settings.php:831
(anonymous) @ settings.php:692
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
k.<computed> @ jquery.min.js:2
(anonymous) @ settings.php:688
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
k.<computed> @ jquery.min.js:2
getData @ settings.php:684
(anonymous) @ settings.php:1317
Show 14 more frames
Show less
```

The nginx/error.log does show errors like this though.
2024/03/11 11:39:16 [warn] 95#95: *291 an upstream response is buffered to a temporary file /var/lib/nginx/tmp/fastcgi/4/00/0000000004 while reading upstream, client: 192.168.29.123, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "pi.alert:20211", referrer: "http://pi.alert:20211/systeminfo.php"
2024/03/11 11:39:17 [warn] 95#95: *293 an upstream response is buffered to a temporary file /var/lib/nginx/tmp/fastcgi/5/00/0000000005 while reading upstream, client: 192.168.29.123, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "pi.alert:20211", referrer: "http://pi.alert:20211/systeminfo.php"
2024/03/11 11:44:53 [warn] 94#94: *379 an upstream response is buffered to a temporary file /var/lib/nginx/tmp/fastcgi/6/00/0000000006 while reading upstream, client: 192.168.29.123, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "pi.alert:20211", referrer: "http://pi.alert:20211/settings.php"
                              
Restarting the container does not help, and neither does parsing a parameter on the query string which normally creates a new request to bypass caching, however if I launch the browser in an incognito window then the settings page looks correct, so it appears that something is not clearing the cache correctly.

**Comment by jokob-sk** [comment]
Hi there, 

please try a different browser or clear the cache. The issue sounds like an older version of a js file is cached. Also, please use caution using the the _dev container as it's under active development so that container is pretty unstable compared to the production one.

Hope this helps,
j
