### ISSUE TITLE
Some installation observations.

### ISSUE THREAD

**Issue by zell-mbc** [jokob-sk/Pi.Alert#58]
After my first issue https://github.com/jokob-sk/Pi.Alert/issues/56 was resolved by manually adding a db file I ran into another issue right away when when trying to change some details of a device. The UI reported that the DB is read only. After playing around with groups and user rights for a while I gave up on Docker and went for a native install on my PiHole (DietPi OS)

First observation, the detailed installation link points to the wrong package: curl -LO https://github.com/pucherot/Pi.Alert/raw/main/tar/pialert_latest.tar Pucherot, insteat of leiweibau.
I didn't notice and it did install nevertheless but I obviously got the version without your new maintenance screen. This version also showed the "DB is read only error"? 

After I noticed that I got the wrong link I started all over with the links from your main page https://github.com/jokob-sk/Pi.Alert
Given that I am already running PiHole I went with the second link which worked, answered all the questions but then the installation stopped with
```
…
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'

- Deleting downloaded tar file...
- Settting Pi.Alert config file
sed: can't read /home/thomas/pialert/config/pialert.conf: No such file or directory
…
```

The error is correct because somehow the installer didn't install the directories in /home/thomas/pialert but in ~ (/home/thomas)
I tried to launch a second time from within a manually created ~/pialert folder which didn't work because the folder was already there.

So I moved all folders manually to ~/pialert and updated the pialert directory in the config file manualy followed by running one of the cron commands:
`python3 ~/pialert/back/pialert.py 1
`
This time it was complaining about a table "Online_History"

`sqlite3.OperationalError: table Online_History has no column named Archived_Devices
`
So I went ahead and moved the template DB I used yesterday over the newly created database, but this one doesn't seem to have the table Online_History at all?
```
python3 ~/pialert/back/pialert.py 1
sqlite3.OperationalError: no such table: Online_History
```

I then discovered the pialert_patch_DB.sh script which adds the missing table, but after running that one I am stuck with
`sqlite3.OperationalError: table Online_History has no column named ScanCycle
`

Here's a screenshot of the "DB read only" error I got on the Docker install as well as now on my PiHole:

![image](https://user-images.githubusercontent.com/29018767/182125578-a8a774fc-e6d2-4b82-b956-4e6e65513d45.png)

There's another DB related issue when trying to create a backup (both on Docker and PiHole), after confirming that I am sure I want to create a backup I get the following error(?)
![image](https://user-images.githubusercontent.com/29018767/182128709-fa02aec6-0939-4f5f-983d-5e961bd988a5.png)

**Comment by jokob-sk** [comment]
Hi!

>After playing around with groups and user rights for a while I gave up on Docker and went for a native install on my PiHole (DietPi OS)

I only support installing the app via the docker container:

https://registry.hub.docker.com/u/jokobsk

> First observation, the detailed installation link points to the wrong package: curl -LO https://github.com/pucherot/Pi.Alert/raw/main/tar/pialert_latest.tar Pucherot, insteat of leiweibau.

You can submit an issue to https://github.com/leiweibau/Pi.Alert and after he fixes them, I'll merge them into this fork.

Thanks!

**Comment by zell-mbc** [comment]
Sorry, looks like I mixed up the 3 sites which almost look identical

**Comment by jokob-sk** [comment]
All good, I know it gets confusing!
