### ISSUE TITLE
Couple of bugs to report

### ISSUE THREAD

**Issue by vladaurosh** [jokob-sk/Pi.Alert#582]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

Hi @jokob-sk 

While doing some tests, I noticed errors in nginx error log file:
```
open() "/var/www/html/pialert/front/css/offline-font.css" failed (2: No such file or directory) ... referrer: "http://192.168.1.1:20211/index.php"
open() "/var/www/html/pialert/lib/AdminLTE/bower_components/font-awesome/css/font-awesome.min.css" failed (2: No such file or directory) ... referrer: "http://192.168.1.1:20211/index.php"
```
font-awesome.min.css file does not exist but fontawesome.min.css exists. 
/var/www/html/pialert/front/css/offline-font.css does not exist but /var/www/html/pialert/css/offline-font.css exists. 

Also, Wake on LAN does not work, I see in front/php/server/devices.php:  
`exec('wakeonlan '.$WOL_HOST_MAC , $output);`

This executable (wakeonlan ) does not exist, as package wakeonlan is not installed. I've installed package in running container, and wake on lan worked. 

### Expected Behavior

N/A

### Steps To Reproduce

N/A

### pialert.conf

```python
N/A
```

### docker-compose.yml

```python
N/A
```

### What branch are you running?

Production

### pialert.log

N/A

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Thanks, hopefully, I fixed everything outstanding.

**Comment by jokob-sk** [comment]
released -> closing
