### ISSUE TITLE
Define number of scan cycles before device is marked as offline/down

### ISSUE THREAD

**Issue by AdmiralRaccoon** [jokob-sk/Pi.Alert#587]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have some devices (A switch, some shelly devices), which for what reason doesn´t seem to respond during a scan and get marked as offline/down, although they´re online

### Describe the solution you'd like

A device setting that allows to define a value after how many scan cycles the device becomes offline/down

### Describe alternatives you've considered

edit: Or, maybe something similar to home assistant´s "consider home", a period of time that must pass without reaching the device, to set it as offline/down

### Anything else?

-

**Comment by jokob-sk** [comment]
Hi @AdmiralRaccoon ,

Thanks for the suggestion! From what you are describing these devices are unmovable so once detected their online status is not that important. 

There is a setting for down devices already, which should enable you to achieve the described scenario for down notifications:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/6a024864-98ad-4324-a19f-8ed390ffb888)

You could theoretically ignore the devices via the `NTFPRCS_event_condition` setting for offline notifications. 

Another alternative is to mark specific devices as `Scan device: NO` via one of these settings:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/10c3cf6c-d0f1-43f9-80e2-936b6a238abc)

BTW: There is a mass-edit functionality coming in the next release so marking multiple devices will be easier. You can test the `pi.alert_dev` container if interested. 

Happy to hear your thoughts. I could implement a similar offline detection mechanism for down notifications, but I want to avoid overcomplicating the logic if you can cater to your use case with the existing configuration options. 

Thanks,
j

**Comment by AdmiralRaccoon** [comment]
Thanks for the reply, I should have read the docs more carefully! :-D
I will test it asap

**Comment by AdmiralRaccoon** [comment]
Another thinh...would it be possible to make the "Alter down after" a per device setting? For some devices, 10-15min is great, but  for others 5 minutes would be better to trigger automations in Home Assisant for example.

**Comment by jokob-sk** [comment]
Hey there!

I don't plan to extend the functionality to a per-device setting as it would require DB changes, thus changing the CSV export import functionality, the device columns and the columns ordering and picker, and the dependent plugin. So, even if the changes might look small, the downflow effect is pretty significant. 

You can list your exact use case in the Workflows feedback issue and I might consider it for a custom workflow scenario: https://github.com/jokob-sk/Pi.Alert/issues/562

You could also move that logic into HA, e.g. have a list of devices that you want to trigger automation right away and some that have a wait timer (e.g. based on the device name based on some naming convention). 

Or you could have a middle layer via n8n/nodeRed to cater to more advanced automation needs: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/WEBHOOK_N8N.md

Hope the above gives you some ideas.

Thanks,
j

**Comment by AdmiralRaccoon** [comment]
Ok thank you for you hints, I´ll give it a try.

Apart from that - I guess there´s nothing PiAlert can do but to deactivate the scan for example this device: It´s a small managed Draytek switch, i simply don´t know why the arp-scan doesn´t recognize it all the time as it´s online 24/7 and I would loose my internet connection if it would be malfunctioning.

![image](https://github.com/jokob-sk/Pi.Alert/assets/41727850/2a402db8-441a-4252-b0c6-7f3ee1d68b3d)

**Comment by jokob-sk** [comment]
Yeah, that is a possible workaround. I regrettably don't have the mentioned switch so I can't reproduce the behavior. If you have time & know how to code you can help me to improve PiAlert and the arp-scan if you have ideas on how to possibly make it more reliable.
