### ISSUE TITLE
prod copy of test install reports many online devices as offline

### ISSUE THREAD

**Issue by flhtk2012** [jokob-sk/Pi.Alert#589]
I have 2 identical OMV Ras Pis running Docker- one for prod, one for test.
I setup PiAlert in a test sandbox machine and got familiar with it. I configured hardware descriptions etc. When I was ready to move to prod, I copied my conf & db files to my prod machine & entered new volume paths.
Everything seemed fine initially,  but now many online devices report as offline. 
I still have my sandbox running and it still reports properly.
Can someone point me in the proper direction & suggest what to check. Both configurations look to be identical. 
Kind regards 
T

**Comment by jokob-sk** [comment]
Hi @flhtk2012 ,

Thanks for the message!

During troubleshooting, please enable debug: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_TIPS.md

Please have a look at what your enabled plugins produce as output in the Plugins -> <Enbaled plugin> section. Please check this for details:  https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_PLUGINS.md

Another one is the network interface, if you use different hardware they might use different network hardware IDs, which is important if you use arp-scan to detect the status of your devices. Please read this for details: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/SUBNETS.md

Hope the above helps!
j

**Comment by jokob-sk** [comment]
no reply for a week -> Closing
