### ISSUE TITLE
Error appending to file: [Error 5] Input/output error

### ISSUE THREAD

**Issue by servebeer** [jokob-sk/Pi.Alert#590]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

When stating up my Pi.Alert docker image, on UnRAID, i keep getting the errors shown in the attached screen-shot.

![Screenshot 2024-03-15 at 13 43 53](https://github.com/jokob-sk/Pi.Alert/assets/8514341/957c5473-9e95-4518-9258-62fdaae214d8)

### Expected Behavior

Pi.Alert should load w/o any errors

### pialert.conf

```python
Too big to post
```

### docker-compose.yml

```python
n/a, using Pi.Alert from the UnRAID App Store.
```

### What branch are you running?

Production

############################################################
 Pi.Alert Update
############################################################
Thu Mar 14 09:26:30 CDT 2024
Logfile: pialert_update_2024-03-14_09-26.log

************************************************************
************************************************************
**             ERROR UPDATING PI.ALERT                    **
************************************************************
************************************************************

Pi.Alert directory dosn't exists: /root/pialert

Use 'cat pialert_update_2024-03-14_09-26.log' to view update log

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @servebeer ,

Unfortunately, I don't have experience with the UnRaid store. There should still be a docker file and judging from the error messages, it seems like the `/log` folder might not have sufficient write permissions. Is there an UnRaid forum you can check your config on? It would also be great to update this thread if you figure out the culprit. 

Thanks in advance,
j

**Comment by jokob-sk** [comment]
no reply for a week -> Closing
