### ISSUE TITLE
Pi.Alert does not scan VLANs with ARP scan, from within container, I can

### ISSUE THREAD

**Issue by CrappyTan** [jokob-sk/Pi.Alert#592]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

tldr: Pi Alert not scanning / detecting clients on VLANS. If I exec into the container, I can scan. 

Container: VLAN 54, 10.10.54.0/24
Scan VLAN: VLAN 56, 10.10.56.1/24

` arp-scan 10.10.56.0/24 --interface=enp2s0 --vlan=56`

Output: 
`Interface: enp2s0, type: EN10MB, MAC: 14:b3:1f:1f:25:ea, IPv4: 10.10.54.20
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)
10.10.56.1      00:e0:67:1b:14:ce       eac AUTOMATION-CONSULTING GmbH (802.1Q VLAN=56)
10.10.56.50     ec:71:db:55:70:ba       Reolink Innovation Limited (802.1Q VLAN=56)
10.10.56.53     b4:6d:c2:c4:87:3d       SHENZHEN BILIAN ELECTRONIC CO.，LTD (802.1Q VLAN=56)
10.10.56.56     ec:71:db:26:87:0d       Reolink Innovation Limited (802.1Q VLAN=56)
10.10.56.60     ec:71:db:84:08:80       Reolink Innovation Limited (802.1Q VLAN=56)
`

Logs from PiAlert:
`09:22:46 [ARP Scan] arpscan_output: Interface: enp2s0, type: EN10MB, MAC: 14:b3:1f:1f:25:ea, IPv4: 10.10.54.20
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)
10.10.56.1	00:e0:67:1b:14:ce	eac AUTOMATION-CONSULTING GmbH (802.1Q VLAN=56)
10.10.56.50	ec:71:db:55:70:ba	Reolink Innovation Limited (802.1Q VLAN=56)
10.10.56.53	b4:6d:c2:c4:87:3d	SHENZHEN BILIAN ELECTRONIC CO.，LTD (802.1Q VLAN=56)
10.10.56.56	ec:71:db:26:87:0d	Reolink Innovation Limited (802.1Q VLAN=56)
10.10.56.60	ec:71:db:84:08:80	Reolink Innovation Limited (802.1Q VLAN=56)

24 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.10.0: 256 hosts scanned in 11.176 seconds (22.91 hosts/sec). 5 responded
`

As you can see, pialert version of the scan also sees them. 
When I click on the Devices tab in the UI, I do not see them listed. 

note sure if this is relevant: 
`09:43:11 [NSLOOKUP] ⚠ ERROR - check logs
09:43:11 [NSLOOKUP] Scan: FAIL - check logs
09:43:11 [NSLOOKUP]** server can't find 137.54.10.10.in-addr.arpa: NXDOMAIN
`
The NSLookup has a valid IP address but reversed. 

### Expected Behavior

To show and monitor devices found on VLANs and act accordingly. 

### Steps To Reproduce

Described above

### pialert.conf

```python
#-----------------AUTOGENERATED FILE-----------------#
#                                                    #
#         Generated:  2022-12-30_22-19-40            #
#                                                    #
#   Config file for the LAN intruder detection app:  #
#      https://github.com/jokob-sk/Pi.Alert          #
#                                                    #
#-----------------AUTOGENERATED FILE-----------------#


# General
#---------------------------
# Scan using interface eth0
# SCAN_SUBNETS    = ['192.168.1.0/24 --interface=eth0']
#
# Scan multiple interfaces (eth1 and eth0):
# SCAN_SUBNETS    = [ '192.168.1.0/24 --interface=eth1', '192.168.1.0/24 --interface=eth0' ]

#SCAN_SUBNETS=['192.168.1.0/24 --interface=eth1']
SCAN_SUBNETS=['10.10.54.0/24 --interface=enp2s0 -vlan=54','10.10.50.0/24 --interface=enp2s0 -vlan=1','10.10.51.0/24 --interface=enp2s0 -vlan=51','10.10.57.0/24 --interface=enp2s0 -vlan=57','10.10.55.0/24 --interface=enp2s0 -vlan=55','10.10.56.0/24 --interface=enp2s0 -vlan=56','171.17.0.0/16 --interface=docker0']

TIMEZONE='Europe/London'
PIALERT_WEB_PROTECTION=False
PIALERT_WEB_PASSWORD='8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92'
DAYS_TO_KEEP_EVENTS=90
# Used for generating links in emails. Make sure not to add a trailing slash!
REPORT_DASHBOARD_URL='http://pi.alert'


# Email
#---------------------------
REPORT_MAIL=False
SMTP_SERVER='smtp.gmail.com'
SMTP_PORT=587
SMTP_REPORT_TO='user@gmail.com'
SMTP_REPORT_FROM='Pi.Alert <user@gmail.com>'
SMTP_SKIP_LOGIN=False
SMTP_USER='user@gmail.com'
SMTP_PASS='password'
SMTP_SKIP_TLS=False


# Webhooks
#---------------------------
REPORT_WEBHOOK=False
WEBHOOK_URL='http://n8n.local:5555/webhook-test/aaaaaaaa-aaaa-aaaa-aaaaa-aaaaaaaaaaaa'
WEBHOOK_PAYLOAD='json'                 # webhook payload data format for the "body > attachements > text" attribute 
                                       # in https://github.com/jokob-sk/Pi.Alert/blob/main/docs/webhook_json_sample.json 
                                       #   supported values: 'json', 'html' or 'text'
                                       #   e.g.: for discord use 'html'
WEBHOOK_REQUEST_METHOD='GET'


# Apprise
#---------------------------
REPORT_APPRISE=False
APPRISE_HOST='http://localhost:8000/notify'
APPRISE_URL='mailto://smtp-relay.sendinblue.com:587?from=user@gmail.com&name=apprise&user=user@gmail.com&pass=password&to=user@gmail.com'


# NTFY
#---------------------------
REPORT_NTFY=False
NTFY_HOST='https://ntfy.sh'
NTFY_TOPIC='replace_my_secure_topicname_91h889f28'
NTFY_USER='user'
NTFY_PASSWORD='passw0rd'


# PUSHSAFER
#---------------------------
REPORT_PUSHSAFER=False
PUSHSAFER_TOKEN='ApiKey'


# MQTT
#---------------------------
REPORT_MQTT=False
MQTT_BROKER='192.168.1.2'
MQTT_PORT=1883
MQTT_USER='mqtt'
MQTT_PASSWORD='passw0rd'
MQTT_QOS=0
MQTT_DELAY_SEC=2


# DynDNS
#---------------------------
DDNS_ACTIVE=False
DDNS_DOMAIN='your_domain.freeddns.org'
DDNS_USER='dynu_user'
DDNS_PASSWORD='A0000000B0000000C0000000D0000000'
DDNS_UPDATE_URL='https://api.dynu.com/nic/update?'


#-------------------IMPORTANT INFO-------------------#
#   This file is ingested by a python script, so if  #
#        modified it needs to use python syntax      #
#-------------------IMPORTANT INFO-------------------#
```

### docker-compose.yml

```python
container_name: pialert
        # use the below line if you want to test the latest dev image
        # image: "jokobsk/pi.alert_dev:latest" 
        image: "jokobsk/pi.alert:latest"      
        network_mode: "host"        
        restart: unless-stopped
        volumes:
          - /mnt/storage/containers/pialert/config:/home/pi/pialert/config
          - /mnt/storage/containers/pialert/db:/home/pi/pialert/db      
          # (optional) useful for debugging if you have issues setting up the container
          - /mnt/storage/containers/pialert/logs:/home/pi/pialert/front/log
        environment:
          - TZ=Europe/London
          - HOST_USER_ID=1000
          - HOST_USER_GID=1000
          - PORT=20211
```

### What branch are you running?

Production

### pialert.log

...snip

10:10:43 [Plugin utils] Flattening the below array
10:10:43 ['10.10.54.0/24 --interface=enp2s0 -vlan=54', '10.10.50.0/24 --interface=enp2s0 -vlan=1', '10.10.51.0/24 --interface=enp2s0 -vlan=51', '10.10.57.0/24 --interface=enp2s0 -vlan=57', '10.10.55.0/24 --interface=enp2s0 -vlan=55', '10.10.56.0/24 --interface=enp2s0 -vlan=56', '171.17.0.0/16 --interface=docker0']
10:10:43 [Plugin utils] isinstance(arr, list) : False | isinstance(arr, str) : True
10:10:43 [Plugins] Resolved value: 10.10.54.0/24 --interface=enp2s0 -vlan=54,10.10.50.0/24 --interface=enp2s0 -vlan=1,10.10.51.0/24 --interface=enp2s0 -vlan=51,10.10.57.0/24 --interface=enp2s0 -vlan=57,10.10.55.0/24 --interface=enp2s0 -vlan=55,10.10.56.0/24 --interface=enp2s0 -vlan=56,171.17.0.0/16 --interface=docker0
10:10:43 [Plugins] Convert to Base64: True
10:10:43 [Plugins] base64 value: b'MTAuMTAuNTQuMC8yNCAtLWludGVyZmFjZT1lbnAyczAgLXZsYW49NTQsMTAuMTAuNTAuMC8yNCAtLWludGVyZmFjZT1lbnAyczAgLXZsYW49MSwxMC4xMC41MS4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01MSwxMC4xMC41Ny4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01NywxMC4xMC41NS4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01NSwxMC4xMC41Ni4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01NiwxNzEuMTcuMC4wLzE2IC0taW50ZXJmYWNlPWRvY2tlcjA='
10:10:43 [Plugins] Timeout: 300
10:10:43 [Plugin utils] Pre-Resolved CMD: python3/home/pi/pialert/front/plugins/arp_scan/script.pyuserSubnets={subnets}
10:10:43 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/arp_scan/script.py userSubnets={subnets}
10:10:43 [Plugins] Resolved : ['python3', '/home/pi/pialert/front/plugins/arp_scan/script.py', "userSubnets=b'MTAuMTAuNTQuMC8yNCAtLWludGVyZmFjZT1lbnAyczAgLXZsYW49NTQsMTAuMTAuNTAuMC8yNCAtLWludGVyZmFjZT1lbnAyczAgLXZsYW49MSwxMC4xMC41MS4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01MSwxMC4xMC41Ny4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01NywxMC4xMC41NS4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01NSwxMC4xMC41Ni4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01NiwxNzEuMTcuMC4wLzE2IC0taW50ZXJmYWNlPWRvY2tlcjA='"]
10:10:43 [ARP Scan] In script 
10:10:43 [ARP Scan] values.userSubnets: ["userSubnets=b'MTAuMTAuNTQuMC8yNCAtLWludGVyZmFjZT1lbnAyczAgLXZsYW49NTQsMTAuMTAuNTAuMC8yNCAtLWludGVyZmFjZT1lbnAyczAgLXZsYW49MSwxMC4xMC41MS4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01MSwxMC4xMC41Ny4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01NywxMC4xMC41NS4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01NSwxMC4xMC41Ni4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01NiwxNzEuMTcuMC4wLzE2IC0taW50ZXJmYWNlPWRvY2tlcjA='"]
10:10:43 [ARP Scan] userSubnetsParamBase64: 'MTAuMTAuNTQuMC8yNCAtLWludGVyZmFjZT1lbnAyczAgLXZsYW49NTQsMTAuMTAuNTAuMC8yNCAtLWludGVyZmFjZT1lbnAyczAgLXZsYW49MSwxMC4xMC41MS4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01MSwxMC4xMC41Ny4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01NywxMC4xMC41NS4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01NSwxMC4xMC41Ni4wLzI0IC0taW50ZXJmYWNlPWVucDJzMCAtdmxhbj01NiwxNzEuMTcuMC4wLzE2IC0taW50ZXJmYWNlPWRvY2tlcjA='
10:10:43 [ARP Scan] userSubnetsParam: 10.10.54.0/24 --interface=enp2s0 -vlan=54,10.10.50.0/24 --interface=enp2s0 -vlan=1,10.10.51.0/24 --interface=enp2s0 -vlan=51,10.10.57.0/24 --interface=enp2s0 -vlan=57,10.10.55.0/24 --interface=enp2s0 -vlan=55,10.10.56.0/24 --interface=enp2s0 -vlan=56,171.17.0.0/16 --interface=docker0
10:10:43 [Database] Opening DB
10:10:54 [ARP Scan] arpscan_output: Interface: enp2s0, type: EN10MB, MAC: 14:b3:1f:1f:25:ea, IPv4: 10.10.54.20
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)
10.10.54.1	00:e0:67:1b:14:ce	eac AUTOMATION-CONSULTING GmbH
10.10.54.2	02:42:0a:0a:36:02	(Unknown: locally administered)
10.10.54.4	02:42:0a:0a:36:04	(Unknown: locally administered)
10.10.54.10	dc:a6:32:0d:2a:3d	Raspberry Pi Trading Ltd
10.10.54.11	dc:a6:32:e0:d5:ca	Raspberry Pi Trading Ltd
10.10.54.13	dc:a6:32:03:38:6d	Raspberry Pi Trading Ltd
10.10.54.31	02:42:0a:0a:36:1f	(Unknown: locally administered)
10.10.54.32	02:42:0a:0a:36:20	(Unknown: locally administered)
10.10.54.35	02:42:0a:0a:36:23	(Unknown: locally administered)
10.10.54.36	02:42:0a:0a:36:24	(Unknown: locally administered)
10.10.54.40	02:42:0a:0a:36:28	(Unknown: locally administered)
10.10.54.137	02:42:0a:0a:36:89	(Unknown: locally administered)
10.10.54.200	02:42:0a:0a:36:c8	(Unknown: locally administered)
10.10.54.235	02:42:0a:0a:36:eb	(Unknown: locally administered)

23 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.10.0: 256 hosts scanned in 11.181 seconds (22.90 hosts/sec). 14 responded

10:11:05 [ARP Scan] arpscan_output: Interface: enp2s0, type: EN10MB, MAC: 14:b3:1f:1f:25:ea, IPv4: 10.10.54.20
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)
10.10.50.1	00:e0:67:1b:14:cd	eac AUTOMATION-CONSULTING GmbH (802.1Q VLAN=1)
10.10.50.13	c0:61:9a:b1:11:68	Victron Energy B.V. (802.1Q VLAN=1)
10.10.50.9	64:90:c1:15:88:69	Beijing Xiaomi Mobile Software Co., Ltd (802.1Q VLAN=1)
10.10.50.19	94:18:82:37:18:70	Hewlett Packard Enterprise (802.1Q VLAN=1)
10.10.50.33	f0:9f:c2:a9:4e:bc	Ubiquiti Networks Inc. (802.1Q VLAN=1)
10.10.50.31	78:8a:20:42:b4:bc	Ubiquiti Networks Inc. (802.1Q VLAN=1)
10.10.50.34	f0:9f:c2:7c:38:25	Ubiquiti Networks Inc. (802.1Q VLAN=1)
10.10.50.35	f0:9f:c2:f3:0d:c6	Ubiquiti Networks Inc. (802.1Q VLAN=1)
10.10.50.36	78:8a:20:b3:b3:e2	Ubiquiti Networks Inc. (802.1Q VLAN=1)
10.10.50.39	24:5a:4c:8f:c3:4f	Ubiquiti Networks Inc. (802.1Q VLAN=1)
10.10.50.40	78:45:58:85:2b:7d	Ubiquiti Networks Inc. (802.1Q VLAN=1)
10.10.50.41	24:5a:4c:8f:93:8e	Ubiquiti Networks Inc. (802.1Q VLAN=1)
10.10.50.38	74:83:c2:6d:6e:af	Ubiquiti Networks Inc. (802.1Q VLAN=1)
10.10.50.53	b0:4a:39:85:c0:de	Beijing Roborock Technology Co., Ltd. (802.1Q VLAN=1)
10.10.50.76	68:c6:3a:95:77:8d	Espressif Inc. (802.1Q VLAN=1)
10.10.50.78	48:a2:e6:4d:00:73	Resideo (802.1Q VLAN=1)
10.10.50.52	5c:cf:7f:7f:fb:a6	Espressif Inc. (802.1Q VLAN=1)
10.10.50.83	bc:dd:c2:ea:59:60	Espressif Inc. (802.1Q VLAN=1)
10.10.50.75	84:f3:eb:48:bc:5f	Espressif Inc. (802.1Q VLAN=1)
10.10.50.59	a0:20:a6:06:31:3a	Espressif Inc. (802.1Q VLAN=1)
10.10.50.88	d8:f1:5b:92:36:37	Espressif Inc. (802.1Q VLAN=1)
10.10.50.51	b4:e6:2d:25:48:d4	Espressif Inc. (802.1Q VLAN=1)
10.10.50.100	44:65:0d:02:d4:30	Amazon Technologies Inc. (802.1Q VLAN=1)
10.10.50.58	cc:50:e3:54:8d:04	Espressif Inc. (802.1Q VLAN=1)
10.10.50.104	dc:4f:22:09:cf:11	Espressif Inc. (802.1Q VLAN=1)
10.10.50.112	5c:cf:7f:97:00:e2	Espressif Inc. (802.1Q VLAN=1)
10.10.50.103	ac:0b:fb:d0:81:c8	Espressif Inc. (802.1Q VLAN=1)
10.10.50.117	2c:3a:e8:4e:b9:08	Espressif Inc. (802.1Q VLAN=1)
10.10.50.110	84:f3:eb:db:50:63	Espressif Inc. (802.1Q VLAN=1)
10.10.50.113	70:61:be:7f:96:3e	Wistron Neweb Corporation (802.1Q VLAN=1)
10.10.50.120	bc:dd:c2:24:b1:b8	Espressif Inc. (802.1Q VLAN=1)
10.10.50.127	bc:dd:c2:ea:a9:6c	Espressif Inc. (802.1Q VLAN=1)
10.10.50.139	5c:cf:7f:9f:14:e5	Espressif Inc. (802.1Q VLAN=1)
10.10.50.145	ac:8b:a9:90:49:f3	Ubiquiti Networks Inc. (802.1Q VLAN=1)
10.10.50.151	8c:c6:81:5c:85:eb	Intel Corporate (802.1Q VLAN=1)
10.10.50.149	50:f5:da:6d:92:8d	Amazon Technologies Inc. (802.1Q VLAN=1)
10.10.50.224	7c:0a:3f:85:e0:20	Samsung Electronics Co.,Ltd (802.1Q VLAN=1)
10.10.50.243	9c:8c:6e:61:e3:26	Samsung Electronics Co.,Ltd (802.1Q VLAN=1)
10.10.50.251	00:17:c8:b2:d9:e7	KYOCERA Display Corporation (802.1Q VLAN=1)
10.10.50.84	a4:cf:12:f2:90:cb	Espressif Inc. (802.1Q VLAN=1)
10.10.50.212	44:a8:fc:39:34:5b	Apple, Inc. (802.1Q VLAN=1)
10.10.50.210	92:0d:18:c4:64:ff	(Unknown: locally administered) (802.1Q VLAN=1)
10.10.50.141	c8:d7:78:30:a6:76	BSH Hausgeraete GmbH (802.1Q VLAN=1)
10.10.50.242	4c:4f:ee:d9:6b:4d	OnePlus Technology (Shenzhen) Co., Ltd (802.1Q VLAN=1)

47 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.10.0: 256 hosts scanned in 11.177 seconds (22.90 hosts/sec). 44 responded

10:11:16 [ARP Scan] arpscan_output: Interface: enp2s0, type: EN10MB, MAC: 14:b3:1f:1f:25:ea, IPv4: 10.10.54.20
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)

11 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.10.0: 256 hosts scanned in 11.175 seconds (22.91 hosts/sec). 0 responded

10:11:28 [ARP Scan] arpscan_output: Interface: enp2s0, type: EN10MB, MAC: 14:b3:1f:1f:25:ea, IPv4: 10.10.54.20
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)
10.10.57.1	00:e0:67:1b:14:ce	eac AUTOMATION-CONSULTING GmbH (802.1Q VLAN=57)

3 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.10.0: 256 hosts scanned in 11.212 seconds (22.83 hosts/sec). 1 responded

10:11:39 [ARP Scan] arpscan_output: Interface: enp2s0, type: EN10MB, MAC: 14:b3:1f:1f:25:ea, IPv4: 10.10.54.20
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)
10.10.55.1	00:e0:67:1b:14:ce	eac AUTOMATION-CONSULTING GmbH (802.1Q VLAN=55)

2 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.10.0: 256 hosts scanned in 11.218 seconds (22.82 hosts/sec). 1 responded

10:11:50 [ARP Scan] arpscan_output: Interface: enp2s0, type: EN10MB, MAC: 14:b3:1f:1f:25:ea, IPv4: 10.10.54.20
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)
10.10.56.1	00:e0:67:1b:14:ce	eac AUTOMATION-CONSULTING GmbH (802.1Q VLAN=56)
10.10.56.50	ec:71:db:55:70:ba	Reolink Innovation Limited (802.1Q VLAN=56)
10.10.56.53	b4:6d:c2:c4:87:3d	SHENZHEN BILIAN ELECTRONIC CO.，LTD (802.1Q VLAN=56)
10.10.56.56	ec:71:db:26:87:0d	Reolink Innovation Limited (802.1Q VLAN=56)
10.10.56.60	ec:71:db:84:08:80	Reolink Innovation Limited (802.1Q VLAN=56)

5 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.10.0: 256 hosts scanned in 11.159 seconds (22.94 hosts/sec). 5 responded

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @CrappyTan ,

Thank you for the detailed report.

The log file seems to indicate that scans are performed successfully. May it be that the scans take too long and that you need to increase the **time** and **timeout** between scans from 5 to 10 minutes (a similar topic can be found in this discussion https://github.com/jokob-sk/Pi.Alert/discussions/578)? The logs don't include the processing of the results so not sure if the scan isn't canceled because of the timeout being reached. 

Here are the relevant settings:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/b88e9eb1-1797-4f62-a7d8-64575d93f7bf)
 
You can also check if the results are being loaded into the app in the Plugins -> Arp-Scan section. This doc might help as well: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_PLUGINS.md

Hope the above helps,
j

**Comment by CrappyTan** [comment]
I'm (seemingly) unable to change the settings: 

I've updated the cron from /5 to /10, saved, restarted etc, but the Device Scanners green box still shows /5. 
![image](https://github.com/jokob-sk/Pi.Alert/assets/27884877/ff1977b6-70aa-4ca3-996c-3c168bbea970)

![image](https://github.com/jokob-sk/Pi.Alert/assets/27884877/1d26858d-c537-480c-bc73-320243821f32)


I have changed the timeout from 300 to 600 but alas, still now joy.

As an aside, a scan from within the container finishes in 10-15 seconds. Should 3 minutes not have been enough?

**Comment by CrappyTan** [comment]
Nope. None of the other vlans show up in the list. 
![image](https://github.com/jokob-sk/Pi.Alert/assets/27884877/3ae7f738-ab22-4dd1-a42c-cd74cc5f7766)


How can I run the script.py from within the container? Let's have a play with that and debug from there? 

I pulled the new version this evening - now showing new nav UI. Nice :)

**Comment by jokob-sk** [comment]
Hi @CrappyTan ,

Glad you like the new UI :)

Running the script in the container needs to setup a python environment, so not too straightforward. You can try by checking the log and finding the executed command. It should look something like:

```
23:25:49 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/arp_scan/script.py userSubnets={subnets}
23:25:49 [Plugins] Resolved : ['python3', '/home/pi/pialert/front/plugins/arp_scan/script.py', "userSubnets=b'MTkyLjE2OC4xLjAvMjQgLS1pbnRlcmZhY2U9ZXRoMQ=='"]
12
```

that is translated to:

```
python3 /home/pi/pialert/front/plugins/arp_scan/script.py userSubnets=b'MTkyLjE2OC4xLjAvMjQgLS1pbnRlcmZhY2U9ZXRoMQ==
```

Can you please send me the log with debug enabled after the last VLAN scan is finished? It should look something like this (but for the ARPSCAN plugin:

```
17:31:05 [Scheduler] - Scheduler run for PIHOLE: YES
17:31:05 [Plugin utils] ---------------------------------------------
17:31:05 [Plugin utils] display_name: PiHole (Device sync)
17:31:05 [Plugins] CMD: SELECT n.hwaddr AS Object_PrimaryID, {s-quote}null{s-quote} AS Object_SecondaryID, datetime() AS DateTime, na.ip  AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, {s-quote}null{s-quote} AS Extra, n.hwaddr AS ForeignKey FROM EXTERNAL_PIHOLE.Network AS n LEFT JOIN EXTERNAL_PIHOLE.Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE {s-quote}ip-%{s-quote} AND n.hwaddr is not {s-quote}00:00:00:00:00:00{s-quote}  AND na.ip is not null
17:31:05 [Plugins] setTyp: subnets
17:31:05 [Plugin utils] Flattening the below array
17:31:05 ['192.168.1.0/24 --interface=eth1']
17:31:05 [Plugin utils] isinstance(arr, list) : False | isinstance(arr, str) : True
17:31:05 [Plugins] Resolved value: 192.168.1.0/24 --interface=eth1
17:31:05 [Plugins] Convert to Base64: True
17:31:05 [Plugins] base64 value: b'MTkyLjE2OC4xLjAvMjQgLS1pbnRlcmZhY2U9ZXRoMQ=='
17:31:05 [Plugins] Timeout: 10
17:31:05 [Plugins] Executing: SELECT n.hwaddr AS Object_PrimaryID, 'null' AS Object_SecondaryID, datetime() AS DateTime, na.ip  AS Watched_Value1, n.lastQuery AS Watched_Value2, na.name AS Watched_Value3, n.macVendor AS Watched_Value4, 'null' AS Extra, n.hwaddr AS ForeignKey FROM EXTERNAL_PIHOLE.Network AS n LEFT JOIN EXTERNAL_PIHOLE.Network_Addresses AS na ON na.network_id = n.id WHERE n.hwaddr NOT LIKE 'ip-%' AND n.hwaddr is not '00:00:00:00:00:00'  AND na.ip is not null
🔻
17:31:05 [Plugins] SUCCESS, received 2 entries
17:31:05 [Plugins] sqlParam entries: [(0, 'PIHOLE', '01:01:01:01:01:01', 'null', 'null', '2023-12-25 06:31:05', '172.30.0.1', 0, 'aaaa', 'vvvvvvvvv', 'not-processed', 'null', 'null', '01:01:01:01:01:01'), (0, 'PIHOLE', '02:42:ac:1e:00:02', 'null', 'null', '2023-12-25 06:31:05', '172.30.0.2', 0, 'dddd', 'vvvvv2222', 'not-processed', 'null', 'null', '02:42:ac:1e:00:02')]
17:31:05 [Plugins] Processing        : PIHOLE
17:31:05 [Plugins] Existing objects from Plugins_Objects: 4
17:31:05 [Plugins] Logged events from the plugin run    : 2
17:31:05 [Plugins] pluginEvents      count: 2
17:31:05 [Plugins] pluginObjects     count: 4
17:31:05 [Plugins] events_to_insert  count: 0
17:31:05 [Plugins] history_to_insert count: 4
17:31:05 [Plugins] objects_to_insert count: 0
17:31:05 [Plugins] objects_to_update count: 4
17:31:05 [Plugin utils] In pluginEvents there are 2 events with the status "watched-not-changed" 
17:31:05 [Plugin utils] In pluginObjects there are 2 events with the status "missing-in-last-scan" 
17:31:05 [Plugin utils] In pluginObjects there are 2 events with the status "watched-not-changed" 
17:31:05 [Plugins] Mapping objects to database table: CurrentScan
17:31:05 [Plugins] SQL query for mapping: INSERT into CurrentScan ( "cur_MAC", "cur_IP", "cur_LastQuery", "cur_Name", "cur_Vendor", "cur_ScanMethod") VALUES ( ?, ?, ?, ?, ?, ?)
17:31:05 [Plugins] SQL sqlParams for mapping: [('01:01:01:01:01:01', '172.30.0.1', 0, 'aaaa', 'vvvvvvvvv', 'PIHOLE'), ('02:42:ac:1e:00:02', '172.30.0.2', 0, 'dddd', 'vvvvv2222', 'PIHOLE')]
🔺
17:31:05 [API] Update API starting
17:31:06 [API] Updating table_plugins_history.json file in /front/api
```

> The debug output between the 🔻red arrows🔺 is important for debugging (arrows added only to highlight the section on this page, they are not available in the actual debug log)

you can also forward the log to jokob@duck.com if you are unsure about personal information. Please double check relevant entries are captured and the DEBUG level is enabled.

**Comment by jokob-sk** [comment]
Hi @CrappyTan ,

Thanks for the logs. It seems like even a 10min interval is too short to scan the `'171.17.0.0/16'` VLAN. If you search `⚠ ERROR - TIMEOUT - the plugin ARPSCAN forcefully terminated as timeout reached. Increase TIMEOUT setting and scan interval.` it shows up 1000+ times in your log file. 

```
19:37:38 APR Scan:['sudo', 'arp-scan', '--ignoredups', '--retry=6', '171.17.0.0/16', '--interface=docker0']
19:46:31 [Plugins] ⚠ ERROR - TIMEOUT - the plugin ARPSCAN forcefully terminated as timeout reached. Increase TIMEOUT setting and scan interval.
```

You can try several things:

1. You can try to increase the scan interval further as per my previous message
2. You can try to limit the scan to s smaller range with a different network mask
3. You can try to remove the VLAN completely from the list to test if the other scans are otherwise working

**Comment by CrappyTan** [comment]
In the voice of Homer Simpson - DOH! 
It's a slash-16. That's a bit big. 

I've removed it for now, let's see what happens. 
It was me just being overzealous. 


Will report back

**Comment by CrappyTan** [comment]
Bosh! 
![image](https://github.com/jokob-sk/Pi.Alert/assets/27884877/0cff6f2a-ae48-4efd-a14b-87b7296e3c04)

Devices are now coming alive. 

Thanks for the help!

**Comment by jokob-sk** [comment]
Glad to hear that's starting to come alive :) gl;hf -> closing
