### ISSUE TITLE
Release 24.3.19: ModuleNotFoundError: No module named 'pytz'

### ISSUE THREAD

**Issue by TheCBiker** [jokob-sk/Pi.Alert#596]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

After the update the following error appears.
**ModuleNotFoundError: No module named 'pytz'**
No more devices are displayed.
Data is only available in monitoring.
Portainer shows state unhealthy.
Version 24.2.17 works.
Thank you

### Expected Behavior

New version

### Steps To Reproduce

1. Update container.

### pialert.conf

```python
# General
#---------------------------
LOG_LEVEL='minimal'
LOG_LEVEL__metadata="{}"
TIMEZONE='Europe/Berlin'
TIMEZONE__metadata="{}"
PLUGINS_KEEP_HIST=10000
PLUGINS_KEEP_HIST__metadata="{}"
PIALERT_WEB_PROTECTION=True
PIALERT_WEB_PROTECTION__metadata="{}"
PIALERT_WEB_PASSWORD='********************'
PIALERT_WEB_PASSWORD__metadata="{}"
REPORT_DASHBOARD_URL='http://*********:20211'
REPORT_DASHBOARD_URL__metadata="{}"
UI_LANG='English'
UI_LANG__metadata="{}"
UI_PRESENCE=['online','offline','archived']
UI_PRESENCE__metadata="{}"
UI_MY_DEVICES=['online','offline','archived','new','down']
UI_MY_DEVICES__metadata="{}"
UI_NOT_RANDOM_MAC=[]
UI_NOT_RANDOM_MAC__metadata="{}"
DAYS_TO_KEEP_EVENTS=90
DAYS_TO_KEEP_EVENTS__metadata="{}"
HRS_TO_KEEP_NEWDEV=0
HRS_TO_KEEP_NEWDEV__metadata="{}"
API_CUSTOM_SQL='SELECT * FROM Devices WHERE dev_PresentLastScan = 0'
API_CUSTOM_SQL__metadata="{}"
NETWORK_DEVICE_TYPES=['AP','Gateway','Firewall','Hypervisor','Powerline','Switch','WLAN','PLC','Router','USB LAN Adapter','USB WIFI Adapter','Internet','Repeater']
NETWORK_DEVICE_TYPES__metadata="{}"
```

### docker-compose.yml

```python
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/pi.alert/log:/home/pi/pialert/front/log
      - /portainer/Files/AppData/Config/pi.alert/config:/home/pi/pialert/config
      - /portainer/Files/AppData/Config/pi.alert/db:/home/pi/pialert/db
    environment:
      - TZ=Europe/Berlin      
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
      - PORT=20211
```

### What branch are you running?

Production

### pialert.log

[INSTALL] 🚀 Starting app - navigate to your <server IP>:20211
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/pi/pialert/pialert/__main__.py", line 27, in <module>
    from helper import  filePermissions, timeNowTZ, updateState, get_setting_value
  File "/home/pi/pialert/pialert/helper.py", line 10, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'

### Debug enabled

- [x] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @TheCBiker ,

Can you please read #593 and continue the discussion/troubleshooting over there?

Also, after the below build finishes, can you please try deploying the `pi.alert_dev` container? 

https://github.com/jokob-sk/Pi.Alert/commit/5584512bcc9f1a13db8f5f55041c0f58a55cc9fd

**Comment by jokob-sk** [comment]
duplicate -> closing, please continue the discussion in #593
