### ISSUE TITLE
Permissions fixed when permissions check is sucessful

### ISSUE THREAD

**Issue by dhilltx** [jokob-sk/Pi.Alert#597]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

During startup of the docker container I see:

21:25:08 Permissions check (All should be True)
21:25:08 ------------------------------------------------
21:25:08   /config/pialert.conf |  READ  | True
21:25:08   /config/pialert.conf |  WRITE | True
21:25:08   /db/pialert.db       |  READ  | True
21:25:08   /db/pialert.db       |  WRITE | True
21:25:08 ------------------------------------------------
21:25:08 [Setup] Attempting to fix permissions.
21:25:08 [Setup] Attempting to fix permissions.

Permissions on my /config and /db folders are changed to sshd:82 and it's preventing Syncthing from backing up the folders.

Before start:
drwxr-x--- 2 dhill dhill 4.0K Mar 19 16:25 config
drwxr-x--- 2 dhill dhill 4.0K Mar 17 13:11 db

After start:
drwxr-x--- 2 sshd     82 4.0K Mar 19 17:08 config
drwxr-x--- 2 sshd     82 4.0K Mar 17 13:11 db

### Expected Behavior

If permissions check passes (all being true), the permissions would not be fixed (leaving current permissions intact).

### Steps To Reproduce

Change permissions on /config and /db folder and restart container.

### What branch are you running?

Production

### pialert.log

22:37:20 The container restarted (started). If this is unexpected check https://bit.ly/PiAlertDebug for troubleshooting tips.
22:37:20 

22:37:20 Permissions check (All should be True)
22:37:20 ------------------------------------------------
22:37:20   /config/pialert.conf |  READ  | True
22:37:20   /config/pialert.conf |  WRITE | True
22:37:20   /db/pialert.db       |  READ  | True
22:37:20   /db/pialert.db       |  WRITE | True
22:37:20 ------------------------------------------------
22:37:20 [Setup] Attempting to fix permissions.
22:37:20 [Setup] Attempting to fix permissions.
22:37:20 [Database] Opening DB
22:37:20 [upgradeDB] Re-creating Settings table
22:37:20 [upgradeDB] Re-creating Pholus_Scan table
22:37:20 [upgradeDB] Re-creating Parameters table
22:37:20 [Config] reading config file

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by dhilltx** [comment]
Should have mentioned I have:

HOST_USER_GID=1000
HOST_USER_ID=1000

1000 is the correct ID of the user:group I set on the /config and /db folders before the permissions check changes them to sshd:82

![usg_id](https://github.com/jokob-sk/Pi.Alert/assets/45803631/56a99e1f-1311-4c97-9e8f-bbbd909c38a4)

**Comment by vladaurosh** [comment]
Hi @dhilltx 

Latest pialert version has changed behaviour. There's no need to set owner and group for those 2 directories, pialer container will change it to 101:82 as that's needed by nginx webserver running inside.

**Comment by BambamNZ** [comment]
Also noticed this change in behavior with changes to the Owner and Group of the directories.
This has some unintended impact on my side, access via Samba shared to the folders are lost due to permission miss-match 

Post change: 
drwxr-x---+ 2 systemd-network 82 4.0K Mar 20 12:23 config
drwxr-x---+ 2 systemd-network 82 4.0K Mar 20 12:22 db

**Comment by vladaurosh** [comment]
Probably this should be added to the list of breaking changes for this release @jokob-sk

**Comment by jokob-sk** [comment]
@vladaurosh do you agree with this wording:

> This version has changed the behavior of how the ownership of the `/config` and `/db` folders is handled. There's no need to set owner and group for those directories, as the container will change it to `101:82` as that's needed by the nginx webserver running inside. Thus the `HOST_USER_ID` and `HOST_USER_GID` variables became obsolete.

**Comment by jokob-sk** [comment]
@dhilltx I can try to remove the forced permissions change, and prepare a `pi.alert_dev` build, however I need someone to extensively test the other parts of the app. Let me know if you are interested in testing, otherwise I'm inclined to keep the current approach as the DB and config are also accessed via other means. I know it should only be by the front end, but I don't want to risk other functionality to break (settings, CSV export/import, front-end triggered actions, such as ad-hoc scans, etc.).

**Comment by dhilltx** [comment]
I will try a workaround to solve my backup problem and may have found another issue with accessing via reverse proxy. Give me today to continue testing and I will get back to you by tomorrow, I was hoping this was a simple correction or my mistake vs. something new by design, appreciate the quick feedback.

**Comment by vladaurosh** [comment]
> @vladaurosh do you agree with this wording:
> 
> > This version has changed the behavior of how the ownership of the `/config` and `/db` folders is handled. There's no need to set owner and group for those directories, as the container will change it to `101:82` as that's needed by the nginx webserver running inside. Thus the `HOST_USER_ID` and `HOST_USER_GID` variables became obsolete.

Looks good to me.

**Comment by jokob-sk** [comment]
@vladaurosh Release notes updated - thanks for all the help 🙏
