### ISSUE TITLE
Manual option to mark a device as random mac device

### ISSUE THREAD

**Issue by TheCBiker** [jokob-sk/Pi.Alert#604]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have a device (more precisely a Wahoo Elemnt Roam cycling computer) that has an Android operating system with a random MAC. Unfortunately, when the device is automatically added, it is not recognized that it is a random MAC device. So it is added again every time you turn it on. Can you add an option to manually define a device as a random MAC device to prevent this? Thank you

### Describe the solution you'd like

Manual option to mark a device as random mac device

### Describe alternatives you've considered

No solution other than deleting it manually

### Anything else?

This affects all Wahoo cycling computers that connect to WiFi through which random mac cannot be deactivated

**Comment by jokob-sk** [comment]
Hi @TheCBiker ,

The `Is random MAC` property doesn't prevent the device from being re-added, it's only a visual indicator that this device has a Random MAC. 

If you can the simplest option is to turn off randomized MACs for your network on the device: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/RANDOM_MAC.md

In a similar situation. I'm explaining why it's not easy to detect and link devices with changing MAC addresses in this thread:

https://github.com/jokob-sk/Pi.Alert/issues/217

A possibility is to use the IP address for the existing devices lookup. How about this solution?

1. A device is marked to have a Random MAC
2. During the scan I look-up existing devices 
3. There is an IP match in the newly discovered devices and the existing device with the same IP is marked as static IP & random MAC
4. I replace the MAC of the newly discovered device with the old, previously detected MAC address

The limitation of such an approach is that the MAC address becomes out-of-sync with the real one, which could have unintended consequences elsewhere. I could mark the out-of-synch MAC somehow visually. 

Please let me know your thoughts. I'm not promising anything, just thinking about a possible approach here. 

Thanks,
j

**Comment by TheCBiker** [comment]
Thanks for the explanations.
The device is certainly not marked with a random MAC.
My router also recognizes the device as a new device and always assigns a new IP address. Very annoying.
Unfortunately, there is no way to deactivate the Random Mac function. The device is self-contained.
Only the device name is always the same.
Maybe you can blacklist such a device based on the device name or ignore it when scanning again.

Thank you

**Comment by leiweibau** [comment]
Hello,

This is a text from the support page from wahoo
> ELEMNT, BOLT, and ROAM use dynamic, randomized MAC addresses for privacy and security purposes as prescribed in [Android documentation](https://source.android.com/devices/tech/connect/wifi-mac-randomization), making them incompatible with networks utilizing MAC address filters or whitelists.

I would also like to think about the problem, as it might also affect me at some point.

@jokob-sk

> There is an IP match in the newly discovered devices and the existing device with the same IP is marked as static IP & random MAC

Since the IP changes, the IP will probably also change if DHCP is used. You would therefore have to limit yourself exclusively to the name. However, the name should not be changed by @TheCBiker in Pi.Alert, as otherwise it would no longer match the "real" device name. But what happens if @TheCBiker restarts the wahoo device after a software update, for example? Does the device then still have the same name, or does it change at the request of the DHCP server (e.g. wahoodevice becomes wahoodevice-1)?
It's not that easy 🤔

**Comment by TheCBiker** [comment]
Hi@leiweibau

The device name as it connects to my Fritzbox always the same and does not change even after an update.
The Wahoo connects to the router with the name such as "android-e73f08815e6b8905". Of course you get a new IP from DHCP every time you connect because the MAC changes. This cannot be solved. So it should be enough if you just filter by name.

**Comment by jokob-sk** [comment]
@leiweibau thanks for the insights - it's definitely not an easy one to solve
@TheCBiker is there any pattern in the random MAC addresses we could leverage? To understand things correctly - the name doesn't change at all?

**Comment by TheCBiker** [comment]
@jokob-sk Thank you,

The first 3 bytes of the MAC address are always the same. Just as is usual as a manufacturer identification. You could start there.
The name doesn't change either. I don't have any knowledge of how to implement this.

**Comment by TheCBiker** [comment]
@ameer1234567890 

That's correct. I just want to explicitly exclude a device as a new device after a new scan and you could start with the MAC address or the device name, for example.

**Comment by jokob-sk** [comment]
Hummm, @TheCBiker  if it's the MAC address that you want to use there is already a setting to ignore new devices with certain MAC addresses. Try using the `NEWDEV_ignored_MACs` setting and see if this helps achieve your use case:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/f03235e3-9137-4a6e-bbe5-dd6a04776d99)

I could add a setting to ignore device names, but if the existing settings/options are already sufficient, I'd like to keep the new device discovery logic as it's already a bit convoluted with the various edge cases and overrides.

**Comment by TheCBiker** [comment]
Thanks for the tip. That could be the solution.
I'll try that. I.e. if the device has been recognized once and then excluded in the Mac filter, does it continue to appear in the device list? But the device will probably no longer appear in the presence list?

**Comment by jokob-sk** [comment]
Yes, if I remember correctly when I implemented it that's how it should work.

**Comment by TheCBiker** [comment]
There seems to be no other option than to exclude the device completely using a MAC filter.
That already works. It's not that tragic. As far as I'm concerned, this case can be closed.
Thank you

**Comment by jokob-sk** [comment]
Cool, will close this then. Just FYI there are also Notification specific settings that you can play around with too:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/bdc3d604-2a14-47a0-a51c-a78f5b22b09c)

Let me know if you'd prefer something more user friendly than SQL queries as I'm bit on the fence if this isn't too difficult to configure.
