### ISSUE TITLE
Pi Alert shuts down after startup

### ISSUE THREAD

**Issue by killtux** [jokob-sk/Pi.Alert#607]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

> 
<img width="1316" alt="image" src="https://github.com/jokob-sk/Pi.Alert/assets/36768145/80df1cf7-f4dd-441f-9bff-2d0836a0bda7">

### Expected Behavior

normal startup

### Steps To Reproduce

i upgraded to 24.3.19 over the Synology Container Manger and and wont startup anymore.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @killtux ,

Can you please follow 1 & 2 from this guide and post the startup and pialert.log so I can provide more help?

https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_TIPS.md

Thanks,
j

**Comment by silicon11** [comment]
I had this issue, you have to delete the old image and container and re-add it. When I went to redownload the image I noticed the image name changed to jokobsk/pialert_ngx thought that was odd.

**Comment by jokob-sk** [comment]
@silicon11 that's one of the test images, the official production image is still: https://hub.docker.com/r/jokobsk/pi.alert
From the sounds of it re-creating the image helped so I think the issue might have been resolved even when using a fresh prod image.

**Comment by jokob-sk** [comment]
Glad to hear @killtux it's working again. I hope you were able to restore your setup in the end. 

Closing as resolved
