### ISSUE TITLE
Network Overview Loading

### ISSUE THREAD

**Issue by edd080** [jokob-sk/Pi.Alert#608]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

When I click on the Network Overview Panel it remains in a loading state.
![Screenshot 2024-03-26 071045](https://github.com/jokob-sk/Pi.Alert/assets/158288829/b7e20a28-45b7-471e-85ac-2f36f1be27ea)

### Expected Behavior

I should be able to see the Network Devices.

### Steps To Reproduce

It seems to have happened after updating to 24.2.17, for some reason I had no issues before this version.

### docker-compose.yml

```python
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./data/config:/home/pi/pialert/config
      - ./data/db:/home/pi/pialert/db
      - ./data/logs:/home/pi/pialert/front/log
    environment:
      - TZ=Europe/XXXX
      - PORT=20211
```

### What branch are you running?

Production

### pialert.log

[pialertlog.txt](https://github.com/jokob-sk/Pi.Alert/files/14754195/pialertlog.txt)

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by edd080** [comment]
Attaching pialert conf file.
[pialertconf.txt](https://github.com/jokob-sk/Pi.Alert/files/14754205/pialertconf.txt)

**Comment by jokob-sk** [comment]
Hi @edd080 ,

Can you please verify you followed the network setup guide?

https://github.com/jokob-sk/Pi.Alert/blob/main/docs/NETWORK_TREE.md

If you still have issues, try deleting the Internet root node and let the app rediscover it. Usually, issues occur if people assign the root node to itself.

If the above doesn't work, please check the browser dev console and post any error you receive on the network page.

Thanks in advance,
j

**Comment by edd080** [comment]
Thank you for your reply, the network overview was working fine for me at one point, so I am not sure what is causing this to load continuously. I deleted the root internet node but this did not make any difference, i then deleted the other nodes, switches and access points so as to clear everything but it is still doing the same. I do not wish to delete the rest of the devices and start from scratch, is there anything else I can do please?

**Comment by edd080** [comment]
> Hi @edd080 ,
> 
> Can you please verify you followed the network setup guide?
> 
> https://github.com/jokob-sk/Pi.Alert/blob/main/docs/NETWORK_TREE.md
> 
> If you still have issues, try deleting the Internet root node and let the app rediscover it. Usually, issues occur if people assign the root node to itself.
> 
> If the above doesn't work, please check the browser dev console and post any error you receive on the network page.
> 
> Thanks in advance, j

Thank you for your reply, the network overview was working fine for me at one point, so I am not sure what is causing this to load continuously. I deleted the root internet node but this did not make any difference, i then deleted the other nodes, switches and access points so as to clear everything but it is still doing the same. I do not wish to delete the rest of the devices and start from scratch, is there anything else I can do please?

**Comment by jokob-sk** [comment]
Could you please try to delete the browser cache or try using a different browser? If that doesn't work, please check the browser dev console and post any error you receive on the network page.

**Comment by jokob-sk** [comment]
PLease also note that there are weekly backups of your devices configuration in the /config folder if you need to restore an earlier version of your devices setup: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/BACKUPS.md

**Comment by edd080** [comment]
> Could you please try to delete the browser cache or try using a different browser? If that doesn't work, please check the browser dev console and post any error you receive on the network page.

Its finally working! 😅😁😁 Thankyou so much, deleting the root node, parent devices and giving it time to discover itself again did the trick, the network overview is working fine now.
Thank you once again for your help.
Keep it up! 👍🏻

**Comment by jokob-sk** [comment]
glad to hear that :)

**Comment by PrzemekSkw** [comment]
Hello @jokob-sk I have similar situation with my NetAlertX instance on unraid.
I have fresh install and when I change icon or name I have to wait about 2 minutes because of Loading on Devices page.
I try with different fresh installed browsers.
Regards.
