### ISSUE TITLE
Provide support for reverse proxy

### ISSUE THREAD

**Issue by gkovacsp** [jokob-sk/Pi.Alert#63]
Help setting up the service behind a reverse proxy by adding support for URL Base, e.g. mydomain.com/pialert

**Comment by jokob-sk** [comment]
Hey,

Do you have any example docker images where I can peek on how to do this? I don't have a reverse proxy setup on my network to test this...

**Comment by gkovacsp** [comment]
I use sonarr, radarr, prowlarr from the linuxserver.io fleet and they all support.

Sonarr's details: https://hub.docker.com/r/linuxserver/sonarr
Sonarr's github: https://github.com/Sonarr/Sonarr

**Comment by jokob-sk** [comment]
@gkovacsp - thanks for the examples, I had a look, but I couldn't determine if there is anything specific which would make those containers reverse-proxy compatible (it might be a bit over my head).

According to the contribution of @0x5f3 this should be a bit simpler if the base url doesn't rely on a custom path, here `/pialert`. He submitted a pull request which I merged manually. Can you try to deploy the latest image to see if this update makes setting up a reverse proxy possible?

**Comment by gkovacsp** [comment]
> @gkovacsp - thanks for the examples, I had a look, but I couldn't determine if there is anything specific which would make those containers reverse-proxy compatible (it might be a bit over my head).
> 
> According to the contribution of @0x5f3 this should be a bit simpler if the base url doesn't rely on a custom path, here `/pialert`. He submitted a pull request which I merged manually. Can you try to deploy the latest image to see if this update makes setting up a reverse proxy possible?

It did not help. This is the nginx reverse proxy I use to point pialert to mydomain.com/pialert

```
location /pialert {
    return 301 $scheme://$host/pialert/;
}

location ^~ /pialert/ {
     include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app 192.168.1.95;
    set $upstream_port 20211;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    rewrite /pialert(.*) $1 break;
    proxy_hide_header X-Frame-Options;
}
```

Loading the 
`mydomain.com/pialert `
page it goes to 
`mydomain.com/devices.php `
instead of 
`mydomain.com/pialert/devices.php`

I'm not a developer but the base path setting would mean that it is always applied to the links so it would use it always before the actual page
`mydomain.com/pialert/devices.php`

In sonarr it is called URL base and you set it like the following:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/1654787/183035328-d5a11f8a-10ba-42c2-97a9-8dd976f6a9b9.png">

**Comment by jokob-sk** [comment]
Hummm... Regrettably I really don't know how a reverse proxy works, so if you have an idea how to make the image compatible, feel free to submit a pull request. I keep this issue open for anyone happy to contribute.

**Comment by jokob-sk** [comment]
Thanks a ton @0x5f3 ! I will have a look and if there is nothing wrong on my side I'll publish it and @gkovacsp can test it on his setup

**Comment by jokob-sk** [comment]
No issues on my end so publishing a new image on DockerHub - give it ~10 minutes

@0x5f3 you are a ⭐thanks for the help :)

**Comment by gkovacsp** [comment]
> Thanks a ton @0x5f3 ! I will have a look and if there is nothing wrong on my side I'll publish it and @gkovacsp can test it on his setup

Yes it works!
Thank you
