### ISSUE TITLE
"no such column: dev_Network_Node_MAC" after last docker container update two days ago

### ISSUE THREAD

**Issue by pbek** [jokob-sk/Pi.Alert#66]
When editing devices I got a SQL error message when saving the device:
`no such column: dev_Network_Node_MAC`

I had to add the two missing columns:

```SQL
alter table Devices
    add dev_Network_Node_MAC STRING(50);
alter table Devices
    add dev_Network_Node_port INTEGER;
```

Oddly enough I couldn't find those columns in the git repository nor in https://github.com/pucherot/Pi.Alert.

**Comment by jokob-sk** [comment]
Hey!

Thanks for reporting!

These should be added when accessing the Network tab, but I'll add them into the startup instead so people don't have to navigate to the Network tab.

**Comment by pbek** [comment]
Thank you! I wonder... Where is the code that is using this column? I was trying to figure out what else in the DB changed and wasn't able to find `dev_Network_Node_MAC` anywhere.

**Comment by jokob-sk** [comment]
Well, the thing is that pucherot originally distribute the DB only as a file, not as a setup script which would re-create or upgrade the DB when new features are added. So what I'm trying to do is that if some new functionality is added, the DB gets upgraded in the code so it's backwards compatible with already available deployments. And as you might imagine, this is a bit tricky :) 

Trying my best here to keep this image pretty fresh and backwards compatible. 

Anyway... most of the DB upgrades are performed here: https://github.com/jokob-sk/Pi.Alert/blob/c99f1a6e0d46433e35aee623ff973f8e9b042e08/back/pialert.py#L1521

So I just  need to (hopefully) migrate the code from here: https://github.com/jokob-sk/Pi.Alert/blob/c99f1a6e0d46433e35aee623ff973f8e9b042e08/front/network.php#L28 to the above location...


Phew, hope this makes sense :)

**Comment by jokob-sk** [comment]
So actually I didn't answer your question - the only way to figure out what has changed (due to the setup which I described above) is in some cases to use a DB comparison tool.

**Comment by pbek** [comment]
> Well, the thing is that pucherot originally distribute the DB only as a file,

I thought as much... 😁 

>  $sql = 'ALTER TABLE "Devices" ADD "dev_Network_Node_MAC" INTEGER'; 

Ah, there it is. <https://github.com/jokob-sk/Pi.Alert/search?q=dev_Network_Node_MAC> is still not able to find that string. Very odd...

> So actually I didn't answer your question - the only way to figure out what has changed (due to the setup which I described above) is in some cases to use a DB comparison tool.

Thank you very much for making it as easy as it is now! 👍🏻

**Comment by jokob-sk** [comment]
Trying lol, give me a couple of hours to implement this, test this on a blank DB and hopeful publish an updated docker image in the next ~2h if real life doesn't get into the way (definitely tomorrow the latest :))

**Comment by pbek** [comment]
Very hard commitment for free open source software you are making! 😁 

> if real life doesn't get into the way

What? Real life? Does that really exist somewhere? Children stories! 😆

**Comment by jokob-sk** [comment]
> Very hard commitment for free open source software you are making! 😁

I use plenty of FOSS myself so it's a nice way to give back if time allows :)

> What? Real life? Does that really exist somewhere? Children stories! 😆

😂

**Comment by pbek** [comment]
> I use plenty of FOSS myself so it's a nice way to give back if time allows :)

That's very true! You are doing great!

**Comment by jokob-sk** [comment]
alright, should be fixed in https://github.com/jokob-sk/Pi.Alert/commit/42363879e1b7916d572c61dd732ee52b2491353a

A new image should be available on the DockerHub in about 10 minutes

Cheers for reporting, the column had actually an incorrect type, so the Network functionality was unusable :/ Had to create a new column as it's impossible to alter (even drop) existing SQLite columns. Let me know if there are further issues!

**Comment by jokob-sk** [comment]
Just let me know if it doesn't work, I may have missed stuff

**Comment by pbek** [comment]
Looking good...
But the login dialog UI seems now broken...
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/1798101/182843426-a286427d-04e2-4be4-8d1a-eae2b55966ef.png">

**Comment by jokob-sk** [comment]
pushing out a fix - English language strings were missing: https://github.com/jokob-sk/Pi.Alert/commit/04044bfec5deaa6bf27d113db4d90b92b36e86df

**Comment by pbek** [comment]
You are fast 😁

**Comment by jokob-sk** [comment]
skipped the testing, but should be fine :)

**Comment by pbek** [comment]
Login UI fixed now, thank you! 😁

**Comment by jokob-sk** [comment]
thanks for testing 💯 :)
