### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by bonelifer** [jokob-sk/Pi.Alert#69]
After pulling the new image, I was presented with a password login page. The default password from the README didn't work. And the shell script mentioned at the bottom of the page wasn't present in the image when I went to the console in Portainer. I was able to add the variable to the config file and set it to false. Maybe default behavior when this variable isn't present should be false by default. That and the shell script should be in the containers path to make it easier to use.

**Comment by leiweibau** [comment]
Regarding the login page: This was fixed, came back and is now fixed again (https://github.com/leiweibau/Pi.Alert/commit/c212193d87c16fc0968e4a673517b09518e23338). If the parameter "PIALERT_WEB_PROTECTION" is missing in the configuration file, you will now be logged in automatically, again.
As for the Docker image, I am not responsible. Give [jokob-sk](https://github.com/jokob-sk) the time to fix it in his dockerimage

**Comment by jokob-sk** [comment]
thanks @leiweibau for the fix and @bonelifer for reporting..the image should be updated in about ~15min from posting this message
