### ISSUE TITLE
GMT displayed instead of TZ

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/Pi.Alert#7]
by @[adammckay](https://github.com/adammckay) 

This is a great effort! Thank you for your dedication to getting PiAlert in a good container.

When I set my environment TZ=America/New_York, it works fine. I can bash in and see that the date command yields:
Fri Jun 10 06:39:10 EDT 2022

So it seems all is working correctly there. But PiAlert itself still displays everything in GMT. All date/time columns are GMT. Forgive me if this is more of a PiAlert issue. I'm not sure but it would be nice to fix or know how to fix that.

**Comment by Macleykun** [comment]
believe this isn't docker related, if ya would specify the env in bash and run the app as is, it would still show GMT i assume

**Comment by adammckay** [comment]
it is showing EDT as it should when I bash in.

**Comment by Viper7000** [comment]
I have same problem!
I set TZ=Europe/Kiev
Then I run bash in container I have "Thu Jul  7 12:16:32 EEST 2022"!  EEST is my timezone. Bat in PiAlert time is GMT. Can you fix this problem?

**Comment by jokob-sk** [comment]
I'll have it on my todo list to try to figure this out, but this will be probably app related. Will comment/close this issue once solved for anyone following this

**Comment by jokob-sk** [comment]
This should be fixed in the latest image. The issue was cron running in GMT instead of the local (container specified) TZ. 

Found a workaround (not sure if the nicest) to specify the [TZ in the crontab](https://github.com/jokob-sk/Pi.Alert/blob/4472efa6c49a89eaa4e813b60a11fbcee66b5c03/install/pialert.cron#L10). I also connected this to the environment variable `TZ`, so if you are setting it already (e.g. in your [docker-compose](https://github.com/jokob-sk/Pi.Alert/blob/4472efa6c49a89eaa4e813b60a11fbcee66b5c03/docker-compose.yml#L13)) you should be good once you download the latest image. 

I hope nothing else got broken (FYI the events view might get a bit scrambled as it doesn't update past entries in the DB).

**Comment by adammckay** [comment]
Thanks!  The time thing was driving me so crazy I stopped using it.  This
project is great and I feel like it 'just works'!
