### ISSUE TITLE
Add Apprise to leverage it's notification platform options

### ISSUE THREAD

**Issue by bonelifer** [jokob-sk/Pi.Alert#71]
Add Apprise to leverage it's notification platform options. Allow to set multiple notification types. So for instance email + gotify.
https://github.com/caronc/apprise

**Comment by jokob-sk** [comment]
Hi! Thanks for the suggestion.

For now there are: email, Pushsafer and NTFY as options for notifications. Will consider it, but I lean more towards a more generic approach with webhooks/MQTT. You probably can already automate most of integrations with email + n8n/nodeRed or a similar automation tool. 

In general I want to keep the image on the smaller side.

**Comment by jokob-sk** [comment]
Will be probably part of #49

**Comment by jokob-sk** [comment]
FYI Added Apprise support in the latest image
