### ISSUE TITLE
error url 

### ISSUE THREAD

**Issue by sephirothac** [jokob-sk/Pi.Alert#79]
Hi, 

Thank you for your work, but since the last update after authentication we are redirected to a url http://XXXXXXXXX:20211/pialert/devices.php which returns us to a blank page with error file no found forced to delete pialert/ of url to access the dashboard.

Thanks for your help.

**Comment by jokob-sk** [comment]
Hi,

Thanks for the feedback :)

Yes, it's mentioned in the readme that the /pialert part of the URL is not
needed anymore. It was done when the image was migrated to nginx. If you
know how to enable it to serve old URLs please do submit a pull request. I
don't think it's a major issue, but happy to approve a pull request is
available.

Thanks!

**Comment by sephirothac** [comment]
Thank you for your feedback, sorry I didn't see that you reported it on the Readme.

Thanks again for your project

**Comment by jokob-sk** [comment]
Hey,

All good! It's valid feedback :)

Let me know if changing the URL is a big deal and I could implement a
redirect from the OLD > NEW (I just don't know nginx deeply enough, so I 'd
have to do research...), I just thought the time is better spent elsewhere
(new features) as everyone will eventually figure it out by hopefully
reading the README.
