### ISSUE TITLE
Shoutrrr support for notifications

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/Pi.Alert#8]

**Comment by Final-Hawk** [comment]
Webhooks may also be a good alternative way of delivering notifications. Looks like it has already been [implemented in this fork of piAlert](https://github.com/fosspill/Pi.Alert)

**Comment by jokob-sk** [comment]
Yeah, it leverages NTFY and the implementation is pretty straightforward if you want to give it a go: https://github.com/fosspill/Pi.Alert/blob/3654a07e3cceafdf5e9ebc72c8c6535ec7c6aaab/back/pialert.py#L1523

Otherwise I'll wait until you finish your testing on the arp-scan settings and I'll probably have a look over the weekend/later this week

**Comment by Final-Hawk** [comment]
Seems simple to implement, I will work on that when i get a moment.
Though due to my limited knowledge in building docker images, I don't know how to add additional python packages. The function requires the requests python package.  Would it be as simple as adding a pip command to the Dockerfile or is there a more efficient way?

**Comment by jokob-sk** [comment]
Hummm true.... the package is definitely missing, running this yields `nope`

`python -m requests |& grep -q 'No module named' && echo 'Nope' || echo 'Yup'`

Not sure if to put the installation of the missing python package into the Dockerfile or the start.sh script.

@Macleykun Any suggestions?

I think the Dockerfile makes more sense, but I'm easily convinced otherwise

**Comment by Macleykun** [comment]
You want to do any installation during the build of the image which is the dockerfile!

**Comment by jokob-sk** [comment]
merged: NTFY PUSHSAFER in https://github.com/jokob-sk/Pi.Alert/tree/leiweibau-merge-2022-07-24_1, will switch it to main after some additional work probably in the next few hours
