### ISSUE TITLE
Maintenance tools & crontab

### ISSUE THREAD

**Issue by manageseverin** [jokob-sk/Pi.Alert#85]
Hello and thanks for the tool.
I'm running it on a virtual ubuntu 22.01 and faced several issues. If I install it under my ubuntu user ( with root privileges ) cronjob refuse to execute the "python3 ~/pialert/back/pialert.py 1" and other commands.
I uninstalled it, switched to root (sudo -i) and installed it as root in the root user folder and the cronjob run fine and it updates the scans by itself.

Second issue is that my Maintenance tools page is blank.

Thanks

**Comment by jokob-sk** [comment]
Hi there!

Thanks for using it 😀

Could you please let me know how you have configured your docker container
so I can try to help? Did you follow the setup instructions in the
dockerfiles/readme?


Regarding the maintenance tasks, can you please send me a screenshot of the
network tab/errors in the console if there are any?

Cheers in advance!
