### ISSUE TITLE
PHP Error pia_lang_selected + pia_skin_test

### ISSUE THREAD

**Issue by WalterWampe** [jokob-sk/Pi.Alert#93]
Hi, I was wondering what took up that much space on my vm, when I realized that it was the
/var/log/nginx/error.log of my inside pialert container havin reached almost 250GB!

Here are the thrown errors:

> tail -f error.log 
2022/09/18 13:57:28 [error] 50#50: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: login in /home/pi/pialert/front/devices.php on line 13" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /devices.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 13:57:29 [error] 50#50: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: action in /home/pi/pialert/front/index.php on line 4PHP message: PHP Notice:  Undefined variable: pia_skin_selected in /home/pi/pialert/front/index.php on line 23PHP message: PHP Notice:  Undefined variable: pia_lang_selected in /home/pi/pialert/front/index.php on line 28" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 13:57:29 [error] 50#50: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_skin_selected in /home/pi/pialert/front/php/templates/header.php on line 34PHP message: PHP Notice:  Undefined variable: pia_lang_selected in /home/pi/pialert/front/php/templates/header.php on line 39PHP message: PHP Notice:  Undefined variable: ENABLED_DARKMODE in /home/pi/pialert/front/php/templates/header.php on line 97" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /devices.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 13:57:29 [error] 50#50: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  file(../../../config/pialert.conf): failed to open stream: No such file or directory in /home/pi/pialert/front/php/server/db.php on line 13PHP message: PHP Warning:  preg_grep() expects parameter 2 to be array, bool given in /home/pi/pialert/front/php/server/db.php on line 14PHP message: PHP Warning:  array_values() expects parameter 1 to be array, null given in /home/pi/pialert/front/php/server/db.php on line 14PHP message: PHP Notice:  Trying to access array offset on value of type null in /home/pi/pialert/front/php/server/db.php on line 15PHP message: PHP Notice:  Undefined offset: 1 in /home/pi/pialert/front/php/server/db.php on line 16PHP message: PHP Notice:  date_default_timezone_set(): Timezone ID '' is invalid in /home/pi/pialert/front/php/server/db.php on line 17" while reading upstream, client: 192.168.1.250, server: , request: "GET /devices.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 13:57:29 [error] 50#50: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_lang_selected in /home/pi/pialert/front/php/server/devices.php on line 21" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /php/server/devices.php?action=getDevicesList&status=all&_=1663502249546 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 13:57:29 [error] 50#50: *10 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_lang_selected in /home/pi/pialert/front/php/server/devices.php on line 21" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /php/server/devices.php?action=getDevicesTotals HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 13:58:02 [error] 50#50: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_skin_selected in /home/pi/pialert/front/php/templates/header.php on line 34PHP message: PHP Notice:  Undefined variable: pia_lang_selected in /home/pi/pialert/front/php/templates/header.php on line 39PHP message: PHP Notice:  Undefined variable: ENABLED_DARKMODE in /home/pi/pialert/front/php/templates/header.php on line 97" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 13:58:02 [error] 50#50: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 0 in /home/pi/pialert/front/maintenance.php on line 113PHP message: PHP Warning:  Use of undefined constant submit - assumed 'submit' (this will throw an Error in a future version of PHP) in /home/pi/pialert/front/maintenance.php on line 118PHP message: PHP Warning:  Use of undefined constant submit - assumed 'submit' (this will throw an Error in a future version of PHP) in /home/pi/pialert/front/maintenance" while reading upstream, client: 192.168.1.250, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 13:58:02 [error] 50#50: *8 FastCGI sent in stderr: "php on line 146PHP message: PHP Notice:  Undefined variable: pia_lang_test in /home/pi/pialert/front/maintenance.php on line 237" while reading upstream, client: 192.168.1.250, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 13:58:02 [error] 50#50: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_skin_test in /home/pi/pialert/front/maintenance.php on line 265" while reading upstream, client: 192.168.1.250, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 13:59:01 [error] 50#50: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_skin_selected in /home/pi/pialert/front/php/templates/header.php on line 34PHP message: PHP Notice:  Undefined variable: pia_lang_selected in /home/pi/pialert/front/php/templates/header.php on line 39PHP message: PHP Notice:  Undefined variable: ENABLED_DARKMODE in /home/pi/pialert/front/php/templates/header.php on line 97" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /devices.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/maintenance.php"
2022/09/18 13:59:01 [error] 50#50: *8 FastCGI sent in stderr: "PHP message: PHP Warning:  file(../../../config/pialert.conf): failed to open stream: No such file or directory in /home/pi/pialert/front/php/server/db.php on line 13PHP message: PHP Warning:  preg_grep() expects parameter 2 to be array, bool given in /home/pi/pialert/front/php/server/db.php on line 14PHP message: PHP Warning:  array_values() expects parameter 1 to be array, null given in /home/pi/pialert/front/php/server/db.php on line 14PHP message: PHP Notice:  Trying to access array offset on value of type null in /home/pi/pialert/front/php/server/db.php on line 15PHP message: PHP Notice:  Undefined offset: 1 in /home/pi/pialert/front/php/server/db.php on line 16PHP message: PHP Notice:  date_default_timezone_set(): Timezone ID '' is invalid in /home/pi/pialert/front/php/server/db.php on line 17" while reading upstream, client: 192.168.1.250, server: , request: "GET /devices.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/maintenance.php"
2022/09/18 13:59:02 [error] 50#50: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_lang_selected in /home/pi/pialert/front/php/server/devices.php on line 21" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /php/server/devices.php?action=getDevicesTotals HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 13:59:02 [error] 50#50: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_lang_selected in /home/pi/pialert/front/php/server/devices.php on line 21" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /php/server/devices.php?action=getDevicesList&status=all&_=1663502342237 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 14:00:02 [error] 50#50: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_lang_selected in /home/pi/pialert/front/php/server/devices.php on line 21" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /php/server/devices.php?action=getDevicesTotals HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 14:01:03 [error] 50#50: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_lang_selected in /home/pi/pialert/front/php/server/devices.php on line 21" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /php/server/devices.php?action=getDevicesTotals HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 14:02:03 [error] 50#50: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_lang_selected in /home/pi/pialert/front/php/server/devices.php on line 21" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /php/server/devices.php?action=getDevicesTotals HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 14:03:04 [error] 50#50: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_lang_selected in /home/pi/pialert/front/php/server/devices.php on line 21" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /php/server/devices.php?action=getDevicesTotals HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 14:03:29 [error] 50#50: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_skin_selected in /home/pi/pialert/front/php/templates/header.php on line 34PHP message: PHP Notice:  Undefined variable: pia_lang_selected in /home/pi/pialert/front/php/templates/header.php on line 39PHP message: PHP Notice:  Undefined variable: ENABLED_DARKMODE in /home/pi/pialert/front/php/templates/header.php on line 97" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 14:03:29 [error] 50#50: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 0 in /home/pi/pialert/front/maintenance.php on line 113PHP message: PHP Warning:  Use of undefined constant submit - assumed 'submit' (this will throw an Error in a future version of PHP) in /home/pi/pialert/front/maintenance.php on line 118PHP message: PHP Warning:  Use of undefined constant submit - assumed 'submit' (this will throw an Error in a future version of PHP) in /home/pi/pialert/front/maintenance" while reading upstream, client: 192.168.1.250, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 14:03:29 [error] 50#50: *8 FastCGI sent in stderr: "php on line 146PHP message: PHP Notice:  Undefined variable: pia_lang_test in /home/pi/pialert/front/maintenance.php on line 237" while reading upstream, client: 192.168.1.250, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 14:03:29 [error] 50#50: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_skin_test in /home/pi/pialert/front/maintenance.php on line 265" while reading upstream, client: 192.168.1.250, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/devices.php"
2022/09/18 14:03:33 [error] 50#50: *26 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_skin_selected in /home/pi/pialert/front/php/templates/header.php on line 34PHP message: PHP Notice:  Undefined variable: pia_lang_selected in /home/pi/pialert/front/php/templates/header.php on line 39PHP message: PHP Notice:  Undefined variable: ENABLED_DARKMODE in /home/pi/pialert/front/php/templates/header.php on line 97" while reading response header from upstream, client: 192.168.1.250, server: , request: "POST /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/maintenance.php"
2022/09/18 14:03:33 [error] 50#50: *26 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 0 in /home/pi/pialert/front/maintenance.php on line 113PHP message: PHP Warning:  Use of undefined constant submit - assumed 'submit' (this will throw an Error in a future version of PHP) in /home/pi/pialert/front/maintenance.php on line 118PHP message: PHP Warning:  Use of undefined constant submit - assumed 'submit' (this will throw an Error in a future version of PHP) in /home/pi/pialert/front/maintenance" while reading upstream, client: 192.168.1.250, server: , request: "POST /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/maintenance.php"
2022/09/18 14:03:33 [error] 50#50: *26 FastCGI sent in stderr: "php on line 146PHP message: PHP Warning:  unlink(../db//setting_language_en_us): No such file or directory in /home/pi/pialert/front/maintenance.php on line 151PHP message: PHP Warning:  unlink(../db//setting_language_de_de): No such file or directory in /home/pi/pialert/front/maintenance.php on line 151PHP message: PHP Warning:  unlink(../db//setting_language_es_es): No such file or directory in /home/pi/pialert/front/maintenance.php on line 151" while reading upstream, client: 192.168.1.250, server: , request: "POST /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/maintenance.php"
2022/09/18 14:03:33 [error] 50#50: *26 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_skin_test in /home/pi/pialert/front/maintenance.php on line 265" while reading upstream, client: 192.168.1.250, server: , request: "POST /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/maintenance.php"
2022/09/18 14:03:34 [error] 50#50: *26 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_skin_selected in /home/pi/pialert/front/php/templates/header.php on line 34PHP message: PHP Notice:  Undefined variable: ENABLED_DARKMODE in /home/pi/pialert/front/php/templates/header.php on line 97" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211"
2022/09/18 14:03:34 [error] 50#50: *26 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 0 in /home/pi/pialert/front/maintenance.php on line 113PHP message: PHP Warning:  Use of undefined constant submit - assumed 'submit' (this will throw an Error in a future version of PHP) in /home/pi/pialert/front/maintenance.php on line 118PHP message: PHP Warning:  Use of undefined constant submit - assumed 'submit' (this will throw an Error in a future version of PHP) in /home/pi/pialert/front/maintenance.php on line 146PHP message: PHP Notice:  Undefined variable: pia_lang_test in /home/pi/pialert/front/maintenance.php on" while reading upstream, client: 192.168.1.250, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211"
2022/09/18 14:03:34 [error] 50#50: *26 FastCGI sent in stderr: "line 237" while reading upstream, client: 192.168.1.250, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211"
2022/09/18 14:03:34 [error] 50#50: *26 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_skin_test in /home/pi/pialert/front/maintenance.php on line 265" while reading upstream, client: 192.168.1.250, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211"
2022/09/18 14:03:39 [error] 50#50: *26 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_skin_selected in /home/pi/pialert/front/php/templates/header.php on line 34PHP message: PHP Notice:  Undefined variable: ENABLED_DARKMODE in /home/pi/pialert/front/php/templates/header.php on line 97" while reading response header from upstream, client: 192.168.1.250, server: , request: "POST /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/maintenance.php"
2022/09/18 14:03:39 [error] 50#50: *26 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 0 in /home/pi/pialert/front/maintenance.php on line 113PHP message: PHP Warning:  Use of undefined constant submit - assumed 'submit' (this will throw an Error in a future version of PHP) in /home/pi/pialert/front/maintenance.php on line 118PHP message: PHP Warning:  unlink(../db//setting_skin-black-light): No such file or directory in /home/pi/pialert/front/maintenance.php on line 123PHP message: PHP Warning:  unlink(../db//setting_skin-black): No such file or directory in /home/pi/pialert/front/maintenance.php on line 123PHP" while reading upstream, client: 192.168.1.250, server: , request: "POST /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/maintenance.php"
2022/09/18 14:03:39 [error] 50#50: *26 FastCGI sent in stderr: " message: PHP Warning:  unlink(../db//setting_skin-blue-light): No such file or directory in /home/pi/pialert/front/maintenance.php on line 123PHP message: PHP Warning:  unlink(../db//setting_skin-blue): No such file or directory in /home/pi/pialert/front/maintenance.php on line 123PHP message: PHP Warning:  unlink(../db//setting_skin-green-light): No such file or directory in /home/pi/pialert/front/maintenance.php on line 123PHP message: PHP Warning:  unlink(../db//setting_skin-green): No such file or directory in /home/pi/pialert/front/maintenance.php on line 123PHP message: PHP Warning:  unlink(../db//setting_skin-purple-light): No such file or directory in /home/pi/pialert/front/maintenance.php on line 123PHP message: PHP Warning:  unlink(../db//setting_skin-purple): No such file or directory in /home/pi/pialert/front/maintenance.php on line 123PHP message: PHP Warning:  unlink(../db//setting_skin-red-light): No such file or directory in /home/pi/pialert/front/maintenance.php on line 123PHP message: PHP Warning:  unlink(../db//setting_skin-red): No such file or directory in /home/pi/pialert/front/maintenance.php on line 123PHP message: PHP Warning:  unlink(../db//setting_skin-yellow-light): No such file or directory in /home/pi/pialert/front/maintenance.php on line 123PHP message: PHP Warning:  unlink(../db//setting_skin-yellow): No such file or directory in /home/pi/pialert/front/maintenance.php on line 123PHP message: PHP Warning:  Use of undefined constant submit - assumed 'submit' (this will throw an Error in a future version of PHP) in /home/pi/pialert/front/maintenance.php on line 146PHP message: PHP Notice:  Undefined variable: pia_lang_test in /home/pi/pialert/front/maintenance.php on line 237" while reading upstream, client: 192.168.1.250, server: , request: "POST /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211", referrer: "http://192.168.1.211:20211/maintenance.php"
2022/09/18 14:03:41 [error] 50#50: *26 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: ENABLED_DARKMODE in /home/pi/pialert/front/php/templates/header.php on line 97" while reading response header from upstream, client: 192.168.1.250, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211"
2022/09/18 14:03:41 [error] 50#50: *26 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 0 in /home/pi/pialert/front/maintenance.php on line 113PHP message: PHP Warning:  Use of undefined constant submit - assumed 'submit' (this will throw an Error in a future version of PHP) in /home/pi/pialert/front/maintenance.php on line 118PHP message: PHP Warning:  Use of undefined constant submit - assumed 'submit' (this will throw an Error in a future version of PHP) in /home/pi/pialert/front/maintenance.php on line 146PHP message: PHP Notice:  Undefined variable: pia_lang_test in /home/pi/pialert/front/maintenance.php on line 237" while reading upstream, client: 192.168.1.250, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211"
2022/09/18 14:03:41 [error] 50#50: *26 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: pia_skin_test in /home/pi/pialert/front/maintenance.php on line 265" while reading upstream, client: 192.168.1.250, server: , request: "GET /maintenance.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.211:20211"

unsure if the error is in my .conf or not. Maybe sombody knows what to do.

Thank you
Walter

**Comment by leiweibau** [comment]
Hello,

"pia_skin_test" is a leftover from development. I had left the variable empty because it was no longer needed. In my fork I have now deleted it.

The other errors, like the one with "pia_lang_selected" are normal due to the way language support was built. I disabled reporting for the "maintenance.php" and "network.php" page. It will take some time until this change will be included in this fork as well.

That you have 250GB logfiles is still not explainable. I also have a nginx as webserver and no such huge logfiles. What happens in the docker container in addition, I can not answer.

**Comment by WalterWampe** [comment]
Hi leiweibau,
thanks for the quick response.
Yes you are right, I was not reporting that I was missing several items (TIMEZONE,PIALERT_WEB_PROTECTION,PIALERT_WEB_PASSWORD, and several of the addon) env vars in my pialert.conf due to using an old config which I had since a former release.
This was causing a lot more errors, hence the big logfile I guess.

Now that I added these missing variables I am left with the errors I reported above.

Sorry for the miscommunication. And thanks again for all your effort.

**Comment by jokob-sk** [comment]
Hi @WalterWampe and thanks for checking this project!

Looking at the errors, are you using an older image? The latest image doesn't seem to be throwing these errors...

Could you please try re-deploying the latest docker image to see if it solves the errors? You can download it from the docker hub here: https://registry.hub.docker.com/r/jokobsk/pi.alert

Just FYI if that's the case, I'm not supporting stand-alone installs, only the docker installation method. You can check out the fork from @leiweibau if you are looking for a stand-alone deployment.

**Comment by WalterWampe** [comment]
Hi @jokob-sk  , thanks for you reply!

Sorry for not providing this information. 
Actually I am using the latest image.
Maybe my conf is wrong somehow.
Here is my setup:

docker-compose.yaml
```
version: "3.1"
services:
  pialert:
    image: jokobsk/pi.alert:latest
    container_name: pialert
    restart: unless-stopped
    environment:
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
      - TZ=Europe/Berlin
    network_mode: "host" # The UI is located on <host IP>:20211/pialert/
    volumes:
      - ./pialert.conf:/home/pi/pialert/config/pialert.conf
      - ./version.conf:/home/pi/pialert/config/version.conf
      - /vmdisk/volumes/pialert/db/pialert.db:/home/pi/pialert/db/pialert.db
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
      - "com.centurylinklabs.watchtower.enable=true"
```

pialert.conf
```
#-------------------------------------------------------------------------------
#  Pi.Alert
#  Open Source Network Guard / WIFI & LAN intrusion detector 
#
#  pialert.conf - Back module. Configuration file
#-------------------------------------------------------------------------------
#  Puche 2021        pi.alert.application@gmail.com        GNU GPLv3
#-------------------------------------------------------------------------------

PIALERT_PATH            = '/home/pi/pialert'
DB_PATH                 = PIALERT_PATH + '/db/pialert.db'
LOG_PATH                = PIALERT_PATH + '/log'
VENDORS_DB              = '/usr/share/arp-scan/ieee-oui.txt'
PRINT_LOG               = False
TIMEZONE                = 'Europe/Berlin'
PIALERT_WEB_PROTECTION  = False
PIALERT_WEB_PASSWORD    = 'asdfasdfasdfasdfasdasdfasdfasdfasdfasdf'


SMTP_SERVER             = 'smtp.gmail.com'
SMTP_PORT               = 587
SMTP_USER               = 'yyy@gmail.com'
SMTP_PASS               = 'xyzsososecret'
SMTP_SKIP_TLS	        = False
SMTP_SKIP_LOGIN	        = False


REPORT_MAIL             = True
REPORT_FROM             = 'Pi.Alert <' + SMTP_USER +'>'
REPORT_TO               = 'xxx@xxx.net'
REPORT_DEVICE_URL       = 'http://192.168.1.211:20211/deviceDetails.php?mac='
REPORT_DASHBOARD_URL    = 'http://192.168.1.211:20211'





# Webhook settings
# ----------------------
REPORT_WEBHOOK          = False
WEBHOOK_URL             = 'http://n8n.local:5555/webhook-test/aaaaaaaa-aaaa-aaaa-aaaaa-aaaaaaaaaaaa'
# webhook payload data format for the "body > attachements > text" attribute in https://github.com/jokob-sk/Pi.Alert/blob/main/docs/webhook_json_sample.json
#   supported values: 'json' or 'html' 
#   e.g.: for discord use 'html'
WEBHOOK_PAYLOAD         = 'json'  

# Apprise settings
#-----------------------
REPORT_APPRISE          = False
APPRISE_HOST            = 'http://localhost:8000/notify'
APPRISE_URL             = 'mailto://smtp-relay.sendinblue.com:587?from=user@gmail.com&name=apprise&user=user@gmail.com&pass=password&to=user@gmail.com'

# NTFY (https://ntfy.sh/) settings
# ----------------------
REPORT_NTFY             = False
NTFY_TOPIC              = 'replace_my_secure_topicname_91h889f28'

# PUSHSAFER (https://www.pushsafer.com/) settings
# ----------------------
REPORT_PUSHSAFER        = False
PUSHSAFER_TOKEN         = 'ApiKey'

# DynDNS
# ----------------------
# QUERY_MYIP_SERVER       = 'https://diagnostic.opendns.com/myip'
QUERY_MYIP_SERVER       = 'http://ipv4.icanhazip.com'
DDNS_ACTIVE             = False
DDNS_DOMAIN             = 'your_domain.freeddns.org'
DDNS_USER               = 'dynu_user'
DDNS_PASSWORD           = 'A0000000B0000000C0000000D0000000'
DDNS_UPDATE_URL         = 'https://api.dynu.com/nic/update?'

# PIHOLE settings
# ----------------------
PIHOLE_ACTIVE           = False
PIHOLE_DB               = '/etc/pihole/pihole-FTL.db'
DHCP_ACTIVE             = False
DHCP_LEASES             = '/etc/pihole/dhcp.leases'

# arp-scan options & samples
# ----------------------
#
# Scan local network (default)
# SCAN_SUBNETS    = '--localnet'
#
# Scan two subnets
# SCAN_SUBNETS    = '192.168.11.0/24 192.168.144.0/24'
#
# Scan using interface eth0
# SCAN_SUBNETS    = '--localnet --interface=eth0'
#
# Scan multiple interfaces (eth1 and eth0):
# SCAN_SUBNETS    = [ '192.168.1.0/24 --interface=eth1', '192.168.1.0/24 --interface=eth0' ]

# SCAN_SUBNETS            = '--localnet'
SCAN_SUBNETS    = '192.168.1.0/24 --interface=ens18'


# Maintenance Tasks Cron
# ----------------------
DAYS_TO_KEEP_EVENTS = 90
```

version.conf
```
VERSION           = '3.6_jokobsk'
VERSION_YEAR      = '2022'
VERSION_DATE      = '2022-08-03'
```

**Comment by jokob-sk** [comment]
Thanks for the details!

Apologies, seems like I also have those errors, however the overall size of the log files on my end is pretty small:

![image](https://user-images.githubusercontent.com/96159884/193453966-2d10009f-10f7-45cf-8ee5-828152f6fcf7.png)

So you can consider those errors "normal" :)

My guess is that the previous errors caused the huge file sizes, but these seem not to be a big concern in my opinion. I'd try deleting the files and see if nginx generates those huge log files again. I can investigate further if it happens again.

**Comment by jokob-sk** [comment]
Also merged some improvements from @leiweibau's fork, so after releasing a new image the errors hopefully won't show up again.

**Comment by WalterWampe** [comment]
Thanks a lot and no reason at all to apologize!
I appreciate your work! Thanks also for taking your time to look into this. Looking forward to the new image!
