### ISSUE TITLE
Telegram notification

### ISSUE THREAD

**Issue by celesduran** [jokob-sk/Pi.Alert#94]
Would it be possible for you to add notifications through Telegram?

**Comment by jokob-sk** [comment]
Hi there!

Thanks for checking this project!

You can send telegram notifications via apprise as an intermediary. 


1. Here is the docker image: https://hub.docker.com/r/caronc/apprise

2. You point to your apprise instance via the relevant config [settings here](https://github.com/jokob-sk/Pi.Alert/blob/32d5455f45873bdcf1f0a08200173cef97fb7a7d/config/pialert.conf#L44))

3. And here how to setup telegram notifications for your apprise instance: https://github.com/caronc/apprise/wiki/Notify_telegram

Hope this helps!

**Comment by garanda21** [comment]
For me, I've setup [stmp_to_telegram](https://hub.docker.com/r/kostyaesmukov/smtp_to_telegram) for telegram notifications on pi.alert, and works flawlessly! There's a ton of stmp to telegram tools, use the one that best suits you!

Cheers!
