### ISSUE TITLE
Can't change default password

### ISSUE THREAD

**Issue by GentleHoneyLover** [jokob-sk/Pi.Alert#97]
When enabling web protection, the tip on the login screen says "To change password run: ./reset_password.sh new_password
in the config folder." However, there's no reset_password.sh script in the paler config folder.

What's the procedure for changing the default password then?

**Comment by leiweibau** [comment]
use /back/pialert-cli help to get the correct command

**Comment by GentleHoneyLover** [comment]
Yep, that worked — thanks!

It would be great to add to the documentation ;)

**Comment by leiweibau** [comment]
In my fork it is documented. For this fork I can do nothing ;-)

**Comment by GentleHoneyLover** [comment]
Ah, I didn't find it in your docs. All I found was this (in the README.md):

```
There is a configurable login to prevent unauthorized use.

Set PIALERT_WEB_PROTECTION = True in pialert.conf to enable. The default password is 123456.
```

**Comment by leiweibau** [comment]
"If you want to use password protection, enable it in the configuration file ~/pialert/config/pialert.conf or via pialert-cli."

For this part, you are right, that is not the best way of documentation.  :(

But I give, if the default password is set, a correct hint on the login page how to change the password. And this part was not merged correctly.
But the most important thing is that I could help you.

**Comment by jokob-sk** [comment]
Thanks @leiweibau for assistance ❤ and @GentleHoneyLover for the #98 💪
